PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(18, '-께', 'honorific particle (to)', strftime('%s','now')*1000),
(18, '꼬다', 'to twist/ to be warped', strftime('%s','now')*1000),
(18, '꼬르륵', 'rumble (stomach sound)', strftime('%s','now')*1000),
(18, '꼬마', 'kid/ little child', strftime('%s','now')*1000),
(18, '꼬박01', 'the whole time/ straight', strftime('%s','now')*1000),
(18, '꼬박꼬박', 'regularly/ without fail', strftime('%s','now')*1000),
(18, '꼭꼭01', 'firmly/ tightly/ thoroughly', strftime('%s','now')*1000),
(18, '-꼴', 'shape/ form (suffix)', strftime('%s','now')*1000),
(18, '꼴01', 'shape/ look/ figure', strftime('%s','now')*1000),
(18, '꼴찌', 'last place', strftime('%s','now')*1000),
(18, '꼼짝없이', 'helplessly/ without a move', strftime('%s','now')*1000),
(18, '꽁꽁', 'frozen solid/ tightly', strftime('%s','now')*1000),
(18, '꽃샘추위', 'spring cold snap', strftime('%s','now')*1000),
(18, '꾸벅꾸벅01', 'dozing/ nodding off', strftime('%s','now')*1000),
(18, '꾸짖다', 'to scold/ to rebuke', strftime('%s','now')*1000),
(18, '-꾼', 'person engaged in (suffix)', strftime('%s','now')*1000),
(18, '꿰매다', 'to sew up/ to stitch', strftime('%s','now')*1000),
(18, '끄집어내다', 'to pull out/ to drag out', strftime('%s','now')*1000),
(18, '끈기', 'perseverance/ tenacity', strftime('%s','now')*1000),
(18, '끊이다', 'to cease/ to stop', strftime('%s','now')*1000),
(18, '끌어내다', 'to draw out/ to bring out', strftime('%s','now')*1000),
(18, '끌어들이다', 'to drag in/ to involve', strftime('%s','now')*1000),
(18, '끌어올리다', 'to raise/ to lift up', strftime('%s','now')*1000),
(18, '끔찍하다', 'terrible/ horrible/ awful', strftime('%s','now')*1000),
(18, '끝맺다', 'to conclude/ to finish', strftime('%s','now')*1000),
(18, '끝장', 'the end/ ruin/ finish', strftime('%s','now')*1000),
(18, '끼니', 'meal (daily)', strftime('%s','now')*1000),
(18, '-끼리', 'among/ together (group-only)', strftime('%s','now')*1000),
(18, '나날이', 'day by day/ steadily', strftime('%s','now')*1000),
(18, '나돌다', 'to circulate/ to be rumored', strftime('%s','now')*1000),
(18, '나들이', 'outing/ excursion', strftime('%s','now')*1000),
(18, '나열', 'listing/ arrangement', strftime('%s','now')*1000),
(18, '나침반', 'compass', strftime('%s','now')*1000),
(18, '낙', 'joy/ pleasure', strftime('%s','now')*1000),
(18, '낙관02', 'optimism', strftime('%s','now')*1000),
(18, '낙관적01∙낙관적02', 'optimistic', strftime('%s','now')*1000),
(18, '낙방', 'failure (in exam)', strftime('%s','now')*1000),
(18, '낙서', 'scribble/ graffiti', strftime('%s','now')*1000),
(18, '낙심', 'discouragement/ dejection', strftime('%s','now')*1000),
(18, '낙원', 'paradise', strftime('%s','now')*1000),
(18, '낙제', 'failure (a course/ flunk)', strftime('%s','now')*1000),
(18, '낙천적01∙낙천적02', 'optimistic/ cheerful', strftime('%s','now')*1000),
(18, '낚다', 'to fish/ to lure', strftime('%s','now')*1000),
(18, '낚시터', 'fishing spot', strftime('%s','now')*1000),
(18, '-난', 'difficulty/ crisis (suffix)', strftime('%s','now')*1000),
(18, '난01', 'orchid', strftime('%s','now')*1000),
(18, '난간', 'railing/ handrail', strftime('%s','now')*1000),
(18, '난치병', 'incurable disease', strftime('%s','now')*1000),
(18, '날로01', 'day by day/ with the day', strftime('%s','now')*1000),
(18, '날아들다', 'to fly in/ to come flying', strftime('%s','now')*1000),
(18, '날아오르다', 'to soar/ to fly up', strftime('%s','now')*1000),
(18, '남극', 'Antarctica/ the South Pole', strftime('%s','now')*1000),
(18, '남녀노소', 'men and women of all ages', strftime('%s','now')*1000),
(18, '남다르다', 'distinct/ unusual', strftime('%s','now')*1000),
(18, '남몰래', 'secretly/ stealthily', strftime('%s','now')*1000),
(18, '남색', 'indigo/ navy blue', strftime('%s','now')*1000),
(18, '남아', 'boy/ male child', strftime('%s','now')*1000),
(18, '남짓', 'a little over/ about', strftime('%s','now')*1000),
(18, '남한01', 'South Korea', strftime('%s','now')*1000),
(18, '남향', 'south-facing', strftime('%s','now')*1000),
(18, '납부', 'payment/ remittance', strftime('%s','now')*1000),
(18, '납작하다', 'flat/ flattened', strftime('%s','now')*1000),
(18, '납치', 'kidnapping/ abduction', strftime('%s','now')*1000),
(18, '낭독', 'reading aloud/ recitation', strftime('%s','now')*1000),
(18, '낭만', 'romance/ romanticism', strftime('%s','now')*1000),
(18, '낭만적01∙낭만적02', 'romantic', strftime('%s','now')*1000),
(18, '낯', 'face/ familiarity', strftime('%s','now')*1000),
(18, '낯익다', 'familiar', strftime('%s','now')*1000),
(18, '낱말', 'word/ vocabulary item', strftime('%s','now')*1000),
(18, '내기', 'bet/ wager', strftime('%s','now')*1000),
(18, '내딛다', 'to step forward', strftime('%s','now')*1000),
(18, '내리치다', 'to strike down/ to slam', strftime('%s','now')*1000),
(18, '내면', 'inner side/ inside/ inner world', strftime('%s','now')*1000),
(18, '내뱉다', 'to spit out/ to blurt', strftime('%s','now')*1000),
(18, '내보이다02', 'to show/ to display', strftime('%s','now')*1000),
(18, '내복', 'thermal underwear', strftime('%s','now')*1000),
(18, '내비게이션00', 'navigation (device)', strftime('%s','now')*1000),
(18, '내비치다', 'to show through/ to be revealed', strftime('%s','now')*1000),
(18, '내쉬다', 'to exhale', strftime('%s','now')*1000),
(18, '내역', 'breakdown/ itemized list', strftime('%s','now')*1000),
(18, '내오다', 'to bring out', strftime('%s','now')*1000),
(18, '내용물', 'contents/ inner stuff', strftime('%s','now')*1000),
(18, '내지르다', 'to shout/ to thrust', strftime('%s','now')*1000),
(18, '냉기', 'cold air/ chill', strftime('%s','now')*1000),
(18, '냉대02', 'cold reception/ snub', strftime('%s','now')*1000),
(18, '너무하다01/너무하다02', 'to be too much/ excessive', strftime('%s','now')*1000),
(18, '너비', 'width/ breadth', strftime('%s','now')*1000),
(18, '넉', 'four (native)', strftime('%s','now')*1000),
(18, '널뛰기', 'seesawing/ Korean seesaw', strftime('%s','now')*1000),
(18, '-네02', 'sentence ending (exclamatory)', strftime('%s','now')*1000),
(18, '네모나다', 'to be square', strftime('%s','now')*1000),
(18, '네트워크', 'network', strftime('%s','now')*1000),
(18, '-녀', 'woman/ female (suffix)', strftime('%s','now')*1000),
(18, '년생', 'born in (year)', strftime('%s','now')*1000),
(18, '노년', 'old age/ elderly years', strftime('%s','now')*1000),
(18, '노동력', 'labor force/ manpower', strftime('%s','now')*1000),
(18, '노숙자', 'homeless person', strftime('%s','now')*1000),
(18, '노예', 'slave', strftime('%s','now')*1000),
(18, '노을', 'afterglow/ sunset glow', strftime('%s','now')*1000),
(18, '노처녀', 'spinster', strftime('%s','now')*1000),
(18, '노총각', 'old bachelor', strftime('%s','now')*1000),
(18, '노출', 'exposure', strftime('%s','now')*1000),
(18, '노화', 'aging/ senescence', strftime('%s','now')*1000),
(18, '노후02', 'post-retirement/ old age', strftime('%s','now')*1000),
(18, '논', 'rice paddy', strftime('%s','now')*1000),
(18, '논문', 'thesis/ paper', strftime('%s','now')*1000),
(18, '논밭', 'fields and paddies', strftime('%s','now')*1000),
(18, '논술', 'essay/ writing (exam)', strftime('%s','now')*1000),
(18, '놈01/놈02', 'guy/ fellow (pejorative)', strftime('%s','now')*1000),
(18, '농가', 'farm household', strftime('%s','now')*1000),
(18, '농경', 'farming/ agriculture', strftime('%s','now')*1000),
(18, '농도', 'concentration (solution)', strftime('%s','now')*1000),
(18, '농수산물', 'agricultural and marine products', strftime('%s','now')*1000),
(18, '농악', 'farmer''s music', strftime('%s','now')*1000),
(18, '농작물', 'crops/ farm produce', strftime('%s','now')*1000),
(18, '농장', 'farm/ ranch', strftime('%s','now')*1000),
(18, '농축산물', 'agricultural and livestock products', strftime('%s','now')*1000),
(18, '놓아주다', 'to let go/ to release', strftime('%s','now')*1000),
(18, '누다', 'to defecate (colloquial)', strftime('%s','now')*1000),
(18, '누렇다', 'yellowish/ sallow', strftime('%s','now')*1000),
(18, '누리다01', 'to enjoy', strftime('%s','now')*1000),
(18, '누전', 'leakage of electricity', strftime('%s','now')*1000),
(18, '눈높이', 'eye level', strftime('%s','now')*1000),
(18, '눈발', 'snow flurries', strftime('%s','now')*1000),
(18, '눈사태', 'avalanche', strftime('%s','now')*1000),
(18, '눈살01', 'brow/ frown', strftime('%s','now')*1000),
(18, '눈짓', 'signal with the eyes', strftime('%s','now')*1000),
(18, '눈치채다00', 'to notice/ to realize', strftime('%s','now')*1000),
(18, '눌리다01', 'to be pressed/ be oppressed', strftime('%s','now')*1000),
(18, '뉘우치다', 'to repent/ to regret', strftime('%s','now')*1000),
(18, '늑대', 'wolf', strftime('%s','now')*1000),
(18, '늘어지다', 'to droop/ to be prolonged', strftime('%s','now')*1000),
(18, '능동적01∙능동적02', 'active (not passive)', strftime('%s','now')*1000),
(18, '능률', 'efficiency', strftime('%s','now')*1000),
(18, '능숙하다', 'to be skillful/ adept', strftime('%s','now')*1000),
(18, '다-01', 'prefix: all-, whole-', strftime('%s','now')*1000),
(18, '다급하다', 'urgent/ pressing', strftime('%s','now')*1000),
(18, '다다르다', 'to reach/ to arrive at', strftime('%s','now')*1000),
(18, '다다익선', 'the more, the better', strftime('%s','now')*1000),
(18, '다름없이', 'no different(ly)/ as usual', strftime('%s','now')*1000),
(18, '다발01', 'bundle/ bunch', strftime('%s','now')*1000),
(18, '다방면', 'in many fields/ various areas', strftime('%s','now')*1000),
(18, '다스리다', 'to govern/ to control', strftime('%s','now')*1000),
(18, '다시다', 'Dasida (seasoning mix)', strftime('%s','now')*1000),
(18, '다양성', 'diversity', strftime('%s','now')*1000),
(18, '다양화', 'diversification', strftime('%s','now')*1000),
(18, '다이빙', 'diving', strftime('%s','now')*1000),
(18, '다이아몬드', 'diamond', strftime('%s','now')*1000),
(18, '다큐멘터리', 'documentary', strftime('%s','now')*1000),
(18, '닥치다01', 'to approach/ to befall', strftime('%s','now')*1000),
(18, '-단02', 'suffix: group/ corps/ squad', strftime('%s','now')*1000),
(18, '단05', 'dan rank (martial arts)', strftime('%s','now')*1000),
(18, '단군', 'Dangun (legendary founder)', strftime('%s','now')*1000),
(18, '단기간', 'short period', strftime('%s','now')*1000),
(18, '단락', 'paragraph/ break/ end', strftime('%s','now')*1000),
(18, '단말기', 'terminal device', strftime('%s','now')*1000),
(18, '단백질', 'protein', strftime('%s','now')*1000),
(18, '단일', 'single/ unitary', strftime('%s','now')*1000),
(18, '단절', 'severance/ break-off', strftime('%s','now')*1000),
(18, '단정', 'judgment/ conclusion', strftime('%s','now')*1000),
(18, '단조롭다', 'monotonous', strftime('%s','now')*1000),
(18, '단축', 'shortening/ reduction', strftime('%s','now')*1000),
(18, '단합', 'unity/ union', strftime('%s','now')*1000),
(18, '달다03', 'to attach/ to hang', strftime('%s','now')*1000),
(18, '달리하다', 'to do differently/ differentiate', strftime('%s','now')*1000),
(18, '당구', 'billiards/ pool', strftime('%s','now')*1000),
(18, '당국02', 'the authorities', strftime('%s','now')*1000),
(18, '당뇨병', 'diabetes', strftime('%s','now')*1000),
(18, '당면02', 'immediate/ pending', strftime('%s','now')*1000),
(18, '당부', 'request/ entreaty', strftime('%s','now')*1000),
(18, '당선', 'election/ being elected', strftime('%s','now')*1000),
(18, '대04', 'generation/ era', strftime('%s','now')*1000),
(18, '대06/대07', 'against/ versus / great/ big', strftime('%s','now')*1000),
(18, '대가족', 'extended family', strftime('%s','now')*1000),
(18, '대견하다', 'admirable/ proud', strftime('%s','now')*1000),
(18, '대결', 'confrontation/ contest', strftime('%s','now')*1000),
(18, '대꾸', 'retort/ reply', strftime('%s','now')*1000),
(18, '대나무', 'bamboo', strftime('%s','now')*1000),
(18, '대담02', 'talk/ interview', strftime('%s','now')*1000),
(18, '대대로', 'for generations', strftime('%s','now')*1000),
(18, '대등', 'equal/ on equal terms', strftime('%s','now')*1000),
(18, '대략적01∙대략적02', 'approximate', strftime('%s','now')*1000),
(18, '대륙01', 'continent', strftime('%s','now')*1000),
(18, '대리점', 'agency/ dealership', strftime('%s','now')*1000),
(18, '대머리', 'bald(headed)', strftime('%s','now')*1000),
(18, '대명사', 'pronoun', strftime('%s','now')*1000),
(18, '대보름', 'Daeboreum (First Full Moon Day)', strftime('%s','now')*1000),
(18, '대본', 'script', strftime('%s','now')*1000),
(18, '대상00', 'subject/ target', strftime('%s','now')*1000),
(18, '대안', 'alternative', strftime('%s','now')*1000),
(18, '대여', 'rental/ loan', strftime('%s','now')*1000),
(18, '대우', 'treatment', strftime('%s','now')*1000),
(18, '대인02', 'adult', strftime('%s','now')*1000),
(18, '대입01', 'college entrance', strftime('%s','now')*1000),
(18, '대장01', 'commander/ captain', strftime('%s','now')*1000),
(18, '대조적01∙대조적02', 'contrasting', strftime('%s','now')*1000),
(18, '대졸', 'college graduate', strftime('%s','now')*1000),
(18, '대중적01∙대중적02', 'popular', strftime('%s','now')*1000),
(18, '대중화', 'popularization', strftime('%s','now')*1000),
(18, '대체00/대체01', 'substitution/ alternative / on earth', strftime('%s','now')*1000),
(18, '대추', 'jujube', strftime('%s','now')*1000),
(18, '대피', 'evacuation', strftime('%s','now')*1000),
(18, '대형차', 'large vehicle', strftime('%s','now')*1000),
(18, '댓글00', 'comment (online)', strftime('%s','now')*1000),
(18, '더듬거리다', 'to stammer/ to fumble', strftime('%s','now')*1000),
(18, '더없이', 'incomparably/ supremely', strftime('%s','now')*1000),
(18, '덜하다', 'to be less', strftime('%s','now')*1000),
(18, '덧나다', 'to get worse/ to fester', strftime('%s','now')*1000),
(18, '데모', 'demo/ demonstration (protest)', strftime('%s','now')*1000),
(18, '도04', 'province (administrative division)', strftime('%s','now')*1000),
(18, '도깨비', 'goblin', strftime('%s','now')*1000),
(18, '도끼', 'axe', strftime('%s','now')*1000),
(18, '도달', 'arrival/ reach', strftime('%s','now')*1000),
(18, '도둑맞다', 'to be robbed', strftime('%s','now')*1000),
(18, '도매02', 'wholesale', strftime('%s','now')*1000),
(18, '도박', 'gambling', strftime('%s','now')*1000),
(18, '도보', 'on foot', strftime('%s','now')*1000),
(18, '도시화', 'urbanization', strftime('%s','now')*1000),
(18, '도우미', 'assistant/ helper', strftime('%s','now')*1000),
(18, '도표', 'chart/ diagram', strftime('%s','now')*1000),
(18, '도피', 'escape/ evasion', strftime('%s','now')*1000),
(18, '독립적01∙ 독립적02', 'independent', strftime('%s','now')*1000),
(18, '독방', 'solitary cell/ single room', strftime('%s','now')*1000),
(18, '독신', 'single (unmarried)', strftime('%s','now')*1000),
(18, '독창적01∙ 독창적02', 'original/ creative', strftime('%s','now')*1000),
(18, '돋보이다', 'to stand out', strftime('%s','now')*1000),
(18, '돋우다', 'to raise/ to stimulate', strftime('%s','now')*1000),
(18, '돌이키다', 'to turn back/ to reflect', strftime('%s','now')*1000),
(18, '동04', 'dong (neighborhood unit)', strftime('%s','now')*1000),
(18, '동감', 'sympathy/ agreement', strftime('%s','now')*1000),
(18, '동거', 'cohabitation', strftime('%s','now')*1000),
(18, '동굴', 'cave', strftime('%s','now')*1000),
(18, '동동02', 'bobbing/ hopping lightly', strftime('%s','now')*1000),
(18, '동문01', 'alumnus/ schoolmate', strftime('%s','now')*1000),
(18, '동반', 'accompaniment', strftime('%s','now')*1000),
(18, '동사02', 'verb', strftime('%s','now')*1000),
(18, '동상02', 'statue', strftime('%s','now')*1000),
(18, '동서양', 'East and West', strftime('%s','now')*1000),
(18, '동식물', 'plants and animals', strftime('%s','now')*1000),
(18, '동원', 'mobilization', strftime('%s','now')*1000),
(18, '동지02', 'comrade', strftime('%s','now')*1000),
(18, '동행', 'accompanying/ company', strftime('%s','now')*1000),
(18, '동향02', 'trend/ tendency', strftime('%s','now')*1000),
(18, '동화01', 'fairy tale/ children’s story', strftime('%s','now')*1000),
(18, '되돌아보다', 'to look back', strftime('%s','now')*1000),
(18, '되묻다', 'to ask back', strftime('%s','now')*1000),
(18, '두근거리다', 'to throb/ palpitate', strftime('%s','now')*1000),
(18, '두꺼비', 'toad', strftime('%s','now')*1000),
(18, '두들기다', 'to pound/ to knock repeatedly', strftime('%s','now')*1000),
(18, '두텁다', 'thick/ deep (friendship)', strftime('%s','now')*1000),
(18, '둔하다', 'dull/ blunt', strftime('%s','now')*1000),
(18, '뒤덮다', 'to cover over', strftime('%s','now')*1000),
(18, '뒤엎다', 'to overturn', strftime('%s','now')*1000),
(18, '뒤집어쓰다', 'to pull over one’s head/ be saddled with', strftime('%s','now')*1000),
(18, '뒤집히다', 'to be overturned', strftime('%s','now')*1000),
(18, '뒤처지다', 'to fall behind', strftime('%s','now')*1000),
(18, '뒤척이다', 'to toss and turn', strftime('%s','now')*1000),
(18, '뒤풀이', 'after-party', strftime('%s','now')*1000),
(18, '뒤흔들다', 'to shake violently', strftime('%s','now')*1000),
(18, '뒷걸음', 'backward step', strftime('%s','now')*1000),
(18, '뒷받침', 'support/ backing', strftime('%s','now')*1000),
(18, '들01', 'field/ plain', strftime('%s','now')*1000),
(18, '들락거리다', 'to come and go frequently', strftime('%s','now')*1000),
(18, '들어앉다', 'to settle down/ to sink down', strftime('%s','now')*1000),
(18, '들여오다', 'to bring in/ to import', strftime('%s','now')*1000),
(18, '들이대다02', 'to thrust at/ to bring up (an argument)', strftime('%s','now')*1000),
(18, '들이밀다', 'to push in', strftime('%s','now')*1000),
(18, '들통', 'exposure/ getting caught', strftime('%s','now')*1000),
(18, '들판', 'field', strftime('%s','now')*1000),
(18, '듬뿍', 'plenty/ generously', strftime('%s','now')*1000),
(18, '등교', 'going to school', strftime('%s','now')*1000),
(18, '등반', 'mountain climbing', strftime('%s','now')*1000),
(18, '등장인물', 'characters (in a story)', strftime('%s','now')*1000),
(18, '디디다', 'to step on/ to tread', strftime('%s','now')*1000),
(18, '따갑다', 'stinging/ prickly', strftime('%s','now')*1000),
(18, '따돌림00', 'bullying/ ostracism', strftime('%s','now')*1000),
(18, '따라잡다', 'to catch up with', strftime('%s','now')*1000),
(18, '따위', 'such things/ and the like', strftime('%s','now')*1000),
(18, '딱02', 'exactly/ smack/ just', strftime('%s','now')*1000),
(18, '딸리다01', 'to be attached to/ belong to', strftime('%s','now')*1000),
(18, '때다', 'to burn (fuel)/ to fire (a kiln)', strftime('%s','now')*1000),
(18, '때우다', 'to make do/ to patch up', strftime('%s','now')*1000),
(18, '떠내려가다', 'to be swept away (by water)', strftime('%s','now')*1000),
(18, '떠돌다', 'to wander/ to drift', strftime('%s','now')*1000),
(18, '떠들썩하다01/ 떠들썩하다02', 'boisterous/ uproarious', strftime('%s','now')*1000),
(18, '떠맡다', 'to take on/ to assume', strftime('%s','now')*1000),
(18, '떡02', 'rice cake', strftime('%s','now')*1000),
(18, '떫다', 'astringent (taste)', strftime('%s','now')*1000),
(18, '떳떳하다', 'upright/ honorable', strftime('%s','now')*1000),
(18, '또래', 'peer/ same age group', strftime('%s','now')*1000),
(18, '또렷하다', 'clear/ distinct', strftime('%s','now')*1000),
(18, '똑00', 'exactly/ precisely', strftime('%s','now')*1000),
(18, '똑똑', 'knock-knock/ smart', strftime('%s','now')*1000),
(18, '뚜렷이', 'clearly/ distinctly', strftime('%s','now')*1000),
(18, '뚝02', 'suddenly/ with a snap', strftime('%s','now')*1000),
(18, '뚝뚝01', 'drip-drip/ bluntly', strftime('%s','now')*1000),
(18, '뛰어오다', 'to run up/ to leap here', strftime('%s','now')*1000),
(18, '뛰쳐나가다', 'to burst out/ rush out', strftime('%s','now')*1000),
(18, '뛰쳐나오다', 'to burst out (toward speaker)', strftime('%s','now')*1000),
(18, '뜨다03', 'to float/ to rise', strftime('%s','now')*1000),
(18, '뜯어보다', 'to scrutinize/ to open and look', strftime('%s','now')*1000),
(18, '뜸하다', 'infrequent/ rare', strftime('%s','now')*1000),
(18, '띄우다02', 'to float/ to launch/ to raise', strftime('%s','now')*1000),
(18, '라일락00', 'lilac', strftime('%s','now')*1000),
(18, '라켓', 'racket', strftime('%s','now')*1000),
(18, '란00', 'bound form: “so-called/ called”', strftime('%s','now')*1000),
(18, '레슬링', 'wrestling', strftime('%s','now')*1000),
(18, '레저', 'leisure', strftime('%s','now')*1000),
(18, '-로01', 'particle: to/ toward/ by (means)', strftime('%s','now')*1000),
(18, '-론', 'suffix: -ism/ theory', strftime('%s','now')*1000),
(18, '-류02', 'suffix: type/ class/ category', strftime('%s','now')*1000),
(18, '리더십', 'leadership', strftime('%s','now')*1000),
(18, '리포터', 'reporter', strftime('%s','now')*1000),
(18, '마감', 'deadline/ closing', strftime('%s','now')*1000),
(18, '마비', 'paralysis/ numbness', strftime('%s','now')*1000),
(18, '마일리지00', 'mileage (points)', strftime('%s','now')*1000),
(18, '마저', 'even/ the rest (also)', strftime('%s','now')*1000),
(18, '마케팅', 'marketing', strftime('%s','now')*1000),
(18, '막03/ 막04', 'just now/ at random / membrane/ film', strftime('%s','now')*1000),
(18, '막막하다02', 'desolate/ at a loss', strftime('%s','now')*1000),
(18, '만병', 'all diseases', strftime('%s','now')*1000),
(18, '만족도', 'satisfaction level', strftime('%s','now')*1000),
(18, '맏이', 'firstborn', strftime('%s','now')*1000),
(18, '말끝', 'end of one’s words', strftime('%s','now')*1000),
(18, '말재주', 'gift of gab', strftime('%s','now')*1000),
(18, '맞대다', 'to put together/ to face', strftime('%s','now')*1000),
(18, '맞들다', 'to get to like/ to share the load', strftime('%s','now')*1000),
(18, '맞히다02', 'to guess right/ to hit the mark', strftime('%s','now')*1000),
(18, '매03', 'per/ each', strftime('%s','now')*1000),
(18, '매끄럽다', 'smooth', strftime('%s','now')*1000),
(18, '매다02', 'to tie/ to fasten', strftime('%s','now')*1000),
(18, '매력적01∙ 매력적02', 'attractive/ charming', strftime('%s','now')*1000),
(18, '매매', 'buying and selling/ trade', strftime('%s','now')*1000),
(18, '매사01/ 매사02', 'everything/ every matter', strftime('%s','now')*1000),
(18, '매섭다', 'severe/ fierce', strftime('%s','now')*1000),
(18, '매연', 'soot/ exhaust fumes', strftime('%s','now')*1000),
(18, '매입', 'purchase/ acquisition', strftime('%s','now')*1000),
(18, '매출', 'sales/ revenue', strftime('%s','now')*1000),
(18, '매콤하다', 'moderately spicy', strftime('%s','now')*1000),
(18, '맨손', 'bare hands', strftime('%s','now')*1000),
(18, '맹세', 'oath/ vow', strftime('%s','now')*1000),
(18, '머리기사', 'headline article', strftime('%s','now')*1000),
(18, '머지않다', 'not far off/ soon', strftime('%s','now')*1000),
(18, '먹음직스럽다', 'appetizing', strftime('%s','now')*1000),
(18, '멍청하다', 'stupid/ dumb', strftime('%s','now')*1000),
(18, '멍하니', 'blankly/ vacantly', strftime('%s','now')*1000),
(18, '멍하다', 'blank/ dazed', strftime('%s','now')*1000),
(18, '메다00', 'to carry on the shoulder', strftime('%s','now')*1000),
(18, '메마르다', 'to be dry/ barren', strftime('%s','now')*1000),
(18, '멜로00', 'melodrama/ romance', strftime('%s','now')*1000),
(18, '면03', 'township (myeon)', strftime('%s','now')*1000);