PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(25, '뒤돌아보다', 'look back', strftime('%s','now')*1000),
(25, '뒤바뀌다', 'be swapped/ be reversed', strftime('%s','now')*1000),
(25, '뒤섞이다', 'be mixed together', strftime('%s','now')*1000),
(25, '뒤엉키다', 'get entangled', strftime('%s','now')*1000),
(25, '뒤적이다', 'rummage', strftime('%s','now')*1000),
(25, '뒤죽박죽', 'all mixed up/ jumbled', strftime('%s','now')*1000),
(25, '뒤쫓다', 'chase after/ pursue', strftime('%s','now')*1000),
(25, '뒤통수', 'back of the head', strftime('%s','now')*1000),
(25, '뒤틀리다', 'be twisted/ be distorted', strftime('%s','now')*1000),
(25, '뒷바라지', 'support/ care (behind the scenes)', strftime('%s','now')*1000),
(25, '뒷일', 'aftermath/ what follows', strftime('%s','now')*1000),
(25, '뒷전', 'the back burner/ sidelines', strftime('%s','now')*1000),
(25, '뒹굴다', 'roll about', strftime('%s','now')*1000),
(25, '드러눕다', 'lie down flat', strftime('%s','now')*1000),
(25, '드리우다', 'hang/ cast (a shadow)', strftime('%s','now')*1000),
(25, '드세다', 'fierce/ strong', strftime('%s','now')*1000),
(25, '득점', 'scoring/ points', strftime('%s','now')*1000),
(25, '들끓다', 'seethe/ boil up', strftime('%s','now')*1000),
(25, '들뜨다', 'be excited/ be restless', strftime('%s','now')*1000),
(25, '들락날락하다', 'come and go repeatedly', strftime('%s','now')*1000),
(25, '들먹이다', 'brandish/ raise (a topic)', strftime('%s','now')*1000),
(25, '들썩이다', 'heave/ be excited', strftime('%s','now')*1000),
(25, '들어맞다', 'fit/ be right', strftime('%s','now')*1000),
(25, '들어차다', 'be filled', strftime('%s','now')*1000),
(25, '들여놓다', 'bring in/ let in', strftime('%s','now')*1000),
(25, '들여다보이다', 'be seen into/ visible inside', strftime('%s','now')*1000),
(25, '들이닥치다', 'storm in/ rush in', strftime('%s','now')*1000),
(25, '들이마시다02', 'inhale', strftime('%s','now')*1000),
(25, '들이켜다', 'gulp down/ drink up', strftime('%s','now')*1000),
(25, '들추다', 'lift up/ bring up', strftime('%s','now')*1000),
(25, '등04', 'lamp/ light', strftime('%s','now')*1000),
(25, '등골01', 'backbone/ spine', strftime('%s','now')*1000),
(25, '"등급/\n등급00"', 'grade/ rating', strftime('%s','now')*1000),
(25, '등용문', 'gateway to success', strftime('%s','now')*1000),
(25, '등재00', 'registration/ listing', strftime('%s','now')*1000),
(25, '등지', 'region(s)/ area(s)', strftime('%s','now')*1000),
(25, '등지다', 'turn one’s back on', strftime('%s','now')*1000),
(25, '딛다', 'step on/ overcome', strftime('%s','now')*1000),
(25, '따돌리다', 'ostracize/ outpace', strftime('%s','now')*1000),
(25, '따라나서다', 'set out following', strftime('%s','now')*1000),
(25, '딱하다', 'awkward/ pitiful', strftime('%s','now')*1000),
(25, '딱히02', 'particularly/ especially', strftime('%s','now')*1000),
(25, '때마침', 'just then/ timely', strftime('%s','now')*1000),
(25, '떠넘기다', 'shift (responsibility)', strftime('%s','now')*1000),
(25, '떠다니다', 'drift about/ float around', strftime('%s','now')*1000),
(25, '떠돌아다니다', 'wander about', strftime('%s','now')*1000),
(25, '떠밀리다', 'be pushed/ be thrust', strftime('%s','now')*1000),
(25, '떨구다', 'drop/ lower', strftime('%s','now')*1000),
(25, '떨치다01', 'shake off', strftime('%s','now')*1000),
(25, '떨치다02', 'make a name for oneself', strftime('%s','now')*1000),
(25, '뜨이다', 'be seen/ catch one’s eye', strftime('%s','now')*1000),
(25, '뜯어내다', 'rip off/ tear out', strftime('%s','now')*1000),
(25, '띄어쓰기', 'word spacing', strftime('%s','now')*1000),
(25, '로맨틱00', 'romantic', strftime('%s','now')*1000),
(25, '리그', 'league', strftime('%s','now')*1000),
(25, '마누라', 'wife (colloquial)', strftime('%s','now')*1000),
(25, '마다하다', 'refuse/ decline', strftime('%s','now')*1000),
(25, '마지못하다', 'do unwillingly', strftime('%s','now')*1000),
(25, '마취', 'anesthesia', strftime('%s','now')*1000),
(25, '막강', 'mighty/ powerful', strftime('%s','now')*1000),
(25, '막다르다', 'come to a dead end', strftime('%s','now')*1000),
(25, '막대', 'stick/ rod', strftime('%s','now')*1000),
(25, '막대하다', 'enormous', strftime('%s','now')*1000),
(25, '막론하다', 'regardless of', strftime('%s','now')*1000),
(25, '막무가내', 'obstinate/ headstrong', strftime('%s','now')*1000),
(25, '막바지', 'final stage', strftime('%s','now')*1000),
(25, '막상막하', 'neck and neck', strftime('%s','now')*1000),
(25, '막연히', 'vaguely', strftime('%s','now')*1000),
(25, '막중하다', 'weighty/ very heavy (duty)', strftime('%s','now')*1000),
(25, '막힘없이', 'smoothly/ without a hitch', strftime('%s','now')*1000),
(25, '만끽00', 'savor fully', strftime('%s','now')*1000),
(25, '만사', 'everything', strftime('%s','now')*1000),
(25, '"만세00・\n만세03"', 'hurrah/ long live', strftime('%s','now')*1000),
(25, '만연', 'rampant/ widespread', strftime('%s','now')*1000),
(25, '만장일치', 'unanimity', strftime('%s','now')*1000),
(25, '맏형', 'eldest brother', strftime('%s','now')*1000),
(25, '말단', 'the lowest level', strftime('%s','now')*1000),
(25, '말문', 'one’s tongue (power of speech)', strftime('%s','now')*1000),
(25, '말미암다', 'be due to', strftime('%s','now')*1000),
(25, '말솜씨', 'speaking skill', strftime('%s','now')*1000),
(25, '말썽', 'trouble', strftime('%s','now')*1000),
(25, '망03', 'net/ mesh', strftime('%s','now')*1000),
(25, '망신', 'disgrace', strftime('%s','now')*1000),
(25, '망원경', 'telescope', strftime('%s','now')*1000),
(25, '망치', 'hammer', strftime('%s','now')*1000),
(25, '맞먹다', 'be equal to/ be comparable to', strftime('%s','now')*1000),
(25, '맞붙다', 'face off/ compete', strftime('%s','now')*1000),
(25, '맞아떨어지다', 'coincide/ fit perfectly', strftime('%s','now')*1000),
(25, '맞장구', 'backchannel/ chime in', strftime('%s','now')*1000),
(25, '맞춤', 'customized/ tailored', strftime('%s','now')*1000),
(25, '매04', 'hawk (bird of prey)', strftime('%s','now')*1000),
(25, '매기다', 'assign/ fix (a price/grade)', strftime('%s','now')*1000),
(25, '매니저', 'manager', strftime('%s','now')*1000),
(25, '매듭', 'knot', strftime('%s','now')*1000),
(25, '매료00', 'fascination/ charm', strftime('%s','now')*1000),
(25, '매립', 'landfill/ reclamation', strftime('%s','now')*1000),
(25, '매장01', 'store/ shop', strftime('%s','now')*1000),
(25, '매진02', 'push forward/ make every effort', strftime('%s','now')*1000),
(25, '맥', 'pulse/ veins (figurative thread)', strftime('%s','now')*1000),
(25, '맥락', 'context', strftime('%s','now')*1000),
(25, '맥박', 'pulse', strftime('%s','now')*1000),
(25, '맴돌다', 'hover/ linger', strftime('%s','now')*1000),
(25, '맵시', 'style/ shapeliness', strftime('%s','now')*1000),
(25, '맹렬하다', 'fierce/ intense', strftime('%s','now')*1000),
(25, '맺히다', 'be formed/ gather (tears)', strftime('%s','now')*1000),
(25, '머금다', 'hold in (tears)/ keep in mouth', strftime('%s','now')*1000),
(25, '머리맡', 'bedside', strftime('%s','now')*1000),
(25, '먹구름', 'dark cloud', strftime('%s','now')*1000),
(25, '멀다01', 'be far', strftime('%s','now')*1000),
(25, '멋스럽다', 'stylish', strftime('%s','now')*1000),
(25, '멍들다', 'bruise', strftime('%s','now')*1000),
(25, '면모', 'aspect/ face', strftime('%s','now')*1000),
(25, '면역', 'immunity', strftime('%s','now')*1000),
(25, '면회', 'visit (patient/prisoner)', strftime('%s','now')*1000),
(25, '명당', 'auspicious site/ prime spot', strftime('%s','now')*1000),
(25, '명료하다', 'clear/ lucid', strftime('%s','now')*1000),
(25, '명목', 'nominal/ in name', strftime('%s','now')*1000),
(25, '명문02', 'prestigious school/family', strftime('%s','now')*1000),
(25, '명백하다', 'obvious/ evident', strftime('%s','now')*1000),
(25, '명복', 'repose of the deceased', strftime('%s','now')*1000),
(25, '명분', 'justification/ cause', strftime('%s','now')*1000),
(25, '명승지', 'scenic spot', strftime('%s','now')*1000),
(25, '명실상부00', 'true in name and reality', strftime('%s','now')*1000),
(25, '명중', 'bull’s-eye/ hit the mark', strftime('%s','now')*1000),
(25, '명칭', 'name/ designation', strftime('%s','now')*1000),
(25, '모닥불', 'campfire', strftime('%s','now')*1000),
(25, '모색', 'seek/ explore', strftime('%s','now')*1000),
(25, '모서리', 'edge/ corner', strftime('%s','now')*1000),
(25, '모순', 'contradiction', strftime('%s','now')*1000),
(25, '모욕', 'insult', strftime('%s','now')*1000),
(25, '모유', 'breast milk', strftime('%s','now')*1000),
(25, '모질다', 'harsh/ severe', strftime('%s','now')*1000),
(25, '모퉁이', 'corner', strftime('%s','now')*1000),
(25, '모티브', 'motif', strftime('%s','now')*1000),
(25, '모호하다', 'ambiguous/ vague', strftime('%s','now')*1000),
(25, '목덜미', 'nape (of the neck)', strftime('%s','now')*1000),
(25, '몰락', 'downfall', strftime('%s','now')*1000),
(25, '몰려가다', 'flock/ crowd', strftime('%s','now')*1000),
(25, '몰아가다', 'drive/ force into', strftime('%s','now')*1000),
(25, '몰아내다', 'drive out', strftime('%s','now')*1000),
(25, '몰아넣다', 'drive into/ corner', strftime('%s','now')*1000),
(25, '몰아쉬다', 'pant/ breathe hard', strftime('%s','now')*1000),
(25, '몰아치다', 'rage/ lash', strftime('%s','now')*1000),
(25, '몰입', 'immersion', strftime('%s','now')*1000),
(25, '몸집', 'body size/ build', strftime('%s','now')*1000),
(25, '못마땅하다', 'unsatisfactory/ displeased', strftime('%s','now')*1000),
(25, '묘미', 'charm/ real taste', strftime('%s','now')*1000),
(25, '묘지', 'cemetery', strftime('%s','now')*1000),
(25, '묘하다', 'peculiar/ strange', strftime('%s','now')*1000),
(25, '무공해', 'pollution-free', strftime('%s','now')*1000),
(25, '무궁무진', 'inexhaustible', strftime('%s','now')*1000),
(25, '무기력', 'lethargy', strftime('%s','now')*1000),
(25, '무더기', 'a heap/ a mass', strftime('%s','now')*1000),
(25, '무던히', 'fairly/ quite/ tolerably', strftime('%s','now')*1000),
(25, '무럭무럭', 'rapidly (growing)', strftime('%s','now')*1000),
(25, '무력01', 'powerlessness/ impotence', strftime('%s','now')*1000),
(25, '무례', 'rudeness', strftime('%s','now')*1000),
(25, '무료하다', 'boring', strftime('%s','now')*1000),
(25, '무르다03', 'soft/ tender', strftime('%s','now')*1000),
(25, '무르익다', 'ripen/ mature', strftime('%s','now')*1000),
(25, '무릅쓰다', 'risk/ brave', strftime('%s','now')*1000),
(25, '무리01', 'group/ crowd', strftime('%s','now')*1000),
(25, '무모하다', 'reckless', strftime('%s','now')*1000),
(25, '무병장수00', 'long life without illness', strftime('%s','now')*1000),
(25, '무성하다', 'luxuriant/ thick', strftime('%s','now')*1000),
(25, '무수하다', 'innumerable', strftime('%s','now')*1000),
(25, '무수히', 'innumerably', strftime('%s','now')*1000),
(25, '무심히', 'indifferently/ carelessly', strftime('%s','now')*1000),
(25, '무언', 'wordless/ mute', strftime('%s','now')*1000),
(25, '무용지물', 'useless thing', strftime('%s','now')*1000),
(25, '"무작정01/\n무작정02"', 'blindly/ without a plan', strftime('%s','now')*1000),
(25, '"무차별적01/\n무차별적02"', 'indiscriminate', strftime('%s','now')*1000),
(25, '무한', 'infinite', strftime('%s','now')*1000),
(25, '무형', 'intangible', strftime('%s','now')*1000),
(25, '묵념', 'silent tribute', strftime('%s','now')*1000),
(25, '묵직하다', 'hefty/ weighty', strftime('%s','now')*1000),
(25, '묵히다', 'let sit/ age (store)', strftime('%s','now')*1000),
(25, '문과', 'liberal arts', strftime('%s','now')*1000),
(25, '문단02', 'literary world', strftime('%s','now')*1000),
(25, '문상', 'condolence visit', strftime('%s','now')*1000),
(25, '문안02', 'formal greeting/ asking after', strftime('%s','now')*1000),
(25, '문지르다', 'rub', strftime('%s','now')*1000),
(25, '"문학적01/\n문학적02"', 'literary', strftime('%s','now')*1000),
(25, '문헌', 'literature/ documents', strftime('%s','now')*1000),
(25, '물끄러미', 'vacantly/ blankly', strftime('%s','now')*1000),
(25, '물들이다', 'dye/ color', strftime('%s','now')*1000),
(25, '물러가다', 'step back/ retire', strftime('%s','now')*1000),
(25, '물리다03', 'be fed up with', strftime('%s','now')*1000),
(25, '"물리적01/\n물리적02"', 'physical', strftime('%s','now')*1000),
(25, '물자', 'supplies/ materials', strftime('%s','now')*1000),
(25, '물체', 'object', strftime('%s','now')*1000),
(25, '미각', 'sense of taste', strftime('%s','now')*1000),
(25, '미남', 'handsome man', strftime('%s','now')*1000),
(25, '미달', 'falling short', strftime('%s','now')*1000),
(25, '미덕', 'virtue', strftime('%s','now')*1000),
(25, '미묘하다', 'subtle/ delicate', strftime('%s','now')*1000),
(25, '미사', 'Mass (Catholic)', strftime('%s','now')*1000),
(25, '미숙하다', 'immature', strftime('%s','now')*1000),
(25, '미술가', 'artist (fine arts)', strftime('%s','now')*1000),
(25, '미약하다', 'slight/ feeble', strftime('%s','now')*1000),
(25, '미어지다', 'be jam-packed/ be crammed', strftime('%s','now')*1000),
(25, '미정', 'undecided', strftime('%s','now')*1000),
(25, '미지', 'unknown', strftime('%s','now')*1000),
(25, '미혼모', 'single mother', strftime('%s','now')*1000),
(25, '미흡하다', 'insufficient/ inadequate', strftime('%s','now')*1000),
(25, '민간', 'private/ civilian', strftime('%s','now')*1000),
(25, '민간단체00', 'civic organization', strftime('%s','now')*1000),
(25, '민망하다', 'embarrassed/ ashamed', strftime('%s','now')*1000),
(25, '민족주의', 'nationalism', strftime('%s','now')*1000),
(25, '민주', 'democracy', strftime('%s','now')*1000),
(25, '"민주적01∙\n민주적02"', 'democratic', strftime('%s','now')*1000),
(25, '민주화', 'democratization', strftime('%s','now')*1000),
(25, '민첩하다', 'agile/ nimble', strftime('%s','now')*1000),
(25, '밀도', 'density', strftime('%s','now')*1000),
(25, '밀려나다', 'be pushed out', strftime('%s','now')*1000),
(25, '밀려들다', 'pour in/ stream in', strftime('%s','now')*1000),
(25, '밀림', 'jungle', strftime('%s','now')*1000),
(25, '밀어붙이다', 'push ahead', strftime('%s','now')*1000),
(25, '밀어주다', 'back/ support', strftime('%s','now')*1000),
(25, '밀접', 'close/ intimate', strftime('%s','now')*1000),
(25, '밀착', 'close adhesion/ close attachment', strftime('%s','now')*1000),
(25, '밑거름', 'base fertilizer/ foundation', strftime('%s','now')*1000),
(25, '밑창', 'sole (of a shoe)', strftime('%s','now')*1000),
(25, '바래다01', 'fade (in color)', strftime('%s','now')*1000),
(25, '바삐', 'busily', strftime('%s','now')*1000),
(25, '바짝', 'very close/ completely', strftime('%s','now')*1000),
(25, '바퀴벌레', 'cockroach', strftime('%s','now')*1000),
(25, '박자', 'beat/ tempo', strftime('%s','now')*1000),
(25, '박탈', 'deprivation', strftime('%s','now')*1000),
(25, '반감', 'antipathy/ hostility', strftime('%s','now')*1000),
(25, '반나절', 'half a day', strftime('%s','now')*1000),
(25, '반도', 'peninsula', strftime('%s','now')*1000),
(25, '반도체', 'semiconductor', strftime('%s','now')*1000),
(25, '반론', 'counterargument', strftime('%s','now')*1000),
(25, '반목', 'animosity/ discord', strftime('%s','now')*1000),
(25, '반세기', 'half a century', strftime('%s','now')*1000),
(25, '반신욕', 'half-body bath', strftime('%s','now')*1000),
(25, '반주01', 'accompaniment', strftime('%s','now')*1000),
(25, '반칙', 'foul/ rule infraction', strftime('%s','now')*1000),
(25, '받들다', 'revere', strftime('%s','now')*1000),
(25, '발각', 'detection/ discovery', strftime('%s','now')*1000),
(25, '발굴', 'excavation', strftime('%s','now')*1000),
(25, '발단', 'beginning/ start', strftime('%s','now')*1000),
(25, '발돋움', 'rise/ stepping up', strftime('%s','now')*1000),
(25, '발령', 'appointment (to post)', strftime('%s','now')*1000),
(25, '발병02', 'outbreak (of disease)', strftime('%s','now')*1000),
(25, '발상02', 'idea/ conception', strftime('%s','now')*1000),
(25, '밥벌이', 'livelihood', strftime('%s','now')*1000),
(25, '밧줄', 'rope', strftime('%s','now')*1000),
(25, '방귀', 'fart', strftime('%s','now')*1000),
(25, '방범', 'crime prevention', strftime('%s','now')*1000),
(25, '방사능', 'radioactivity', strftime('%s','now')*1000),
(25, '방어', 'defense', strftime('%s','now')*1000),
(25, '방언', 'dialect', strftime('%s','now')*1000),
(25, '방치', 'neglect/ leave unattended', strftime('%s','now')*1000),
(25, '방침', 'policy', strftime('%s','now')*1000),
(25, '방패', 'shield', strftime('%s','now')*1000),
(25, '배상02', 'compensation (damages)', strftime('%s','now')*1000),
(25, '배설', 'excretion/ discharge', strftime('%s','now')*1000),
(25, '배신', 'betrayal', strftime('%s','now')*1000),
(25, '배역', 'role (cast)', strftime('%s','now')*1000),
(25, '배제', 'exclusion', strftime('%s','now')*1000),
(25, '배출00', 'emission/ discharge', strftime('%s','now')*1000),
(25, '배타적01∙배타적02', 'exclusive', strftime('%s','now')*1000),
(25, '배포', 'distribution', strftime('%s','now')*1000),
(25, '배회', 'wandering/ loitering', strftime('%s','now')*1000),
(25, '배후', 'background/ behind', strftime('%s','now')*1000),
(25, '백년해로', 'live together to old age', strftime('%s','now')*1000),
(25, '백미02', 'best part/ highlight', strftime('%s','now')*1000),
(25, '백수01', 'unemployed person', strftime('%s','now')*1000),
(25, '백지', 'blank paper/ blank slate', strftime('%s','now')*1000),
(25, '백혈병', 'leukemia', strftime('%s','now')*1000),
(25, '번성', 'thriving/ prosperity', strftime('%s','now')*1000),
(25, '번식', 'reproduction/ breeding', strftime('%s','now')*1000),
(25, '번영', 'prosperity', strftime('%s','now')*1000),
(25, '번쩍02', 'in a flash/ flash', strftime('%s','now')*1000),
(25, '번창', 'flourishing/ prosperity', strftime('%s','now')*1000),
(25, '벌판', 'open field/ plain', strftime('%s','now')*1000),
(25, '범주', 'category', strftime('%s','now')*1000),
(25, '범하다', 'commit (a crime)', strftime('%s','now')*1000),
(25, '범행', 'criminal act', strftime('%s','now')*1000),
(25, '법률가', 'jurist/ lawyer', strftime('%s','now')*1000),
(25, '법안', 'bill (legislative)', strftime('%s','now')*1000),
(25, '법정01', 'court (of law)', strftime('%s','now')*1000),
(25, '벗', 'friend/ companion', strftime('%s','now')*1000),
(25, '벤처', 'venture (startup)', strftime('%s','now')*1000),
(25, '벼르다', 'bide one’s time/ plan', strftime('%s','now')*1000),
(25, '벽화', 'mural', strftime('%s','now')*1000),
(25, '변02', 'feces/ stool', strftime('%s','now')*1000),
(25, '변덕', 'fickleness', strftime('%s','now')*1000),
(25, '변두리', 'outskirts/ fringe', strftime('%s','now')*1000),
(25, '변모', 'transformation', strftime('%s','now')*1000),
(25, '변변찮다', 'poor/ inferior', strftime('%s','now')*1000),
(25, '변수', 'variable', strftime('%s','now')*1000),
(25, '변천', 'change/ vicissitudes', strftime('%s','now')*1000),
(25, '변형', 'transformation/ deformation', strftime('%s','now')*1000),
(25, '변호', 'legal defense', strftime('%s','now')*1000),
(25, '변화무쌍', 'ever-changing', strftime('%s','now')*1000),
(25, '별개', 'separate/ different', strftime('%s','now')*1000),
(25, '별안간', 'suddenly', strftime('%s','now')*1000),
(25, '별의별', 'all sorts of', strftime('%s','now')*1000),
(25, '병동', 'ward', strftime('%s','now')*1000),
(25, '병상', 'sickbed', strftime('%s','now')*1000),
(25, '병세', 'course of illness/ condition', strftime('%s','now')*1000),
(25, '병적01∙병적02', 'pathological', strftime('%s','now')*1000),
(25, '병행', 'concurrently/ in parallel', strftime('%s','now')*1000),
(25, '보건', 'public health', strftime('%s','now')*1000),
(25, '보답', 'recompense/ repayment', strftime('%s','now')*1000),
(25, '보류', 'deferment/ holdover', strftime('%s','now')*1000),
(25, '보배', 'treasure', strftime('%s','now')*1000),
(25, '보복', 'retaliation', strftime('%s','now')*1000),
(25, '보유', 'possession/ holding', strftime('%s','now')*1000),
(25, '보육원', 'orphanage/ childcare home', strftime('%s','now')*1000),
(25, '보잘것없다', 'insignificant/ trivial', strftime('%s','now')*1000),
(25, '보조금', 'subsidy/ grant', strftime('%s','now')*1000),
(25, '보태다', 'add/ supplement', strftime('%s','now')*1000),
(25, '보호자', 'guardian/ protector', strftime('%s','now')*1000),
(25, '복귀', 'return/ comeback', strftime('%s','now')*1000),
(25, '복리01', 'welfare', strftime('%s','now')*1000),
(25, '복부', 'abdomen', strftime('%s','now')*1000),
(25, '복수02', 'revenge', strftime('%s','now')*1000),
(25, '복장', 'attire/ dress', strftime('%s','now')*1000),
(25, '복제', 'duplication/ cloning', strftime('%s','now')*1000),
(25, '복종', 'obedience', strftime('%s','now')*1000),
(25, '복합적01∙복합적02', 'complex/ composite', strftime('%s','now')*1000),
(25, '본격화00', 'going full-scale', strftime('%s','now')*1000),
(25, '본성', 'inherent nature', strftime('%s','now')*1000),
(25, '본전', 'principal/ stake', strftime('%s','now')*1000),
(25, '봉우리', 'peak/ summit', strftime('%s','now')*1000),
(25, '봐주다', 'go easy on/ overlook', strftime('%s','now')*1000),
(25, '부가', 'addition/ extra', strftime('%s','now')*1000),
(25, '부각', 'highlighting/ bring into relief', strftime('%s','now')*1000),
(25, '부고02', 'obituary', strftime('%s','now')*1000),
(25, '부닥치다', 'bump into/ face', strftime('%s','now')*1000),
(25, '부당', 'unjust/ unfair', strftime('%s','now')*1000),
(25, '부도01', 'default/ dishonor (of note)', strftime('%s','now')*1000),
(25, '부도나다', 'default/ go bankrupt', strftime('%s','now')*1000),
(25, '부득이', 'unavoidable', strftime('%s','now')*1000),
(25, '부디', 'please', strftime('%s','now')*1000),
(25, '부르짖다', 'cry out/ shout', strftime('%s','now')*1000),
(25, '부리다01', 'use/ wield/ display', strftime('%s','now')*1000),
(25, '부설', 'installation/ laying', strftime('%s','now')*1000),
(25, '부실', 'weak/ poor (quality)', strftime('%s','now')*1000),
(25, '부양', 'support (financial)', strftime('%s','now')*1000),
(25, '부응', 'meet/ live up to', strftime('%s','now')*1000),
(25, '부임', 'assumption of office', strftime('%s','now')*1000),
(25, '부재', 'absence', strftime('%s','now')*1000),
(25, '부진', 'sluggishness/ slump', strftime('%s','now')*1000),
(25, '부착', 'attachment/ adhesion', strftime('%s','now')*1000),
(25, '부추기다', 'instigate/ stir up', strftime('%s','now')*1000);