PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(17, '가01', 'song', strftime('%s','now')*1000),
(17, '-가04', 'street (suffix)', strftime('%s','now')*1000),
(17, '-가06', 'family/ house (suffix)', strftime('%s','now')*1000),
(17, '가곡', 'art song', strftime('%s','now')*1000),
(17, '가공01', 'processing/ manufacture', strftime('%s','now')*1000),
(17, '가구01', 'furniture', strftime('%s','now')*1000),
(17, '가급적01/가급적02', 'if possible/ preferably', strftime('%s','now')*1000),
(17, '가느다랗다', 'very thin/ slender', strftime('%s','now')*1000),
(17, '가닥', 'strand/ clue', strftime('%s','now')*1000),
(17, '가로수', 'roadside tree', strftime('%s','now')*1000),
(17, '가리다01', 'to cover/ to block/ to distinguish', strftime('%s','now')*1000),
(17, '가면', 'mask', strftime('%s','now')*1000),
(17, '가문', 'family/ lineage/ clan', strftime('%s','now')*1000),
(17, '가부장적01∙가부장적02', 'patriarchal', strftime('%s','now')*1000),
(17, '가사01', 'lyrics', strftime('%s','now')*1000),
(17, '가속화', 'acceleration', strftime('%s','now')*1000),
(17, '가시01', 'thorn/ spine', strftime('%s','now')*1000),
(17, '가시다', 'to subside/ to go away', strftime('%s','now')*1000),
(17, '가야금', 'gayageum (Korean zither)', strftime('%s','now')*1000),
(17, '가옥', 'house/ building', strftime('%s','now')*1000),
(17, '가요계', 'pop music industry', strftime('%s','now')*1000),
(17, '가장자리', 'edge/ rim/ border', strftime('%s','now')*1000),
(17, '가중', 'aggravation/ increase (of penalty)', strftime('%s','now')*1000),
(17, '가지런히', 'neatly/ evenly', strftime('%s','now')*1000),
(17, '가창력', 'vocal ability', strftime('%s','now')*1000),
(17, '가축', 'livestock', strftime('%s','now')*1000),
(17, '가해자', 'perpetrator/ assailant', strftime('%s','now')*1000),
(17, '각광', 'spotlight/ limelight', strftime('%s','now')*1000),
(17, '각지', 'various places/ every region', strftime('%s','now')*1000),
(17, '간간이', 'occasionally/ at times', strftime('%s','now')*1000),
(17, '간결하다', 'concise', strftime('%s','now')*1000),
(17, '간소하다', 'simple/ plain', strftime('%s','now')*1000),
(17, '간절히', 'earnestly/ ardently', strftime('%s','now')*1000),
(17, '간접', 'indirect/ indirectly', strftime('%s','now')*1000),
(17, '간직00', 'to keep/ to treasure', strftime('%s','now')*1000),
(17, '갈다02', 'to replace/ to change', strftime('%s','now')*1000),
(17, '갈대', 'reed', strftime('%s','now')*1000),
(17, '감격', 'deep emotion/ being moved', strftime('%s','now')*1000),
(17, '감기다02', 'to be wound (around)/ to close (eyes)', strftime('%s','now')*1000),
(17, '감미롭다', 'sweet/ mellifluous', strftime('%s','now')*1000),
(17, '감사03', 'audit/ inspector', strftime('%s','now')*1000),
(17, '감상01', 'appreciation (of art/music)', strftime('%s','now')*1000),
(17, '감상적01∙감상적02', 'sentimental', strftime('%s','now')*1000),
(17, '감성', 'emotion/ sensitivity', strftime('%s','now')*1000),
(17, '감성적01∙감성적02', 'emotional/ sentimental', strftime('%s','now')*1000),
(17, '감염', 'infection', strftime('%s','now')*1000),
(17, '감정적01∙감정적02', 'emotional', strftime('%s','now')*1000),
(17, '감탄', 'admiration/ exclamation', strftime('%s','now')*1000),
(17, '감탄사', 'interjection', strftime('%s','now')*1000),
(17, '갑01', 'first/ A (grade/class)', strftime('%s','now')*1000),
(17, '갑갑하다', 'stifled/ stuffy/ frustrated', strftime('%s','now')*1000),
(17, '값지다', 'valuable/ precious', strftime('%s','now')*1000),
(17, '강국', 'powerful nation', strftime('%s','now')*1000),
(17, '강당', 'auditorium', strftime('%s','now')*1000),
(17, '강대국', 'great power', strftime('%s','now')*1000),
(17, '강도02', 'robber/ robbery', strftime('%s','now')*1000),
(17, '강력00', 'powerful/ strong', strftime('%s','now')*1000),
(17, '강력히', 'strongly/ firmly', strftime('%s','now')*1000),
(17, '강렬하다', 'intense/ strong', strftime('%s','now')*1000),
(17, '강산01', 'rivers and mountains/ landscape', strftime('%s','now')*1000),
(17, '강연', 'lecture/ talk', strftime('%s','now')*1000),
(17, '강우량', 'rainfall (amount)', strftime('%s','now')*1000),
(17, '강자', 'the strong/ a powerful person', strftime('%s','now')*1000),
(17, '강좌', 'course/ lecture series', strftime('%s','now')*1000),
(17, '강풍', 'strong wind/ gale', strftime('%s','now')*1000),
(17, '강화', 'strengthening/ reinforcement', strftime('%s','now')*1000),
(17, '갖은', 'various/ all kinds of', strftime('%s','now')*1000),
(17, '개강', 'start of classes', strftime('%s','now')*1000),
(17, '개개인', 'each individual', strftime('%s','now')*1000),
(17, '개국01', 'founding of a nation/ opening (of broadcasting)', strftime('%s','now')*1000),
(17, '개막식', 'opening ceremony', strftime('%s','now')*1000),
(17, '개방적01∙개방적02', 'open/ liberal (in attitude)', strftime('%s','now')*1000),
(17, '개봉', 'release/ premiere', strftime('%s','now')*1000),
(17, '개설', 'establishment/ opening', strftime('%s','now')*1000),
(17, '개수', 'number (of items)', strftime('%s','now')*1000),
(17, '개업', 'opening a business', strftime('%s','now')*1000),
(17, '개요', 'outline/ summary', strftime('%s','now')*1000),
(17, '개인주의', 'individualism', strftime('%s','now')*1000),
(17, '개장', 'opening (of market/park)', strftime('%s','now')*1000),
(17, '개조01', 'remodeling/ renovation', strftime('%s','now')*1000),
(17, '개척', 'pioneering/ development', strftime('%s','now')*1000),
(17, '개통', 'opening (to traffic/service)', strftime('%s','now')*1000),
(17, '객석', 'auditorium seat', strftime('%s','now')*1000),
(17, '객실', 'guest room/ hotel room', strftime('%s','now')*1000),
(17, '거느리다', 'to lead/ to command/ to head', strftime('%s','now')*1000),
(17, '거닐다', 'to stroll/ to saunter', strftime('%s','now')*1000),
(17, '거리02', 'distance', strftime('%s','now')*1000),
(17, '거만', 'arrogance/ haughtiness', strftime('%s','now')*1000),
(17, '거부02', 'rejection/ refusal', strftime('%s','now')*1000),
(17, '거세다', 'strong/ fierce/ intense', strftime('%s','now')*1000),
(17, '거액', 'a large sum (of money)', strftime('%s','now')*1000),
(17, '거인', 'giant', strftime('%s','now')*1000),
(17, '거주', 'residence/ residing', strftime('%s','now')*1000),
(17, '거주자', 'resident', strftime('%s','now')*1000),
(17, '걱정거리', 'cause of worry/ concern', strftime('%s','now')*1000),
(17, '건00/건01', 'matter/ case/ affair', strftime('%s','now')*1000),
(17, '건국', 'founding of a nation', strftime('%s','now')*1000),
(17, '건기', 'dry season', strftime('%s','now')*1000),
(17, '건망증', 'amnesia/ forgetfulness', strftime('%s','now')*1000),
(17, '건설업', 'construction industry', strftime('%s','now')*1000),
(17, '건수', 'number of cases', strftime('%s','now')*1000),
(17, '건의', 'proposal/ suggestion', strftime('%s','now')*1000),
(17, '건축가', 'architect', strftime('%s','now')*1000),
(17, '건축물', 'architectural structure/ building', strftime('%s','now')*1000),
(17, '걷어차다', 'to kick away/ to kick', strftime('%s','now')*1000),
(17, '걸음걸이', 'gait/ way of walking', strftime('%s','now')*1000),
(17, '검', 'sword', strftime('%s','now')*1000),
(17, '검진', 'medical checkup/ screening', strftime('%s','now')*1000),
(17, '겁내다', 'to be scared/ to fear', strftime('%s','now')*1000),
(17, '겉보기', 'outward appearance/ looks', strftime('%s','now')*1000),
(17, '겨드랑이', 'armpit', strftime('%s','now')*1000),
(17, '겨를', 'spare time/ leisure', strftime('%s','now')*1000),
(17, '격01/격02', 'class/ rank/ dignity', strftime('%s','now')*1000),
(17, '격렬하다', 'fierce/ intense/ violent', strftime('%s','now')*1000),
(17, '격식', 'formality/ formalities', strftime('%s','now')*1000),
(17, '결말', 'ending/ conclusion', strftime('%s','now')*1000),
(17, '결별', 'parting/ breakup', strftime('%s','now')*1000),
(17, '결승전', 'final match', strftime('%s','now')*1000),
(17, '결실', 'fruit/ fruition/ result', strftime('%s','now')*1000),
(17, '결재', 'approval/ authorization', strftime('%s','now')*1000),
(17, '결정적01∙결정적02', 'decisive/ crucial', strftime('%s','now')*1000),
(17, '겸', 'and/ also (dual role)', strftime('%s','now')*1000),
(17, '겸하다', 'to double as/ to serve also as', strftime('%s','now')*1000),
(17, '겹', 'layer/ fold', strftime('%s','now')*1000),
(17, '-경01', 'lightly/ slightly (adverbial suffix)', strftime('%s','now')*1000),
(17, '경과', 'elapse/ course/ progress', strftime('%s','now')*1000),
(17, '경비02', 'security/ guard', strftime('%s','now')*1000),
(17, '경솔하다', 'rash/ careless', strftime('%s','now')*1000),
(17, '경영자', 'manager/ executive', strftime('%s','now')*1000),
(17, '경영학', 'business administration', strftime('%s','now')*1000),
(17, '경위02', 'details/ circumstances', strftime('%s','now')*1000),
(17, '경쟁률', 'competition rate/ acceptance rate', strftime('%s','now')*1000),
(17, '경쟁적01∙경쟁적02', 'competitive', strftime('%s','now')*1000),
(17, '경제학', 'economics', strftime('%s','now')*1000),
(17, '경조사', 'family events (happy and sad)', strftime('%s','now')*1000),
(17, '경주02', 'race/ racing', strftime('%s','now')*1000),
(17, '경찰청', 'National Police Agency', strftime('%s','now')*1000),
(17, '경쾌하다', 'light/ cheerful', strftime('%s','now')*1000),
(17, '경품', 'free gift/ giveaway prize', strftime('%s','now')*1000),
(17, '경험담', 'account of experience/ story', strftime('%s','now')*1000),
(17, '경호', 'security/ guard (protection)', strftime('%s','now')*1000),
(17, '계00', 'lineage/ system/ series', strftime('%s','now')*1000),
(17, '-계04', 'system/ department (suffix)', strftime('%s','now')*1000),
(17, '계급', 'class/ rank', strftime('%s','now')*1000),
(17, '계발', 'development/ self-improvement', strftime('%s','now')*1000),
(17, '계열', 'affiliation/ line/ series', strftime('%s','now')*1000),
(17, '계획적01∙계획적02', 'planned/ systematic', strftime('%s','now')*1000),
(17, '고00', 'suffering/ hardship', strftime('%s','now')*1000),
(17, '고02', 'high/ tall', strftime('%s','now')*1000),
(17, '고-02', 'high- (prefix)', strftime('%s','now')*1000),
(17, '고가품', 'expensive item', strftime('%s','now')*1000),
(17, '고개02', 'nape (of the neck)', strftime('%s','now')*1000),
(17, '고교생', 'high school student', strftime('%s','now')*1000),
(17, '고구려', 'Goguryeo', strftime('%s','now')*1000),
(17, '고기압', 'high pressure (atmospheric)', strftime('%s','now')*1000),
(17, '고단하다', 'exhausted/ weary', strftime('%s','now')*1000),
(17, '고도00', 'altitude/ degree (of)', strftime('%s','now')*1000),
(17, '고려02', 'consideration', strftime('%s','now')*1000),
(17, '고르다03', 'even/ uniform', strftime('%s','now')*1000),
(17, '고리01', 'ring/ loop', strftime('%s','now')*1000),
(17, '고발', 'accusation/ report (to authorities)', strftime('%s','now')*1000),
(17, '고상하다', 'elegant/ refined', strftime('%s','now')*1000),
(17, '고생스럽다', 'hard/ laborious/ tough', strftime('%s','now')*1000),
(17, '고소01', 'lawsuit/ accusation', strftime('%s','now')*1000),
(17, '고아', 'orphan', strftime('%s','now')*1000),
(17, '고아원', 'orphanage', strftime('%s','now')*1000),
(17, '고온', 'high temperature', strftime('%s','now')*1000),
(17, '고원', 'plateau/ highland', strftime('%s','now')*1000),
(17, '고이다', 'to pool/ to collect (liquid)', strftime('%s','now')*1000),
(17, '고작01/고작02', 'only/ at most/ mere', strftime('%s','now')*1000),
(17, '고졸', 'high-school graduate', strftime('%s','now')*1000),
(17, '고지서', 'bill/ notice', strftime('%s','now')*1000),
(17, '고체', 'solid (state)', strftime('%s','now')*1000),
(17, '고학력', 'high educational background', strftime('%s','now')*1000),
(17, '고혈압', 'high blood pressure/ hypertension', strftime('%s','now')*1000),
(17, '곡물', 'grain/ cereals', strftime('%s','now')*1000),
(17, '곡선', 'curve', strftime('%s','now')*1000),
(17, '곤충', 'insect', strftime('%s','now')*1000),
(17, '골동품', 'antique', strftime('%s','now')*1000),
(17, '골치', 'head/ headache (figurative)', strftime('%s','now')*1000),
(17, '곱슬머리', 'curly hair', strftime('%s','now')*1000),
(17, '공00', 'ball/ zero/ emptiness (various senses)', strftime('%s','now')*1000),
(17, '공감대', 'consensus/ bond of sympathy', strftime('%s','now')*1000),
(17, '공경', 'respect/ reverence', strftime('%s','now')*1000),
(17, '공고02', 'announcement/ public notice', strftime('%s','now')*1000),
(17, '공고문', 'public notice (document)', strftime('%s','now')*1000),
(17, '공공시설', 'public facilities', strftime('%s','now')*1000),
(17, '공교육', 'public education', strftime('%s','now')*1000),
(17, '공군', 'air force', strftime('%s','now')*1000),
(17, '공룡', 'dinosaur', strftime('%s','now')*1000),
(17, '공문', 'official document', strftime('%s','now')*1000),
(17, '공사장', 'construction site', strftime('%s','now')*1000),
(17, '공상', 'daydream/ fantasy', strftime('%s','now')*1000),
(17, '공식적01∙공식적02', 'official/ formal', strftime('%s','now')*1000),
(17, '공예', 'craft/ handicraft', strftime('%s','now')*1000),
(17, '공유02', 'sharing', strftime('%s','now')*1000),
(17, '공익01', 'public interest', strftime('%s','now')*1000),
(17, '공중01', 'air/ the sky', strftime('%s','now')*1000),
(17, '공중02', 'public/ community', strftime('%s','now')*1000),
(17, '공통적01∙공통적02', 'common/ shared', strftime('%s','now')*1000),
(17, '공평하다', 'fair/ impartial', strftime('%s','now')*1000),
(17, '공포감', 'sense of fear/ dread', strftime('%s','now')*1000),
(17, '공학01', 'engineering', strftime('%s','now')*1000),
(17, '-과', 'and/ with (particle)', strftime('%s','now')*1000),
(17, '과01', 'lesson/ chapter/ department', strftime('%s','now')*1000),
(17, '과감하다', 'bold/ daring', strftime('%s','now')*1000),
(17, '과대평가', 'overestimation', strftime('%s','now')*1000),
(17, '과도하다', 'excessive/ too much', strftime('%s','now')*1000),
(17, '과반수', 'majority', strftime('%s','now')*1000),
(17, '과보호', 'overprotection', strftime('%s','now')*1000),
(17, '과소평가', 'underestimation', strftime('%s','now')*1000),
(17, '과언', 'exaggeration (not an overstatement)', strftime('%s','now')*1000),
(17, '과음', 'heavy drinking', strftime('%s','now')*1000),
(17, '과정02', 'process/ course', strftime('%s','now')*1000),
(17, '과하다01', 'excessive', strftime('%s','now')*1000),
(17, '-관01', 'related to/ concerning (suffix)', strftime('%s','now')*1000),
(17, '관공서', 'government office', strftime('%s','now')*1000),
(17, '관대하다02', 'generous/ lenient', strftime('%s','now')*1000),
(17, '관련짓다', 'to relate/ to connect', strftime('%s','now')*1000),
(17, '관습', 'custom/ convention', strftime('%s','now')*1000),
(17, '관용03', 'tolerance/ forbearance', strftime('%s','now')*1000),
(17, '관용어', 'idiom', strftime('%s','now')*1000),
(17, '관중', 'audience/ spectators', strftime('%s','now')*1000),
(17, '관청', 'government office', strftime('%s','now')*1000),
(17, '관하다', 'to concern/ to be about', strftime('%s','now')*1000),
(17, '관형사', 'adnominal (modifier)', strftime('%s','now')*1000),
(17, '광장', 'square/ plaza', strftime('%s','now')*1000),
(17, '괴물', 'monster', strftime('%s','now')*1000),
(17, '교과', 'subject/ curriculum', strftime('%s','now')*1000),
(17, '교도소', 'prison', strftime('%s','now')*1000),
(17, '교무실', 'teachers'' office', strftime('%s','now')*1000),
(17, '교원', 'teaching staff/ faculty', strftime('%s','now')*1000),
(17, '교육부', 'Ministry of Education', strftime('%s','now')*1000),
(17, '교육열', 'zeal for education', strftime('%s','now')*1000),
(17, '교육적01∙교육적02', 'educational', strftime('%s','now')*1000),
(17, '교제', 'dating/ association', strftime('%s','now')*1000),
(17, '교직', 'teaching profession', strftime('%s','now')*1000),
(17, '교훈적01∙교훈적02', 'instructive/ didactic', strftime('%s','now')*1000),
(17, '구간01', 'section/ segment', strftime('%s','now')*1000),
(17, '구겨지다', 'to get crumpled', strftime('%s','now')*1000),
(17, '구경꾼', 'spectator/ onlooker', strftime('%s','now')*1000),
(17, '구급차', 'ambulance', strftime('%s','now')*1000),
(17, '구내식당', 'cafeteria (company)', strftime('%s','now')*1000),
(17, '구독', 'subscription', strftime('%s','now')*1000),
(17, '구두02', 'oral/ verbal', strftime('%s','now')*1000),
(17, '구두쇠', 'miser', strftime('%s','now')*1000),
(17, '구르다02', 'to roll/ to tumble', strftime('%s','now')*1000),
(17, '구매자', 'buyer/ purchaser', strftime('%s','now')*1000),
(17, '구박', 'abuse/ mistreatment', strftime('%s','now')*1000),
(17, '구비02', 'to be equipped/ provision', strftime('%s','now')*1000),
(17, '구사', 'command/ use (of language/skill)', strftime('%s','now')*1000),
(17, '구상02', 'conception/ plan', strftime('%s','now')*1000),
(17, '구석구석', 'every nook and cranny', strftime('%s','now')*1000),
(17, '구성원', 'member (of a group)', strftime('%s','now')*1000),
(17, '구애02', 'wooing/ courtship/ constraint', strftime('%s','now')*1000),
(17, '구인01', 'recruitment/ hiring', strftime('%s','now')*1000),
(17, '구직', 'job seeking', strftime('%s','now')*1000),
(17, '구직난00', 'job shortage/ hiring slump', strftime('%s','now')*1000),
(17, '구직자00', 'job seeker', strftime('%s','now')*1000),
(17, '구청', 'district office', strftime('%s','now')*1000),
(17, '-국01', 'nation/ country (suffix)', strftime('%s','now')*1000),
(17, '-국02', 'soup/ broth (suffix/noun)', strftime('%s','now')*1000),
(17, '국도', 'national highway', strftime('%s','now')*1000),
(17, '국방부', 'Ministry of National Defense', strftime('%s','now')*1000),
(17, '국세청', 'National Tax Service', strftime('%s','now')*1000),
(17, '국악', 'Korean traditional music', strftime('%s','now')*1000),
(17, '국익', 'national interest', strftime('%s','now')*1000),
(17, '국토', 'national territory/ land', strftime('%s','now')*1000),
(17, '군01/군02', 'county/ army/ group', strftime('%s','now')*1000),
(17, '군03', 'Mr./ military/ group (bound)', strftime('%s','now')*1000),
(17, '군데군데01/군데군데02', 'here and there/ in places', strftime('%s','now')*1000),
(17, '굳히다', 'to harden/ to solidify', strftime('%s','now')*1000),
(17, '굴뚝', 'chimney', strftime('%s','now')*1000),
(17, '굴러가다', 'to roll/ to go along', strftime('%s','now')*1000),
(17, '궁02', 'palace', strftime('%s','now')*1000),
(17, '궁궐', 'royal palace', strftime('%s','now')*1000),
(17, '궁금증', 'curiosity', strftime('%s','now')*1000),
(17, '궁중', 'court/ royal court', strftime('%s','now')*1000),
(17, '권위적01∙권위적02', 'authoritarian', strftime('%s','now')*1000),
(17, '귓속말', 'whisper', strftime('%s','now')*1000),
(17, '그때그때00/그때그때', 'as the occasion demands', strftime('%s','now')*1000),
(17, '그래야00', 'only then/ that way', strftime('%s','now')*1000),
(17, '그리02', 'that much/ so', strftime('%s','now')*1000),
(17, '그리다01', 'to draw/ to paint', strftime('%s','now')*1000),
(17, '그리하여', 'and so/ thus', strftime('%s','now')*1000),
(17, '그물', 'net', strftime('%s','now')*1000),
(17, '극-', 'ultra-/ extreme (prefix)', strftime('%s','now')*1000),
(17, '극단적01∙극단적02', 'extreme', strftime('%s','now')*1000),
(17, '극심하다', 'severe/ extreme', strftime('%s','now')*1000),
(17, '근검절약', 'thrift and frugality', strftime('%s','now')*1000),
(17, '근로', 'labor/ work', strftime('%s','now')*1000),
(17, '근사하다', 'nice/ splendid/ wonderful', strftime('%s','now')*1000),
(17, '근원', 'source/ origin', strftime('%s','now')*1000),
(17, '근황', 'recent situation/ how one has been', strftime('%s','now')*1000),
(17, '글쓴이', 'author/ writer', strftime('%s','now')*1000),
(17, '금01', 'gold', strftime('%s','now')*1000),
(17, '금기', 'taboo', strftime('%s','now')*1000),
(17, '금리', 'interest rate', strftime('%s','now')*1000),
(17, '금메달', 'gold medal', strftime('%s','now')*1000),
(17, '금세', 'in no time/ quickly', strftime('%s','now')*1000),
(17, '금속', 'metal', strftime('%s','now')*1000),
(17, '금전', 'money/ funds', strftime('%s','now')*1000),
(17, '급02', 'grade/ class/ level', strftime('%s','now')*1000),
(17, '급격하다', 'rapid/ drastic', strftime('%s','now')*1000),
(17, '급상승', 'rapid rise', strftime('%s','now')*1000),
(17, '급속도', 'high speed/ rapid pace', strftime('%s','now')*1000),
(17, '급식', 'meal service/ school lunch', strftime('%s','now')*1000),
(17, '급여', 'salary/ pay', strftime('%s','now')*1000),
(17, '기01', 'flag/ spirit/ energy', strftime('%s','now')*1000),
(17, '기03', 'base/ foundation/ record', strftime('%s','now')*1000),
(17, '기04', 'period/ time/ machine (various senses)', strftime('%s','now')*1000),
(17, '-기05', 'nominalizer (gerund suffix)', strftime('%s','now')*1000),
(17, '기관00', 'organ/ institution/ engine', strftime('%s','now')*1000),
(17, '기구02', 'apparatus/ organization', strftime('%s','now')*1000),
(17, '기내', 'in-flight/ inside the plane', strftime('%s','now')*1000),
(17, '기대감', 'sense of expectation', strftime('%s','now')*1000),
(17, '기름기', 'fatty content/ oiliness', strftime('%s','now')*1000),
(17, '기름지다', 'fatty/ greasy/ fertile', strftime('%s','now')*1000),
(17, '기린', 'giraffe', strftime('%s','now')*1000),
(17, '기막히다', 'brilliant/ astounding/ absurd', strftime('%s','now')*1000),
(17, '기말', 'end of term/ final', strftime('%s','now')*1000),
(17, '기발하다', 'original/ ingenious', strftime('%s','now')*1000),
(17, '기부금', 'donation/ contribution', strftime('%s','now')*1000),
(17, '기상01', 'weather/ meteorology', strftime('%s','now')*1000),
(17, '기상청', 'Korea Meteorological Administration', strftime('%s','now')*1000),
(17, '기성세대', 'older generation', strftime('%s','now')*1000),
(17, '기세', 'spirit/ vigor/ momentum', strftime('%s','now')*1000),
(17, '기압', 'atmospheric pressure', strftime('%s','now')*1000),
(17, '기와집', 'tile-roofed house', strftime('%s','now')*1000),
(17, '기원01', 'origin/ beginning', strftime('%s','now')*1000),
(17, '기원전', 'B.C./ before Christ', strftime('%s','now')*1000),
(17, '기원후', 'A.D./ anno Domini', strftime('%s','now')*1000),
(17, '기일02', 'due date/ appointed day', strftime('%s','now')*1000),
(17, '기점', 'starting point', strftime('%s','now')*1000),
(17, '기증', 'donation (of goods/organs)', strftime('%s','now')*1000),
(17, '기체01', 'gas (state of matter)', strftime('%s','now')*1000),
(17, '기하다', 'to take/ to set (as a standard)', strftime('%s','now')*1000),
(17, '기한', 'deadline/ time limit', strftime('%s','now')*1000),
(17, '기행문', 'travel essay', strftime('%s','now')*1000),
(17, '기호01', 'symbol/ sign', strftime('%s','now')*1000),
(17, '기호02', 'preference/ taste', strftime('%s','now')*1000),
(17, '긴장감', 'tension/ sense of strain', strftime('%s','now')*1000),
(17, '김장', 'kimchi-making (for winter)', strftime('%s','now')*1000),
(17, '깃털', 'feather', strftime('%s','now')*1000),
(17, '까딱', 'slightly/ a bit (movement)', strftime('%s','now')*1000),
(17, '까치', 'magpie', strftime('%s','now')*1000),
(17, '깜짝하다01', 'to be startled/ surprised', strftime('%s','now')*1000),
(17, '깡충깡충', 'boing boing/ hop hop', strftime('%s','now')*1000),
(17, '꺼지다02', 'to be turned off/ to go out', strftime('%s','now')*1000),
(17, '꺾이다', 'to be broken/ to be bent', strftime('%s','now')*1000),
(17, '껍데기', 'shell/ husk/ peel', strftime('%s','now')*1000);