PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(10, '천장', 'ceiling', strftime('%s','now')*1000),
(10, '천재', 'genius', strftime('%s','now')*1000),
(10, '철', 'season / iron', strftime('%s','now')*1000),
(10, '철도', 'railroad / railway', strftime('%s','now')*1000),
(10, '첫눈', 'first snow / first sight', strftime('%s','now')*1000),
(10, '첫인상', 'first impression', strftime('%s','now')*1000),
(10, '청소기', 'vacuum cleaner', strftime('%s','now')*1000),
(10, '청혼', 'marriage proposal', strftime('%s','now')*1000),
(10, '체력', 'physical strength', strftime('%s','now')*1000),
(10, '체크무늬', 'check pattern / plaid', strftime('%s','now')*1000),
(10, '체하다', 'pretend / have indigestion', strftime('%s','now')*1000),
(10, '체험', 'experience (hands-on)', strftime('%s','now')*1000),
(10, '초급', 'beginner level', strftime('%s','now')*1000),
(10, '초록', 'green color', strftime('%s','now')*1000),
(10, '촌스럽다', 'old-fashioned / countrified', strftime('%s','now')*1000),
(10, '총', 'gun / total', strftime('%s','now')*1000),
(10, '촬영', 'filming / shooting', strftime('%s','now')*1000),
(10, '최고급', 'highest class / luxury', strftime('%s','now')*1000),
(10, '최선', 'the best / one’s best effort', strftime('%s','now')*1000),
(10, '최저', 'lowest / minimum', strftime('%s','now')*1000),
(10, '추억', 'memory / recollection', strftime('%s','now')*1000),
(10, '추천', 'recommendation', strftime('%s','now')*1000),
(10, '추측', 'guess / speculation', strftime('%s','now')*1000),
(10, '축구장', 'soccer field', strftime('%s','now')*1000),
(10, '축제', 'festival', strftime('%s','now')*1000),
(10, '출국', 'departure from a country', strftime('%s','now')*1000),
(10, '충분히', 'enough / sufficiently', strftime('%s','now')*1000),
(10, '취하다', 'get drunk / adopt / take', strftime('%s','now')*1000),
(10, '취향', 'preference / taste', strftime('%s','now')*1000),
(10, '치다', 'hit / play / strike', strftime('%s','now')*1000),
(10, '치료법', 'treatment method / therapy', strftime('%s','now')*1000),
(10, '치르다', 'pay / hold / undergo', strftime('%s','now')*1000),
(10, '치수', 'size / measurement', strftime('%s','now')*1000),
(10, '치우다', 'clean up / remove', strftime('%s','now')*1000),
(10, '치즈', 'cheese', strftime('%s','now')*1000),
(10, '친-', 'prefix meaning close / intimate', strftime('%s','now')*1000),
(10, '친딸', 'one’s own daughter', strftime('%s','now')*1000),
(10, '칸', 'space / compartment', strftime('%s','now')*1000),
(10, '커지다', 'grow / become larger', strftime('%s','now')*1000),
(10, '커튼', 'curtain', strftime('%s','now')*1000),
(10, '코너', 'corner / section', strftime('%s','now')*1000),
(10, '코미디', 'comedy', strftime('%s','now')*1000),
(10, '코스', 'course / route', strftime('%s','now')*1000),
(10, '코트', 'coat / court (tennis etc.)', strftime('%s','now')*1000),
(10, '코피', 'nosebleed', strftime('%s','now')*1000),
(10, '콘도', 'condominium / resort condo', strftime('%s','now')*1000),
(10, '콜록콜록', 'coughing sound', strftime('%s','now')*1000),
(10, '콧노래', 'humming / hum tune', strftime('%s','now')*1000),
(10, '큰길', 'main road', strftime('%s','now')*1000),
(10, '큰아버지', 'uncle (father’s older brother)', strftime('%s','now')*1000),
(10, '큰어머니', 'aunt (older uncle’s wife)', strftime('%s','now')*1000),
(10, '클래식', 'classical music / classic', strftime('%s','now')*1000),
(10, '키스', 'kiss', strftime('%s','now')*1000),
(10, '탁자', 'table', strftime('%s','now')*1000),
(10, '탑승', 'boarding', strftime('%s','now')*1000),
(10, '탑승객', 'passenger / boarding person', strftime('%s','now')*1000),
(10, '태우다', 'burn / give a ride', strftime('%s','now')*1000),
(10, '터뜨리다', 'burst / pop', strftime('%s','now')*1000),
(10, '털', 'hair / fur', strftime('%s','now')*1000),
(10, '털다', 'shake off / empty / clean out', strftime('%s','now')*1000),
(10, '테이프', 'tape / cassette', strftime('%s','now')*1000),
(10, '토', 'soil / Saturday / vomit', strftime('%s','now')*1000),
(10, '토론', 'discussion / debate', strftime('%s','now')*1000),
(10, '토하다', 'vomit', strftime('%s','now')*1000),
(10, '통', 'container / communication / pass', strftime('%s','now')*1000),
(10, '통신', 'communication / correspondence', strftime('%s','now')*1000),
(10, '통역', 'interpretation / translator', strftime('%s','now')*1000),
(10, '통일', 'unification', strftime('%s','now')*1000),
(10, '통통하다', 'chubby / plump', strftime('%s','now')*1000),
(10, '통하다', 'go through / communicate / flow', strftime('%s','now')*1000),
(10, '특기', 'special skill / specialty', strftime('%s','now')*1000),
(10, '특성', 'characteristic / property', strftime('%s','now')*1000),
(10, '특징', 'feature / trait', strftime('%s','now')*1000),
(10, '틀림없이', 'certainly / surely', strftime('%s','now')*1000),
(10, '틈틈이', 'in one’s spare time / from time to time', strftime('%s','now')*1000),
(10, '파', 'green onion / group / faction', strftime('%s','now')*1000),
(10, '파다', 'dig', strftime('%s','now')*1000),
(10, '파도', 'wave', strftime('%s','now')*1000),
(10, '파랑', 'blue color / wave', strftime('%s','now')*1000),
(10, '파마', 'perm (hairstyle)', strftime('%s','now')*1000),
(10, '파일', 'file', strftime('%s','now')*1000),
(10, '파출소', 'police substation', strftime('%s','now')*1000),
(10, '판매', 'sale / selling', strftime('%s','now')*1000),
(10, '패션', 'fashion', strftime('%s','now')*1000),
(10, '팬티', 'underpants', strftime('%s','now')*1000),
(10, '퍼센트', 'percent', strftime('%s','now')*1000),
(10, '페이지', 'page', strftime('%s','now')*1000),
(10, '편', 'side / direction / episode', strftime('%s','now')*1000),
(10, '편식', 'picky eating / unbalanced diet', strftime('%s','now')*1000),
(10, '평가', 'evaluation / assessment', strftime('%s','now')*1000),
(10, '포기', 'giving up / abandonment', strftime('%s','now')*1000),
(10, '포도주', 'wine', strftime('%s','now')*1000),
(10, '포크', 'fork', strftime('%s','now')*1000),
(10, '포함', 'inclusion / contain', strftime('%s','now')*1000),
(10, '폭포', 'waterfall', strftime('%s','now')*1000),
(10, '표', 'ticket / sign / table / chart', strftime('%s','now')*1000),
(10, '표시', 'mark / indication', strftime('%s','now')*1000),
(10, '표정', 'facial expression', strftime('%s','now')*1000),
(10, '표지판', 'signboard / notice', strftime('%s','now')*1000),
(10, '표현', 'expression / representation', strftime('%s','now')*1000),
(10, '풀', 'grass / glue', strftime('%s','now')*1000),
(10, '풀리다', 'be untied / be relieved', strftime('%s','now')*1000),
(10, '품질', 'quality of product', strftime('%s','now')*1000),
(10, '풍선', 'balloon', strftime('%s','now')*1000),
(10, '풍습', 'custom / practice', strftime('%s','now')*1000),
(10, '프린터', 'printer', strftime('%s','now')*1000),
(10, '플라스틱', 'plastic', strftime('%s','now')*1000),
(10, '피로', 'fatigue / tiredness', strftime('%s','now')*1000),
(10, '피부', 'skin', strftime('%s','now')*1000),
(10, '피서', 'summer vacation / escape from heat', strftime('%s','now')*1000),
(10, '피하다', 'avoid / escape', strftime('%s','now')*1000),
(10, '피해', 'damage / harm', strftime('%s','now')*1000),
(10, '피해자', 'victim', strftime('%s','now')*1000),
(10, '하나하나', 'one by one / each', strftime('%s','now')*1000),
(10, '하숙', 'boarding / lodging', strftime('%s','now')*1000),
(10, '하양', 'white color', strftime('%s','now')*1000),
(10, '하차', 'get off / disembark', strftime('%s','now')*1000),
(10, '하품', 'yawn', strftime('%s','now')*1000),
(10, '하하', 'haha / laughter', strftime('%s','now')*1000),
(10, '학과', 'department (university)', strftime('%s','now')*1000),
(10, '학습', 'learning / study', strftime('%s','now')*1000),
(10, '학자', 'scholar / academic', strftime('%s','now')*1000),
(10, '한국말', 'Korean language (spoken)', strftime('%s','now')*1000),
(10, '한국어', 'Korean language', strftime('%s','now')*1000),
(10, '한국인', 'Korean person', strftime('%s','now')*1000),
(10, '한동안', 'for a while / for some time', strftime('%s','now')*1000),
(10, '한때', 'once / at one time', strftime('%s','now')*1000),
(10, '한문', 'classical Chinese', strftime('%s','now')*1000),
(10, '한숨', 'sigh / rest', strftime('%s','now')*1000),
(10, '한자', 'Chinese character', strftime('%s','now')*1000),
(10, '한쪽', 'one side / one direction', strftime('%s','now')*1000),
(10, '한참', 'for quite a while / long time', strftime('%s','now')*1000),
(10, '할인점', 'discount store', strftime('%s','now')*1000),
(10, '합격', 'pass / success (exam)', strftime('%s','now')*1000),
(10, '합계', 'total / sum', strftime('%s','now')*1000),
(10, '합치다', 'combine / unite / match', strftime('%s','now')*1000),
(10, '항공료', 'airfare', strftime('%s','now')*1000),
(10, '해결', 'solution / resolution', strftime('%s','now')*1000),
(10, '해돋이', 'sunrise', strftime('%s','now')*1000),
(10, '해물', 'seafood', strftime('%s','now')*1000),
(10, '해변', 'beach / seaside', strftime('%s','now')*1000),
(10, '해산물', 'seafood / marine product', strftime('%s','now')*1000),
(10, '해수욕장', 'beach for swimming / seaside resort', strftime('%s','now')*1000),
(10, '핸드백', 'handbag / purse', strftime('%s','now')*1000),
(10, '햇볕', 'sunlight / sunshine', strftime('%s','now')*1000),
(10, '행사장', 'event hall / venue', strftime('%s','now')*1000),
(10, '행운', 'luck / good fortune', strftime('%s','now')*1000),
(10, '향수', 'perfume / nostalgia', strftime('%s','now')*1000),
(10, '향하다', 'head toward / face / aim', strftime('%s','now')*1000),
(10, '허락', 'permission / approval', strftime('%s','now')*1000),
(10, '허리띠', 'belt', strftime('%s','now')*1000),
(10, '허벅지', 'thigh', strftime('%s','now')*1000),
(10, '현관', 'entrance / doorway', strftime('%s','now')*1000),
(10, '현대', 'modern times / Hyundai (brand)', strftime('%s','now')*1000),
(10, '형태', 'form / shape / structure', strftime('%s','now')*1000),
(10, '호두', 'walnut', strftime('%s','now')*1000),
(10, '호박', 'pumpkin / amber', strftime('%s','now')*1000),
(10, '호실', 'room number', strftime('%s','now')*1000),
(10, '혹은', 'or / alternatively', strftime('%s','now')*1000),
(10, '혼나다', 'get scolded / have a hard time', strftime('%s','now')*1000),
(10, '홈페이지', 'homepage / website', strftime('%s','now')*1000),
(10, '화', 'anger / fire / Tuesday', strftime('%s','now')*1000),
(10, '화면', 'screen / display', strftime('%s','now')*1000),
(10, '화분', 'flower pot / potted plant', strftime('%s','now')*1000),
(10, '화장', 'makeup / cremation', strftime('%s','now')*1000),
(10, '화장대', 'dressing table / vanity', strftime('%s','now')*1000),
(10, '화재', 'fire (accident)', strftime('%s','now')*1000),
(10, '화폐', 'currency / money', strftime('%s','now')*1000),
(10, '화해', 'reconciliation / making up', strftime('%s','now')*1000),
(10, '확인', 'confirmation / check / verify', strftime('%s','now')*1000),
(10, '환불', 'refund', strftime('%s','now')*1000),
(10, '환상적', 'fantastic / dreamy', strftime('%s','now')*1000),
(10, '환승역', 'transfer station', strftime('%s','now')*1000),
(10, '환영회', 'welcome party', strftime('%s','now')*1000),
(10, '환율', 'exchange rate', strftime('%s','now')*1000),
(10, '환하다', 'bright / radiant / clear', strftime('%s','now')*1000),
(10, '활동', 'activity', strftime('%s','now')*1000),
(10, '활발하다', 'active / lively / vigorous', strftime('%s','now')*1000),
(10, '활짝', 'widely / brightly / fully (open)', strftime('%s','now')*1000),
(10, '회', 'meeting / society / sashimi', strftime('%s','now')*1000),
(10, '회비', 'membership fee / dues', strftime('%s','now')*1000),
(10, '회식', 'company dinner / staff meal', strftime('%s','now')*1000),
(10, '회의실', 'conference room / meeting room', strftime('%s','now')*1000),
(10, '회장', 'chairman / president / head', strftime('%s','now')*1000),
(10, '횟수', 'number of times / frequency', strftime('%s','now')*1000),
(10, '효과', 'effect / efficacy / result', strftime('%s','now')*1000),
(10, '후반', 'second half / latter part', strftime('%s','now')*1000),
(10, '후식', 'dessert', strftime('%s','now')*1000),
(10, '후추', 'black pepper', strftime('%s','now')*1000),
(10, '후회', 'regret / remorse', strftime('%s','now')*1000),
(10, '휴가철', 'vacation season / holiday period', strftime('%s','now')*1000),
(10, '휴대', 'carrying / portability', strftime('%s','now')*1000),
(10, '휴식', 'rest / break', strftime('%s','now')*1000),
(10, '휴학', 'leave of absence from school', strftime('%s','now')*1000),
(10, '흘러가다', 'flow / pass by', strftime('%s','now')*1000),
(10, '희다', 'be white / pure', strftime('%s','now')*1000),
(10, '희생', 'sacrifice', strftime('%s','now')*1000);