PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(9, '옮기다', 'move / transfer / shift', strftime('%s','now')*1000),
(9, '옷차림', 'outfit / attire', strftime('%s','now')*1000),
(9, '와인', 'wine', strftime('%s','now')*1000),
(9, '완성', 'completion / perfection', strftime('%s','now')*1000),
(9, '왕복', 'round trip', strftime('%s','now')*1000),
(9, '외', 'outside / except / foreign', strftime('%s','now')*1000),
(9, '외과', 'surgery / surgical department', strftime('%s','now')*1000),
(9, '외교', 'diplomacy', strftime('%s','now')*1000),
(9, '외교관', 'diplomat', strftime('%s','now')*1000),
(9, '외모', 'appearance / looks', strftime('%s','now')*1000),
(9, '외박', 'sleep out / stay out overnight', strftime('%s','now')*1000),
(9, '외부', 'outside / exterior', strftime('%s','now')*1000),
(9, '외삼촌', 'maternal uncle', strftime('%s','now')*1000),
(9, '외숙모', 'maternal aunt (uncle’s wife)', strftime('%s','now')*1000),
(9, '외식', 'eating out', strftime('%s','now')*1000),
(9, '외투', 'coat / overcoat', strftime('%s','now')*1000),
(9, '외할머니', 'maternal grandmother', strftime('%s','now')*1000),
(9, '외할아버지', 'maternal grandfather', strftime('%s','now')*1000),
(9, '왼발', 'left foot', strftime('%s','now')*1000),
(9, '요', 'this / request ending particle', strftime('%s','now')*1000),
(9, '요가', 'yoga', strftime('%s','now')*1000),
(9, '요구르트', 'yogurt', strftime('%s','now')*1000),
(9, '요리법', 'recipe / cooking method', strftime('%s','now')*1000),
(9, '욕실', 'bathroom', strftime('%s','now')*1000),
(9, '용', 'dragon / usage', strftime('%s','now')*1000),
(9, '용기', 'courage / container', strftime('%s','now')*1000),
(9, '용돈', 'allowance / pocket money', strftime('%s','now')*1000),
(9, '용품', 'goods / items / supplies', strftime('%s','now')*1000),
(9, '우물', 'well (for water)', strftime('%s','now')*1000),
(9, '우선', 'first / priority', strftime('%s','now')*1000),
(9, '우수', 'excellent / superiority', strftime('%s','now')*1000),
(9, '우연히', 'by chance / accidentally', strftime('%s','now')*1000),
(9, '우울', 'depression / gloom', strftime('%s','now')*1000),
(9, '우정', 'friendship', strftime('%s','now')*1000),
(9, '우주', 'universe / space', strftime('%s','now')*1000),
(9, '우체통', 'mailbox', strftime('%s','now')*1000),
(9, '우측', 'right side', strftime('%s','now')*1000),
(9, '우편', 'mail / post', strftime('%s','now')*1000),
(9, '우편물', 'postal item / mail', strftime('%s','now')*1000),
(9, '우편함', 'mailbox / postbox', strftime('%s','now')*1000),
(9, '우회전', 'right turn', strftime('%s','now')*1000),
(9, '운', 'luck / fortune', strftime('%s','now')*1000),
(9, '운동량', 'amount of exercise', strftime('%s','now')*1000),
(9, '운동선수', 'athlete / sports player', strftime('%s','now')*1000),
(9, '운명', 'destiny / fate', strftime('%s','now')*1000),
(9, '운전면허', 'driver’s license', strftime('%s','now')*1000),
(9, '울리다', 'ring / make someone cry', strftime('%s','now')*1000),
(9, '웃어른', 'elder / senior', strftime('%s','now')*1000),
(9, '원래', 'originally / by nature', strftime('%s','now')*1000),
(9, '원룸', 'one-room apartment / studio', strftime('%s','now')*1000),
(9, '원숭이', 'monkey', strftime('%s','now')*1000),
(9, '원인', 'cause / reason', strftime('%s','now')*1000),
(9, '월', 'month', strftime('%s','now')*1000),
(9, '월드컵', 'World Cup', strftime('%s','now')*1000),
(9, '월세', 'monthly rent', strftime('%s','now')*1000),
(9, '웬일', 'what matter / what’s the occasion', strftime('%s','now')*1000),
(9, '위', 'above / stomach / position', strftime('%s','now')*1000),
(9, '위층', 'upstairs / upper floor', strftime('%s','now')*1000),
(9, '위하다', 'do for / care for', strftime('%s','now')*1000),
(9, '윗글', 'above text / preceding passage', strftime('%s','now')*1000),
(9, '윗사람', 'senior / superior', strftime('%s','now')*1000),
(9, '유람선', 'cruise ship / excursion boat', strftime('%s','now')*1000),
(9, '유럽', 'Europe', strftime('%s','now')*1000),
(9, '유료', 'paid / for a fee', strftime('%s','now')*1000),
(9, '유머', 'humor', strftime('%s','now')*1000),
(9, '유물', 'relic / artifact', strftime('%s','now')*1000),
(9, '유적', 'ruins / remains', strftime('%s','now')*1000),
(9, '유적지', 'historic site', strftime('%s','now')*1000),
(9, '은', 'silver / topic marker', strftime('%s','now')*1000),
(9, '음력', 'lunar calendar', strftime('%s','now')*1000),
(9, '음성', 'voice / sound', strftime('%s','now')*1000),
(9, '음식물', 'food waste / foodstuff', strftime('%s','now')*1000),
(9, '음악회', 'concert / music performance', strftime('%s','now')*1000),
(9, '음주', 'drinking alcohol', strftime('%s','now')*1000),
(9, '응급실', 'emergency room', strftime('%s','now')*1000),
(9, '응원', 'support / cheer', strftime('%s','now')*1000),
(9, '의견', 'opinion / view', strftime('%s','now')*1000),
(9, '의논', 'discussion / talk', strftime('%s','now')*1000),
(9, '이곳저곳', 'here and there', strftime('%s','now')*1000),
(9, '이국적', 'exotic / foreign-like', strftime('%s','now')*1000),
(9, '이끌다', 'lead / guide', strftime('%s','now')*1000),
(9, '이동', 'movement / transfer', strftime('%s','now')*1000),
(9, '이따', 'later', strftime('%s','now')*1000),
(9, '이래서', 'for this reason / that’s why', strftime('%s','now')*1000),
(9, '이러다', 'do this / act like this', strftime('%s','now')*1000),
(9, '이런저런', 'this and that', strftime('%s','now')*1000),
(9, '이력서', 'résumé / CV', strftime('%s','now')*1000),
(9, '이루다', 'achieve / accomplish', strftime('%s','now')*1000),
(9, '이루어지다', 'be achieved / be formed', strftime('%s','now')*1000),
(9, '이름표', 'name tag', strftime('%s','now')*1000),
(9, '이리', 'this way / here', strftime('%s','now')*1000),
(9, '이만', 'this much / to this extent', strftime('%s','now')*1000),
(9, '이메일', 'email', strftime('%s','now')*1000),
(9, '이미지', 'image', strftime('%s','now')*1000),
(9, '이비인후과', 'ear, nose, throat clinic (ENT)', strftime('%s','now')*1000),
(9, '이성', 'reason / opposite sex', strftime('%s','now')*1000),
(9, '이웃집', 'neighboring house', strftime('%s','now')*1000),
(9, '이자', 'interest (money)', strftime('%s','now')*1000),
(9, '이하', 'below / under', strftime('%s','now')*1000),
(9, '익히다', 'learn / master / cook', strftime('%s','now')*1000),
(9, '인구', 'population', strftime('%s','now')*1000),
(9, '인도', 'India / sidewalk', strftime('%s','now')*1000),
(9, '인삼차', 'ginseng tea', strftime('%s','now')*1000),
(9, '인상', 'impression / raise (in price)', strftime('%s','now')*1000),
(9, '인상적', 'impressive', strftime('%s','now')*1000),
(9, '인생', 'life', strftime('%s','now')*1000),
(9, '인쇄', 'printing', strftime('%s','now')*1000),
(9, '인스턴트', 'instant / ready-made', strftime('%s','now')*1000),
(9, '인심', 'kindness / generosity', strftime('%s','now')*1000),
(9, '인원', 'number of people', strftime('%s','now')*1000),
(9, '인터뷰', 'interview', strftime('%s','now')*1000),
(9, '일', 'work / day / event', strftime('%s','now')*1000),
(9, '일곱째', 'seventh (ordinal)', strftime('%s','now')*1000),
(9, '일반', 'general / common', strftime('%s','now')*1000),
(9, '일본어', 'Japanese language', strftime('%s','now')*1000),
(9, '일본인', 'Japanese person', strftime('%s','now')*1000),
(9, '일부러', 'on purpose / intentionally', strftime('%s','now')*1000),
(9, '일상생활', 'everyday life / daily living', strftime('%s','now')*1000),
(9, '일어', 'Japanese language (일본어) / arise', strftime('%s','now')*1000),
(9, '일자리', 'job / position', strftime('%s','now')*1000),
(9, '일정', 'schedule / fixed / certain', strftime('%s','now')*1000),
(9, '일정표', 'timetable / itinerary', strftime('%s','now')*1000),
(9, '일출', 'sunrise', strftime('%s','now')*1000),
(9, '일행', 'party / company', strftime('%s','now')*1000),
(9, '읽기', 'reading', strftime('%s','now')*1000),
(9, '입국', 'entry into a country', strftime('%s','now')*1000),
(9, '입맛', 'appetite / taste', strftime('%s','now')*1000),
(9, '입장료', 'admission fee', strftime('%s','now')*1000),
(9, '입학시험', 'entrance exam', strftime('%s','now')*1000),
(9, '입학식', 'entrance ceremony', strftime('%s','now')*1000),
(9, '잇다', 'connect / continue / link', strftime('%s','now')*1000),
(9, '자', 'person / self / ruler', strftime('%s','now')*1000),
(9, '자가용', 'private car', strftime('%s','now')*1000),
(9, '자격', 'qualification / eligibility', strftime('%s','now')*1000),
(9, '자기', 'oneself / self', strftime('%s','now')*1000),
(9, '자녀', 'children / offspring', strftime('%s','now')*1000),
(9, '자동', 'automatic', strftime('%s','now')*1000),
(9, '자료', 'data / material / reference', strftime('%s','now')*1000),
(9, '자리', 'seat / place / spot', strftime('%s','now')*1000),
(9, '자매', 'sisters', strftime('%s','now')*1000),
(9, '자세하다', 'detailed / specific', strftime('%s','now')*1000),
(9, '자신', 'confidence / oneself', strftime('%s','now')*1000),
(9, '자유롭다', 'free / unrestricted', strftime('%s','now')*1000),
(9, '자주색', 'purple', strftime('%s','now')*1000),
(9, '작성', 'writing / preparation (of doc)', strftime('%s','now')*1000),
(9, '작은아버지', 'uncle (father’s younger brother)', strftime('%s','now')*1000),
(9, '작은어머니', 'aunt (father’s younger brother’s wife)', strftime('%s','now')*1000),
(9, '작은집', 'uncle’s family (father’s younger brother’s)', strftime('%s','now')*1000),
(9, '잔돈', 'small change', strftime('%s','now')*1000),
(9, '잔디밭', 'lawn', strftime('%s','now')*1000),
(9, '잠그다', 'lock / fasten', strftime('%s','now')*1000),
(9, '잠기다', 'be locked / be fastened', strftime('%s','now')*1000),
(9, '잠옷', 'pajamas', strftime('%s','now')*1000),
(9, '잡아먹다', 'prey on / devour', strftime('%s','now')*1000),
(9, '잡히다', 'be caught / be captured', strftime('%s','now')*1000),
(9, '장', 'chapter / chief / place (suffix)', strftime('%s','now')*1000),
(9, '장단점', 'pros and cons', strftime('%s','now')*1000),
(9, '장래', 'future / prospects', strftime('%s','now')*1000),
(9, '장례식', 'funeral', strftime('%s','now')*1000),
(9, '장마철', 'rainy season', strftime('%s','now')*1000),
(9, '장면', 'scene', strftime('%s','now')*1000),
(9, '장미꽃', 'rose flower', strftime('%s','now')*1000),
(9, '장수', 'longevity / general', strftime('%s','now')*1000),
(9, '장식', 'decoration', strftime('%s','now')*1000),
(9, '장점', 'strength / advantage', strftime('%s','now')*1000),
(9, '장학금', 'scholarship', strftime('%s','now')*1000),
(9, '재다', 'measure / be quick', strftime('%s','now')*1000),
(9, '재킷', 'jacket', strftime('%s','now')*1000),
(9, '재학', 'be enrolled at school', strftime('%s','now')*1000),
(9, '재활용', 'recycling', strftime('%s','now')*1000),
(9, '잼', 'jam', strftime('%s','now')*1000),
(9, '쟤', 'that kid (over there)', strftime('%s','now')*1000),
(9, '저기', 'there / over there', strftime('%s','now')*1000),
(9, '저녁때', 'around dinner time', strftime('%s','now')*1000),
(9, '저러다', 'do like that', strftime('%s','now')*1000),
(9, '저렴하다', 'be inexpensive', strftime('%s','now')*1000),
(9, '저울', 'scale / balance', strftime('%s','now')*1000),
(9, '저자', 'author', strftime('%s','now')*1000),
(9, '저축', 'savings / deposit', strftime('%s','now')*1000),
(9, '적', 'enemy / record / past / suitable', strftime('%s','now')*1000),
(9, '적어도', 'at least', strftime('%s','now')*1000),
(9, '적응', 'adaptation / adjustment', strftime('%s','now')*1000),
(9, '적히다', 'be written / be recorded', strftime('%s','now')*1000),
(9, '전국', 'nationwide / the whole country', strftime('%s','now')*1000),
(9, '전국적', 'national / nationwide', strftime('%s','now')*1000),
(9, '전날', 'the previous day / the day before', strftime('%s','now')*1000),
(9, '전달', 'delivery / conveyance', strftime('%s','now')*1000),
(9, '전망', 'view / prospect / outlook', strftime('%s','now')*1000),
(9, '전문', 'specialty / expert field', strftime('%s','now')*1000),
(9, '전문가', 'expert / specialist', strftime('%s','now')*1000),
(9, '전문점', 'specialty store', strftime('%s','now')*1000),
(9, '전설', 'legend / myth', strftime('%s','now')*1000),
(9, '전세', 'lease / deposit rental', strftime('%s','now')*1000),
(9, '전시', 'exhibition / display', strftime('%s','now')*1000),
(9, '전시회', 'exhibition / exposition', strftime('%s','now')*1000),
(9, '전용', 'exclusive use / private use', strftime('%s','now')*1000),
(9, '전원', 'all members / power supply', strftime('%s','now')*1000),
(9, '전자', 'electronics / electronic', strftime('%s','now')*1000),
(9, '전자레인지', 'microwave oven', strftime('%s','now')*1000),
(9, '전자사전', 'electronic dictionary', strftime('%s','now')*1000),
(9, '전쟁', 'war', strftime('%s','now')*1000),
(9, '전통', 'tradition / custom', strftime('%s','now')*1000),
(9, '전통적', 'traditional', strftime('%s','now')*1000),
(9, '절', 'temple / bow / section', strftime('%s','now')*1000),
(9, '절대', 'absolutely / never', strftime('%s','now')*1000),
(9, '절대로', 'never / absolutely not', strftime('%s','now')*1000),
(9, '절약', 'saving / frugality', strftime('%s','now')*1000),
(9, '젊은이', 'young person / youth', strftime('%s','now')*1000),
(9, '점', 'dot / point / store', strftime('%s','now')*1000),
(9, '점원', 'store clerk / sales clerk', strftime('%s','now')*1000),
(9, '점차', 'gradually / step by step', strftime('%s','now')*1000),
(9, '점퍼', 'jumper / jacket', strftime('%s','now')*1000),
(9, '접수', 'receipt / registration / acceptance', strftime('%s','now')*1000),
(9, '젓다', 'stir / row', strftime('%s','now')*1000),
(9, '정', 'affection / sentiment / feeling', strftime('%s','now')*1000),
(9, '정답', 'correct answer', strftime('%s','now')*1000),
(9, '정말로', 'really / truly', strftime('%s','now')*1000),
(9, '정보', 'information', strftime('%s','now')*1000),
(9, '정수기', 'water purifier', strftime('%s','now')*1000),
(9, '정신', 'mind / spirit / sanity', strftime('%s','now')*1000),
(9, '정신없다', 'be hectic / be out of one’s mind', strftime('%s','now')*1000),
(9, '정신없이', 'frantically / in a rush', strftime('%s','now')*1000),
(9, '정오', 'noon', strftime('%s','now')*1000),
(9, '정원', 'garden / number of people / courtyard', strftime('%s','now')*1000),
(9, '정육점', 'butcher shop', strftime('%s','now')*1000),
(9, '정장', 'formal suit / formal wear', strftime('%s','now')*1000),
(9, '정치', 'politics', strftime('%s','now')*1000),
(9, '정형외과', 'orthopedics department', strftime('%s','now')*1000),
(9, '정확히', 'exactly / precisely', strftime('%s','now')*1000),
(9, '제공', 'offer / provide / supply', strftime('%s','now')*1000),
(9, '제과점', 'bakery / pastry shop', strftime('%s','now')*1000),
(9, '제대로', 'properly / correctly', strftime('%s','now')*1000),
(9, '제시간', 'on time', strftime('%s','now')*1000),
(9, '제안', 'suggestion / proposal', strftime('%s','now')*1000),
(9, '제출', 'submission / turn in', strftime('%s','now')*1000),
(9, '제품', 'product / manufactured goods', strftime('%s','now')*1000),
(9, '조건', 'condition / requirement', strftime('%s','now')*1000),
(9, '조깅', 'jogging', strftime('%s','now')*1000),
(9, '조끼', 'vest', strftime('%s','now')*1000),
(9, '조리', 'cooking / preparation', strftime('%s','now')*1000),
(9, '조미료', 'seasoning / condiment', strftime('%s','now')*1000),
(9, '조사', 'investigation / survey / grammar particle', strftime('%s','now')*1000),
(9, '조상', 'ancestor', strftime('%s','now')*1000),
(9, '조언', 'advice / counsel', strftime('%s','now')*1000),
(9, '존경', 'respect / admiration', strftime('%s','now')*1000),
(9, '졸리다', 'be sleepy', strftime('%s','now')*1000),
(9, '졸업생', 'graduate / alumnus', strftime('%s','now')*1000),
(9, '졸업식', 'graduation ceremony', strftime('%s','now')*1000),
(9, '종교', 'religion / faith', strftime('%s','now')*1000),
(9, '종이컵', 'paper cup', strftime('%s','now')*1000),
(9, '종일', 'all day long', strftime('%s','now')*1000),
(9, '종합', 'comprehensive / general', strftime('%s','now')*1000),
(9, '좌석', 'seat', strftime('%s','now')*1000),
(9, '좌측', 'left side', strftime('%s','now')*1000),
(9, '좌회전', 'left turn', strftime('%s','now')*1000),
(9, '주간', 'week / daytime', strftime('%s','now')*1000),
(9, '주고받다', 'give and take / exchange', strftime('%s','now')*1000),
(9, '주민', 'resident / inhabitant', strftime('%s','now')*1000),
(9, '주방', 'kitchen', strftime('%s','now')*1000),
(9, '주요', 'main / major', strftime('%s','now')*1000),
(9, '주유소', 'gas station', strftime('%s','now')*1000),
(9, '주의', 'caution / attention / warning', strftime('%s','now')*1000),
(9, '주인공', 'main character / hero', strftime('%s','now')*1000),
(9, '주제', 'subject / theme / topic', strftime('%s','now')*1000),
(9, '주차권', 'parking ticket', strftime('%s','now')*1000),
(9, '주차료', 'parking fee', strftime('%s','now')*1000),
(9, '죽', 'porridge', strftime('%s','now')*1000),
(9, '죽음', 'death', strftime('%s','now')*1000),
(9, '죽이다', 'kill', strftime('%s','now')*1000),
(9, '준비물', 'preparation items / supplies', strftime('%s','now')*1000),
(9, '줄넘기', 'jump rope', strftime('%s','now')*1000),
(9, '줄무늬', 'stripe pattern', strftime('%s','now')*1000),
(9, '중', 'middle / among / during', strftime('%s','now')*1000),
(9, '중고', 'used / secondhand', strftime('%s','now')*1000),
(9, '중고차', 'used car', strftime('%s','now')*1000),
(9, '중국어', 'Chinese language', strftime('%s','now')*1000),
(9, '중국인', 'Chinese person', strftime('%s','now')*1000),
(9, '중급', 'intermediate level', strftime('%s','now')*1000),
(9, '중단', 'halt / suspension', strftime('%s','now')*1000),
(9, '중부', 'central region', strftime('%s','now')*1000),
(9, '중순', 'middle of the month', strftime('%s','now')*1000),
(9, '중식', 'lunch / Chinese cuisine', strftime('%s','now')*1000),
(9, '중심지', 'center / core area', strftime('%s','now')*1000),
(9, '중형차', 'mid-sized car', strftime('%s','now')*1000),
(9, '쥐', 'mouse / rat', strftime('%s','now')*1000),
(9, '즉', 'that is / namely / in other words', strftime('%s','now')*1000),
(9, '즉시', 'immediately / right away', strftime('%s','now')*1000),
(9, '즐거움', 'joy / pleasure', strftime('%s','now')*1000),
(9, '증가', 'increase / growth', strftime('%s','now')*1000),
(9, '증명서', 'certificate / document of proof', strftime('%s','now')*1000),
(9, '증상', 'symptom', strftime('%s','now')*1000),
(9, '증세', 'condition / state (symptom)', strftime('%s','now')*1000),
(9, '지각', 'lateness / perception', strftime('%s','now')*1000),
(9, '지나치다', 'go too far / overdo', strftime('%s','now')*1000),
(9, '지난날', 'past days / old times', strftime('%s','now')*1000),
(9, '지다', 'lose / set (sun)', strftime('%s','now')*1000),
(9, '지도', 'map / guidance', strftime('%s','now')*1000),
(9, '지방', 'region / fat', strftime('%s','now')*1000),
(9, '지붕', 'roof', strftime('%s','now')*1000),
(9, '지역', 'area / region', strftime('%s','now')*1000),
(9, '지원', 'support / application', strftime('%s','now')*1000),
(9, '지저분하다', 'messy / dirty', strftime('%s','now')*1000),
(9, '지퍼', 'zipper', strftime('%s','now')*1000),
(9, '직장인', 'office worker / employee', strftime('%s','now')*1000),
(9, '직진', 'go straight', strftime('%s','now')*1000),
(9, '진단서', 'medical certificate', strftime('%s','now')*1000),
(9, '진심', 'sincerity / true heart', strftime('%s','now')*1000),
(9, '진찰', 'medical examination', strftime('%s','now')*1000),
(9, '진통제', 'painkiller', strftime('%s','now')*1000),
(9, '진학', 'entering higher education', strftime('%s','now')*1000),
(9, '진행', 'progress / proceed', strftime('%s','now')*1000),
(9, '진행자', 'host / MC / presenter', strftime('%s','now')*1000),
(9, '질', 'quality / texture / matter', strftime('%s','now')*1000),
(9, '집다', 'pick up / point out', strftime('%s','now')*1000),
(9, '집세', 'house rent', strftime('%s','now')*1000),
(9, '집안', 'family / household', strftime('%s','now')*1000),
(9, '집중', 'concentration / focus', strftime('%s','now')*1000),
(9, '짜다', 'make / plan / squeeze / salty', strftime('%s','now')*1000),
(9, '짜리', 'worth / valued at (counter suffix)', strftime('%s','now')*1000),
(9, '쪽', 'side / direction / piece', strftime('%s','now')*1000),
(9, '쭉', 'continuously / straight', strftime('%s','now')*1000),
(9, '찌르다', 'stab / pierce / poke', strftime('%s','now')*1000),
(9, '찜질', 'hot/cold pack / steaming therapy', strftime('%s','now')*1000),
(9, '찢다', 'tear / rip', strftime('%s','now')*1000),
(9, '찢어지다', 'be torn / ripped', strftime('%s','now')*1000),
(9, '차량', 'vehicle', strftime('%s','now')*1000),
(9, '차로', 'lane / by car', strftime('%s','now')*1000),
(9, '차리다', 'prepare / set (table) / compose oneself', strftime('%s','now')*1000),
(9, '차림표', 'menu', strftime('%s','now')*1000),
(9, '차이', 'difference / gap', strftime('%s','now')*1000),
(9, '차이점', 'difference point / distinction', strftime('%s','now')*1000),
(9, '찬성', 'agreement / approval', strftime('%s','now')*1000),
(9, '참가', 'participation', strftime('%s','now')*1000),
(9, '참고', 'reference / refer to', strftime('%s','now')*1000),
(9, '참기름', 'sesame oil', strftime('%s','now')*1000),
(9, '참석', 'attendance / participation', strftime('%s','now')*1000),
(9, '창', 'window', strftime('%s','now')*1000),
(9, '창가', 'by the window', strftime('%s','now')*1000),
(9, '창고', 'warehouse / storage', strftime('%s','now')*1000),
(9, '창구', 'counter / window (office)', strftime('%s','now')*1000),
(9, '창밖', 'outside the window', strftime('%s','now')*1000),
(9, '창피', 'embarrassment / shame', strftime('%s','now')*1000),
(9, '채우다', 'fill / fulfill / fasten', strftime('%s','now')*1000),
(9, '책가방', 'school bag', strftime('%s','now')*1000),
(9, '챙기다', 'pack / take care of / prepare', strftime('%s','now')*1000),
(9, '처녀', 'unmarried woman / virgin', strftime('%s','now')*1000),
(9, '처방', 'prescription', strftime('%s','now')*1000),
(9, '처방전', 'medical prescription slip', strftime('%s','now')*1000),
(9, '천둥', 'thunder', strftime('%s','now')*1000),
(9, '천사', 'angel', strftime('%s','now')*1000);