PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(26, '심의', 'deliberation', strftime('%s','now')*1000),
(26, '심혈', 'heart and soul', strftime('%s','now')*1000),
(26, '심화', 'deepening/ intensification', strftime('%s','now')*1000),
(26, '심히', 'deeply/ extremely', strftime('%s','now')*1000),
(26, '십시일반', 'many hands make light work', strftime('%s','now')*1000),
(26, '싱그럽다', 'fresh/ verdant', strftime('%s','now')*1000),
(26, '싸늘하다', 'chilly/ cold', strftime('%s','now')*1000),
(26, '싹02', 'sprout/ bud', strftime('%s','now')*1000),
(26, '싹트다', 'sprout/ bud', strftime('%s','now')*1000),
(26, '쌍방', 'both sides', strftime('%s','now')*1000),
(26, '쌍벽', 'two equals/ a match', strftime('%s','now')*1000),
(26, '쏠리다', 'be slanted/ be concentrated on', strftime('%s','now')*1000),
(26, '씁쓸하다', 'bitter/ bittersweet', strftime('%s','now')*1000),
(26, '아낌없다', 'unstinting/ generous', strftime('%s','now')*1000),
(26, '아낌없이', 'unstintingly/ generously', strftime('%s','now')*1000),
(26, '아늑하다', 'cozy/ snug', strftime('%s','now')*1000),
(26, '아득하다', 'far/ faint/ dim', strftime('%s','now')*1000),
(26, '아랑곳없이', 'regardless/ without concern', strftime('%s','now')*1000),
(26, '아무쪼록', 'please/ by all means', strftime('%s','now')*1000),
(26, '아부', 'flattery', strftime('%s','now')*1000),
(26, '아비', 'father', strftime('%s','now')*1000),
(26, '아슬아슬', 'hair-raising/ thrilling', strftime('%s','now')*1000),
(26, '아우르다', 'embrace/ encompass', strftime('%s','now')*1000),
(26, '아찔하다', 'dizzy/ giddy', strftime('%s','now')*1000),
(26, '악01', 'evil', strftime('%s','now')*1000),
(26, '악성00', 'malignant/ vicious', strftime('%s','now')*1000),
(26, '악역', 'villain’s role', strftime('%s','now')*1000),
(26, '악하다', 'evil/ wicked', strftime('%s','now')*1000),
(26, '안간힘', 'desperate effort', strftime('%s','now')*1000),
(26, '안건', 'agenda item/ bill', strftime('%s','now')*1000),
(26, '안달', 'be anxious/ fret', strftime('%s','now')*1000),
(26, '안락', 'comfort/ ease', strftime('%s','now')*1000),
(26, '안락사', 'euthanasia', strftime('%s','now')*1000),
(26, '안목', 'discernment/ eye (for)', strftime('%s','now')*1000),
(26, '안쓰럽다', 'pitiable/ pathetic', strftime('%s','now')*1000),
(26, '안이하다', 'easygoing/ complacent', strftime('%s','now')*1000),
(26, '안일', 'complacency/ idleness', strftime('%s','now')*1000),
(26, '안절부절', 'restlessness/ fidgeting', strftime('%s','now')*1000),
(26, '안주01', 'side dish (with alcohol)', strftime('%s','now')*1000),
(26, '알선', 'arrangement/ mediation', strftime('%s','now')*1000),
(26, '알아채다', 'notice/ perceive', strftime('%s','now')*1000),
(26, '암기력00', 'memorization ability', strftime('%s','now')*1000),
(26, '암시', 'hint/ implication', strftime('%s','now')*1000),
(26, '암컷', 'female (animal)', strftime('%s','now')*1000),
(26, '암호', 'code/ password', strftime('%s','now')*1000),
(26, '암흑기', 'dark age/ dark period', strftime('%s','now')*1000),
(26, '압도', 'overwhelm', strftime('%s','now')*1000),
(26, '압도적01∙압도적02', 'overwhelming', strftime('%s','now')*1000),
(26, '압박감', 'sense of pressure', strftime('%s','now')*1000),
(26, '압축', 'compression', strftime('%s','now')*1000),
(26, '앞다투다', 'vie with one another', strftime('%s','now')*1000),
(26, '앞당기다', 'move up/ advance (schedule)', strftime('%s','now')*1000),
(26, '앞장', 'the lead/ forefront', strftime('%s','now')*1000),
(26, '애지중지', 'cherish dearly', strftime('%s','now')*1000),
(26, '애착', 'attachment', strftime('%s','now')*1000),
(26, '애창곡', 'favorite song to sing', strftime('%s','now')*1000),
(26, '애초01', 'from the beginning', strftime('%s','now')*1000),
(26, '애틋하다', 'poignant/ affectionate', strftime('%s','now')*1000),
(26, '야광', 'luminous glow/ phosphorescence', strftime('%s','now')*1000),
(26, '야기', 'cause/ bring about', strftime('%s','now')*1000),
(26, '야단맞다', 'be scolded', strftime('%s','now')*1000),
(26, '야당', 'opposition party', strftime('%s','now')*1000),
(26, '약물', 'drug/ medication', strftime('%s','now')*1000),
(26, '약세00', 'weak trend/ bearishness', strftime('%s','now')*1000),
(26, '약소하다00', 'be meager/ be small', strftime('%s','now')*1000),
(26, '약탈', 'plunder/ looting', strftime('%s','now')*1000),
(26, '얌체', 'shameless person', strftime('%s','now')*1000),
(26, '양상', 'aspect/ pattern', strftime('%s','now')*1000),
(26, '양성03', 'cultivation/ fostering', strftime('%s','now')*1000),
(26, '양성평등', 'gender equality', strftime('%s','now')*1000),
(26, '양식06', 'form/ format', strftime('%s','now')*1000),
(26, '양질', 'high quality', strftime('%s','now')*1000),
(26, '양측', 'both sides', strftime('%s','now')*1000),
(26, '얕보다', 'look down on', strftime('%s','now')*1000),
(26, '어감00', 'nuance of sound/ tone', strftime('%s','now')*1000),
(26, '어금니', 'molar', strftime('%s','now')*1000),
(26, '어김없이', 'unfailingly', strftime('%s','now')*1000),
(26, '어둑어둑', 'dusky/ dim', strftime('%s','now')*1000),
(26, '어렴풋이', 'vaguely/ dimly', strftime('%s','now')*1000),
(26, '어리다01', 'be young', strftime('%s','now')*1000),
(26, '어리둥절하다', 'be bewildered', strftime('%s','now')*1000),
(26, '어마어마하다', 'enormous', strftime('%s','now')*1000),
(26, '어민', 'fishermen/ fishers', strftime('%s','now')*1000),
(26, '어부지리', 'windfall (fisherman’s gain)', strftime('%s','now')*1000),
(26, '어설프다', 'clumsy/ sloppy', strftime('%s','now')*1000),
(26, '어수선하다', 'disorderly/ chaotic', strftime('%s','now')*1000),
(26, '어조', 'tone/ intonation', strftime('%s','now')*1000),
(26, '어지럽히다', 'make messy/ throw into disorder', strftime('%s','now')*1000),
(26, '어처구니', 'absurdity/ nonsense', strftime('%s','now')*1000),
(26, '어처구니없다', 'preposterous/ absurd', strftime('%s','now')*1000),
(26, '어투', 'manner of speaking/ diction', strftime('%s','now')*1000),
(26, '억세다', 'tough/ strong', strftime('%s','now')*1000),
(26, '억수', 'downpour/ torrent', strftime('%s','now')*1000),
(26, '억압', 'oppression', strftime('%s','now')*1000),
(26, '억지', 'obstinacy/ forcedness', strftime('%s','now')*1000),
(26, '언뜻', 'at first glance/ suddenly', strftime('%s','now')*1000),
(26, '언론사', 'news organization', strftime('%s','now')*1000),
(26, '언행', 'words and deeds', strftime('%s','now')*1000),
(26, '얻어맞다', 'be beaten/ be hit', strftime('%s','now')*1000),
(26, '얼', 'spirit/ soul', strftime('%s','now')*1000),
(26, '얼버무리다', 'gloss over/ evade', strftime('%s','now')*1000),
(26, '얼핏', 'at a glance/ briefly', strftime('%s','now')*1000),
(26, '얽매이다', 'be tied up/ be bound', strftime('%s','now')*1000),
(26, '엄두', 'nerve/ daring (to try)', strftime('%s','now')*1000),
(26, '엄중하다', 'be strict/ stern', strftime('%s','now')*1000),
(26, '엄지', 'thumb', strftime('%s','now')*1000),
(26, '업소', 'business establishment', strftime('%s','now')*1000),
(26, '업자', 'operator/ tradesperson', strftime('%s','now')*1000),
(26, '업종', 'industry/ business type', strftime('%s','now')*1000),
(26, '엇갈리다', 'cross/ miss/ diverge', strftime('%s','now')*1000),
(26, '엉금엉금', 'crawling slowly', strftime('%s','now')*1000),
(26, '엉기다', 'clump/ coagulate', strftime('%s','now')*1000),
(26, '엉성하다', 'loose/ sloppy', strftime('%s','now')*1000),
(26, '엉키다', 'be entangled', strftime('%s','now')*1000),
(26, '엎다', 'lay face down/ overturn', strftime('%s','now')*1000),
(26, '에워싸다', 'surround/ encircle', strftime('%s','now')*1000),
(26, '여당', 'ruling party', strftime('%s','now')*1000),
(26, '여류', 'female (writer/artist)', strftime('%s','now')*1000),
(26, '여리다', 'delicate/ tender', strftime('%s','now')*1000),
(26, '여성상00', 'image of woman (ideal type)', strftime('%s','now')*1000),
(26, '여성적01∙여성적02', 'feminine', strftime('%s','now')*1000),
(26, '여아00', 'girl (female child)', strftime('%s','now')*1000),
(26, '여야', 'ruling and opposition parties', strftime('%s','now')*1000),
(26, '여의다', 'lose (one’s parents)/ be bereaved of', strftime('%s','now')*1000),
(26, '여지00/여지', 'leeway/ room/ possibility', strftime('%s','now')*1000),
(26, '여파', 'aftermath/ fallout', strftime('%s','now')*1000),
(26, '역겹다', 'disgusting', strftime('%s','now')*1000),
(26, '역경', 'adversity', strftime('%s','now')*1000),
(26, '역대', 'successive generations/ all previous', strftime('%s','now')*1000),
(26, '역도', 'weightlifting', strftime('%s','now')*1000),
(26, '역동적01∙역동적02', 'dynamic', strftime('%s','now')*1000),
(26, '역량', 'capability/ competence', strftime('%s','now')*1000),
(26, '역지사지', 'putting oneself in another’s shoes', strftime('%s','now')*1000),
(26, '역효과', 'counterproductive effect', strftime('%s','now')*1000),
(26, '연계', 'linkage/ connection', strftime('%s','now')*1000),
(26, '연대01', 'solidarity', strftime('%s','now')*1000),
(26, '연료', 'fuel', strftime('%s','now')*1000),
(26, '연비', 'fuel efficiency', strftime('%s','now')*1000),
(26, '연상01', 'association/ being reminded', strftime('%s','now')*1000),
(26, '연약하다', 'frail/ delicate', strftime('%s','now')*1000),
(26, '연연하다01/연연하다02', 'cling to/ be preoccupied with', strftime('%s','now')*1000),
(26, '연잇다', 'one after another/ in succession', strftime('%s','now')*1000),
(26, '연장자', 'elder person', strftime('%s','now')*1000),
(26, '연재', 'serialization', strftime('%s','now')*1000),
(26, '연초', 'beginning of the year', strftime('%s','now')*1000),
(26, '열거', 'enumeration/ list', strftime('%s','now')*1000),
(26, '열광', 'wild enthusiasm', strftime('%s','now')*1000),
(26, '열띠다', 'be heated/ ardent', strftime('%s','now')*1000),
(26, '열망', 'longing/ aspiration', strftime('%s','now')*1000),
(26, '열성00', 'zeal/ enthusiasm', strftime('%s','now')*1000),
(26, '열성적01∙열성적02', 'enthusiastic', strftime('%s','now')*1000),
(26, '열악하다', 'poor/ inferior', strftime('%s','now')*1000),
(26, '열풍01', 'craze/ boom', strftime('%s','now')*1000),
(26, '염두', 'mind/ consideration', strftime('%s','now')*1000),
(26, '염려', 'worry/ concern', strftime('%s','now')*1000),
(26, '염원', 'earnest desire', strftime('%s','now')*1000),
(26, '염증', 'inflammation/ disgust', strftime('%s','now')*1000),
(26, '염치', 'sense of shame', strftime('%s','now')*1000),
(26, '영광', 'glory/ honor', strftime('%s','now')*1000),
(26, '영락없이00', 'unmistakably/ without fail', strftime('%s','now')*1000),
(26, '영리', 'profit/ gain', strftime('%s','now')*1000),
(26, '영문01', 'English (language)', strftime('%s','now')*1000),
(26, '영문02', 'reason/ grounds', strftime('%s','now')*1000),
(26, '영세민', 'the very poor', strftime('%s','now')*1000),
(26, '영양사00', 'dietitian/ nutritionist', strftime('%s','now')*1000),
(26, '영입', 'recruitment/ bringing in', strftime('%s','now')*1000),
(26, '영장', 'arrest warrant', strftime('%s','now')*1000),
(26, '영재', 'gifted child/ prodigy', strftime('%s','now')*1000),
(26, '영토', 'territory', strftime('%s','now')*1000),
(26, '예견', 'prediction/ foresight', strftime('%s','now')*1000),
(26, '예리하다', 'sharp/ keen', strftime('%s','now')*1000),
(26, '예배', 'worship service', strftime('%s','now')*1000),
(26, '예사롭다', 'ordinary/ usual', strftime('%s','now')*1000),
(26, '예수', 'Jesus', strftime('%s','now')*1000),
(26, '예술성', 'artistry', strftime('%s','now')*1000),
(26, '예의범절', 'etiquette/ manners', strftime('%s','now')*1000),
(26, '예체능', 'arts and physical education', strftime('%s','now')*1000),
(26, '오기01', 'sheer will/ obstinacy', strftime('%s','now')*1000),
(26, '오르막길', 'uphill road', strftime('%s','now')*1000),
(26, '오른팔', 'right-hand man/ right arm', strftime('%s','now')*1000),
(26, '오붓하다', 'cozy/ snug', strftime('%s','now')*1000),
(26, '오죽', 'how (so much)/ no wonder', strftime('%s','now')*1000),
(26, '옥상', 'rooftop', strftime('%s','now')*1000),
(26, '온실가스00', 'greenhouse gas', strftime('%s','now')*1000),
(26, '온전하다', 'intact/ whole', strftime('%s','now')*1000),
(26, '올바로', 'properly/ correctly', strftime('%s','now')*1000),
(26, '옷깃', 'collar', strftime('%s','now')*1000),
(26, '옷자락', 'hem/ edge of clothes', strftime('%s','now')*1000),
(26, '옹기종기', 'closely huddled', strftime('%s','now')*1000),
(26, '완만하다02', 'gentle/ gradual', strftime('%s','now')*1000),
(26, '완주', 'finish (a race)', strftime('%s','now')*1000),
(26, '완화', 'easing/ mitigation', strftime('%s','now')*1000),
(26, '왈가왈부', 'argue back and forth', strftime('%s','now')*1000),
(26, '왕궁', 'royal palace', strftime('%s','now')*1000),
(26, '왕권', 'royal authority', strftime('%s','now')*1000),
(26, '왕위', 'royal throne', strftime('%s','now')*1000),
(26, '왕조', 'dynasty', strftime('%s','now')*1000),
(26, '왜곡', 'distortion', strftime('%s','now')*1000),
(26, '왜소하다', 'petite/ small', strftime('%s','now')*1000),
(26, '외무부00', 'Ministry of Foreign Affairs', strftime('%s','now')*1000),
(26, '외신', 'foreign news', strftime('%s','now')*1000),
(26, '외유내강', 'gentle outside, firm inside', strftime('%s','now')*1000),
(26, '외적01∙외적02', 'external', strftime('%s','now')*1000),
(26, '외제', 'foreign make', strftime('%s','now')*1000),
(26, '외형', 'outward form/ appearance', strftime('%s','now')*1000),
(26, '외형적01∙외형적02', 'external/ superficial', strftime('%s','now')*1000),
(26, '외환', 'foreign exchange', strftime('%s','now')*1000),
(26, '요건', 'requirement', strftime('%s','now')*1000),
(26, '요란', 'noisy/ showy', strftime('%s','now')*1000),
(26, '요양', 'recuperation/ care', strftime('%s','now')*1000),
(26, '요양원', 'nursing home/ sanatorium', strftime('%s','now')*1000),
(26, '요점', 'main point', strftime('%s','now')*1000),
(26, '요컨대', 'in short/ to sum up', strftime('%s','now')*1000),
(26, '요트', 'yacht', strftime('%s','now')*1000),
(26, '용례', 'usage example', strftime('%s','now')*1000),
(26, '용모', 'appearance', strftime('%s','now')*1000),
(26, '용법', 'usage/ dosage', strftime('%s','now')*1000),
(26, '용의자', 'suspect', strftime('%s','now')*1000),
(26, '용이하다', 'easy/ feasible', strftime('%s','now')*1000),
(26, '용하다', 'skilled/ excellent', strftime('%s','now')*1000),
(26, '우거지다', 'be thick/ luxuriant', strftime('%s','now')*1000),
(26, '우뇌00', 'right brain', strftime('%s','now')*1000),
(26, '우뚝', 'prominently/ towering', strftime('%s','now')*1000),
(26, '우러나다', 'be infused/ well up', strftime('%s','now')*1000),
(26, '우렁차다', 'resonant/ sonorous', strftime('%s','now')*1000),
(26, '우발적01∙우발적02', 'accidental/ incidental', strftime('%s','now')*1000),
(26, '우선순위', 'priority', strftime('%s','now')*1000),
(26, '우성', 'dominant (gene)', strftime('%s','now')*1000),
(26, '우세', 'superiority/ predominance', strftime('%s','now')*1000),
(26, '우스꽝스럽다', 'ridiculous/ comical', strftime('%s','now')*1000),
(26, '우여곡절', 'twists and turns', strftime('%s','now')*1000),
(26, '우열00', 'superiority and inferiority', strftime('%s','now')*1000),
(26, '우월', 'superiority', strftime('%s','now')*1000),
(26, '우위', 'upper hand/ advantage', strftime('%s','now')*1000),
(26, '우직하다', 'simple and honest', strftime('%s','now')*1000),
(26, '우파', 'right-wing', strftime('%s','now')*1000),
(26, '우호적01∙우호적02', 'friendly/ amicable', strftime('%s','now')*1000),
(26, '우후죽순', 'like mushrooms after rain', strftime('%s','now')*1000),
(26, '운용', 'operation/ management', strftime('%s','now')*1000),
(26, '운항', 'operation of flights/ships', strftime('%s','now')*1000),
(26, '울렁거리다', 'feel queasy/ churn', strftime('%s','now')*1000),
(26, '울먹이다', 'be on the verge of tears', strftime('%s','now')*1000),
(26, '울부짖다', 'wail/ howl', strftime('%s','now')*1000),
(26, '울창하다', 'dense/ luxuriant', strftime('%s','now')*1000),
(26, '울퉁불퉁', 'bumpy/ uneven', strftime('%s','now')*1000),
(26, '울퉁불퉁하다', 'be bumpy/ be uneven', strftime('%s','now')*1000),
(26, '움츠리다', 'shrink/ cower', strftime('%s','now')*1000),
(26, '움켜잡다', 'grab/ clutch', strftime('%s','now')*1000),
(26, '움켜쥐다', 'grasp/ clutch', strftime('%s','now')*1000),
(26, '웃돌다', 'exceed/ surpass', strftime('%s','now')*1000),
(26, '웅성웅성', 'with a buzz of chatter', strftime('%s','now')*1000),
(26, '웅장하다', 'magnificent/ grand', strftime('%s','now')*1000),
(26, '웅크리다', 'crouch/ huddle', strftime('%s','now')*1000),
(26, '원-', 'prefix: original/ proto-', strftime('%s','now')*1000),
(26, '-원03', 'suffix: person/ member', strftime('%s','now')*1000),
(26, '원가', 'cost (of production)', strftime('%s','now')*1000),
(26, '원격', 'remote', strftime('%s','now')*1000),
(26, '원고01', 'manuscript', strftime('%s','now')*1000),
(26, '원금', 'principal (capital)', strftime('%s','now')*1000),
(26, '원동력', 'driving force', strftime('%s','now')*1000),
(26, '원료', 'raw material', strftime('%s','now')*1000),
(26, '원색적01∙원색적02', 'lurid/ crude/ primary-colored', strftime('%s','now')*1000),
(26, '원시01', 'primitive times/ primeval', strftime('%s','now')*1000),
(26, '원심력', 'centrifugal force', strftime('%s','now')*1000),
(26, '원어민', 'native speaker', strftime('%s','now')*1000),
(26, '원조02', 'aid/ assistance', strftime('%s','now')*1000),
(26, '원주민', 'indigenous people', strftime('%s','now')*1000),
(26, '원형01', 'original form/ prototype', strftime('%s','now')*1000),
(26, '원활', 'smooth/ unhindered', strftime('%s','now')*1000),
(26, '월간01', 'monthly (publication)', strftime('%s','now')*1000),
(26, '월차', 'monthly leave', strftime('%s','now')*1000),
(26, '웰빙00', 'well-being', strftime('%s','now')*1000),
(26, '위계질서', 'hierarchy', strftime('%s','now')*1000),
(26, '위독하다', 'be in critical condition', strftime('%s','now')*1000),
(26, '위력', 'might/ power', strftime('%s','now')*1000),
(26, '위상', 'status/ standing', strftime('%s','now')*1000),
(26, '위생적01∙위생적02', 'hygienic', strftime('%s','now')*1000),
(26, '위성', 'satellite', strftime('%s','now')*1000),
(26, '위안', 'consolation', strftime('%s','now')*1000),
(26, '위암', 'stomach cancer', strftime('%s','now')*1000),
(26, '위원', 'committee member', strftime('%s','now')*1000),
(26, '위인01', 'great person', strftime('%s','now')*1000),
(26, '위인02', 'one’s character/ disposition', strftime('%s','now')*1000),
(26, '위조', 'forgery', strftime('%s','now')*1000),
(26, '위축', 'shrinkage/ contraction', strftime('%s','now')*1000),
(26, '위태롭다', 'precarious/ risky', strftime('%s','now')*1000),
(26, '위화감', 'sense of disharmony', strftime('%s','now')*1000),
(26, '유02', 'oil', strftime('%s','now')*1000),
(26, '유가01', 'oil price', strftime('%s','now')*1000),
(26, '유감', 'regret', strftime('%s','now')*1000),
(26, '유골', 'remains/ bones (ashes)', strftime('%s','now')*1000),
(26, '유권자', 'voter', strftime('%s','now')*1000),
(26, '유난스럽다', 'overly fussy/ over-the-top', strftime('%s','now')*1000),
(26, '유대감', 'sense of bond', strftime('%s','now')*1000),
(26, '유도01', 'inducement/ guidance', strftime('%s','now')*1000),
(26, '유독02', 'toxic/ poisonous', strftime('%s','now')*1000),
(26, '유동', 'flow/ movement', strftime('%s','now')*1000),
(26, '유동적01∙유동적02', 'fluid/ flexible', strftime('%s','now')*1000),
(26, '유례', 'precedent', strftime('%s','now')*1000),
(26, '유발', 'cause/ induce', strftime('%s','now')*1000),
(26, '유비무환', 'forewarned is forearmed', strftime('%s','now')*1000),
(26, '유서02', 'will/ testament', strftime('%s','now')*1000),
(26, '유세', 'electioneering/ campaigning', strftime('%s','now')*1000),
(26, '유식하다', 'erudite/ learned', strftime('%s','now')*1000),
(26, '유언', 'dying words/ last will', strftime('%s','now')*1000),
(26, '유언비어', 'groundless rumor', strftime('%s','now')*1000),
(26, '유연성', 'flexibility', strftime('%s','now')*1000),
(26, '유유상종', 'birds of a feather flock together', strftime('%s','now')*1000),
(26, '유일무이', 'one and only', strftime('%s','now')*1000),
(26, '유입', 'inflow', strftime('%s','now')*1000),
(26, '유전02', 'heredity', strftime('%s','now')*1000),
(26, '유전병', 'genetic disease', strftime('%s','now')*1000),
(26, '유창성', 'fluency', strftime('%s','now')*1000),
(26, '유치02', 'primary tooth/ baby tooth', strftime('%s','now')*1000),
(26, '유포', 'dissemination/ circulation', strftime('%s','now')*1000),
(26, '유학03', 'study abroad', strftime('%s','now')*1000),
(26, '유행가', 'popular song', strftime('%s','now')*1000),
(26, '유흥비', 'entertainment expenses', strftime('%s','now')*1000),
(26, '유희', 'play/ amusement', strftime('%s','now')*1000),
(26, '육로', 'overland route', strftime('%s','now')*1000),
(26, '윤리적00', 'ethical', strftime('%s','now')*1000),
(26, '율동', 'rhythmic movement', strftime('%s','now')*1000),
(26, '융통성', 'flexibility', strftime('%s','now')*1000),
(26, '융합', 'fusion/ convergence', strftime('%s','now')*1000),
(26, '으스대다', 'swagger/ show off', strftime('%s','now')*1000),
(26, '은근히', 'subtly/ quietly', strftime('%s','now')*1000),
(26, '은메달', 'silver medal', strftime('%s','now')*1000),
(26, '은사01', 'benefactor/ former teacher', strftime('%s','now')*1000),
(26, '은은하다', 'faint/ subdued', strftime('%s','now')*1000),
(26, '음02', 'sound/ note', strftime('%s','now')*1000),
(26, '음모00', 'conspiracy/ plot', strftime('%s','now')*1000),
(26, '음향', 'sound/ acoustics', strftime('%s','now')*1000),
(26, '의02', 'righteousness/ justice', strftime('%s','now')*1000),
(26, '의도적01∙의도적02', 'intentional', strftime('%s','now')*1000),
(26, '의례적01∙의례적02', 'ceremonial/ customary', strftime('%s','now')*1000),
(26, '의뢰', 'request/ commission', strftime('%s','now')*1000),
(26, '의리', 'loyalty/ fidelity', strftime('%s','now')*1000),
(26, '의생활', 'clothing life/ dress habits', strftime('%s','now')*1000),
(26, '의술', 'medical skill', strftime('%s','now')*1000),
(26, '의식적01∙의식적02', 'conscious/ deliberate', strftime('%s','now')*1000),
(26, '의아하다', 'be doubtful/ puzzled', strftime('%s','now')*1000),
(26, '의욕적01∙의욕적02', 'motivated/ eager', strftime('%s','now')*1000),
(26, '의원02', 'lawmaker/ assembly member', strftime('%s','now')*1000),
(26, '의젓하다', 'mature/ composed', strftime('%s','now')*1000),
(26, '의존도', 'degree of dependence', strftime('%s','now')*1000),
(26, '의존적01∙의존적02', 'dependent', strftime('%s','now')*1000),
(26, '의학적01∙의학적02', 'medical', strftime('%s','now')*1000),
(26, '의향', 'intention/ willingness', strftime('%s','now')*1000),
(26, '의혹', 'suspicion/ doubt', strftime('%s','now')*1000),
(26, '의회', 'assembly/ parliament', strftime('%s','now')*1000);