PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(5, '올림픽', 'Olympics', strftime('%s','now')*1000),
(5, '옳다', 'right, correct', strftime('%s','now')*1000),
(5, '옷걸이', 'hanger', strftime('%s','now')*1000),
(5, '옷장', 'wardrobe, closet', strftime('%s','now')*1000),
(5, '와이셔츠', 'dress shirt', strftime('%s','now')*1000),
(5, '완전히', 'completely', strftime('%s','now')*1000),
(5, '왕', 'king', strftime('%s','now')*1000),
(5, '왜냐하면', 'because', strftime('%s','now')*1000),
(5, '외롭다', 'lonely', strftime('%s','now')*1000),
(5, '외우다', 'to memorize', strftime('%s','now')*1000),
(5, '외출', 'going out', strftime('%s','now')*1000),
(5, '왼손', 'left hand', strftime('%s','now')*1000),
(5, '요금', 'fee, fare', strftime('%s','now')*1000),
(5, '요리사', 'chef, cook', strftime('%s','now')*1000),
(5, '우동', 'udon (noodles)', strftime('%s','now')*1000),
(5, '우리나라', 'our country (Korea)', strftime('%s','now')*1000),
(5, '우선', 'first, above all', strftime('%s','now')*1000),
(5, '운동복', 'sportswear', strftime('%s','now')*1000),
(5, '운전사', 'driver', strftime('%s','now')*1000),
(5, '울산', 'Ulsan (city)', strftime('%s','now')*1000),
(5, '울음', 'crying, weeping', strftime('%s','now')*1000),
(5, '움직이다', 'to move', strftime('%s','now')*1000),
(5, '웃음', 'laughter', strftime('%s','now')*1000),
(5, '원피스', 'one-piece dress', strftime('%s','now')*1000),
(5, '원하다', 'to want', strftime('%s','now')*1000),
(5, '월급', 'salary, wages', strftime('%s','now')*1000),
(5, '위쪽', 'upper part, above', strftime('%s','now')*1000),
(5, '위치', 'location', strftime('%s','now')*1000),
(5, '위험', 'danger', strftime('%s','now')*1000),
(5, '유리', 'glass', strftime('%s','now')*1000),
(5, '유치원', 'kindergarten', strftime('%s','now')*1000),
(5, '유학', 'study abroad', strftime('%s','now')*1000),
(5, '유학생', 'international student', strftime('%s','now')*1000),
(5, '유행', 'fashion, trend', strftime('%s','now')*1000),
(5, '육교', 'pedestrian overpass', strftime('%s','now')*1000),
(5, '윷놀이', 'yut game', strftime('%s','now')*1000),
(5, '음료', 'beverage', strftime('%s','now')*1000),
(5, '음식점', 'restaurant', strftime('%s','now')*1000),
(5, '음악가', 'musician', strftime('%s','now')*1000),
(5, '응', 'uh-huh, yes', strftime('%s','now')*1000),
(5, '의미', 'meaning', strftime('%s','now')*1000),
(5, '이', 'this', strftime('%s','now')*1000),
(5, '이거', 'this thing', strftime('%s','now')*1000),
(5, '이곳', 'this place', strftime('%s','now')*1000),
(5, '이기다', 'to win', strftime('%s','now')*1000),
(5, '이날', 'on this day', strftime('%s','now')*1000),
(5, '이때', 'at this time', strftime('%s','now')*1000),
(5, '이런', 'such, like this', strftime('%s','now')*1000),
(5, '이렇다', 'to be like this', strftime('%s','now')*1000),
(5, '이르다', 'to be early', strftime('%s','now')*1000),
(5, '이마', 'forehead', strftime('%s','now')*1000),
(5, '이모', 'aunt (maternal)', strftime('%s','now')*1000),
(5, '이미', 'already', strftime('%s','now')*1000),
(5, '이분', 'this person (hon.)', strftime('%s','now')*1000),
(5, '이불', 'blanket, quilt', strftime('%s','now')*1000),
(5, '이사', 'moving (house)', strftime('%s','now')*1000),
(5, '이삿짐', 'moving belongings', strftime('%s','now')*1000),
(5, '이상', 'abnormality, above', strftime('%s','now')*1000),
(5, '이용', 'use, utilization', strftime('%s','now')*1000),
(5, '이웃', 'neighbor', strftime('%s','now')*1000),
(5, '이전', 'before, previous', strftime('%s','now')*1000),
(5, '이제', 'now, already', strftime('%s','now')*1000),
(5, '이틀', 'two days', strftime('%s','now')*1000),
(5, '이해', 'understanding', strftime('%s','now')*1000),
(5, '이후', 'after, afterwards', strftime('%s','now')*1000),
(5, '익다', 'to ripen, be cooked', strftime('%s','now')*1000),
(5, '익숙하다', 'to be accustomed, familiar', strftime('%s','now')*1000),
(5, '인기', 'popularity', strftime('%s','now')*1000),
(5, '인삼', 'ginseng', strftime('%s','now')*1000),
(5, '인형', 'doll', strftime('%s','now')*1000),
(5, '일기', 'diary', strftime('%s','now')*1000),
(5, '일부', 'part, portion', strftime('%s','now')*1000),
(5, '일식', 'Japanese cuisine', strftime('%s','now')*1000),
(5, '일식집', 'Japanese restaurant', strftime('%s','now')*1000),
(5, '일어서다', 'to stand up', strftime('%s','now')*1000),
(5, '잃다', 'to lose', strftime('%s','now')*1000),
(5, '잃어버리다', 'to lose completely', strftime('%s','now')*1000),
(5, '입구', 'entrance', strftime('%s','now')*1000),
(5, '입술', 'lips', strftime('%s','now')*1000),
(5, '입원', 'hospitalization', strftime('%s','now')*1000),
(5, '입장권', 'admission ticket', strftime('%s','now')*1000),
(5, '입학', 'admission (to school)', strftime('%s','now')*1000),
(5, '잊다', 'to forget', strftime('%s','now')*1000),
(5, '잊어버리다', 'to completely forget', strftime('%s','now')*1000),
(5, '잎', 'leaf', strftime('%s','now')*1000),
(5, '자기소개', 'self-introduction', strftime('%s','now')*1000),
(5, '자꾸', 'constantly, repeatedly', strftime('%s','now')*1000),
(5, '자동판매기', 'vending machine', strftime('%s','now')*1000),
(5, '자라다', 'to grow (up)', strftime('%s','now')*1000),
(5, '자랑', 'pride, boasting', strftime('%s','now')*1000),
(5, '자르다', 'to cut', strftime('%s','now')*1000),
(5, '자리', 'seat, place', strftime('%s','now')*1000),
(5, '자세히', 'in detail', strftime('%s','now')*1000),
(5, '자식', 'children (one’s)', strftime('%s','now')*1000),
(5, '자신', 'confidence, oneself', strftime('%s','now')*1000),
(5, '자연', 'nature', strftime('%s','now')*1000),
(5, '자유', 'freedom', strftime('%s','now')*1000),
(5, '자장면', 'jjajangmyeon (noodles)', strftime('%s','now')*1000),
(5, '자판기', 'vending machine', strftime('%s','now')*1000),
(5, '잔치', 'feast, party', strftime('%s','now')*1000),
(5, '잘되다', 'to go well, succeed', strftime('%s','now')*1000),
(5, '잘못되다', 'to be wrong, go wrong', strftime('%s','now')*1000),
(5, '잘못하다', 'to make a mistake', strftime('%s','now')*1000),
(5, '잘생기다', 'to be handsome', strftime('%s','now')*1000),
(5, '잠자다', 'to sleep', strftime('%s','now')*1000),
(5, '잡다', 'to catch, grab', strftime('%s','now')*1000),
(5, '잡지', 'magazine', strftime('%s','now')*1000),
(5, '장', 'chapter, market', strftime('%s','now')*1000),
(5, '장갑', 'gloves', strftime('%s','now')*1000),
(5, '장난감', 'toy', strftime('%s','now')*1000),
(5, '장마', 'rainy season', strftime('%s','now')*1000),
(5, '장미', 'rose', strftime('%s','now')*1000),
(5, '재료', 'material, ingredient', strftime('%s','now')*1000),
(5, '재미', 'interest, fun', strftime('%s','now')*1000),
(5, '재채기', 'sneeze', strftime('%s','now')*1000),
(5, '저거', 'that thing (over there)', strftime('%s','now')*1000),
(5, '저곳', 'that place (over there)', strftime('%s','now')*1000),
(5, '저금', 'savings', strftime('%s','now')*1000),
(5, '저런', 'that kind (over there)', strftime('%s','now')*1000),
(5, '저렇다', 'to be like that (over there)', strftime('%s','now')*1000),
(5, '저번', 'last time', strftime('%s','now')*1000),
(5, '저분', 'that person (hon.)', strftime('%s','now')*1000),
(5, '저희', 'we, our (humble)', strftime('%s','now')*1000),
(5, '적다', 'to write down, be few', strftime('%s','now')*1000),
(5, '적당하다', 'appropriate, suitable', strftime('%s','now')*1000),
(5, '전', 'before, earlier', strftime('%s','now')*1000),
(5, '전기', 'electricity', strftime('%s','now')*1000),
(5, '전부', 'all, entirely', strftime('%s','now')*1000),
(5, '전철', 'subway', strftime('%s','now')*1000),
(5, '전체', 'the whole, entire', strftime('%s','now')*1000),
(5, '전하다', 'to convey, deliver', strftime('%s','now')*1000),
(5, '전혀', 'not at all', strftime('%s','now')*1000),
(5, '전화기', 'telephone set', strftime('%s','now')*1000),
(5, '젊다', 'young', strftime('%s','now')*1000),
(5, '점수', 'score, grade', strftime('%s','now')*1000),
(5, '점심시간', 'lunchtime', strftime('%s','now')*1000),
(5, '점점', 'gradually', strftime('%s','now')*1000),
(5, '접다', 'to fold', strftime('%s','now')*1000),
(5, '접시', 'plate', strftime('%s','now')*1000),
(5, '젓가락', 'chopsticks', strftime('%s','now')*1000),
(5, '정거장', 'stop, station', strftime('%s','now')*1000),
(5, '정도', 'degree, level', strftime('%s','now')*1000),
(5, '정리', 'tidying, organizing', strftime('%s','now')*1000),
(5, '정문', 'main gate', strftime('%s','now')*1000),
(5, '정원', 'garden', strftime('%s','now')*1000),
(5, '정하다', 'to decide, determine', strftime('%s','now')*1000),
(5, '정확', 'accuracy', strftime('%s','now')*1000),
(5, '젖다', 'to get wet', strftime('%s','now')*1000),
(5, '제목', 'title, subject', strftime('%s','now')*1000),
(5, '조금씩', 'little by little', strftime('%s','now')*1000),
(5, '조심', 'caution, care', strftime('%s','now')*1000),
(5, '조용히', 'quietly', strftime('%s','now')*1000),
(5, '조카', 'nephew, niece', strftime('%s','now')*1000),
(5, '졸다', 'to doze', strftime('%s','now')*1000),
(5, '좁다', 'narrow, cramped', strftime('%s','now')*1000),
(5, '종류', 'kind, type', strftime('%s','now')*1000),
(5, '종이', 'paper', strftime('%s','now')*1000),
(5, '주머니', 'pocket', strftime('%s','now')*1000),
(5, '주문', 'order', strftime('%s','now')*1000),
(5, '주변', 'surroundings, vicinity', strftime('%s','now')*1000),
(5, '주사', 'injection', strftime('%s','now')*1000),
(5, '주위', 'around, surroundings', strftime('%s','now')*1000),
(5, '주차', 'parking', strftime('%s','now')*1000),
(5, '주차장', 'parking lot', strftime('%s','now')*1000),
(5, '주황색', 'orange (color)', strftime('%s','now')*1000),
(5, '죽다', 'to die', strftime('%s','now')*1000),
(5, '줄', 'rope, line, row', strftime('%s','now')*1000),
(5, '줄다', 'to decrease', strftime('%s','now')*1000),
(5, '줄이다', 'to reduce', strftime('%s','now')*1000),
(5, '줍다', 'to pick up', strftime('%s','now')*1000),
(5, '중간', 'middle', strftime('%s','now')*1000),
(5, '중국집', 'Chinese restaurant', strftime('%s','now')*1000),
(5, '중심', 'center, core', strftime('%s','now')*1000),
(5, '중앙', 'center', strftime('%s','now')*1000),
(5, '중요', 'importance', strftime('%s','now')*1000),
(5, '중학교', 'middle school', strftime('%s','now')*1000),
(5, '중학생', 'middle school student', strftime('%s','now')*1000),
(5, '즐거워하다', 'to feel happy, delight', strftime('%s','now')*1000),
(5, '즐겁다', 'pleasant, joyful', strftime('%s','now')*1000),
(5, '즐기다', 'to enjoy', strftime('%s','now')*1000),
(5, '지각', 'tardiness', strftime('%s','now')*1000),
(5, '지나가다', 'to pass by', strftime('%s','now')*1000),
(5, '지난번', 'last time', strftime('%s','now')*1000),
(5, '지다', 'to lose, (sun) set', strftime('%s','now')*1000),
(5, '지도', 'map', strftime('%s','now')*1000),
(5, '지루하다', 'boring', strftime('%s','now')*1000),
(5, '지르다', 'to shout, yell', strftime('%s','now')*1000),
(5, '지방', 'region, area', strftime('%s','now')*1000),
(5, '지우다', 'to erase, delete', strftime('%s','now')*1000),
(5, '지키다', 'to protect, keep', strftime('%s','now')*1000),
(5, '지하', 'underground', strftime('%s','now')*1000),
(5, '지하도', 'underpass', strftime('%s','now')*1000),
(5, '직장', 'workplace, job', strftime('%s','now')*1000),
(5, '직접', 'directly, in person', strftime('%s','now')*1000),
(5, '진짜', 'real, really', strftime('%s','now')*1000),
(5, '진하다', 'thick, rich', strftime('%s','now')*1000),
(5, '짐', 'baggage, stuff', strftime('%s','now')*1000),
(5, '집들이', 'housewarming', strftime('%s','now')*1000),
(5, '집안일', 'housework', strftime('%s','now')*1000),
(5, '짓다', 'to build, compose', strftime('%s','now')*1000),
(5, '짜증', 'irritation', strftime('%s','now')*1000),
(5, '짝', 'pair, partner', strftime('%s','now')*1000),
(5, '짧다', 'short', strftime('%s','now')*1000),
(5, '짬뽕', 'jjamppong (noodles)', strftime('%s','now')*1000),
(5, '찌개', 'stew (jjigae)', strftime('%s','now')*1000),
(5, '찌다', 'to steam, to gain weight', strftime('%s','now')*1000),
(5, '차', 'car, tea', strftime('%s','now')*1000),
(5, '차갑다', 'cold (to the touch)', strftime('%s','now')*1000),
(5, '차다', 'to be full, to kick, to wear', strftime('%s','now')*1000),
(5, '차례', 'turn, order', strftime('%s','now')*1000),
(5, '착하다', 'kind', strftime('%s','now')*1000),
(5, '찬물', 'cold water', strftime('%s','now')*1000),
(5, '참다', 'to endure', strftime('%s','now')*1000),
(5, '찾아가다', 'to go visit', strftime('%s','now')*1000),
(5, '찾아오다', 'to come visit', strftime('%s','now')*1000),
(5, '채소', 'vegetables', strftime('%s','now')*1000),
(5, '책장', 'bookcase', strftime('%s','now')*1000),
(5, '첫', 'first', strftime('%s','now')*1000),
(5, '첫날', 'first day', strftime('%s','now')*1000),
(5, '첫째', 'first, eldest', strftime('%s','now')*1000),
(5, '청년', 'youth, young man', strftime('%s','now')*1000),
(5, '청바지', 'jeans', strftime('%s','now')*1000),
(5, '청소년', 'adolescent, teenager', strftime('%s','now')*1000),
(5, '체육관', 'gymnasium', strftime('%s','now')*1000),
(5, '쳐다보다', 'to look up at, gaze at', strftime('%s','now')*1000),
(5, '초', 'beginning, candle, second', strftime('%s','now')*1000),
(5, '초대장', 'invitation card', strftime('%s','now')*1000),
(5, '초등학교', 'elementary school', strftime('%s','now')*1000),
(5, '초등학생', 'elementary school student', strftime('%s','now')*1000),
(5, '초록색', 'green (color)', strftime('%s','now')*1000),
(5, '최고', 'the best, highest', strftime('%s','now')*1000),
(5, '최근', 'recently, lately', strftime('%s','now')*1000),
(5, '추석', 'Chuseok (harvest festival)', strftime('%s','now')*1000),
(5, '축구공', 'soccer ball', strftime('%s','now')*1000),
(5, '출구', 'exit', strftime('%s','now')*1000),
(5, '출근', 'going to work', strftime('%s','now')*1000),
(5, '출석', 'attendance', strftime('%s','now')*1000),
(5, '출입', 'entry and exit', strftime('%s','now')*1000),
(5, '출입국', 'immigration (in/out of country)', strftime('%s','now')*1000),
(5, '출장', 'business trip', strftime('%s','now')*1000),
(5, '출퇴근', 'commuting', strftime('%s','now')*1000),
(5, '충분하다', 'sufficient', strftime('%s','now')*1000),
(5, '취소', 'cancellation', strftime('%s','now')*1000),
(5, '취직', 'getting a job', strftime('%s','now')*1000),
(5, '치과', 'dentistry, dental clinic', strftime('%s','now')*1000),
(5, '치료', 'treatment', strftime('%s','now')*1000),
(5, '치약', 'toothpaste', strftime('%s','now')*1000),
(5, '치킨', 'fried chicken', strftime('%s','now')*1000),
(5, '친척', 'relative', strftime('%s','now')*1000),
(5, '침실', 'bedroom', strftime('%s','now')*1000),
(5, '칫솔', 'toothbrush', strftime('%s','now')*1000),
(5, '칭찬', 'praise', strftime('%s','now')*1000),
(5, '카레', 'curry', strftime('%s','now')*1000),
(5, '카페', 'cafe', strftime('%s','now')*1000),
(5, '칼', 'knife', strftime('%s','now')*1000),
(5, '칼국수', 'kalguksu (noodles)', strftime('%s','now')*1000),
(5, '켜다', 'to turn on', strftime('%s','now')*1000),
(5, '켤레', 'pair (shoes, socks)', strftime('%s','now')*1000),
(5, '코끼리', 'elephant', strftime('%s','now')*1000),
(5, '콧물', 'snot, runny nose', strftime('%s','now')*1000),
(5, '콩', 'bean', strftime('%s','now')*1000),
(5, '크기', 'size', strftime('%s','now')*1000),
(5, '크리스마스', 'Christmas', strftime('%s','now')*1000),
(5, '큰소리', 'loud voice', strftime('%s','now')*1000),
(5, '키우다', 'to raise, grow', strftime('%s','now')*1000),
(5, '킬로그램', 'kilogram', strftime('%s','now')*1000),
(5, '킬로미터', 'kilometer', strftime('%s','now')*1000),
(5, '타다', 'to ride, get on', strftime('%s','now')*1000),
(5, '탕수육', 'tangsuyuk', strftime('%s','now')*1000),
(5, '태극기', 'Taegeukgi (Korean flag)', strftime('%s','now')*1000),
(5, '태도', 'attitude, behavior', strftime('%s','now')*1000),
(5, '태어나다', 'to be born', strftime('%s','now')*1000),
(5, '태풍', 'typhoon', strftime('%s','now')*1000),
(5, '택배', 'parcel delivery', strftime('%s','now')*1000),
(5, '테니스장', 'tennis court', strftime('%s','now')*1000),
(5, '테이블', 'table', strftime('%s','now')*1000),
(5, '토끼', 'rabbit', strftime('%s','now')*1000),
(5, '토마토', 'tomato', strftime('%s','now')*1000),
(5, '통장', 'bankbook', strftime('%s','now')*1000),
(5, '통화', 'phone call, currency', strftime('%s','now')*1000),
(5, '퇴원', 'discharge from hospital', strftime('%s','now')*1000),
(5, '튀기다', 'to deep-fry', strftime('%s','now')*1000),
(5, '튀김', 'fried food', strftime('%s','now')*1000),
(5, '트럭', 'truck', strftime('%s','now')*1000),
(5, '특별히', 'especially, particularly', strftime('%s','now')*1000),
(5, '튼튼하다', 'strong, sturdy', strftime('%s','now')*1000),
(5, '틀다', 'to turn on, turn', strftime('%s','now')*1000),
(5, '틀리다', 'to be wrong', strftime('%s','now')*1000),
(5, '팀', 'team', strftime('%s','now')*1000),
(5, '파란색', 'blue (color)', strftime('%s','now')*1000),
(5, '파랗다', 'to be blue', strftime('%s','now')*1000),
(5, '팔리다', 'to be sold', strftime('%s','now')*1000),
(5, '펴다', 'to open, spread out', strftime('%s','now')*1000),
(5, '편리', 'convenience', strftime('%s','now')*1000),
(5, '편안', 'comfort, peace', strftime('%s','now')*1000),
(5, '편찮다', 'to be ill (hon.)', strftime('%s','now')*1000),
(5, '편하다', 'comfortable, easy', strftime('%s','now')*1000),
(5, '평소', 'ordinary times, usually', strftime('%s','now')*1000),
(5, '평일', 'weekday', strftime('%s','now')*1000),
(5, '포장', 'packaging', strftime('%s','now')*1000),
(5, '푸르다', 'blue, green', strftime('%s','now')*1000),
(5, '푹', 'deeply, fully', strftime('%s','now')*1000),
(5, '풀다', 'to untie, solve', strftime('%s','now')*1000),
(5, '풍경', 'scenery, landscape', strftime('%s','now')*1000),
(5, '프라이팬', 'frying pan', strftime('%s','now')*1000),
(5, '피', 'blood', strftime('%s','now')*1000),
(5, '피다', 'to bloom', strftime('%s','now')*1000),
(5, '하늘', 'sky', strftime('%s','now')*1000),
(5, '하늘색', 'sky blue', strftime('%s','now')*1000),
(5, '-하다', 'verb-forming suffix “-hada”', strftime('%s','now')*1000),
(5, '하숙비', 'boarding fee', strftime('%s','now')*1000),
(5, '하얀색', 'white (color)', strftime('%s','now')*1000),
(5, '하얗다', 'to be white', strftime('%s','now')*1000),
(5, '학기', 'semester', strftime('%s','now')*1000),
(5, '학년', 'grade, year (school)', strftime('%s','now')*1000),
(5, '학원', 'private academy', strftime('%s','now')*1000),
(5, '한강', 'Han River', strftime('%s','now')*1000),
(5, '한글', 'Hangeul', strftime('%s','now')*1000),
(5, '한두', 'one or two', strftime('%s','now')*1000),
(5, '한번', 'once, sometime', strftime('%s','now')*1000),
(5, '한식', 'Korean cuisine', strftime('%s','now')*1000),
(5, '한식집', 'Korean restaurant', strftime('%s','now')*1000),
(5, '한옥', 'traditional Korean house', strftime('%s','now')*1000),
(5, '한잔', 'one drink, have a drink', strftime('%s','now')*1000),
(5, '한턱', 'treat (one’s shout)', strftime('%s','now')*1000),
(5, '할인', 'discount', strftime('%s','now')*1000),
(5, '항공', 'aviation, air', strftime('%s','now')*1000),
(5, '항공권', 'air ticket', strftime('%s','now')*1000),
(5, '항상', 'always', strftime('%s','now')*1000),
(5, '해', 'sun, year', strftime('%s','now')*1000),
(5, '해마다', 'every year', strftime('%s','now')*1000),
(5, '해외', 'overseas, abroad', strftime('%s','now')*1000),
(5, '해외여행', 'overseas trip', strftime('%s','now')*1000),
(5, '햄버거', 'hamburger', strftime('%s','now')*1000),
(5, '햇빛', 'sunlight', strftime('%s','now')*1000),
(5, '행동', 'behavior, action', strftime('%s','now')*1000),
(5, '행복', 'happiness', strftime('%s','now')*1000),
(5, '행사', 'event', strftime('%s','now')*1000),
(5, '허리', 'waist, lower back', strftime('%s','now')*1000),
(5, '헤어지다', 'to part, break up', strftime('%s','now')*1000),
(5, '헬스클럽', 'fitness club', strftime('%s','now')*1000),
(5, '혀', 'tongue (organ)', strftime('%s','now')*1000),
(5, '현금', 'cash', strftime('%s','now')*1000),
(5, '현재', 'present, current', strftime('%s','now')*1000),
(5, '형제', 'brothers, siblings', strftime('%s','now')*1000),
(5, '호랑이', 'tiger', strftime('%s','now')*1000),
(5, '호수', 'lake', strftime('%s','now')*1000),
(5, '혹시', 'by any chance, perhaps', strftime('%s','now')*1000),
(5, '홍차', 'black tea', strftime('%s','now')*1000),
(5, '화', 'anger', strftime('%s','now')*1000),
(5, '화가', 'painter (artist)', strftime('%s','now')*1000),
(5, '화나다', 'to get angry', strftime('%s','now')*1000),
(5, '화내다', 'to express anger', strftime('%s','now')*1000),
(5, '화려하다', 'splendid, luxurious', strftime('%s','now')*1000),
(5, '화장품', 'cosmetics', strftime('%s','now')*1000),
(5, '환영', 'welcome, warm reception', strftime('%s','now')*1000),
(5, '환자', 'patient', strftime('%s','now')*1000),
(5, '환전', 'currency exchange', strftime('%s','now')*1000),
(5, '회', 'meeting, time (counter)', strftime('%s','now')*1000),
(5, '회색', 'gray (color)', strftime('%s','now')*1000),
(5, '회원', 'member', strftime('%s','now')*1000),
(5, '횡단보도', 'crosswalk', strftime('%s','now')*1000),
(5, '후배', 'junior (at school/work)', strftime('%s','now')*1000),
(5, '훌륭하다', 'excellent, outstanding', strftime('%s','now')*1000),
(5, '훨씬', 'much, far more', strftime('%s','now')*1000),
(5, '휴게실', 'lounge, break room', strftime('%s','now')*1000),
(5, '휴대폰', 'mobile phone', strftime('%s','now')*1000),
(5, '휴일', 'day off, holiday', strftime('%s','now')*1000),
(5, '휴지', 'tissue, paper', strftime('%s','now')*1000),
(5, '휴지통', 'trash can', strftime('%s','now')*1000),
(5, '흐르다', 'to flow', strftime('%s','now')*1000),
(5, '흔들다', 'to shake, swing', strftime('%s','now')*1000),
(5, '흘리다', 'to drop, spill', strftime('%s','now')*1000),
(5, '희망', 'hope', strftime('%s','now')*1000),
(5, '흰색', 'white (color)', strftime('%s','now')*1000),
(5, '힘', 'strength, power', strftime('%s','now')*1000)
/


