PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(3, '가까이01', 'nearly', strftime('%s','now')*1000),
(3, '가까이02', 'nearby', strftime('%s','now')*1000),
(3, '가끔', 'sometimes', strftime('%s','now')*1000),
(3, '가늘다', 'to be thin', strftime('%s','now')*1000),
(3, '가득', 'full', strftime('%s','now')*1000),
(3, '가리키다', 'to point', strftime('%s','now')*1000),
(3, '가슴', 'chest', strftime('%s','now')*1000),
(3, '가위01', 'scissors', strftime('%s','now')*1000),
(3, '가져가다', 'to take', strftime('%s','now')*1000),
(3, '가져오다', 'to bring', strftime('%s','now')*1000),
(3, '각각02', 'each (version 2)', strftime('%s','now')*1000),
(3, '각각01', 'each (version 1)', strftime('%s','now')*1000),
(3, '간단하다', 'to be simple', strftime('%s','now')*1000),
(3, '간단히', 'simply', strftime('%s','now')*1000),
(3, '간식', 'snack', strftime('%s','now')*1000),
(3, '간장01', 'soy sauce (version 1)', strftime('%s','now')*1000),
(3, '간호사', 'nurse', strftime('%s','now')*1000),
(3, '갈색', 'brown', strftime('%s','now')*1000),
(3, '갈아입다', 'to change clothes', strftime('%s','now')*1000),
(3, '감기약', 'cold medicine', strftime('%s','now')*1000),
(3, '감다01', 'to close (eyes version 1)', strftime('%s','now')*1000),
(3, '감다02', 'to close (eyes version 2)', strftime('%s','now')*1000),
(3, '감자01', 'potato (version 1)', strftime('%s','now')*1000),
(3, '갑자기', 'suddenly', strftime('%s','now')*1000),
(3, '강', 'river', strftime('%s','now')*1000),
(3, '강아지', 'puppy', strftime('%s','now')*1000),
(3, '강하다02', 'to be strong (version 2)', strftime('%s','now')*1000),
(3, '갖다01', 'to have (version 1)', strftime('%s','now')*1000),
(3, '갚다', 'to repay', strftime('%s','now')*1000),
(3, '개월', 'month (counter)', strftime('%s','now')*1000),
(3, '거01', 'thing (version 1)', strftime('%s','now')*1000),
(3, '거리01', 'distance (version 1)', strftime('%s','now')*1000),
(3, '거리03', 'distance (version 3)', strftime('%s','now')*1000),
(3, '거울', 'mirror', strftime('%s','now')*1000),
(3, '거의02', 'almost (version 2)', strftime('%s','now')*1000),
(3, '거의01', 'almost (version 1)', strftime('%s','now')*1000),
(3, '거절', 'refusal', strftime('%s','now')*1000),
(3, '거짓말', 'lie', strftime('%s','now')*1000),
(3, '걱정', 'worry', strftime('%s','now')*1000),
(3, '건너가다', 'to cross over', strftime('%s','now')*1000),
(3, '건너다', 'to cross', strftime('%s','now')*1000),
(3, '걸어가다', 'to walk', strftime('%s','now')*1000),
(3, '걸어오다01', 'to walk over (version 1)', strftime('%s','now')*1000),
(3, '걸음', 'step', strftime('%s','now')*1000),
(3, '검사02', 'inspection (version 2)', strftime('%s','now')*1000),
(3, '검은색', 'black color', strftime('%s','now')*1000),
(3, '검정01', 'black (version 1)', strftime('%s','now')*1000),
(3, '겉', 'outside', strftime('%s','now')*1000),
(3, '게으르다', 'to be lazy', strftime('%s','now')*1000),
(3, '결과', 'result', strftime('%s','now')*1000),
(3, '결석', 'absence', strftime('%s','now')*1000),
(3, '결심', 'decision', strftime('%s','now')*1000),
(3, '결정01', 'decision (version 1)', strftime('%s','now')*1000),
(3, '결혼', 'marriage', strftime('%s','now')*1000),
(3, '결혼식', 'wedding', strftime('%s','now')*1000),
(3, '경기02', 'game (version 2)', strftime('%s','now')*1000),
(3, '경찰', 'police', strftime('%s','now')*1000),
(3, '경찰서', 'police station', strftime('%s','now')*1000),
(3, '경치', 'scenery', strftime('%s','now')*1000),
(3, '경험', 'experience', strftime('%s','now')*1000),
(3, '계단', 'stairs', strftime('%s','now')*1000),
(3, '계란', 'egg', strftime('%s','now')*1000),
(3, '계산', 'calculation', strftime('%s','now')*1000),
(3, '고개01', 'head (version 1)', strftime('%s','now')*1000),
(3, '고등학교', 'high school', strftime('%s','now')*1000),
(3, '고등학생', 'high school student', strftime('%s','now')*1000),
(3, '고모', 'aunt (father’s side)', strftime('%s','now')*1000),
(3, '고민', 'worry, concern', strftime('%s','now')*1000),
(3, '고속버스', 'express bus', strftime('%s','now')*1000),
(3, '고장02', 'breakdown (version 2)', strftime('%s','now')*1000),
(3, '고추장', 'gochujang (Korean chili paste)', strftime('%s','now')*1000),
(3, '고치다', 'to fix, repair', strftime('%s','now')*1000),
(3, '곧', 'soon', strftime('%s','now')*1000),
(3, '공01', 'public (version 1)', strftime('%s','now')*1000),
(3, '공무원', 'civil servant', strftime('%s','now')*1000),
(3, '공장', 'factory', strftime('%s','now')*1000),
(3, '공짜', 'free, no charge', strftime('%s','now')*1000),
(3, '공휴일', 'public holiday', strftime('%s','now')*1000),
(3, '과거02', 'past (version 2)', strftime('%s','now')*1000),
(3, '과자', 'snack, biscuit', strftime('%s','now')*1000),
(3, '관계02', 'relationship (version 2)', strftime('%s','now')*1000),
(3, '관광', 'tourism', strftime('%s','now')*1000),
(3, '관광객', 'tourist', strftime('%s','now')*1000),
(3, '관광지', 'tourist spot', strftime('%s','now')*1000),
(3, '관심', 'interest, concern', strftime('%s','now')*1000),
(3, '광고', 'advertisement', strftime('%s','now')*1000),
(3, '광주', 'Gwangju (city)', strftime('%s','now')*1000),
(3, '교과서', 'textbook', strftime('%s','now')*1000),
(3, '교사03', 'teacher (version 3)', strftime('%s','now')*1000),
(3, '교수', 'professor', strftime('%s','now')*1000),
(3, '교육', 'education', strftime('%s','now')*1000),
(3, '교통비', 'transportation fee', strftime('%s','now')*1000),
(3, '교통사고', 'traffic accident', strftime('%s','now')*1000),
(3, '교환', 'exchange', strftime('%s','now')*1000),
(3, '교회', 'church', strftime('%s','now')*1000),
(3, '구름', 'cloud', strftime('%s','now')*1000),
(3, '국', 'country', strftime('%s','now')*1000),
(3, '국내', 'domestic', strftime('%s','now')*1000),
(3, '국수', 'noodle', strftime('%s','now')*1000),
(3, '국제', 'international', strftime('%s','now')*1000),
(3, '군인', 'soldier', strftime('%s','now')*1000),
(3, '굵다', 'to be thick', strftime('%s','now')*1000),
(3, '굽다01', 'to bake, grill (version 1)', strftime('%s','now')*1000),
(3, '궁금하다', 'to be curious', strftime('%s','now')*1000),
(3, '귀걸이', 'earrings', strftime('%s','now')*1000),
(3, '귀여워하다', 'to find something cute', strftime('%s','now')*1000),
(3, '귀엽다', 'to be cute', strftime('%s','now')*1000),
(3, '귀찮다', 'to be bothersome', strftime('%s','now')*1000),
(3, '규칙', 'rule', strftime('%s','now')*1000),
(3, '그거', 'that thing', strftime('%s','now')*1000),
(3, '그곳', 'that place', strftime('%s','now')*1000),
(3, '그날', 'that day', strftime('%s','now')*1000),
(3, '그냥', 'just, simply', strftime('%s','now')*1000),
(3, '그대로', 'as it is', strftime('%s','now')*1000),
(3, '그동안', 'during that time', strftime('%s','now')*1000),
(3, '그때', 'at that time', strftime('%s','now')*1000),
(3, '그러나01', 'however (version 1)', strftime('%s','now')*1000),
(3, '그러므로', 'therefore', strftime('%s','now')*1000),
(3, '그런01', 'such (version 1)', strftime('%s','now')*1000),
(3, '그립다', 'to miss (someone)', strftime('%s','now')*1000),
(3, '그만02', 'stop (version 2)', strftime('%s','now')*1000),
(3, '그만두다', 'to quit', strftime('%s','now')*1000),
(3, '그분', 'that person (respectful)', strftime('%s','now')*1000),
(3, '그치다', 'to stop (doing something)', strftime('%s','now')*1000),
(3, '글쎄', 'well (expressing hesitation)', strftime('%s','now')*1000),
(3, '글씨', 'writing, handwriting', strftime('%s','now')*1000),
(3, '글자', 'letter, character', strftime('%s','now')*1000),
(3, '금방', 'soon, right away', strftime('%s','now')*1000),
(3, '금지', 'prohibition', strftime('%s','now')*1000),
(3, '급하다', 'to be urgent', strftime('%s','now')*1000),
(3, '기르다', 'to raise (a pet, child)', strftime('%s','now')*1000),
(3, '기름', 'oil', strftime('%s','now')*1000),
(3, '기뻐하다', 'to be glad, happy', strftime('%s','now')*1000),
(3, '기쁨', 'joy, happiness', strftime('%s','now')*1000),
(3, '기억', 'memory', strftime('%s','now')*1000),
(3, '기억나다', 'to remember', strftime('%s','now')*1000),
(3, '기온', 'temperature', strftime('%s','now')*1000),
(3, '기자', 'journalist', strftime('%s','now')*1000),
(3, '기차역', 'train station', strftime('%s','now')*1000),
(3, '기차표', 'train ticket', strftime('%s','now')*1000),
(3, '기침', 'cough', strftime('%s','now')*1000),
(3, '기타02', 'etc (version 2)', strftime('%s','now')*1000),
(3, '기회', 'opportunity', strftime('%s','now')*1000),
(3, '긴장', 'nervousness', strftime('%s','now')*1000),
(3, '길이01', 'length (version 1)', strftime('%s','now')*1000),
(3, '김02', 'Kim (common Korean surname)', strftime('%s','now')*1000),
(3, '깊다', 'to be deep', strftime('%s','now')*1000),
(3, '깊이02', 'depth (version 2)', strftime('%s','now')*1000),
(3, '까만색', 'black color', strftime('%s','now')*1000),
(3, '까맣다', 'to be black', strftime('%s','now')*1000),
(3, '깎다', 'to trim, cut', strftime('%s','now')*1000),
(3, '깜짝02', 'surprise (version 2)', strftime('%s','now')*1000),
(3, '깨끗이', 'cleanly', strftime('%s','now')*1000),
(3, '깨다01', 'to wake up (version 1)', strftime('%s','now')*1000),
(3, '꺼내다', 'to take out', strftime('%s','now')*1000),
(3, '껌', 'gum', strftime('%s','now')*1000),
(3, '꽃다발', 'flower bouquet', strftime('%s','now')*1000),
(3, '꽃병', 'vase', strftime('%s','now')*1000),
(3, '꽃집', 'flower shop', strftime('%s','now')*1000),
(3, '꾸다01', 'to dream (version 1)', strftime('%s','now')*1000),
(3, '꿈', 'dream', strftime('%s','now')*1000),
(3, '끊다', 'to cut off', strftime('%s','now')*1000),
(3, '끓다', 'to boil', strftime('%s','now')*1000),
(3, '끓이다', 'to make boil', strftime('%s','now')*1000),
(3, '끝', 'end', strftime('%s','now')*1000),
(3, '끝내다', 'to finish', strftime('%s','now')*1000),
(3, '끼다03', 'to put on (version 3)', strftime('%s','now')*1000),
(3, '나누다', 'to divide, share', strftime('%s','now')*1000),
(3, '나머지', 'remaining', strftime('%s','now')*1000),
(3, '나이', 'age', strftime('%s','now')*1000),
(3, '나타나다', 'to appear, emerge', strftime('%s','now')*1000),
(3, '나흘', 'four days', strftime('%s','now')*1000),
(3, '낚시', 'fishing', strftime('%s','now')*1000),
(3, '날다', 'to fly', strftime('%s','now')*1000),
(3, '날씬하다', 'to be slim', strftime('%s','now')*1000),
(3, '남01', 'man (version 1)', strftime('%s','now')*1000),
(3, '남기다', 'to leave behind', strftime('%s','now')*1000),
(3, '남녀', 'men and women', strftime('%s','now')*1000),
(3, '남다', 'to remain', strftime('%s','now')*1000),
(3, '남성', 'male', strftime('%s','now')*1000),
(3, '남쪽', 'south', strftime('%s','now')*1000),
(3, '남학생', 'male student', strftime('%s','now')*1000),
(3, '낫다01', 'to get better (version 1)', strftime('%s','now')*1000),
(3, '낫다02', 'to be better (version 2)', strftime('%s','now')*1000),
(3, '낮잠', 'nap', strftime('%s','now')*1000),
(3, '내과', 'internal medicine', strftime('%s','now')*1000),
(3, '내다01', 'to pay, put out (version 1)', strftime('%s','now')*1000),
(3, '내려가다', 'to go down', strftime('%s','now')*1000),
(3, '내려오다', 'to come down', strftime('%s','now')*1000),
(3, '내용', 'content, details', strftime('%s','now')*1000),
(3, '냄비', 'pot', strftime('%s','now')*1000),
(3, '냄새', 'smell', strftime('%s','now')*1000),
(3, '냉장고', 'refrigerator', strftime('%s','now')*1000),
(3, '너희', 'you (plural)', strftime('%s','now')*1000),
(3, '넘다', 'to exceed', strftime('%s','now')*1000),
(3, '넘어지다', 'to fall down', strftime('%s','now')*1000),
(3, '네01', 'yes (version 1)', strftime('%s','now')*1000),
(3, '넥타이', 'tie (necktie)', strftime('%s','now')*1000),
(3, '넷째02∙넷째01/넷째03', 'fourth (version 2/1/3)', strftime('%s','now')*1000),
(3, '노란색', 'yellow color', strftime('%s','now')*1000),
(3, '노랗다', 'to be yellow', strftime('%s','now')*1000),
(3, '노력01', 'effort (version 1)', strftime('%s','now')*1000),
(3, '노인', 'elderly person', strftime('%s','now')*1000),
(3, '노트02', 'notebook (version 2)', strftime('%s','now')*1000),
(3, '녹색', 'green color', strftime('%s','now')*1000),
(3, '녹차', 'green tea', strftime('%s','now')*1000),
(3, '놀라다', 'to be surprised', strftime('%s','now')*1000),
(3, '놀이', 'game, play', strftime('%s','now')*1000),
(3, '농담', 'joke', strftime('%s','now')*1000),
(3, '높이01', 'height (version 1)', strftime('%s','now')*1000),
(3, '높이02', 'height (version 2)', strftime('%s','now')*1000),
(3, '놓다01', 'to put (version 1)', strftime('%s','now')*1000),
(3, '누르다01', 'to press (version 1)', strftime('%s','now')*1000),
(3, '눈물', 'tear', strftime('%s','now')*1000),
(3, '눕다', 'to lie down', strftime('%s','now')*1000),
(3, '느끼다02', 'to feel (version 2)', strftime('%s','now')*1000),
(3, '느낌', 'feeling', strftime('%s','now')*1000),
(3, '느리다', 'to be slow', strftime('%s','now')*1000),
(3, '늘', 'always', strftime('%s','now')*1000),
(3, '늘다', 'to increase, grow', strftime('%s','now')*1000),
(3, '늙다', 'to age', strftime('%s','now')*1000),
(3, '능력', 'ability', strftime('%s','now')*1000),
(3, '다리02', 'leg (version 2)', strftime('%s','now')*1000),
(3, '다섯째02∙다섯째01/다섯째03', 'fifth (version 2/1/3)', strftime('%s','now')*1000),
(3, '다양', 'variety', strftime('%s','now')*1000),
(3, '다음날', 'next day', strftime('%s','now')*1000),
(3, '다이어트', 'diet', strftime('%s','now')*1000),
(3, '다치다01', 'to be hurt (version 1)', strftime('%s','now')*1000),
(3, '다하다', 'to do, finish', strftime('%s','now')*1000),
(3, '닦다', 'to wipe, clean', strftime('%s','now')*1000),
(3, '단순', 'simple', strftime('%s','now')*1000),
(3, '단추', 'button', strftime('%s','now')*1000),
(3, '단풍', 'autumn leaves', strftime('%s','now')*1000),
(3, '달걀', 'egg', strftime('%s','now')*1000),
(3, '달력', 'calendar', strftime('%s','now')*1000),
(3, '달리기', 'running', strftime('%s','now')*1000),
(3, '달리다03', 'to run (version 3)', strftime('%s','now')*1000),
(3, '닭', 'chicken (animal)', strftime('%s','now')*1000),
(3, '닭고기', 'chicken meat', strftime('%s','now')*1000),
(3, '닮다', 'to resemble', strftime('%s','now')*1000),
(3, '답', 'answer', strftime('%s','now')*1000),
(3, '답답하다', 'to feel frustrated', strftime('%s','now')*1000),
(3, '답장', 'reply', strftime('%s','now')*1000),
(3, '대10', 'university (version 10)', strftime('%s','now')*1000),
(3, '대구', 'Daegu (city)', strftime('%s','now')*1000),
(3, '대부분01/대부분02', 'most (version 1/2)', strftime('%s','now')*1000),
(3, '대전01', 'Daejeon (city, version 1)', strftime('%s','now')*1000),
(3, '대학원', 'graduate school', strftime('%s','now')*1000),
(3, '대회', 'competition', strftime('%s','now')*1000),
(3, '댁02/댁01', 'home (respectful version 2/1)', strftime('%s','now')*1000),
(3, '더럽다', 'to be dirty', strftime('%s','now')*1000),
(3, '더욱', 'more', strftime('%s','now')*1000),
(3, '덕분', 'thanks to', strftime('%s','now')*1000),
(3, '던지다', 'to throw', strftime('%s','now')*1000),
(3, '데려가다', 'to take someone (somewhere)', strftime('%s','now')*1000),
(3, '데려오다', 'to bring someone (somewhere)', strftime('%s','now')*1000),
(3, '데이트', 'date (romantic)', strftime('%s','now')*1000),
(3, '도03', 'street, road (version 3)', strftime('%s','now')*1000),
(3, '도로02', 'road (version 2)', strftime('%s','now')*1000),
(3, '도시', 'city', strftime('%s','now')*1000),
(3, '도움', 'help', strftime('%s','now')*1000),
(3, '독서', 'reading (books)', strftime('%s','now')*1000),
(3, '돈가스', 'tonkatsu (breaded pork cutlet)', strftime('%s','now')*1000),
(3, '돌03', 'stone (version 3)', strftime('%s','now')*1000),
(3, '돌다', 'to rotate, turn', strftime('%s','now')*1000),
(3, '돌려주다', 'to return (something)', strftime('%s','now')*1000),
(3, '돌리다02', 'to turn, spin (version 2)', strftime('%s','now')*1000),
(3, '동네', 'neighborhood', strftime('%s','now')*1000),
(3, '동물', 'animal', strftime('%s','now')*1000),
(3, '동물원', 'zoo', strftime('%s','now')*1000),
(3, '동시01', 'poem (version 1)', strftime('%s','now')*1000),
(3, '동전', 'coin', strftime('%s','now')*1000),
(3, '동쪽', 'east', strftime('%s','now')*1000),
(3, '돼지', 'pig', strftime('%s','now')*1000),
(3, '돼지고기', 'pork', strftime('%s','now')*1000),
(3, '-되다', 'to become', strftime('%s','now')*1000),
(3, '된장', 'fermented soybean paste', strftime('%s','now')*1000),
(3, '두껍다', 'to be thick', strftime('%s','now')*1000),
(3, '두다01', 'to place, put (version 1)', strftime('%s','now')*1000),
(3, '두부', 'tofu', strftime('%s','now')*1000),
(3, '두세', 'two or three', strftime('%s','now')*1000),
(3, '두통', 'headache', strftime('%s','now')*1000),
(3, '둘째02∙둘째01/둘째03', 'second (version 2/1/3)', strftime('%s','now')*1000),
(3, '뒤쪽', 'back side', strftime('%s','now')*1000),
(3, '드디어', 'finally', strftime('%s','now')*1000),
(3, '들르다', 'to stop by', strftime('%s','now')*1000),
(3, '들리다02', 'to be heard (version 2)', strftime('%s','now')*1000),
(3, '등01', 'back (of body)', strftime('%s','now')*1000),
(3, '디자인', 'design', strftime('%s','now')*1000),
(3, '따로', 'separately', strftime('%s','now')*1000),
(3, '땀01', 'sweat (version 1)', strftime('%s','now')*1000),
(3, '땅', 'ground, land', strftime('%s','now')*1000),
(3, '떠나다', 'to leave', strftime('%s','now')*1000),
(3, '떠들다01', 'to make noise (version 1)', strftime('%s','now')*1000),
(3, '떡01', 'rice cake (version 1)', strftime('%s','now')*1000),
(3, '떡국', 'rice cake soup', strftime('%s','now')*1000),
(3, '떨어지다', 'to fall', strftime('%s','now')*1000),
(3, '또는', 'or', strftime('%s','now')*1000),
(3, '똑같다', 'to be the same', strftime('%s','now')*1000),
(3, '똑같이', 'exactly the same', strftime('%s','now')*1000),
(3, '똑똑하다', 'to be smart', strftime('%s','now')*1000),
(3, '똑바로', 'straight', strftime('%s','now')*1000),
(3, '뚱뚱하다', 'to be fat', strftime('%s','now')*1000),
(3, '뛰다02', 'to run (version 2)', strftime('%s','now')*1000),
(3, '뛰어가다', 'to run to', strftime('%s','now')*1000),
(3, '뜨겁다', 'to be hot (in temperature)', strftime('%s','now')*1000),
(3, '뜨다05', 'to float (version 5)', strftime('%s','now')*1000),
(3, '뜻', 'meaning', strftime('%s','now')*1000),
(3, '라디오', 'radio', strftime('%s','now')*1000),
(3, '레스토랑', 'restaurant', strftime('%s','now')*1000),
(3, '마당01', 'yard (version 1)', strftime('%s','now')*1000),
(3, '마르다01', 'to be dry (version 1)', strftime('%s','now')*1000),
(3, '마을', 'village', strftime('%s','now')*1000),
(3, '마중', 'meeting (someone)', strftime('%s','now')*1000),
(3, '마지막', 'last', strftime('%s','now')*1000),
(3, '마치다', 'to finish, complete', strftime('%s','now')*1000),
(3, '마트', 'mart', strftime('%s','now')*1000),
(3, '막걸리', 'makgeolli (Korean rice wine)', strftime('%s','now')*1000),
(3, '막히다', 'to be blocked', strftime('%s','now')*1000),
(3, '만두', 'dumpling', strftime('%s','now')*1000),
(3, '만약', 'if', strftime('%s','now')*1000),
(3, '만일', 'if (formal)', strftime('%s','now')*1000),
(3, '만지다', 'to touch', strftime('%s','now')*1000),
(3, '만화', 'comic, cartoon', strftime('%s','now')*1000),
(3, '말04', 'word (version 4)', strftime('%s','now')*1000),
(3, '말06', 'horse (version 6)', strftime('%s','now')*1000),
(3, '맞추다', 'to match, set', strftime('%s','now')*1000),
(3, '매년02/매년01', 'every year (version 2/1)', strftime('%s','now')*1000),
(3, '매다01', 'to tie, fasten (version 1)', strftime('%s','now')*1000),
(3, '매달02/매달01', 'every month (version 2/1)', strftime('%s','now')*1000),
(3, '매우', 'very', strftime('%s','now')*1000),
(3, '매주02/매주01', 'every week (version 2/1)', strftime('%s','now')*1000),
(3, '매표소', 'ticket office', strftime('%s','now')*1000),
(3, '맥주', 'beer', strftime('%s','now')*1000),
(3, '머리카락', 'hair', strftime('%s','now')*1000),
(3, '멀리', 'far', strftime('%s','now')*1000),
(3, '멈추다', 'to stop', strftime('%s','now')*1000),
(3, '멋', 'style', strftime('%s','now')*1000),
(3, '메다', 'to carry (on shoulder)', strftime('%s','now')*1000),
(3, '메모', 'memo', strftime('%s','now')*1000),
(3, '메시지', 'message', strftime('%s','now')*1000),
(3, '메일', 'email', strftime('%s','now')*1000),
(3, '명절', 'holiday', strftime('%s','now')*1000),
(3, '모기', 'mosquito', strftime('%s','now')*1000),
(3, '모든', 'all', strftime('%s','now')*1000),
(3, '모습', 'appearance', strftime('%s','now')*1000),
(3, '모시다', 'to serve, escort', strftime('%s','now')*1000),
(3, '모양01', 'shape (version 1)', strftime('%s','now')*1000),
(3, '모으다', 'to collect', strftime('%s','now')*1000),
(3, '모이다', 'to gather', strftime('%s','now')*1000),
(3, '모임', 'meeting, gathering', strftime('%s','now')*1000);
