PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(8, '사전', 'dictionary / beforehand', strftime('%s','now')*1000),
(8, '사진관', 'photo studio', strftime('%s','now')*1000),
(8, '사촌', 'cousin', strftime('%s','now')*1000),
(8, '사항', 'matter / item / detail', strftime('%s','now')*1000),
(8, '사회', 'society / hosting', strftime('%s','now')*1000),
(8, '사회자', 'MC / host', strftime('%s','now')*1000),
(8, '사회적', 'social', strftime('%s','now')*1000),
(8, '삭제', 'deletion / remove', strftime('%s','now')*1000),
(8, '산꼭대기', 'mountaintop', strftime('%s','now')*1000),
(8, '산업', 'industry', strftime('%s','now')*1000),
(8, '살아나다', 'come back to life / survive', strftime('%s','now')*1000),
(8, '살인', 'murder', strftime('%s','now')*1000),
(8, '살짝', 'lightly / slightly', strftime('%s','now')*1000),
(8, '살찌다', 'gain weight', strftime('%s','now')*1000),
(8, '살펴보다', 'look over / examine', strftime('%s','now')*1000),
(8, '살피다', 'check / inspect', strftime('%s','now')*1000),
(8, '삶', 'life / living', strftime('%s','now')*1000),
(8, '삶다', 'boil / cook', strftime('%s','now')*1000),
(8, '상', 'prize / award / top', strftime('%s','now')*1000),
(8, '상관없다', 'doesn’t matter / irrelevant', strftime('%s','now')*1000),
(8, '상담', 'counseling / consultation', strftime('%s','now')*1000),
(8, '상대방', 'the other party / counterpart', strftime('%s','now')*1000),
(8, '상식', 'common sense', strftime('%s','now')*1000),
(8, '상영', 'screening (film)', strftime('%s','now')*1000),
(8, '상점', 'store / shop', strftime('%s','now')*1000),
(8, '상태', 'state / condition', strftime('%s','now')*1000),
(8, '상하다', 'go bad / be damaged', strftime('%s','now')*1000),
(8, '상황', 'situation / circumstance', strftime('%s','now')*1000),
(8, '새로이', 'anew / afresh', strftime('%s','now')*1000),
(8, '새엄마', 'stepmother', strftime('%s','now')*1000),
(8, '새우', 'shrimp', strftime('%s','now')*1000),
(8, '새집', 'new house', strftime('%s','now')*1000),
(8, '샌들', 'sandals', strftime('%s','now')*1000),
(8, '생년월일', 'date of birth', strftime('%s','now')*1000),
(8, '생머리', 'straight hair', strftime('%s','now')*1000),
(8, '생활비', 'living expenses', strftime('%s','now')*1000),
(8, '생활용품', 'daily necessities', strftime('%s','now')*1000),
(8, '샴푸', 'shampoo', strftime('%s','now')*1000),
(8, '서', 'west / book / stand', strftime('%s','now')*1000),
(8, '서넛', 'three or four', strftime('%s','now')*1000),
(8, '서명', 'signature', strftime('%s','now')*1000),
(8, '서부', 'western region', strftime('%s','now')*1000),
(8, '서투르다', 'clumsy / unskilled', strftime('%s','now')*1000),
(8, '석유', 'oil / petroleum', strftime('%s','now')*1000),
(8, '선', 'line / wire / selection', strftime('%s','now')*1000),
(8, '선글라스', 'sunglasses', strftime('%s','now')*1000),
(8, '선약', 'prior appointment', strftime('%s','now')*1000),
(8, '설', 'Lunar New Year', strftime('%s','now')*1000),
(8, '설명서', 'manual / instruction book', strftime('%s','now')*1000),
(8, '설문', 'survey / questionnaire', strftime('%s','now')*1000),
(8, '설문지', 'survey form', strftime('%s','now')*1000),
(8, '설사', 'diarrhea', strftime('%s','now')*1000),
(8, '성당', 'cathedral / church', strftime('%s','now')*1000),
(8, '성명', 'full name', strftime('%s','now')*1000),
(8, '성별', 'gender', strftime('%s','now')*1000),
(8, '성실', 'sincerity / diligence', strftime('%s','now')*1000),
(8, '성인', 'adult', strftime('%s','now')*1000),
(8, '세기', 'century', strftime('%s','now')*1000),
(8, '세다', 'strong / count', strftime('%s','now')*1000),
(8, '세련되다', 'sophisticated / polished', strftime('%s','now')*1000),
(8, '세로', 'vertical / lengthwise', strftime('%s','now')*1000),
(8, '세월', 'time / years', strftime('%s','now')*1000),
(8, '세일', 'sale / discount', strftime('%s','now')*1000),
(8, '세제', 'detergent', strftime('%s','now')*1000),
(8, '세차', 'car wash', strftime('%s','now')*1000),
(8, '세탁물', 'laundry', strftime('%s','now')*1000),
(8, '세트', 'set', strftime('%s','now')*1000),
(8, '센티', 'centimeter', strftime('%s','now')*1000),
(8, '셔츠', 'shirt', strftime('%s','now')*1000),
(8, '소', 'cow / small / rumor', strftime('%s','now')*1000),
(8, '소감', 'impression / thoughts', strftime('%s','now')*1000),
(8, '소개팅', 'blind date', strftime('%s','now')*1000),
(8, '소극장', 'small theater', strftime('%s','now')*1000),
(8, '소금물', 'salt water', strftime('%s','now')*1000),
(8, '소나기', 'shower / rainstorm', strftime('%s','now')*1000),
(8, '소독', 'disinfection', strftime('%s','now')*1000),
(8, '소독약', 'disinfectant', strftime('%s','now')*1000),
(8, '소매', 'sleeve / retail', strftime('%s','now')*1000),
(8, '소문', 'rumor', strftime('%s','now')*1000),
(8, '소방관', 'firefighter', strftime('%s','now')*1000),
(8, '소방서', 'fire station', strftime('%s','now')*1000),
(8, '소변', 'urine', strftime('%s','now')*1000),
(8, '소설가', 'novelist', strftime('%s','now')*1000),
(8, '소설책', 'novel book', strftime('%s','now')*1000),
(8, '소시지', 'sausage', strftime('%s','now')*1000),
(8, '소아과', 'pediatrics', strftime('%s','now')*1000),
(8, '소요', 'requirement / need', strftime('%s','now')*1000),
(8, '소원', 'wish / desire', strftime('%s','now')*1000),
(8, '소화', 'digestion / extinguish', strftime('%s','now')*1000),
(8, '속담', 'proverb / saying', strftime('%s','now')*1000),
(8, '속상하다', 'upset / distressed', strftime('%s','now')*1000),
(8, '손가방', 'handbag', strftime('%s','now')*1000),
(8, '손등', 'back of the hand', strftime('%s','now')*1000),
(8, '손목', 'wrist', strftime('%s','now')*1000),
(8, '손목시계', 'wristwatch', strftime('%s','now')*1000),
(8, '손발', 'hands and feet', strftime('%s','now')*1000),
(8, '손뼉', 'clap / palm', strftime('%s','now')*1000),
(8, '손자', 'grandson', strftime('%s','now')*1000),
(8, '솜씨', 'skill / ability', strftime('%s','now')*1000),
(8, '송별회', 'farewell party', strftime('%s','now')*1000),
(8, '송이', 'counter for flowers or grapes', strftime('%s','now')*1000),
(8, '쇠고기', 'beef', strftime('%s','now')*1000),
(8, '쇼', 'show', strftime('%s','now')*1000),
(8, '쇼핑몰', 'shopping mall', strftime('%s','now')*1000),
(8, '쇼핑센터', 'shopping center', strftime('%s','now')*1000),
(8, '수', 'number / water / ability', strftime('%s','now')*1000),
(8, '수다', 'chatter / talk', strftime('%s','now')*1000),
(8, '수단', 'means / method', strftime('%s','now')*1000),
(8, '수도', 'capital city / water supply', strftime('%s','now')*1000),
(8, '수량', 'quantity / amount of water', strftime('%s','now')*1000),
(8, '수리', 'repair', strftime('%s','now')*1000),
(8, '수면', 'sleep', strftime('%s','now')*1000),
(8, '수면제', 'sleeping pill', strftime('%s','now')*1000),
(8, '수선', 'mending / alteration', strftime('%s','now')*1000),
(8, '수수료', 'commission / fee', strftime('%s','now')*1000),
(8, '수입', 'income / import', strftime('%s','now')*1000),
(8, '수정', 'correction / revision', strftime('%s','now')*1000),
(8, '수집', 'collection / gathering', strftime('%s','now')*1000),
(8, '수출', 'export', strftime('%s','now')*1000),
(8, '수표', 'bank check', strftime('%s','now')*1000),
(8, '수학', 'mathematics', strftime('%s','now')*1000),
(8, '숙박', 'lodging / accommodation', strftime('%s','now')*1000),
(8, '숙박비', 'lodging fee', strftime('%s','now')*1000),
(8, '숙소', 'accommodation / place to stay', strftime('%s','now')*1000),
(8, '순간', 'moment / instant', strftime('%s','now')*1000),
(8, '술잔', 'drinking glass', strftime('%s','now')*1000),
(8, '숨다', 'hide', strftime('%s','now')*1000),
(8, '숲', 'forest / woods', strftime('%s','now')*1000),
(8, '쉬다', 'rest', strftime('%s','now')*1000),
(8, '쉿', 'shh (be quiet)', strftime('%s','now')*1000),
(8, '슈퍼', 'supermarket', strftime('%s','now')*1000),
(8, '스무째', 'twentieth (ordinal)', strftime('%s','now')*1000),
(8, '스커트', 'skirt', strftime('%s','now')*1000),
(8, '스타일', 'style', strftime('%s','now')*1000),
(8, '스타킹', 'stockings', strftime('%s','now')*1000),
(8, '슬리퍼', 'slippers', strftime('%s','now')*1000),
(8, '습기', 'humidity / dampness', strftime('%s','now')*1000),
(8, '습도', 'humidity level', strftime('%s','now')*1000),
(8, '습하다', 'humid / damp', strftime('%s','now')*1000),
(8, '승객', 'passenger', strftime('%s','now')*1000),
(8, '승무원', 'crew member / flight attendant', strftime('%s','now')*1000),
(8, '승진', 'promotion / advancement', strftime('%s','now')*1000),
(8, '승차', 'boarding', strftime('%s','now')*1000),
(8, '승차권', 'boarding ticket', strftime('%s','now')*1000),
(8, '시', 'city / poetry / time', strftime('%s','now')*1000),
(8, '시각', 'time / viewpoint', strftime('%s','now')*1000),
(8, '시기', 'time period / opportunity', strftime('%s','now')*1000),
(8, '시내버스', 'city bus', strftime('%s','now')*1000),
(8, '시대', 'era / age / period', strftime('%s','now')*1000),
(8, '시디', 'CD / compact disc', strftime('%s','now')*1000),
(8, '시설', 'facility / installation', strftime('%s','now')*1000),
(8, '시아버지', 'father-in-law (husband’s father)', strftime('%s','now')*1000),
(8, '시외', 'suburbs / outside the city', strftime('%s','now')*1000),
(8, '시외버스', 'intercity bus', strftime('%s','now')*1000),
(8, '시장', 'market / mayor', strftime('%s','now')*1000),
(8, '시집', 'married woman’s new home / poetry book', strftime('%s','now')*1000),
(8, '시험지', 'exam paper', strftime('%s','now')*1000),
(8, '식기', 'tableware / dishes', strftime('%s','now')*1000),
(8, '식당가', 'restaurant area / food court', strftime('%s','now')*1000),
(8, '식료품', 'groceries / foodstuffs', strftime('%s','now')*1000),
(8, '식비', 'meal expenses', strftime('%s','now')*1000),
(8, '식사량', 'amount of food intake', strftime('%s','now')*1000),
(8, '식용유', 'cooking oil', strftime('%s','now')*1000),
(8, '식중독', 'food poisoning', strftime('%s','now')*1000),
(8, '식품점', 'food store / grocery store', strftime('%s','now')*1000),
(8, '식후', 'after a meal', strftime('%s','now')*1000),
(8, '식히다', 'cool down / let cool', strftime('%s','now')*1000),
(8, '신경', 'nerve / concern / care', strftime('%s','now')*1000),
(8, '신고', 'report / declaration', strftime('%s','now')*1000),
(8, '신기하다', 'amazing / marvelous', strftime('%s','now')*1000),
(8, '신나다', 'be excited / have fun', strftime('%s','now')*1000),
(8, '신문사', 'newspaper company', strftime('%s','now')*1000),
(8, '신문지', 'newspaper paper', strftime('%s','now')*1000),
(8, '신부', 'bride / Catholic priest', strftime('%s','now')*1000),
(8, '신분', 'social status / identity', strftime('%s','now')*1000),
(8, '신사', 'gentleman', strftime('%s','now')*1000),
(8, '신용', 'credit / trust', strftime('%s','now')*1000),
(8, '신입', 'newcomer / beginner', strftime('%s','now')*1000),
(8, '신입생', 'new student / freshman', strftime('%s','now')*1000),
(8, '신청서', 'application form', strftime('%s','now')*1000),
(8, '신체', 'body / physique', strftime('%s','now')*1000),
(8, '신혼', 'newlywed life', strftime('%s','now')*1000),
(8, '신혼부부', 'newlywed couple', strftime('%s','now')*1000),
(8, '실', 'room / thread / cord', strftime('%s','now')*1000),
(8, '실내', 'indoor / inside', strftime('%s','now')*1000),
(8, '실력', 'ability / skill', strftime('%s','now')*1000),
(8, '실리다', 'be put / be loaded', strftime('%s','now')*1000),
(8, '실망', 'disappointment', strftime('%s','now')*1000),
(8, '실제로', 'in reality / actually', strftime('%s','now')*1000),
(8, '실종', 'disappearance / missing', strftime('%s','now')*1000),
(8, '실컷', 'to one’s heart’s content / fully', strftime('%s','now')*1000),
(8, '싫증', 'boredom / disinterest', strftime('%s','now')*1000),
(8, '심각하다', 'serious / severe', strftime('%s','now')*1000),
(8, '심리', 'psychology / mentality', strftime('%s','now')*1000),
(8, '싱싱하다', 'fresh / lively', strftime('%s','now')*1000),
(8, '싸다', 'cheap / pack', strftime('%s','now')*1000),
(8, '쌍', 'pair / couple / twin', strftime('%s','now')*1000),
(8, '쌍둥이', 'twins', strftime('%s','now')*1000),
(8, '쌓이다', 'pile up / accumulate', strftime('%s','now')*1000),
(8, '썩다', 'rot / spoil', strftime('%s','now')*1000),
(8, '쏟다', 'pour / devote', strftime('%s','now')*1000),
(8, '쏟아지다', 'pour down / fall heavily', strftime('%s','now')*1000),
(8, '쓰기', 'writing / use', strftime('%s','now')*1000),
(8, '쓰이다', 'be used / be written', strftime('%s','now')*1000),
(8, '쓸다', 'sweep / brush', strftime('%s','now')*1000),
(8, '씨', 'seed / Mr.', strftime('%s','now')*1000),
(8, '아가', 'baby', strftime('%s','now')*1000),
(8, '아끼다', 'save / cherish', strftime('%s','now')*1000),
(8, '아래층', 'lower floor', strftime('%s','now')*1000),
(8, '아랫사람', 'junior / subordinate', strftime('%s','now')*1000),
(8, '아랫집', 'downstairs neighbor', strftime('%s','now')*1000),
(8, '아쉽다', 'feel sorry / regretful', strftime('%s','now')*1000),
(8, '아시아', 'Asia', strftime('%s','now')*1000),
(8, '아이', 'child / kid', strftime('%s','now')*1000),
(8, '아이고', 'oh my! / dear me', strftime('%s','now')*1000),
(8, '아이디어', 'idea', strftime('%s','now')*1000),
(8, '아침밥', 'breakfast', strftime('%s','now')*1000),
(8, '아침저녁', 'morning and evening', strftime('%s','now')*1000),
(8, '아프리카', 'Africa', strftime('%s','now')*1000),
(8, '아픔', 'pain / ache', strftime('%s','now')*1000),
(8, '아홉째', 'ninth (ordinal)', strftime('%s','now')*1000),
(8, '악수', 'handshake', strftime('%s','now')*1000),
(8, '안과', 'ophthalmology / eye clinic', strftime('%s','now')*1000),
(8, '안내서', 'guidebook / brochure', strftime('%s','now')*1000),
(8, '안내원', 'guide / attendant', strftime('%s','now')*1000),
(8, '안내판', 'information board / sign', strftime('%s','now')*1000),
(8, '안방', 'main room / master bedroom', strftime('%s','now')*1000),
(8, '안부', 'regards / well-being', strftime('%s','now')*1000),
(8, '안색', 'complexion', strftime('%s','now')*1000),
(8, '안심', 'relief / reassurance', strftime('%s','now')*1000),
(8, '안약', 'eye drops', strftime('%s','now')*1000),
(8, '안전띠', 'seat belt', strftime('%s','now')*1000),
(8, '안정', 'stability / calmness', strftime('%s','now')*1000),
(8, '않다', 'not do', strftime('%s','now')*1000),
(8, '알', 'egg / grain / unit', strftime('%s','now')*1000),
(8, '알레르기', 'allergy', strftime('%s','now')*1000),
(8, '알려지다', 'be known / be informed', strftime('%s','now')*1000),
(8, '알아내다', 'find out / discover', strftime('%s','now')*1000),
(8, '알아듣다', 'understand (spoken)', strftime('%s','now')*1000),
(8, '암', 'cancer', strftime('%s','now')*1000),
(8, '앞날', 'future / days ahead', strftime('%s','now')*1000),
(8, '앞뒤', 'front and back / order', strftime('%s','now')*1000),
(8, '앞머리', 'bangs / front hair', strftime('%s','now')*1000),
(8, '앞집', 'house in front', strftime('%s','now')*1000),
(8, '애기', 'baby / infant (casual)', strftime('%s','now')*1000),
(8, '애완동물', 'pet', strftime('%s','now')*1000),
(8, '액세서리', 'accessory', strftime('%s','now')*1000),
(8, '액자', 'frame', strftime('%s','now')*1000),
(8, '야경', 'night view', strftime('%s','now')*1000),
(8, '야근', 'night shift / overtime', strftime('%s','now')*1000),
(8, '야외', 'outdoors', strftime('%s','now')*1000),
(8, '약도', 'map / sketch map', strftime('%s','now')*1000),
(8, '약품', 'medicine / drug', strftime('%s','now')*1000),
(8, '양', 'amount / sheep', strftime('%s','now')*1000),
(8, '양념', 'seasoning / spice', strftime('%s','now')*1000),
(8, '양력', 'solar calendar', strftime('%s','now')*1000),
(8, '양배추', 'cabbage', strftime('%s','now')*1000),
(8, '양보', 'concession / yield', strftime('%s','now')*1000),
(8, '양산', 'parasol', strftime('%s','now')*1000),
(8, '양식', 'form / western food', strftime('%s','now')*1000),
(8, '양옆', 'both sides', strftime('%s','now')*1000),
(8, '양쪽', 'both sides', strftime('%s','now')*1000),
(8, '양파', 'onion', strftime('%s','now')*1000),
(8, '얘', 'this kid / child', strftime('%s','now')*1000),
(8, '어기다', 'break / violate', strftime('%s','now')*1000),
(8, '어느새', 'before one knows / already', strftime('%s','now')*1000),
(8, '어떡하다', 'what to do / how to act', strftime('%s','now')*1000),
(8, '어려움', 'difficulty / hardship', strftime('%s','now')*1000),
(8, '어머', 'oh my! (surprise)', strftime('%s','now')*1000),
(8, '어저께', 'yesterday', strftime('%s','now')*1000),
(8, '어지럽다', 'dizzy / chaotic', strftime('%s','now')*1000),
(8, '어휘', 'vocabulary', strftime('%s','now')*1000),
(8, '어휴', 'phew / sigh', strftime('%s','now')*1000),
(8, '언덕', 'hill / slope', strftime('%s','now')*1000),
(8, '얼룩', 'stain / spot', strftime('%s','now')*1000),
(8, '얼른', 'quickly / immediately', strftime('%s','now')*1000),
(8, '얼마간', 'for some time / somewhat', strftime('%s','now')*1000),
(8, '업다', 'carry on the back', strftime('%s','now')*1000),
(8, '업무', 'business / duty / task', strftime('%s','now')*1000),
(8, '없애다', 'remove / eliminate', strftime('%s','now')*1000),
(8, '없어지다', 'disappear / vanish', strftime('%s','now')*1000),
(8, '없이', 'without', strftime('%s','now')*1000),
(8, '엊그제', 'a few days ago / recently', strftime('%s','now')*1000),
(8, '에스컬레이터', 'escalator', strftime('%s','now')*1000),
(8, '여가', 'leisure time', strftime('%s','now')*1000),
(8, '여관', 'inn / small hotel', strftime('%s','now')*1000),
(8, '여기다', 'regard / consider', strftime('%s','now')*1000),
(8, '여드름', 'pimple / acne', strftime('%s','now')*1000),
(8, '여름철', 'summer season', strftime('%s','now')*1000),
(8, '여름휴가', 'summer vacation', strftime('%s','now')*1000),
(8, '여보', 'honey / dear (spouse)', strftime('%s','now')*1000),
(8, '여유', 'spare time / composure', strftime('%s','now')*1000),
(8, '여유롭다', 'relaxed / easygoing', strftime('%s','now')*1000),
(8, '여인', 'woman / lady', strftime('%s','now')*1000),
(8, '여쭈다', 'ask (honorific)', strftime('%s','now')*1000),
(8, '역사가', 'historian', strftime('%s','now')*1000),
(8, '역사적', 'historical', strftime('%s','now')*1000),
(8, '역할', 'role / part', strftime('%s','now')*1000),
(8, '연', 'kite / connection / relationship', strftime('%s','now')*1000),
(8, '연고', 'ointment', strftime('%s','now')*1000),
(8, '연구', 'research / study', strftime('%s','now')*1000),
(8, '연기', 'smoke / acting / postponement', strftime('%s','now')*1000),
(8, '연두색', 'light green', strftime('%s','now')*1000),
(8, '연인', 'lover / couple', strftime('%s','now')*1000),
(8, '연장', 'extension / tool', strftime('%s','now')*1000),
(8, '연주', 'performance / play (music)', strftime('%s','now')*1000),
(8, '연주회', 'concert / recital', strftime('%s','now')*1000),
(8, '연하다', 'light / soft / mild', strftime('%s','now')*1000),
(8, '열리다', 'open / be held', strftime('%s','now')*1000),
(8, '열쇠고리', 'key ring', strftime('%s','now')*1000),
(8, '열째', 'tenth (ordinal)', strftime('%s','now')*1000),
(8, '영', 'zero / spirit / young', strftime('%s','now')*1000),
(8, '영리하다', 'clever / intelligent', strftime('%s','now')*1000),
(8, '영상', 'image / video', strftime('%s','now')*1000),
(8, '영양', 'nutrition', strftime('%s','now')*1000),
(8, '영양제', 'nutrient supplement', strftime('%s','now')*1000),
(8, '영웅', 'hero', strftime('%s','now')*1000),
(8, '영원히', 'forever / eternally', strftime('%s','now')*1000),
(8, '영향', 'influence / effect', strftime('%s','now')*1000),
(8, '예', 'example / case / manners', strftime('%s','now')*1000),
(8, '예금', 'deposit / savings', strftime('%s','now')*1000),
(8, '예방', 'prevention', strftime('%s','now')*1000),
(8, '예보', 'forecast / prediction', strftime('%s','now')*1000),
(8, '예상', 'expectation / anticipation', strftime('%s','now')*1000),
(8, '예식장', 'wedding hall', strftime('%s','now')*1000),
(8, '예의', 'manners / courtesy', strftime('%s','now')*1000),
(8, '예절', 'etiquette / decorum', strftime('%s','now')*1000),
(8, '예정', 'schedule / plan', strftime('%s','now')*1000),
(8, '예측', 'prediction / forecast', strftime('%s','now')*1000),
(8, '예컨대', 'for example / for instance', strftime('%s','now')*1000),
(8, '옛날이야기', 'old story / folktale', strftime('%s','now')*1000),
(8, '오', 'five / oh / come', strftime('%s','now')*1000),
(8, '오락실', 'game arcade', strftime('%s','now')*1000),
(8, '오래오래', 'for a long long time', strftime('%s','now')*1000),
(8, '오랜', 'long / of long duration', strftime('%s','now')*1000),
(8, '오른편', 'right side', strftime('%s','now')*1000),
(8, '오리', 'duck', strftime('%s','now')*1000),
(8, '오징어', 'squid', strftime('%s','now')*1000),
(8, '오토바이', 'motorcycle', strftime('%s','now')*1000),
(8, '오페라', 'opera', strftime('%s','now')*1000),
(8, '오피스텔', 'studio apartment / officetel', strftime('%s','now')*1000),
(8, '오해', 'misunderstanding', strftime('%s','now')*1000),
(8, '온', 'all / entire / whole', strftime('%s','now')*1000),
(8, '온몸', 'whole body', strftime('%s','now')*1000),
(8, '온천', 'hot spring', strftime('%s','now')*1000),
(8, '올', 'this year / thread', strftime('%s','now')*1000),
(8, '올라서다', 'step up / rise onto', strftime('%s','now')*1000),
(8, '올려놓다', 'put up / place on', strftime('%s','now')*1000),
(8, '올바르다', 'right / correct / proper', strftime('%s','now')*1000),
(8, '올여름', 'this summer', strftime('%s','now')*1000);