PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(14, '새01', 'bird', strftime('%s','now')*1000),
(14, '새기다', 'to engrave, to inscribe', strftime('%s','now')*1000),
(14, '새끼02', 'young (animal), baby', strftime('%s','now')*1000),
(14, '새다01', 'to leak', strftime('%s','now')*1000),
(14, '새다02', 'to dawn, to become light', strftime('%s','now')*1000),
(14, '새삼', 'anew, afresh', strftime('%s','now')*1000),
(14, '새우다', 'to stay up (all night)', strftime('%s','now')*1000),
(14, '색다르다', 'different, unusual', strftime('%s','now')*1000),
(14, '-생01', 'suffix: student', strftime('%s','now')*1000),
(14, '생겨나다', 'to arise, to come into being', strftime('%s','now')*1000),
(14, '생기', 'vitality, liveliness', strftime('%s','now')*1000),
(14, '생김새', 'appearance, looks', strftime('%s','now')*1000),
(14, '생략', 'omission, ellipsis', strftime('%s','now')*1000),
(14, '생명', 'life', strftime('%s','now')*1000),
(14, '생방송', 'live broadcast', strftime('%s','now')*1000),
(14, '생산', 'production', strftime('%s','now')*1000),
(14, '생생하다', 'vivid, lively', strftime('%s','now')*1000),
(14, '생존', 'survival', strftime('%s','now')*1000),
(14, '서늘하다', 'cool, chilly', strftime('%s','now')*1000),
(14, '서럽다', 'sorrowful, bitterly sad', strftime('%s','now')*1000),
(14, '서서히', 'gradually, slowly', strftime('%s','now')*1000),
(14, '서양인', 'Westerner', strftime('%s','now')*1000),
(14, '서운하다', 'to feel hurt, to feel sad', strftime('%s','now')*1000),
(14, '서적', 'books, publications', strftime('%s','now')*1000),
(14, '서툴다', 'clumsy, unskilled', strftime('%s','now')*1000),
(14, '섞이다', 'to be mixed, to get mixed', strftime('%s','now')*1000),
(14, '선거', 'election', strftime('%s','now')*1000),
(14, '선전01', 'propaganda; publicity', strftime('%s','now')*1000),
(14, '선정02', 'selection, choice', strftime('%s','now')*1000),
(14, '선진', 'advanced', strftime('%s','now')*1000),
(14, '선진국', 'advanced country', strftime('%s','now')*1000),
(14, '선호', 'preference', strftime('%s','now')*1000),
(14, '설득', 'persuasion', strftime('%s','now')*1000),
(14, '설레다', 'to flutter, to be excited', strftime('%s','now')*1000),
(14, '설립', 'establishment, founding', strftime('%s','now')*1000),
(14, '설마', 'hardly; I doubt it', strftime('%s','now')*1000),
(14, '설정', 'setting, configuration', strftime('%s','now')*1000),
(14, '설치', 'installation', strftime('%s','now')*1000),
(14, '섭씨', 'Celsius', strftime('%s','now')*1000),
(14, '-성', 'suffix: -ness; -ity; nature', strftime('%s','now')*1000),
(14, '성공적01∙성공적02', 'successful', strftime('%s','now')*1000),
(14, '성과', 'outcome, result, achievement', strftime('%s','now')*1000),
(14, '성립', 'establishment, formation', strftime('%s','now')*1000),
(14, '성숙', 'maturity', strftime('%s','now')*1000),
(14, '성장', 'growth', strftime('%s','now')*1000),
(14, '성적표', 'report card', strftime('%s','now')*1000),
(14, '성질', 'temper, nature', strftime('%s','now')*1000),
(14, '세계적01∙세계적02', 'global, worldwide', strftime('%s','now')*1000),
(14, '세계화', 'globalization', strftime('%s','now')*1000),
(14, '세금', 'tax', strftime('%s','now')*1000),
(14, '세대01', 'generation', strftime('%s','now')*1000),
(14, '세대02', 'household (housing unit)', strftime('%s','now')*1000),
(14, '세력', 'power, influence', strftime('%s','now')*1000),
(14, '세모', 'triangle, triangular shape', strftime('%s','now')*1000),
(14, '세미나', 'seminar', strftime('%s','now')*1000),
(14, '소규모', 'small-scale', strftime('%s','now')*1000),
(14, '소극적01‧소극적02', 'passive', strftime('%s','now')*1000),
(14, '소나무', 'pine tree', strftime('%s','now')*1000),
(14, '소녀03', 'girl', strftime('%s','now')*1000),
(14, '소년', 'boy', strftime('%s','now')*1000),
(14, '소득', 'income', strftime('%s','now')*1000),
(14, '소리치다', 'to shout, to yell', strftime('%s','now')*1000),
(14, '소문나다', 'to become rumored, to be talked about', strftime('%s','now')*1000),
(14, '소방차', 'fire engine', strftime('%s','now')*1000),
(14, '소비', 'consumption', strftime('%s','now')*1000),
(14, '소비자', 'consumer', strftime('%s','now')*1000),
(14, '소수02', 'minority', strftime('%s','now')*1000),
(14, '소스01', 'sauce', strftime('%s','now')*1000),
(14, '소용', 'use, usefulness', strftime('%s','now')*1000),
(14, '소용없다', 'useless, futile', strftime('%s','now')*1000),
(14, '소유', 'ownership, possession', strftime('%s','now')*1000),
(14, '소음', 'noise', strftime('%s','now')*1000),
(14, '소재02', 'material, subject matter', strftime('%s','now')*1000),
(14, '소중히', 'preciously, with care', strftime('%s','now')*1000),
(14, '소지품', 'belongings, personal effects', strftime('%s','now')*1000),
(14, '소형', 'small-sized, compact', strftime('%s','now')*1000),
(14, '소홀하다', 'to neglect, to be inattentive', strftime('%s','now')*1000),
(14, '속눈썹', 'eyelash', strftime('%s','now')*1000),
(14, '속다', 'to be deceived, to be cheated', strftime('%s','now')*1000),
(14, '속마음', 'inner feelings, true mind', strftime('%s','now')*1000),
(14, '속이다', 'to deceive, to cheat', strftime('%s','now')*1000),
(14, '속하다', 'to belong to, to be affiliated with', strftime('%s','now')*1000),
(14, '손길', 'helping hand, touch', strftime('%s','now')*1000),
(14, '손끝', 'fingertip', strftime('%s','now')*1000),
(14, '손쉽다', 'easy, simple', strftime('%s','now')*1000),
(14, '손잡다', 'to hold hands; to join forces', strftime('%s','now')*1000),
(14, '손잡이', 'handle, knob', strftime('%s','now')*1000),
(14, '손질', 'trimming, grooming, tidying', strftime('%s','now')*1000),
(14, '손톱', 'fingernail', strftime('%s','now')*1000),
(14, '손해', 'loss, damage', strftime('%s','now')*1000),
(14, '솔직하다', 'honest, frank', strftime('%s','now')*1000),
(14, '솔직히', 'frankly, honestly', strftime('%s','now')*1000),
(14, '솟다', 'to rise, to spring up', strftime('%s','now')*1000),
(14, '송아지', 'calf', strftime('%s','now')*1000),
(14, '쇠', 'iron (metal)', strftime('%s','now')*1000),
(14, '수년', 'several years', strftime('%s','now')*1000),
(14, '수도권', 'capital region (metropolitan area)', strftime('%s','now')*1000),
(14, '수도꼭지', 'faucet, tap', strftime('%s','now')*1000),
(14, '수돗물', 'tap water', strftime('%s','now')*1000),
(14, '수동적01∙수동적02', 'passive', strftime('%s','now')*1000),
(14, '수리비', 'repair cost', strftime('%s','now')*1000),
(14, '수만02∙수만01', 'tens of thousands', strftime('%s','now')*1000),
(14, '수많다', 'numerous, a great many', strftime('%s','now')*1000),
(14, '수명', 'lifespan, life expectancy', strftime('%s','now')*1000),
(14, '수백02∙수백01', 'hundreds', strftime('%s','now')*1000),
(14, '수사01', 'investigation (police)', strftime('%s','now')*1000),
(14, '수상03', 'prize, award', strftime('%s','now')*1000),
(14, '수속', 'formalities, procedures', strftime('%s','now')*1000),
(14, '수수께끼', 'riddle', strftime('%s','now')*1000),
(14, '수시로', 'frequently, from time to time', strftime('%s','now')*1000),
(14, '수십02∙수십01', 'dozens', strftime('%s','now')*1000),
(14, '수없이', 'countlessly, without number', strftime('%s','now')*1000),
(14, '수요', 'demand', strftime('%s','now')*1000),
(14, '수용03', 'acceptance, accommodation', strftime('%s','now')*1000),
(14, '수입품', 'imported goods', strftime('%s','now')*1000),
(14, '수준', 'level, standard', strftime('%s','now')*1000),
(14, '수천02∙수천01', 'thousands', strftime('%s','now')*1000),
(14, '수행02', 'performance, execution', strftime('%s','now')*1000),
(14, '숙녀', 'lady', strftime('%s','now')*1000),
(14, '숙이다', 'to bend, to lower (one’s head)', strftime('%s','now')*1000),
(14, '순간적01∙순간적02', 'momentary, instantaneous', strftime('%s','now')*1000),
(14, '순수하다', 'pure, innocent', strftime('%s','now')*1000),
(14, '순식간', 'an instant, a moment', strftime('%s','now')*1000),
(14, '순위', 'ranking, order', strftime('%s','now')*1000),
(14, '순진', 'naivety, innocence', strftime('%s','now')*1000),
(14, '순하다', 'gentle, mild', strftime('%s','now')*1000),
(14, '술병02', 'hangover', strftime('%s','now')*1000),
(14, '술자리', 'drinking party, get-together', strftime('%s','now')*1000),
(14, '숨', 'breath', strftime('%s','now')*1000),
(14, '숨기다', 'to hide, to conceal', strftime('%s','now')*1000),
(14, '숨소리', 'breathing sound', strftime('%s','now')*1000),
(14, '숨지다', 'to die, to pass away', strftime('%s','now')*1000),
(14, '스님', 'Buddhist monk', strftime('%s','now')*1000),
(14, '스위치', 'switch', strftime('%s','now')*1000),
(14, '스치다', 'to graze, to brush past', strftime('%s','now')*1000),
(14, '스케줄', 'schedule', strftime('%s','now')*1000),
(14, '스튜디오', 'studio', strftime('%s','now')*1000),
(14, '슬쩍', 'stealthily; lightly', strftime('%s','now')*1000),
(14, '승낙', 'consent, approval', strftime('%s','now')*1000),
(14, '승리', 'victory', strftime('%s','now')*1000),
(14, '승용차', 'passenger car', strftime('%s','now')*1000),
(14, '승패', 'victory and defeat, outcome', strftime('%s','now')*1000),
(14, '시각02', 'point of view, perspective', strftime('%s','now')*1000),
(14, '시금치', 'spinach', strftime('%s','now')*1000),
(14, '시달리다', 'to suffer from, to be harassed by', strftime('%s','now')*1000),
(14, '시댁', 'husband’s parents’ home', strftime('%s','now')*1000),
(14, '시도', 'attempt, try', strftime('%s','now')*1000),
(14, '시들다', 'to wither, to fade', strftime('%s','now')*1000),
(14, '시력', 'eyesight, vision', strftime('%s','now')*1000),
(14, '시리즈', 'series', strftime('%s','now')*1000),
(14, '시멘트', 'cement', strftime('%s','now')*1000),
(14, '시부모', 'husband’s parents', strftime('%s','now')*1000),
(14, '시선', 'one’s gaze; attention', strftime('%s','now')*1000),
(14, '시스템', 'system', strftime('%s','now')*1000),
(14, '시야', 'field of vision', strftime('%s','now')*1000),
(14, '시인02', 'poet', strftime('%s','now')*1000),
(14, '시일', 'date; time period', strftime('%s','now')*1000),
(14, '시절', 'times, days', strftime('%s','now')*1000),
(14, '시점02', 'point in time', strftime('%s','now')*1000),
(14, '시중02', 'market (circulation)', strftime('%s','now')*1000),
(14, '시집가다', 'to get married (woman)', strftime('%s','now')*1000),
(14, '시청02', 'viewing, watching (TV)', strftime('%s','now')*1000),
(14, '시청률', 'viewership rating', strftime('%s','now')*1000),
(14, '시청자', 'viewer, audience', strftime('%s','now')*1000),
(14, '시합', 'match, contest', strftime('%s','now')*1000),
(14, '시행01', 'enforcement, implementation', strftime('%s','now')*1000),
(14, '식량', 'food supply, provisions', strftime('%s','now')*1000),
(14, '식물', 'plant', strftime('%s','now')*1000),
(14, '식욕', 'appetite', strftime('%s','now')*1000),
(14, '신-', 'new- (prefix)', strftime('%s','now')*1000),
(14, '신01', 'god, deity', strftime('%s','now')*1000),
(14, '신념', 'belief, creed', strftime('%s','now')*1000),
(14, '신맛', 'sour taste', strftime('%s','now')*1000),
(14, '신비', 'mystery, mystique', strftime('%s','now')*1000),
(14, '신상품', 'new product', strftime('%s','now')*1000),
(14, '신세02', 'indebtedness, favor received', strftime('%s','now')*1000),
(14, '신세대', 'new generation', strftime('%s','now')*1000),
(14, '신앙', 'faith, religion', strftime('%s','now')*1000),
(14, '신제품', 'new product', strftime('%s','now')*1000),
(14, '신중', 'prudence, carefulness', strftime('%s','now')*1000),
(14, '신체적01∙신체적02', 'physical', strftime('%s','now')*1000),
(14, '신화', 'myth, mythology', strftime('%s','now')*1000),
(14, '실감', 'realistic feeling, vivid sense', strftime('%s','now')*1000),
(14, '실례02', 'example, instance', strftime('%s','now')*1000),
(14, '실습', 'practical training, practice', strftime('%s','now')*1000),
(14, '실시', 'implementation, execution', strftime('%s','now')*1000),
(14, '실업01', 'unemployment', strftime('%s','now')*1000),
(14, '실용적01∙실용적02', 'practical, pragmatic', strftime('%s','now')*1000),
(14, '실은', 'in fact, actually', strftime('%s','now')*1000),
(14, '실장', 'section chief, head (of a unit)', strftime('%s','now')*1000),
(14, '실제02/실제01', 'reality; in practice', strftime('%s','now')*1000),
(14, '실천', 'practice, putting into action', strftime('%s','now')*1000),
(14, '실체', 'substance, entity', strftime('%s','now')*1000),
(14, '실험', 'experiment', strftime('%s','now')*1000),
(14, '실현', 'realization, materialization', strftime('%s','now')*1000),
(14, '심리적01∙심리적02', 'psychological', strftime('%s','now')*1000),
(14, '심부름', 'errand', strftime('%s','now')*1000),
(14, '심사02', 'screening, examination', strftime('%s','now')*1000),
(14, '심장', 'heart', strftime('%s','now')*1000),
(14, '심정', 'one’s feelings, heart', strftime('%s','now')*1000),
(14, '심지어', 'even', strftime('%s','now')*1000),
(14, '심판', 'judgment; referee', strftime('%s','now')*1000),
(14, '십상01/십상02', 'very likely, apt to', strftime('%s','now')*1000),
(14, '싸구려', 'cheap stuff', strftime('%s','now')*1000),
(14, '싸움', 'fight, quarrel', strftime('%s','now')*1000),
(14, '싸이다', 'to be covered, to be piled up', strftime('%s','now')*1000),
(14, '싼값', 'low price, cheap price', strftime('%s','now')*1000),
(14, '썩', 'entirely; very', strftime('%s','now')*1000),
(14, '썰렁하다', 'chilly; awkward', strftime('%s','now')*1000),
(14, '쏘다', 'to shoot; to sting', strftime('%s','now')*1000),
(14, '쐬다01', 'to be exposed to (air/sun)', strftime('%s','now')*1000),
(14, '쑤시다01', 'to ache; to poke around', strftime('%s','now')*1000),
(14, '쑥스럽다', 'embarrassed, shy', strftime('%s','now')*1000),
(14, '쓰다듬다', 'to stroke, to pat', strftime('%s','now')*1000),
(14, '쓰러지다', 'to collapse, to fall down', strftime('%s','now')*1000),
(14, '쓴맛', 'bitter taste', strftime('%s','now')*1000),
(14, '쓸데없다', 'useless, pointless', strftime('%s','now')*1000),
(14, '쓸데없이', 'needlessly, pointlessly', strftime('%s','now')*1000),
(14, '쓸쓸하다', 'lonely, desolate', strftime('%s','now')*1000),
(14, '씌우다', 'to put on; to cover', strftime('%s','now')*1000),
(14, '씨름', 'Korean wrestling; struggle', strftime('%s','now')*1000),
(14, '씨앗', 'seed', strftime('%s','now')*1000),
(14, '씩씩하다', 'brave, spirited', strftime('%s','now')*1000),
(14, '씻기다01', 'to be washed', strftime('%s','now')*1000),
(14, '씻기다02', 'to wash (someone/something)', strftime('%s','now')*1000),
(14, '아깝다', 'wasteful; regrettable', strftime('%s','now')*1000),
(14, '아동', 'child, children', strftime('%s','now')*1000),
(14, '아드님', 'son (honorific)', strftime('%s','now')*1000),
(14, '아마도', 'probably, perhaps', strftime('%s','now')*1000),
(14, '아무개', 'so-and-so, unnamed person', strftime('%s','now')*1000),
(14, '아무래도01', 'after all; anyhow', strftime('%s','now')*1000),
(14, '아무런01', 'any (kind of) ~ none', strftime('%s','now')*1000),
(14, '아무렇다', 'in any way; anyhow', strftime('%s','now')*1000),
(14, '아무튼', 'anyhow, anyway', strftime('%s','now')*1000),
(14, '아쉬움', 'regret, sense of lack', strftime('%s','now')*1000),
(14, '아예', 'from the start; at all', strftime('%s','now')*1000),
(14, '아울러', 'and also, together', strftime('%s','now')*1000),
(14, '아하', 'aha', strftime('%s','now')*1000),
(14, '악몽', 'nightmare', strftime('%s','now')*1000),
(14, '악취', 'bad smell, stench', strftime('%s','now')*1000),
(14, '악화', 'deterioration, aggravation', strftime('%s','now')*1000),
(14, '안기다01', 'to be held in one’s arms', strftime('%s','now')*1000),
(14, '안기다02', 'to make someone memorize', strftime('%s','now')*1000),
(14, '안내소', 'information desk', strftime('%s','now')*1000),
(14, '안되다02', 'to go wrong; to be pitiful', strftime('%s','now')*1000),
(14, '안주02', 'snacks (with alcohol)', strftime('%s','now')*1000),
(14, '안타까워하다', 'to feel sorry, to pity', strftime('%s','now')*1000),
(14, '안타깝다', 'pitiful, regrettable', strftime('%s','now')*1000),
(14, '안팎', 'inside and outside; about', strftime('%s','now')*1000),
(14, '앉히다', 'to seat, to make sit', strftime('%s','now')*1000),
(14, '알아맞히다', 'to guess correctly', strftime('%s','now')*1000),
(14, '알아주다', 'to acknowledge, to recognize', strftime('%s','now')*1000),
(14, '알차다', 'substantial, rich (in content)', strftime('%s','now')*1000),
(14, '앓다', 'to be ill, to suffer (from)', strftime('%s','now')*1000),
(14, '암기', 'memorization', strftime('%s','now')*1000),
(14, '압력', 'pressure', strftime('%s','now')*1000),
(14, '앞길', 'future path, way ahead', strftime('%s','now')*1000),
(14, '앞두다', 'to have ahead, to be imminent', strftime('%s','now')*1000),
(14, '앞바다', 'offshore sea, coastal waters', strftime('%s','now')*1000),
(14, '앞서', 'beforehand; earlier', strftime('%s','now')*1000),
(14, '앞서다', 'to be ahead, to lead', strftime('%s','now')*1000),
(14, '앞세우다', 'to put forward, to have go first', strftime('%s','now')*1000),
(14, '앞장서다', 'to take the lead', strftime('%s','now')*1000),
(14, '애01', 'child; trouble', strftime('%s','now')*1000),
(14, '애쓰다', 'to make an effort, to strive', strftime('%s','now')*1000),
(14, '애정', 'affection, love', strftime('%s','now')*1000),
(14, '액수', 'amount (of money)', strftime('%s','now')*1000),
(14, '야간', 'nighttime; at night', strftime('%s','now')*1000),
(14, '야단', 'scolding; fuss', strftime('%s','now')*1000),
(14, '야옹', 'meow', strftime('%s','now')*1000),
(14, '야하다', 'sexy; erotic', strftime('%s','now')*1000),
(14, '약점', 'weak point, weakness', strftime('%s','now')*1000),
(14, '약혼', 'engagement (to marry)', strftime('%s','now')*1000),
(14, '약혼녀', 'fiancée', strftime('%s','now')*1000),
(14, '약혼자', 'fiancé/fiancée', strftime('%s','now')*1000),
(14, '얌전', 'meekness, modesty', strftime('%s','now')*1000),
(14, '양국', 'the two countries', strftime('%s','now')*1000),
(14, '양심', 'conscience', strftime('%s','now')*1000),
(14, '얕다', 'shallow', strftime('%s','now')*1000),
(14, '어긋나다', 'to go wrong; to be out of line', strftime('%s','now')*1000),
(14, '어느덧', 'before one knows; already', strftime('%s','now')*1000),
(14, '어둠', 'darkness', strftime('%s','now')*1000),
(14, '어려워하다', 'to find difficult', strftime('%s','now')*1000),
(14, '어르신', 'elder, respected senior', strftime('%s','now')*1000),
(14, '어리석다', 'foolish, silly', strftime('%s','now')*1000),
(14, '어린애', 'little child', strftime('%s','now')*1000),
(14, '어색하다', 'awkward, clumsy', strftime('%s','now')*1000),
(14, '어쨌든01', 'anyway, in any case', strftime('%s','now')*1000),
(14, '어쩌다02', 'by chance, accidentally', strftime('%s','now')*1000),
(14, '어쩌면01', 'perhaps, maybe', strftime('%s','now')*1000),
(14, '어쩐지', 'somehow; for some reason', strftime('%s','now')*1000),
(14, '어찌나', 'so, so much', strftime('%s','now')*1000),
(14, '어찌하다', 'to do somehow; what to do', strftime('%s','now')*1000),
(14, '어차피', 'anyhow; after all', strftime('%s','now')*1000),
(14, '억양', 'intonation, accent', strftime('%s','now')*1000),
(14, '억울하다', 'unfair, feeling wronged', strftime('%s','now')*1000),
(14, '억지로', 'by force, against one’s will', strftime('%s','now')*1000),
(14, '언급', 'mention, reference', strftime('%s','now')*1000),
(14, '언론', 'the press, media', strftime('%s','now')*1000),
(14, '언젠가', 'someday, sometime', strftime('%s','now')*1000),
(14, '얹다', 'to place on, to put on', strftime('%s','now')*1000),
(14, '얻어먹다', 'to be treated (to food)', strftime('%s','now')*1000),
(14, '얼리다', 'to freeze; to be frozen', strftime('%s','now')*1000),
(14, '엄격', 'strictness, rigor', strftime('%s','now')*1000),
(14, '엄숙하다', 'solemn, serious', strftime('%s','now')*1000),
(14, '엄청나다', 'enormous, tremendous', strftime('%s','now')*1000),
(14, '업계', 'industry field', strftime('%s','now')*1000),
(14, '업적', 'achievement, accomplishment', strftime('%s','now')*1000),
(14, '업체', 'business, company', strftime('%s','now')*1000),
(14, '엉뚱하다', 'absurd; unexpected', strftime('%s','now')*1000),
(14, '엉망', 'mess, in disorder', strftime('%s','now')*1000),
(14, '엉터리', 'nonsense; sham', strftime('%s','now')*1000),
(14, '엎드리다', 'to lie face down', strftime('%s','now')*1000),
(14, '에너지', 'energy', strftime('%s','now')*1000),
(14, '여간', 'easily; quite', strftime('%s','now')*1000),
(14, '여건', 'conditions, circumstances', strftime('%s','now')*1000),
(14, '여고', 'girls’ high school', strftime('%s','now')*1000),
(14, '여럿', 'many, several', strftime('%s','now')*1000),
(14, '여부', 'whether or not', strftime('%s','now')*1000),
(14, '여전히', 'still, as ever', strftime('%s','now')*1000),
(14, '여행가', 'traveler', strftime('%s','now')*1000),
(14, '역사상', 'in history, historical', strftime('%s','now')*1000),
(14, '엮다', 'to weave; to compile', strftime('%s','now')*1000),
(14, '연간', 'per year; yearly', strftime('%s','now')*1000),
(14, '연관', 'relation, connection', strftime('%s','now')*1000),
(14, '연구소', 'research institute', strftime('%s','now')*1000),
(14, '연구실', 'laboratory; office (prof.)', strftime('%s','now')*1000),
(14, '연구원01', 'researcher', strftime('%s','now')*1000),
(14, '연구원02', 'research institute staff', strftime('%s','now')*1000),
(14, '연구자', 'researcher', strftime('%s','now')*1000),
(14, '연기02', 'acting; performance', strftime('%s','now')*1000),
(14, '연기자', 'actor/actress', strftime('%s','now')*1000),
(14, '연도01', 'year', strftime('%s','now')*1000),
(14, '연령', 'age', strftime('%s','now')*1000),
(14, '연못', 'pond', strftime('%s','now')*1000),
(14, '연봉', 'annual salary', strftime('%s','now')*1000),
(14, '연설', 'speech, address', strftime('%s','now')*1000),
(14, '연속', 'continuation; consecutive', strftime('%s','now')*1000),
(14, '연애', 'romance, dating', strftime('%s','now')*1000),
(14, '연체', 'overdue; default', strftime('%s','now')*1000),
(14, '연체료', 'late fee', strftime('%s','now')*1000),
(14, '연출', 'direction (film/stage)', strftime('%s','now')*1000),
(14, '연탄', 'coal briquette', strftime('%s','now')*1000),
(14, '연합', 'union, alliance', strftime('%s','now')*1000),
(14, '열기', 'heat; fervor', strftime('%s','now')*1000),
(14, '열매', 'fruit (of a plant)', strftime('%s','now')*1000),
(14, '열정', 'passion', strftime('%s','now')*1000),
(14, '열중', 'absorption, enthusiasm', strftime('%s','now')*1000),
(14, '염색', 'dyeing', strftime('%s','now')*1000),
(14, '엿보다', 'to peek; to wait for chance', strftime('%s','now')*1000),
(14, '영업', 'sales, business', strftime('%s','now')*1000);