PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(2, '가까이01', 'nearly', strftime('%s','now')*1000),
(2, '가까이02', 'nearby', strftime('%s','now')*1000),
(2, '가끔', 'sometimes', strftime('%s','now')*1000),
(2, '가늘다', 'to be thin', strftime('%s','now')*1000),
(2, '가득', 'full', strftime('%s','now')*1000),
(2, '가리키다', 'to point', strftime('%s','now')*1000),
(2, '가슴', 'chest', strftime('%s','now')*1000),
(2, '가위01', 'scissors', strftime('%s','now')*1000),
(2, '가져가다', 'to take', strftime('%s','now')*1000),
(2, '가져오다', 'to bring', strftime('%s','now')*1000),
(2, '각각02', 'each (version 2)', strftime('%s','now')*1000),
(2, '각각01', 'each (version 1)', strftime('%s','now')*1000),
(2, '간단하다', 'to be simple', strftime('%s','now')*1000),
(2, '간단히', 'simply', strftime('%s','now')*1000),
(2, '간식', 'snack', strftime('%s','now')*1000),
(2, '간장01', 'soy sauce (version 1)', strftime('%s','now')*1000),
(2, '간호사', 'nurse', strftime('%s','now')*1000),
(2, '갈색', 'brown', strftime('%s','now')*1000),
(2, '갈아입다', 'to change clothes', strftime('%s','now')*1000),
(2, '감기약', 'cold medicine', strftime('%s','now')*1000),
(2, '감다01', 'to close (eyes version 1)', strftime('%s','now')*1000),
(2, '감다02', 'to close (eyes version 2)', strftime('%s','now')*1000),
(2, '감자01', 'potato (version 1)', strftime('%s','now')*1000),
(2, '갑자기', 'suddenly', strftime('%s','now')*1000),
(2, '강', 'river', strftime('%s','now')*1000),
(2, '강아지', 'puppy', strftime('%s','now')*1000),
(2, '강하다02', 'to be strong (version 2)', strftime('%s','now')*1000),
(2, '갖다01', 'to have (version 1)', strftime('%s','now')*1000),
(2, '갚다', 'to repay', strftime('%s','now')*1000),
(2, '개월', 'month (counter)', strftime('%s','now')*1000),
(2, '거01', 'thing (version 1)', strftime('%s','now')*1000),
(2, '거리01', 'distance (version 1)', strftime('%s','now')*1000),
(2, '거리03', 'distance (version 3)', strftime('%s','now')*1000),
(2, '거울', 'mirror', strftime('%s','now')*1000),
(2, '거의02', 'almost (version 2)', strftime('%s','now')*1000),
(2, '거의01', 'almost (version 1)', strftime('%s','now')*1000),
(2, '거절', 'refusal', strftime('%s','now')*1000),
(2, '거짓말', 'lie', strftime('%s','now')*1000),
(2, '걱정', 'worry', strftime('%s','now')*1000),
(2, '건너가다', 'to cross over', strftime('%s','now')*1000),
(2, '건너다', 'to cross', strftime('%s','now')*1000),
(2, '걸어가다', 'to walk', strftime('%s','now')*1000),
(2, '걸어오다01', 'to walk over (version 1)', strftime('%s','now')*1000),
(2, '걸음', 'step', strftime('%s','now')*1000),
(2, '검사02', 'inspection (version 2)', strftime('%s','now')*1000),
(2, '검은색', 'black color', strftime('%s','now')*1000),
(2, '검정01', 'black (version 1)', strftime('%s','now')*1000),
(2, '겉', 'outside', strftime('%s','now')*1000),
(2, '게으르다', 'to be lazy', strftime('%s','now')*1000),
(2, '결과', 'result', strftime('%s','now')*1000),
(2, '결석', 'absence', strftime('%s','now')*1000),
(2, '결심', 'decision', strftime('%s','now')*1000),
(2, '결정01', 'decision (version 1)', strftime('%s','now')*1000),
(2, '결혼', 'marriage', strftime('%s','now')*1000),
(2, '결혼식', 'wedding', strftime('%s','now')*1000),
(2, '경기02', 'game (version 2)', strftime('%s','now')*1000),
(2, '경찰', 'police', strftime('%s','now')*1000),
(2, '경찰서', 'police station', strftime('%s','now')*1000),
(2, '경치', 'scenery', strftime('%s','now')*1000),
(2, '경험', 'experience', strftime('%s','now')*1000),
(2, '계단', 'stairs', strftime('%s','now')*1000),
(2, '계란', 'egg', strftime('%s','now')*1000),
(2, '계산', 'calculation', strftime('%s','now')*1000),
(2, '고개01', 'head (version 1)', strftime('%s','now')*1000),
(2, '고등학교', 'high school', strftime('%s','now')*1000),
(2, '고등학생', 'high school student', strftime('%s','now')*1000),
(2, '고모', 'aunt (father’s side)', strftime('%s','now')*1000),
(2, '고민', 'worry, concern', strftime('%s','now')*1000),
(2, '고속버스', 'express bus', strftime('%s','now')*1000),
(2, '고장02', 'breakdown (version 2)', strftime('%s','now')*1000),
(2, '고추장', 'gochujang (Korean chili paste)', strftime('%s','now')*1000),
(2, '고치다', 'to fix, repair', strftime('%s','now')*1000),
(2, '곧', 'soon', strftime('%s','now')*1000),
(2, '공01', 'public (version 1)', strftime('%s','now')*1000),
(2, '공무원', 'civil servant', strftime('%s','now')*1000),
(2, '공장', 'factory', strftime('%s','now')*1000),
(2, '공짜', 'free, no charge', strftime('%s','now')*1000),
(2, '공휴일', 'public holiday', strftime('%s','now')*1000),
(2, '과거02', 'past (version 2)', strftime('%s','now')*1000),
(2, '과자', 'snack, biscuit', strftime('%s','now')*1000),
(2, '관계02', 'relationship (version 2)', strftime('%s','now')*1000),
(2, '관광', 'tourism', strftime('%s','now')*1000),
(2, '관광객', 'tourist', strftime('%s','now')*1000),
(2, '관광지', 'tourist spot', strftime('%s','now')*1000),
(2, '관심', 'interest, concern', strftime('%s','now')*1000),
(2, '광고', 'advertisement', strftime('%s','now')*1000),
(2, '광주', 'Gwangju (city)', strftime('%s','now')*1000),
(2, '교과서', 'textbook', strftime('%s','now')*1000),
(2, '교사03', 'teacher (version 3)', strftime('%s','now')*1000),
(2, '교수', 'professor', strftime('%s','now')*1000),
(2, '교육', 'education', strftime('%s','now')*1000),
(2, '교통비', 'transportation fee', strftime('%s','now')*1000),
(2, '교통사고', 'traffic accident', strftime('%s','now')*1000),
(2, '교환', 'exchange', strftime('%s','now')*1000),
(2, '교회', 'church', strftime('%s','now')*1000),
(2, '구름', 'cloud', strftime('%s','now')*1000),
(2, '국', 'country', strftime('%s','now')*1000),
(2, '국내', 'domestic', strftime('%s','now')*1000),
(2, '국수', 'noodle', strftime('%s','now')*1000),
(2, '국제', 'international', strftime('%s','now')*1000),
(2, '군인', 'soldier', strftime('%s','now')*1000),
(2, '굵다', 'to be thick', strftime('%s','now')*1000),
(2, '굽다01', 'to bake, grill (version 1)', strftime('%s','now')*1000),
(2, '궁금하다', 'to be curious', strftime('%s','now')*1000),
(2, '귀걸이', 'earrings', strftime('%s','now')*1000),
(2, '귀여워하다', 'to find something cute', strftime('%s','now')*1000),
(2, '귀엽다', 'to be cute', strftime('%s','now')*1000),
(2, '귀찮다', 'to be bothersome', strftime('%s','now')*1000),
(2, '규칙', 'rule', strftime('%s','now')*1000),
(2, '그거', 'that thing', strftime('%s','now')*1000),
(2, '그곳', 'that place', strftime('%s','now')*1000),
(2, '그날', 'that day', strftime('%s','now')*1000),
(2, '그냥', 'just, simply', strftime('%s','now')*1000),
(2, '그대로', 'as it is', strftime('%s','now')*1000),
(2, '그동안', 'during that time', strftime('%s','now')*1000),
(2, '그때', 'at that time', strftime('%s','now')*1000),
(2, '그러나01', 'however (version 1)', strftime('%s','now')*1000),
(2, '그러므로', 'therefore', strftime('%s','now')*1000),
(2, '그런01', 'such (version 1)', strftime('%s','now')*1000),
(2, '그립다', 'to miss (someone)', strftime('%s','now')*1000),
(2, '그만02', 'stop (version 2)', strftime('%s','now')*1000),
(2, '그만두다', 'to quit', strftime('%s','now')*1000),
(2, '그분', 'that person (respectful)', strftime('%s','now')*1000),
(2, '그치다', 'to stop (doing something)', strftime('%s','now')*1000),
(2, '글쎄', 'well (expressing hesitation)', strftime('%s','now')*1000),
(2, '글씨', 'writing, handwriting', strftime('%s','now')*1000),
(2, '글자', 'letter, character', strftime('%s','now')*1000),
(2, '금방', 'soon, right away', strftime('%s','now')*1000),
(2, '금지', 'prohibition', strftime('%s','now')*1000),
(2, '급하다', 'to be urgent', strftime('%s','now')*1000),
(2, '기르다', 'to raise (a pet, child)', strftime('%s','now')*1000),
(2, '기름', 'oil', strftime('%s','now')*1000),
(2, '기뻐하다', 'to be glad, happy', strftime('%s','now')*1000),
(2, '기쁨', 'joy, happiness', strftime('%s','now')*1000),
(2, '기억', 'memory', strftime('%s','now')*1000),
(2, '기억나다', 'to remember', strftime('%s','now')*1000),
(2, '기온', 'temperature', strftime('%s','now')*1000),
(2, '기자', 'journalist', strftime('%s','now')*1000),
(2, '기차역', 'train station', strftime('%s','now')*1000),
(2, '기차표', 'train ticket', strftime('%s','now')*1000),
(2, '기침', 'cough', strftime('%s','now')*1000),
(2, '기타02', 'etc (version 2)', strftime('%s','now')*1000),
(2, '기회', 'opportunity', strftime('%s','now')*1000),
(2, '긴장', 'nervousness', strftime('%s','now')*1000),
(2, '길이01', 'length (version 1)', strftime('%s','now')*1000),
(2, '김02', 'Kim (common Korean surname)', strftime('%s','now')*1000),
(2, '깊다', 'to be deep', strftime('%s','now')*1000),
(2, '깊이02', 'depth (version 2)', strftime('%s','now')*1000),
(2, '까만색', 'black color', strftime('%s','now')*1000),
(2, '까맣다', 'to be black', strftime('%s','now')*1000),
(2, '깎다', 'to trim, cut', strftime('%s','now')*1000),
(2, '깜짝02', 'surprise (version 2)', strftime('%s','now')*1000),
(2, '깨끗이', 'cleanly', strftime('%s','now')*1000),
(2, '깨다01', 'to wake up (version 1)', strftime('%s','now')*1000),
(2, '꺼내다', 'to take out', strftime('%s','now')*1000),
(2, '껌', 'gum', strftime('%s','now')*1000),
(2, '꽃다발', 'flower bouquet', strftime('%s','now')*1000),
(2, '꽃병', 'vase', strftime('%s','now')*1000),
(2, '꽃집', 'flower shop', strftime('%s','now')*1000),
(2, '꾸다01', 'to dream (version 1)', strftime('%s','now')*1000),
(2, '꿈', 'dream', strftime('%s','now')*1000),
(2, '끊다', 'to cut off', strftime('%s','now')*1000),
(2, '끓다', 'to boil', strftime('%s','now')*1000),
(2, '끓이다', 'to make boil', strftime('%s','now')*1000),
(2, '끝', 'end', strftime('%s','now')*1000),
(2, '끝내다', 'to finish', strftime('%s','now')*1000),
(2, '끼다03', 'to put on (version 3)', strftime('%s','now')*1000),
(2, '나누다', 'to divide, share', strftime('%s','now')*1000),
(2, '나머지', 'remaining', strftime('%s','now')*1000),
(2, '나이', 'age', strftime('%s','now')*1000),
(2, '나타나다', 'to appear, emerge', strftime('%s','now')*1000),
(2, '나흘', 'four days', strftime('%s','now')*1000),
(2, '낚시', 'fishing', strftime('%s','now')*1000),
(2, '날다', 'to fly', strftime('%s','now')*1000),
(2, '날씬하다', 'to be slim', strftime('%s','now')*1000),
(2, '남01', 'man (version 1)', strftime('%s','now')*1000),
(2, '남기다', 'to leave behind', strftime('%s','now')*1000),
(2, '남녀', 'men and women', strftime('%s','now')*1000),
(2, '남다', 'to remain', strftime('%s','now')*1000),
(2, '남성', 'male', strftime('%s','now')*1000),
(2, '남쪽', 'south', strftime('%s','now')*1000),
(2, '남학생', 'male student', strftime('%s','now')*1000),
(2, '낫다01', 'to get better (version 1)', strftime('%s','now')*1000),
(2, '낫다02', 'to be better (version 2)', strftime('%s','now')*1000),
(2, '낮잠', 'nap', strftime('%s','now')*1000),
(2, '내과', 'internal medicine', strftime('%s','now')*1000),
(2, '내다01', 'to pay, put out (version 1)', strftime('%s','now')*1000),
(2, '내려가다', 'to go down', strftime('%s','now')*1000),
(2, '내려오다', 'to come down', strftime('%s','now')*1000),
(2, '내용', 'content, details', strftime('%s','now')*1000),
(2, '냄비', 'pot', strftime('%s','now')*1000),
(2, '냄새', 'smell', strftime('%s','now')*1000),
(2, '냉장고', 'refrigerator', strftime('%s','now')*1000),
(2, '너희', 'you (plural)', strftime('%s','now')*1000),
(2, '넘다', 'to exceed', strftime('%s','now')*1000),
(2, '넘어지다', 'to fall down', strftime('%s','now')*1000),
(2, '네01', 'yes (version 1)', strftime('%s','now')*1000),
(2, '넥타이', 'tie (necktie)', strftime('%s','now')*1000),
(2, '넷째02∙넷째01/넷째03', 'fourth (version 2/1/3)', strftime('%s','now')*1000),
(2, '노란색', 'yellow color', strftime('%s','now')*1000),
(2, '노랗다', 'to be yellow', strftime('%s','now')*1000),
(2, '노력01', 'effort (version 1)', strftime('%s','now')*1000),
(2, '노인', 'elderly person', strftime('%s','now')*1000),
(2, '노트02', 'notebook (version 2)', strftime('%s','now')*1000),
(2, '녹색', 'green color', strftime('%s','now')*1000),
(2, '녹차', 'green tea', strftime('%s','now')*1000),
(2, '놀라다', 'to be surprised', strftime('%s','now')*1000),
(2, '놀이', 'game, play', strftime('%s','now')*1000),
(2, '농담', 'joke', strftime('%s','now')*1000),
(2, '높이01', 'height (version 1)', strftime('%s','now')*1000),
(2, '높이02', 'height (version 2)', strftime('%s','now')*1000),
(2, '놓다01', 'to put (version 1)', strftime('%s','now')*1000),
(2, '누르다01', 'to press (version 1)', strftime('%s','now')*1000),
(2, '눈물', 'tear', strftime('%s','now')*1000),
(2, '눕다', 'to lie down', strftime('%s','now')*1000),
(2, '느끼다02', 'to feel (version 2)', strftime('%s','now')*1000),
(2, '느낌', 'feeling', strftime('%s','now')*1000),
(2, '느리다', 'to be slow', strftime('%s','now')*1000),
(2, '늘', 'always', strftime('%s','now')*1000),
(2, '늘다', 'to increase, grow', strftime('%s','now')*1000),
(2, '늙다', 'to age', strftime('%s','now')*1000),
(2, '능력', 'ability', strftime('%s','now')*1000),
(2, '다리02', 'leg (version 2)', strftime('%s','now')*1000),
(2, '다섯째02∙다섯째01/다섯째03', 'fifth (version 2/1/3)', strftime('%s','now')*1000),
(2, '다양', 'variety', strftime('%s','now')*1000),
(2, '다음날', 'next day', strftime('%s','now')*1000),
(2, '다이어트', 'diet', strftime('%s','now')*1000),
(2, '다치다01', 'to be hurt (version 1)', strftime('%s','now')*1000),
(2, '다하다', 'to do, finish', strftime('%s','now')*1000),
(2, '닦다', 'to wipe, clean', strftime('%s','now')*1000),
(2, '단순', 'simple', strftime('%s','now')*1000),
(2, '단추', 'button', strftime('%s','now')*1000),
(2, '단풍', 'autumn leaves', strftime('%s','now')*1000),
(2, '달걀', 'egg', strftime('%s','now')*1000),
(2, '달력', 'calendar', strftime('%s','now')*1000),
(2, '달리기', 'running', strftime('%s','now')*1000),
(2, '달리다03', 'to run (version 3)', strftime('%s','now')*1000),
(2, '닭', 'chicken (animal)', strftime('%s','now')*1000),
(2, '닭고기', 'chicken meat', strftime('%s','now')*1000),
(2, '닮다', 'to resemble', strftime('%s','now')*1000),
(2, '답', 'answer', strftime('%s','now')*1000),
(2, '답답하다', 'to feel frustrated', strftime('%s','now')*1000),
(2, '답장', 'reply', strftime('%s','now')*1000),
(2, '대10', 'university (version 10)', strftime('%s','now')*1000),
(2, '대구', 'Daegu (city)', strftime('%s','now')*1000),
(2, '대부분01/대부분02', 'most (version 1/2)', strftime('%s','now')*1000),
(2, '대전01', 'Daejeon (city, version 1)', strftime('%s','now')*1000),
(2, '대학원', 'graduate school', strftime('%s','now')*1000),
(2, '대회', 'competition', strftime('%s','now')*1000),
(2, '댁02/댁01', 'home (respectful version 2/1)', strftime('%s','now')*1000),
(2, '더럽다', 'to be dirty', strftime('%s','now')*1000),
(2, '더욱', 'more', strftime('%s','now')*1000),
(2, '덕분', 'thanks to', strftime('%s','now')*1000),
(2, '던지다', 'to throw', strftime('%s','now')*1000),
(2, '데려가다', 'to take someone (somewhere)', strftime('%s','now')*1000),
(2, '데려오다', 'to bring someone (somewhere)', strftime('%s','now')*1000),
(2, '데이트', 'date (romantic)', strftime('%s','now')*1000),
(2, '도03', 'street, road (version 3)', strftime('%s','now')*1000),
(2, '도로02', 'road (version 2)', strftime('%s','now')*1000),
(2, '도시', 'city', strftime('%s','now')*1000),
(2, '도움', 'help', strftime('%s','now')*1000),
(2, '독서', 'reading (books)', strftime('%s','now')*1000),
(2, '돈가스', 'tonkatsu (breaded pork cutlet)', strftime('%s','now')*1000),
(2, '돌03', 'stone (version 3)', strftime('%s','now')*1000),
(2, '돌다', 'to rotate, turn', strftime('%s','now')*1000),
(2, '돌려주다', 'to return (something)', strftime('%s','now')*1000),
(2, '돌리다02', 'to turn, spin (version 2)', strftime('%s','now')*1000),
(2, '동네', 'neighborhood', strftime('%s','now')*1000),
(2, '동물', 'animal', strftime('%s','now')*1000),
(2, '동물원', 'zoo', strftime('%s','now')*1000),
(2, '동시01', 'poem (version 1)', strftime('%s','now')*1000),
(2, '동전', 'coin', strftime('%s','now')*1000),
(2, '동쪽', 'east', strftime('%s','now')*1000),
(2, '돼지', 'pig', strftime('%s','now')*1000),
(2, '돼지고기', 'pork', strftime('%s','now')*1000),
(2, '-되다', 'to become', strftime('%s','now')*1000),
(2, '된장', 'fermented soybean paste', strftime('%s','now')*1000),
(2, '두껍다', 'to be thick', strftime('%s','now')*1000),
(2, '두다01', 'to place, put (version 1)', strftime('%s','now')*1000),
(2, '두부', 'tofu', strftime('%s','now')*1000),
(2, '두세', 'two or three', strftime('%s','now')*1000),
(2, '두통', 'headache', strftime('%s','now')*1000),
(2, '둘째02∙둘째01/둘째03', 'second (version 2/1/3)', strftime('%s','now')*1000),
(2, '뒤쪽', 'back side', strftime('%s','now')*1000),
(2, '드디어', 'finally', strftime('%s','now')*1000),
(2, '들르다', 'to stop by', strftime('%s','now')*1000),
(2, '들리다02', 'to be heard (version 2)', strftime('%s','now')*1000),
(2, '등01', 'back (of body)', strftime('%s','now')*1000),
(2, '디자인', 'design', strftime('%s','now')*1000),
(2, '따로', 'separately', strftime('%s','now')*1000),
(2, '땀01', 'sweat (version 1)', strftime('%s','now')*1000),
(2, '땅', 'ground, land', strftime('%s','now')*1000),
(2, '떠나다', 'to leave', strftime('%s','now')*1000),
(2, '떠들다01', 'to make noise (version 1)', strftime('%s','now')*1000),
(2, '떡01', 'rice cake (version 1)', strftime('%s','now')*1000),
(2, '떡국', 'rice cake soup', strftime('%s','now')*1000),
(2, '떨어지다', 'to fall', strftime('%s','now')*1000),
(2, '또는', 'or', strftime('%s','now')*1000),
(2, '똑같다', 'to be the same', strftime('%s','now')*1000),
(2, '똑같이', 'exactly the same', strftime('%s','now')*1000),
(2, '똑똑하다', 'to be smart', strftime('%s','now')*1000),
(2, '똑바로', 'straight', strftime('%s','now')*1000),
(2, '뚱뚱하다', 'to be fat', strftime('%s','now')*1000),
(2, '뛰다02', 'to run (version 2)', strftime('%s','now')*1000),
(2, '뛰어가다', 'to run to', strftime('%s','now')*1000),
(2, '뜨겁다', 'to be hot (in temperature)', strftime('%s','now')*1000),
(2, '뜨다05', 'to float (version 5)', strftime('%s','now')*1000),
(2, '뜻', 'meaning', strftime('%s','now')*1000),
(2, '라디오', 'radio', strftime('%s','now')*1000),
(2, '레스토랑', 'restaurant', strftime('%s','now')*1000),
(2, '마당01', 'yard (version 1)', strftime('%s','now')*1000),
(2, '마르다01', 'to be dry (version 1)', strftime('%s','now')*1000),
(2, '마을', 'village', strftime('%s','now')*1000),
(2, '마중', 'meeting (someone)', strftime('%s','now')*1000),
(2, '마지막', 'last', strftime('%s','now')*1000),
(2, '마치다', 'to finish, complete', strftime('%s','now')*1000),
(2, '마트', 'mart', strftime('%s','now')*1000),
(2, '막걸리', 'makgeolli (Korean rice wine)', strftime('%s','now')*1000),
(2, '막히다', 'to be blocked', strftime('%s','now')*1000),
(2, '만두', 'dumpling', strftime('%s','now')*1000),
(2, '만약', 'if', strftime('%s','now')*1000),
(2, '만일', 'if (formal)', strftime('%s','now')*1000),
(2, '만지다', 'to touch', strftime('%s','now')*1000),
(2, '만화', 'comic, cartoon', strftime('%s','now')*1000),
(2, '말04', 'word (version 4)', strftime('%s','now')*1000),
(2, '말06', 'horse (version 6)', strftime('%s','now')*1000),
(2, '맞추다', 'to match, set', strftime('%s','now')*1000),
(2, '매년02/매년01', 'every year (version 2/1)', strftime('%s','now')*1000),
(2, '매다01', 'to tie, fasten (version 1)', strftime('%s','now')*1000),
(2, '매달02/매달01', 'every month (version 2/1)', strftime('%s','now')*1000),
(2, '매우', 'very', strftime('%s','now')*1000),
(2, '매주02/매주01', 'every week (version 2/1)', strftime('%s','now')*1000),
(2, '매표소', 'ticket office', strftime('%s','now')*1000),
(2, '맥주', 'beer', strftime('%s','now')*1000),
(2, '머리카락', 'hair', strftime('%s','now')*1000),
(2, '멀리', 'far', strftime('%s','now')*1000),
(2, '멈추다', 'to stop', strftime('%s','now')*1000),
(2, '멋', 'style', strftime('%s','now')*1000),
(2, '메다', 'to carry (on shoulder)', strftime('%s','now')*1000),
(2, '메모', 'memo', strftime('%s','now')*1000),
(2, '메시지', 'message', strftime('%s','now')*1000),
(2, '메일', 'email', strftime('%s','now')*1000),
(2, '명절', 'holiday', strftime('%s','now')*1000),
(2, '모기', 'mosquito', strftime('%s','now')*1000),
(2, '모든', 'all', strftime('%s','now')*1000),
(2, '모습', 'appearance', strftime('%s','now')*1000),
(2, '모시다', 'to serve, escort', strftime('%s','now')*1000),
(2, '모양01', 'shape (version 1)', strftime('%s','now')*1000),
(2, '모으다', 'to collect', strftime('%s','now')*1000),
(2, '모이다', 'to gather', strftime('%s','now')*1000),
(2, '모임', 'meeting, gathering', strftime('%s','now')*1000),
(2, '모자라다', 'to be short of', strftime('%s','now')*1000),
(2, '목걸이', 'necklace', strftime('%s','now')*1000),
(2, '목도리', 'scarf', strftime('%s','now')*1000),
(2, '목소리', 'voice', strftime('%s','now')*1000),
(2, '목욕', 'bath', strftime('%s','now')*1000),
(2, '목적', 'purpose', strftime('%s','now')*1000),
(2, '못생기다', 'to be ugly', strftime('%s','now')*1000),
(2, '무01', 'no, not (version 1)', strftime('%s','now')*1000),
(2, '무게', 'weight', strftime('%s','now')*1000),
(2, '무궁화', 'rose of Sharon', strftime('%s','now')*1000),
(2, '무료01', 'free (of charge, version 1)', strftime('%s','now')*1000),
(2, '무릎', 'knee', strftime('%s','now')*1000),
(2, '무섭다', 'to be scary', strftime('%s','now')*1000),
(2, '무척', 'very', strftime('%s','now')*1000),
(2, '문제', 'problem', strftime('%s','now')*1000),
(2, '물고기', 'fish', strftime('%s','now')*1000),
(2, '물론02/물론01', 'of course (version 2/1)', strftime('%s','now')*1000),
(2, '물어보다', 'to ask', strftime('%s','now')*1000),
(2, '미끄러지다', 'to slip', strftime('%s','now')*1000),
(2, '미래', 'future', strftime('%s','now')*1000),
(2, '미리', 'in advance', strftime('%s','now')*1000),
(2, '미술관', 'art gallery', strftime('%s','now')*1000),
(2, '미역국', 'seaweed soup', strftime('%s','now')*1000),
(2, '미터', 'meter', strftime('%s','now')*1000),
(2, '믿다', 'to believe', strftime('%s','now')*1000),
(2, '밀가루', 'flour', strftime('%s','now')*1000),
(2, '밀다', 'to push', strftime('%s','now')*1000),
(2, '바깥', 'outside', strftime('%s','now')*1000),
(2, '바깥쪽', 'outer side', strftime('%s','now')*1000),
(2, '바뀌다', 'to be changed', strftime('%s','now')*1000),
(2, '바닥', 'floor', strftime('%s','now')*1000),
(2, '바닷가', 'beach', strftime('%s','now')*1000),
(2, '바라다', 'to wish, hope', strftime('%s','now')*1000),
(2, '바라보다', 'to look at, gaze at', strftime('%s','now')*1000),
(2, '바르다01', 'to apply, to be correct (version 1)', strftime('%s','now')*1000),
(2, '바이올린', 'violin', strftime('%s','now')*1000),
(2, '박수', 'applause', strftime('%s','now')*1000),
(2, '반대', 'opposite, opposition', strftime('%s','now')*1000),
(2, '반드시', 'certainly, surely', strftime('%s','now')*1000),
(2, '반바지', 'shorts', strftime('%s','now')*1000),
(2, '반지', 'ring', strftime('%s','now')*1000),
(2, '반찬', 'side dish', strftime('%s','now')*1000),
(2, '받아쓰다', 'to take dictation', strftime('%s','now')*1000),
(2, '발가락', 'toe', strftime('%s','now')*1000),
(2, '발바닥', 'sole of foot', strftime('%s','now')*1000),
(2, '밝다02/밝다01', 'to be bright (version 2/1)', strftime('%s','now')*1000),
(2, '방금02/방금01', 'just now (version 2/1)', strftime('%s','now')*1000),
(2, '방문02', 'visit (version 2)', strftime('%s','now')*1000),
(2, '방문03', 'door (version 3)', strftime('%s','now')*1000),
(2, '방법', 'method, way', strftime('%s','now')*1000),
(2, '방송01', 'broadcast (version 1)', strftime('%s','now')*1000),
(2, '방송국', 'broadcasting station', strftime('%s','now')*1000),
(2, '방향', 'direction', strftime('%s','now')*1000),
(2, '배05', 'back (of body, version 5)', strftime('%s','now')*1000),
(2, '배달02', 'delivery (version 2)', strftime('%s','now')*1000),
(2, '배드민턴', 'badminton', strftime('%s','now')*1000),
(2, '배추', 'Chinese cabbage', strftime('%s','now')*1000),
(2, '배탈', 'stomach trouble', strftime('%s','now')*1000),
(2, '뱀', 'snake', strftime('%s','now')*1000),
(2, '버릇', 'habit', strftime('%s','now')*1000),
(2, '버리다01', 'to throw away (version 1)', strftime('%s','now')*1000),
(2, '번째', 'th (ordinal number)', strftime('%s','now')*1000),
(2, '벌02', 'bee (version 2)', strftime('%s','now')*1000),
(2, '벌다02', 'to earn (version 2)', strftime('%s','now')*1000),
(2, '벌써', 'already', strftime('%s','now')*1000),
(2, '벗다', 'to take off (clothes)', strftime('%s','now')*1000),
(2, '벽', 'wall', strftime('%s','now')*1000),
(2, '변하다', 'to change', strftime('%s','now')*1000),
(2, '변호사', 'lawyer', strftime('%s','now')*1000),
(2, '별01', 'star (version 1)', strftime('%s','now')*1000),
(2, '병문안', 'hospital visit', strftime('%s','now')*1000),
(2, '보라색', 'purple', strftime('%s','now')*1000),
(2, '보이다01', 'to be seen (version 1)', strftime('%s','now')*1000),
(2, '보이다02', 'to be seen (version 2)', strftime('%s','now')*1000),
(2, '복습', 'review', strftime('%s','now')*1000),
(2, '복잡하다', 'to be complicated', strftime('%s','now')*1000),
(2, '볶다', 'to stir-fry', strftime('%s','now')*1000),
(2, '볶음밥', 'fried rice', strftime('%s','now')*1000),
(2, '봉투', 'envelope, bag', strftime('%s','now')*1000),
(2, '뵙다', 'to meet (humble)', strftime('%s','now')*1000),
(2, '부끄럽다', 'to be shy', strftime('%s','now')*1000),
(2, '부드럽다', 'to be soft', strftime('%s','now')*1000),
(2, '부럽다', 'to be jealous', strftime('%s','now')*1000),
(2, '부르다02', 'to call (version 2)', strftime('%s','now')*1000),
(2, '부부', 'couple', strftime('%s','now')*1000),
(2, '부분', 'part', strftime('%s','now')*1000),
(2, '부인01', 'wife (version 1)', strftime('%s','now')*1000),
(2, '부자02', 'rich person (version 2)', strftime('%s','now')*1000),
(2, '부장', 'department head', strftime('%s','now')*1000),
(2, '부족01', 'shortage (version 1)', strftime('%s','now')*1000),
(2, '부지런하다', 'to be diligent', strftime('%s','now')*1000),
(2, '부치다02', 'to mail (version 2)', strftime('%s','now')*1000),
(2, '북쪽', 'north', strftime('%s','now')*1000),
(2, '분명하다', 'to be clear', strftime('%s','now')*1000),
(2, '분식', 'snack food', strftime('%s','now')*1000),
(2, '분위기', 'atmosphere', strftime('%s','now')*1000),
(2, '분홍색', 'pink', strftime('%s','now')*1000),
(2, '불쌍하다', 'to be pitiful', strftime('%s','now')*1000),
(2, '불안', 'anxiety', strftime('%s','now')*1000),
(2, '불편', 'discomfort', strftime('%s','now')*1000),
(2, '붉다', 'to be red', strftime('%s','now')*1000),
(2, '붙다', 'to stick', strftime('%s','now')*1000),
(2, '붙이다', 'to attach', strftime('%s','now')*1000),
(2, '블라우스', 'blouse', strftime('%s','now')*1000),
(2, '비교', 'comparison', strftime('%s','now')*1000),
(2, '비누', 'soap', strftime('%s','now')*1000),
(2, '비다', 'to be empty', strftime('%s','now')*1000),
(2, '비디오', 'video', strftime('%s','now')*1000),
(2, '비밀', 'secret', strftime('%s','now')*1000),
(2, '비슷하다', 'to be similar', strftime('%s','now')*1000),
(2, '빌딩', 'building', strftime('%s','now')*1000),
(2, '빠지다02', 'to fall out (version 2)', strftime('%s','now')*1000),
(2, '빨간색', 'red', strftime('%s','now')*1000),
(2, '빨갛다', 'to be red', strftime('%s','now')*1000),
(2, '빨다02', 'to suck (version 2)', strftime('%s','now')*1000),
(2, '빨래', 'laundry', strftime('%s','now')*1000),
(2, '빵집', 'bakery', strftime('%s','now')*1000),
(2, '빼다01', 'to take out (version 1)', strftime('%s','now')*1000),
(2, '뽑다', 'to choose, to pick', strftime('%s','now')*1000),
(2, '사거리', 'intersection', strftime('%s','now')*1000),
(2, '사계절', 'four seasons', strftime('%s','now')*1000),
(2, '사고01', 'accident (version 1)', strftime('%s','now')*1000),
(2, '사실01/사실02', 'fact (version 1/2)', strftime('%s','now')*1000),
(2, '사업', 'business', strftime('%s','now')*1000),
(2, '사이즈', 'size', strftime('%s','now')*1000),
(2, '사장', 'boss, president', strftime('%s','now')*1000),
(2, '사탕', 'candy', strftime('%s','now')*1000),
(2, '사흘', 'three days', strftime('%s','now')*1000),
(2, '살01', 'to live, life (version 1)', strftime('%s','now')*1000),
(2, '삼거리', 'three-way intersection', strftime('%s','now')*1000),
(2, '삼겹살', 'pork belly', strftime('%s','now')*1000),
(2, '삼촌', 'uncle', strftime('%s','now')*1000),
(2, '상06', 'reward, prize (version 6)', strftime('%s','now')*1000),
(2, '상자', 'box', strftime('%s','now')*1000),
(2, '상처02', 'wound (version 2)', strftime('%s','now')*1000),
(2, '상추', 'lettuce', strftime('%s','now')*1000),
(2, '상품02', 'product (version 2)', strftime('%s','now')*1000),
(2, '새02', 'bird (version 2)', strftime('%s','now')*1000),
(2, '새03', 'new (version 3)', strftime('%s','now')*1000),
(2, '새로', 'newly', strftime('%s','now')*1000),
(2, '새롭다', 'to be new', strftime('%s','now')*1000),
(2, '새벽', 'dawn', strftime('%s','now')*1000),
(2, '새해', 'new year', strftime('%s','now')*1000),
(2, '색', 'color', strftime('%s','now')*1000),
(2, '색깔', 'color (with more emphasis)', strftime('%s','now')*1000),
(2, '샌드위치', 'sandwich', strftime('%s','now')*1000),
(2, '생각나다', 'to come to mind, to remember', strftime('%s','now')*1000),
(2, '생기다01', 'to appear, to come to life (version 1)', strftime('%s','now')*1000),
(2, '생선', 'fish (for eating)', strftime('%s','now')*1000),
(2, '서너', 'three or four', strftime('%s','now')*1000),
(2, '서다', 'to stand', strftime('%s','now')*1000),
(2, '서두르다', 'to hurry', strftime('%s','now')*1000),
(2, '서랍', 'drawer', strftime('%s','now')*1000),
(2, '서로02', 'each other (version 2)', strftime('%s','now')*1000),
(2, '서류', 'document', strftime('%s','now')*1000),
(2, '서비스', 'service', strftime('%s','now')*1000),
(2, '서양', 'the West', strftime('%s','now')*1000),
(2, '서쪽', 'west', strftime('%s','now')*1000),
(2, '섞다', 'to mix', strftime('%s','now')*1000),
(2, '선배', 'senior (in school or work)', strftime('%s','now')*1000),
(2, '선선하다', 'to be cool (weather)', strftime('%s','now')*1000),
(2, '선수02', 'player (version 2)', strftime('%s','now')*1000),
(2, '선택', 'choice, selection', strftime('%s','now')*1000),
(2, '선풍기', 'electric fan', strftime('%s','now')*1000),
(2, '설거지', 'washing dishes', strftime('%s','now')*1000),
(2, '설날', 'Lunar New Year', strftime('%s','now')*1000),
(2, '설렁탕', 'beef soup', strftime('%s','now')*1000),
(2, '설탕', 'sugar', strftime('%s','now')*1000),
(2, '섬03', 'island (version 3)', strftime('%s','now')*1000),
(2, '섭섭하다', 'to be sorry, disappointed', strftime('%s','now')*1000),
(2, '성02', 'success (version 2)', strftime('%s','now')*1000),
(2, '성격', 'personality', strftime('%s','now')*1000),
(2, '성공', 'success', strftime('%s','now')*1000),
(2, '성적03', 'grades, score (version 3)', strftime('%s','now')*1000),
(2, '성함', 'name (honorific)', strftime('%s','now')*1000),
(2, '세05', 'tax (version 5)', strftime('%s','now')*1000),
(2, '세계', 'world', strftime('%s','now')*1000),
(2, '세다03', 'to count, to be strong (version 3)', strftime('%s','now')*1000),
(2, '세배', 'New Year’s bow', strftime('%s','now')*1000),
(2, '세상', 'world, society', strftime('%s','now')*1000),
(2, '세우다', 'to set up', strftime('%s','now')*1000),
(2, '세탁', 'laundry', strftime('%s','now')*1000),
(2, '세탁기', 'washing machine', strftime('%s','now')*1000),
(2, '세탁소', 'laundry shop', strftime('%s','now')*1000),
(2, '센터', 'center', strftime('%s','now')*1000),
(2, '센티미터', 'centimeter', strftime('%s','now')*1000),
(2, '셋째02‧셋째01/셋째03', 'third (version 2)', strftime('%s','now')*1000),
(2, '소02', 'cow (version 2)', strftime('%s','now')*1000),
(2, '소고기', 'beef', strftime('%s','now')*1000),
(2, '소리', 'sound', strftime('%s','now')*1000),
(2, '소설02', 'novel (version 2)', strftime('%s','now')*1000),
(2, '소식02', 'news (version 2)', strftime('%s','now')*1000),
(2, '소주', 'soju', strftime('%s','now')*1000),
(2, '소중하다', 'to be precious', strftime('%s','now')*1000),
(2, '소파', 'sofa', strftime('%s','now')*1000),
(2, '소포', 'parcel', strftime('%s','now')*1000),
(2, '소풍', 'picnic', strftime('%s','now')*1000),
(2, '소화제', 'digestive medicine', strftime('%s','now')*1000),
(2, '속', 'inside', strftime('%s','now')*1000),
(2, '속도', 'speed', strftime('%s','now')*1000),
(2, '속옷', 'underwear', strftime('%s','now')*1000),
(2, '손가락', 'finger', strftime('%s','now')*1000),
(2, '손녀', 'granddaughter', strftime('%s','now')*1000),
(2, '손바닥', 'palm of hand', strftime('%s','now')*1000),
(2, '손수건', 'handkerchief', strftime('%s','now')*1000),
(2, '송편', 'songpyeon (rice cake)', strftime('%s','now')*1000),
(2, '수10', 'number 10', strftime('%s','now')*1000),
(2, '수건', 'towel', strftime('%s','now')*1000),
(2, '수고', 'effort', strftime('%s','now')*1000),
(2, '수술02', 'surgery (version 2)', strftime('%s','now')*1000),
(2, '수영복', 'swimsuit', strftime('%s','now')*1000),
(2, '수저', 'spoon and chopsticks', strftime('%s','now')*1000),
(2, '순두부찌개', 'soft tofu stew', strftime('%s','now')*1000),
(2, '순서', 'order', strftime('%s','now')*1000),
(2, '숟가락', 'spoon', strftime('%s','now')*1000),
(2, '술집', 'bar', strftime('%s','now')*1000),
(2, '숫자', 'number', strftime('%s','now')*1000),
(2, '쉬다04', 'to rest (version 4)', strftime('%s','now')*1000),
(2, '쉰02·쉰01', 'fifty (version 2)', strftime('%s','now')*1000),
(2, '스무', 'twenty', strftime('%s','now')*1000),
(2, '스스로02/스스로01', 'oneself, by oneself', strftime('%s','now')*1000),
(2, '스웨터', 'sweater', strftime('%s','now')*1000),
(2, '스카프', 'scarf', strftime('%s','now')*1000),
(2, '스케이트', 'skate', strftime('%s','now')*1000),
(2, '스키장', 'ski resort', strftime('%s','now')*1000),
(2, '스타', 'star', strftime('%s','now')*1000),
(2, '스트레스', 'stress', strftime('%s','now')*1000),
(2, '스파게티', 'spaghetti', strftime('%s','now')*1000),
(2, '스포츠', 'sports', strftime('%s','now')*1000),
(2, '슬퍼하다', 'to be sad', strftime('%s','now')*1000),
(2, '슬픔', 'sadness', strftime('%s','now')*1000),
(2, '습관', 'habit', strftime('%s','now')*1000),
(2, '시01', 'poem (version 1)', strftime('%s','now')*1000),
(2, '시간표', 'schedule', strftime('%s','now')*1000),
(2, '시계01', 'clock, watch (version 1)', strftime('%s','now')*1000),
(2, '시골', 'countryside', strftime('%s','now')*1000),
(2, '시끄럽다', 'to be noisy', strftime('%s','now')*1000),
(2, '시내02', 'downtown (version 2)', strftime('%s','now')*1000),
(2, '시민', 'citizen', strftime('%s','now')*1000),
(2, '시어머니', 'mother-in-law', strftime('%s','now')*1000),
(2, '식구', 'family member', strftime('%s','now')*1000),
(2, '식다', 'to become cold (food)', strftime('%s','now')*1000),
(2, '식빵', 'loaf of bread', strftime('%s','now')*1000),
(2, '식초', 'vinegar', strftime('%s','now')*1000),
(2, '식탁', 'dining table', strftime('%s','now')*1000),
(2, '식품', 'food products', strftime('%s','now')*1000),
(2, '신랑', 'bridegroom', strftime('%s','now')*1000),
(2, '신부02', 'bride (version 2)', strftime('%s','now')*1000),
(2, '신분증', 'ID card', strftime('%s','now')*1000),
(2, '신선하다', 'to be fresh', strftime('%s','now')*1000),
(2, '신청', 'application', strftime('%s','now')*1000),
(2, '신호', 'signal', strftime('%s','now')*1000),
(2, '신호등', 'traffic light', strftime('%s','now')*1000),
(2, '신혼여행', 'honeymoon', strftime('%s','now')*1000),
(2, '싣다', 'to load', strftime('%s','now')*1000),
(2, '실수', 'mistake', strftime('%s','now')*1000),
(2, '실패02', 'failure (version 2)', strftime('%s','now')*1000),
(2, '심다', 'to plant', strftime('%s','now')*1000),
(2, '심심하다01', 'to be bored (version 1)', strftime('%s','now')*1000),
(2, '심하다', 'to be severe, intense', strftime('%s','now')*1000),
(2, '싸다01', 'to be cheap (version 1)', strftime('%s','now')*1000),
(2, '싸우다', 'to fight', strftime('%s','now')*1000),
(2, '쌀', 'rice (uncooked)', strftime('%s','now')*1000),
(2, '쌀쌀하다', 'to be chilly', strftime('%s','now')*1000),
(2, '쌓다01', 'to pile up (version 1)', strftime('%s','now')*1000),
(2, '썰다', 'to slice', strftime('%s','now')*1000),
(2, '쓰다02', 'to use (version 2)', strftime('%s','now')*1000),
(2, '쓰레기', 'garbage', strftime('%s','now')*1000),
(2, '쓰레기통', 'garbage can', strftime('%s','now')*1000),
(2, '씹다', 'to chew', strftime('%s','now')*1000),
(2, '아가씨', 'young lady', strftime('%s','now')*1000),
(2, '아까02/아까01', 'earlier (version 2/1)', strftime('%s','now')*1000),
(2, '아나운서', 'announcer', strftime('%s','now')*1000),
(2, '아니02', 'no (version 2)', strftime('%s','now')*1000),
(2, '아들', 'son', strftime('%s','now')*1000),
(2, '아래쪽', 'below, underneath', strftime('%s','now')*1000),
(2, '아마', 'perhaps, maybe', strftime('%s','now')*1000),
(2, '아무02/아무01', 'any, anyone (version 2/1)', strftime('%s','now')*1000),
(2, '아무것', 'anything', strftime('%s','now')*1000),
(2, '아무리01', 'no matter how (version 1)', strftime('%s','now')*1000),
(2, '아버님', 'father (honorific)', strftime('%s','now')*1000),
(2, '아빠', 'dad', strftime('%s','now')*1000),
(2, '아줌마', 'woman (married woman)', strftime('%s','now')*1000),
(2, '악기', 'musical instrument', strftime('%s','now')*1000),
(2, '안개', 'fog', strftime('%s','now')*1000),
(2, '안내문', 'notice, guide', strftime('%s','now')*1000),
(2, '안다', 'to know', strftime('%s','now')*1000),
(2, '안되다01', 'to not work (version 1)', strftime('%s','now')*1000),
(2, '안전01', 'safety (version 1)', strftime('%s','now')*1000),
(2, '안쪽', 'inside', strftime('%s','now')*1000),
(2, '알맞다', 'to be proper, right', strftime('%s','now')*1000),
(2, '알아보다', 'to recognize, to check', strftime('%s','now')*1000),
(2, '앞쪽', 'front side', strftime('%s','now')*1000),
(2, '애02', 'child (version 2)', strftime('%s','now')*1000),
(2, '애인', 'lover', strftime('%s','now')*1000),
(2, '앨범', 'album', strftime('%s','now')*1000),
(2, '야02', 'wild, 야 (version 2)', strftime('%s','now')*1000),
(2, '야채', 'vegetables', strftime('%s','now')*1000),
(2, '약간02/약간01', 'slightly (version 2/1)', strftime('%s','now')*1000),
(2, '약사', 'pharmacist', strftime('%s','now')*1000),
(2, '어울리다', 'to suit to match', strftime('%s','now')*1000),
(2, '어젯밤', 'last night', strftime('%s','now')*1000),
(2, '언어', 'language (speech)', strftime('%s','now')*1000),
(2, '언제나', 'always', strftime('%s','now')*1000),
(2, '얻다', 'to get obtain', strftime('%s','now')*1000),
(2, '얼다', 'to freeze', strftime('%s','now')*1000),
(2, '얼음', 'ice', strftime('%s','now')*1000),
(2, '엄ма', 'mom, mother', strftime('%s','now')*1000),
(2, '엉덩이', 'buttocks', strftime('%s','now')*1000),
(2, '엘리베이터', 'elevator', strftime('%s','now')*1000),
(2, '여기저기', 'here and there, everywhere', strftime('%s','now')*1000),
(2, '여성', 'woman, female', strftime('%s','now')*1000),
(2, '여쭙다', 'to ask (hon.)', strftime('%s','now')*1000),
(2, '여학생', 'female student', strftime('%s','now')*1000),
(2, '여행지', 'travel destination', strftime('%s','now')*1000),
(2, '역사', 'history', strftime('%s','now')*1000),
(2, '역시', 'also, as expected', strftime('%s','now')*1000),
(2, '연결', 'connection, link', strftime('%s','now')*1000),
(2, '연락', 'contact, communication', strftime('%s','now')*1000),
(2, '연락처', 'contact information', strftime('%s','now')*1000),
(2, '연말', 'year-end', strftime('%s','now')*1000),
(2, '연세', 'age (honorific)', strftime('%s','now')*1000),
(2, '연예인', 'celebrity, entertainer', strftime('%s','now')*1000),
(2, '연휴', 'long holiday', strftime('%s','now')*1000),
(2, '열', 'fever, heat, row', strftime('%s','now')*1000),
(2, '열리다', 'to open (be opened)', strftime('%s','now')*1000),
(2, '열차', 'train', strftime('%s','now')*1000),
(2, '열흘', 'ten days', strftime('%s','now')*1000),
(2, '엽서', 'postcard', strftime('%s','now')*1000),
(2, '영수증', 'receipt', strftime('%s','now')*1000),
(2, '영하', 'below zero', strftime('%s','now')*1000),
(2, '옆집', 'next-door house', strftime('%s','now')*1000),
(2, '예매', 'advance purchase (ticket)', strftime('%s','now')*1000),
(2, '예순', 'sixty', strftime('%s','now')*1000),
(2, '예술', 'art', strftime('%s','now')*1000),
(2, '예습', 'pre-study, preparation', strftime('%s','now')*1000),
(2, '예약', 'reservation', strftime('%s','now')*1000),
(2, '옛', 'old, ancient', strftime('%s','now')*1000),
(2, '옛날', 'the old days, long ago', strftime('%s','now')*1000),
(2, '오래', 'for a long time', strftime('%s','now')*1000),
(2, '오래간만', 'after a long time', strftime('%s','now')*1000),
(2, '오래되다', 'old (thing/place)', strftime('%s','now')*1000),
(2, '오랜만', 'long time no see', strftime('%s','now')*1000),
(2, '오랫동안', 'for a long time', strftime('%s','now')*1000),
(2, '오르다', 'to rise, climb', strftime('%s','now')*1000),
(2, '오른손', 'right hand', strftime('%s','now')*1000),
(2, '오이', 'cucumber', strftime('%s','now')*1000),
(2, '온도', 'temperature', strftime('%s','now')*1000),
(2, '올라오다', 'to come up', strftime('%s','now')*1000),
(2, '올리다', 'to raise, upload', strftime('%s','now')*1000),
(2, '올림', 'from (in a letter)', strftime('%s','now')*1000),
(2, '올림픽', 'Olympics', strftime('%s','now')*1000),
(2, '옳다', 'right, correct', strftime('%s','now')*1000),
(2, '옷걸이', 'hanger', strftime('%s','now')*1000),
(2, '옷장', 'wardrobe, closet', strftime('%s','now')*1000),
(2, '와이셔츠', 'dress shirt', strftime('%s','now')*1000),
(2, '완전히', 'completely', strftime('%s','now')*1000),
(2, '왕', 'king', strftime('%s','now')*1000),
(2, '왜냐하면', 'because', strftime('%s','now')*1000),
(2, '외롭다', 'lonely', strftime('%s','now')*1000),
(2, '외우다', 'to memorize', strftime('%s','now')*1000),
(2, '외출', 'going out', strftime('%s','now')*1000),
(2, '왼손', 'left hand', strftime('%s','now')*1000),
(2, '요금', 'fee, fare', strftime('%s','now')*1000),
(2, '요리사', 'chef, cook', strftime('%s','now')*1000),
(2, '우동', 'udon (noodles)', strftime('%s','now')*1000),
(2, '우리나라', 'our country (Korea)', strftime('%s','now')*1000),
(2, '우선', 'first, above all', strftime('%s','now')*1000),
(2, '운동복', 'sportswear', strftime('%s','now')*1000),
(2, '운전사', 'driver', strftime('%s','now')*1000),
(2, '울산', 'Ulsan (city)', strftime('%s','now')*1000),
(2, '울음', 'crying, weeping', strftime('%s','now')*1000),
(2, '움직이다', 'to move', strftime('%s','now')*1000),
(2, '웃음', 'laughter', strftime('%s','now')*1000),
(2, '원피스', 'one-piece dress', strftime('%s','now')*1000),
(2, '원하다', 'to want', strftime('%s','now')*1000),
(2, '월급', 'salary, wages', strftime('%s','now')*1000),
(2, '위쪽', 'upper part, above', strftime('%s','now')*1000),
(2, '위치', 'location', strftime('%s','now')*1000),
(2, '위험', 'danger', strftime('%s','now')*1000),
(2, '유리', 'glass', strftime('%s','now')*1000),
(2, '유치원', 'kindergarten', strftime('%s','now')*1000),
(2, '유학', 'study abroad', strftime('%s','now')*1000),
(2, '유학생', 'international student', strftime('%s','now')*1000),
(2, '유행', 'fashion, trend', strftime('%s','now')*1000),
(2, '육교', 'pedestrian overpass', strftime('%s','now')*1000),
(2, '윷놀이', 'yut game', strftime('%s','now')*1000),
(2, '음료', 'beverage', strftime('%s','now')*1000),
(2, '음식점', 'restaurant', strftime('%s','now')*1000),
(2, '음악가', 'musician', strftime('%s','now')*1000),
(2, '응', 'uh-huh, yes', strftime('%s','now')*1000),
(2, '의미', 'meaning', strftime('%s','now')*1000),
(2, '이', 'this', strftime('%s','now')*1000),
(2, '이거', 'this thing', strftime('%s','now')*1000),
(2, '이곳', 'this place', strftime('%s','now')*1000),
(2, '이기다', 'to win', strftime('%s','now')*1000),
(2, '이날', 'on this day', strftime('%s','now')*1000),
(2, '이때', 'at this time', strftime('%s','now')*1000),
(2, '이런', 'such, like this', strftime('%s','now')*1000),
(2, '이렇다', 'to be like this', strftime('%s','now')*1000),
(2, '이르다', 'to be early', strftime('%s','now')*1000),
(2, '이마', 'forehead', strftime('%s','now')*1000),
(2, '이모', 'aunt (maternal)', strftime('%s','now')*1000),
(2, '이미', 'already', strftime('%s','now')*1000),
(2, '이분', 'this person (hon.)', strftime('%s','now')*1000),
(2, '이불', 'blanket, quilt', strftime('%s','now')*1000),
(2, '이사', 'moving (house)', strftime('%s','now')*1000),
(2, '이삿짐', 'moving belongings', strftime('%s','now')*1000),
(2, '이상', 'abnormality, above', strftime('%s','now')*1000),
(2, '이용', 'use, utilization', strftime('%s','now')*1000),
(2, '이웃', 'neighbor', strftime('%s','now')*1000),
(2, '이전', 'before, previous', strftime('%s','now')*1000),
(2, '이제', 'now, already', strftime('%s','now')*1000),
(2, '이틀', 'two days', strftime('%s','now')*1000),
(2, '이해', 'understanding', strftime('%s','now')*1000),
(2, '이후', 'after, afterwards', strftime('%s','now')*1000),
(2, '익다', 'to ripen, be cooked', strftime('%s','now')*1000),
(2, '익숙하다', 'to be accustomed, familiar', strftime('%s','now')*1000),
(2, '인기', 'popularity', strftime('%s','now')*1000),
(2, '인삼', 'ginseng', strftime('%s','now')*1000),
(2, '인형', 'doll', strftime('%s','now')*1000),
(2, '일기', 'diary', strftime('%s','now')*1000),
(2, '일부', 'part, portion', strftime('%s','now')*1000),
(2, '일식', 'Japanese cuisine', strftime('%s','now')*1000),
(2, '일식집', 'Japanese restaurant', strftime('%s','now')*1000),
(2, '일어서다', 'to stand up', strftime('%s','now')*1000),
(2, '잃다', 'to lose', strftime('%s','now')*1000),
(2, '잃어버리다', 'to lose completely', strftime('%s','now')*1000),
(2, '입구', 'entrance', strftime('%s','now')*1000),
(2, '입술', 'lips', strftime('%s','now')*1000),
(2, '입원', 'hospitalization', strftime('%s','now')*1000),
(2, '입장권', 'admission ticket', strftime('%s','now')*1000),
(2, '입학', 'admission (to school)', strftime('%s','now')*1000),
(2, '잊다', 'to forget', strftime('%s','now')*1000),
(2, '잊어버리다', 'to completely forget', strftime('%s','now')*1000),
(2, '잎', 'leaf', strftime('%s','now')*1000),
(2, '자기소개', 'self-introduction', strftime('%s','now')*1000),
(2, '자꾸', 'constantly, repeatedly', strftime('%s','now')*1000),
(2, '자동판매기', 'vending machine', strftime('%s','now')*1000),
(2, '자라다', 'to grow (up)', strftime('%s','now')*1000),
(2, '자랑', 'pride, boasting', strftime('%s','now')*1000),
(2, '자르다', 'to cut', strftime('%s','now')*1000),
(2, '자리', 'seat, place', strftime('%s','now')*1000),
(2, '자세히', 'in detail', strftime('%s','now')*1000),
(2, '자식', 'children (one’s)', strftime('%s','now')*1000),
(2, '자신', 'confidence, oneself', strftime('%s','now')*1000),
(2, '자연', 'nature', strftime('%s','now')*1000),
(2, '자유', 'freedom', strftime('%s','now')*1000),
(2, '자장면', 'jjajangmyeon (noodles)', strftime('%s','now')*1000),
(2, '자판기', 'vending machine', strftime('%s','now')*1000),
(2, '잔치', 'feast, party', strftime('%s','now')*1000),
(2, '잘되다', 'to go well, succeed', strftime('%s','now')*1000),
(2, '잘못되다', 'to be wrong, go wrong', strftime('%s','now')*1000),
(2, '잘못하다', 'to make a mistake', strftime('%s','now')*1000),
(2, '잘생기다', 'to be handsome', strftime('%s','now')*1000),
(2, '잠자다', 'to sleep', strftime('%s','now')*1000),
(2, '잡다', 'to catch, grab', strftime('%s','now')*1000),
(2, '잡지', 'magazine', strftime('%s','now')*1000),
(2, '장', 'chapter, market', strftime('%s','now')*1000),
(2, '장갑', 'gloves', strftime('%s','now')*1000),
(2, '장난감', 'toy', strftime('%s','now')*1000),
(2, '장마', 'rainy season', strftime('%s','now')*1000),
(2, '장미', 'rose', strftime('%s','now')*1000),
(2, '재료', 'material, ingredient', strftime('%s','now')*1000),
(2, '재미', 'interest, fun', strftime('%s','now')*1000),
(2, '재채기', 'sneeze', strftime('%s','now')*1000),
(2, '저거', 'that thing (over there)', strftime('%s','now')*1000),
(2, '저곳', 'that place (over there)', strftime('%s','now')*1000),
(2, '저금', 'savings', strftime('%s','now')*1000),
(2, '저런', 'that kind (over there)', strftime('%s','now')*1000),
(2, '저렇다', 'to be like that (over there)', strftime('%s','now')*1000),
(2, '저번', 'last time', strftime('%s','now')*1000),
(2, '저분', 'that person (hon.)', strftime('%s','now')*1000),
(2, '저희', 'we, our (humble)', strftime('%s','now')*1000),
(2, '적다', 'to write down, be few', strftime('%s','now')*1000),
(2, '적당하다', 'appropriate, suitable', strftime('%s','now')*1000),
(2, '전', 'before, earlier', strftime('%s','now')*1000),
(2, '전기', 'electricity', strftime('%s','now')*1000),
(2, '전부', 'all, entirely', strftime('%s','now')*1000),
(2, '전철', 'subway', strftime('%s','now')*1000),
(2, '전체', 'the whole, entire', strftime('%s','now')*1000),
(2, '전하다', 'to convey, deliver', strftime('%s','now')*1000),
(2, '전혀', 'not at all', strftime('%s','now')*1000),
(2, '전화기', 'telephone set', strftime('%s','now')*1000),
(2, '젊다', 'young', strftime('%s','now')*1000),
(2, '점수', 'score, grade', strftime('%s','now')*1000),
(2, '점심시간', 'lunchtime', strftime('%s','now')*1000),
(2, '점점', 'gradually', strftime('%s','now')*1000),
(2, '접다', 'to fold', strftime('%s','now')*1000),
(2, '접시', 'plate', strftime('%s','now')*1000),
(2, '젓가락', 'chopsticks', strftime('%s','now')*1000),
(2, '정거장', 'stop, station', strftime('%s','now')*1000),
(2, '정도', 'degree, level', strftime('%s','now')*1000),
(2, '정리', 'tidying, organizing', strftime('%s','now')*1000),
(2, '정문', 'main gate', strftime('%s','now')*1000),
(2, '정원', 'garden', strftime('%s','now')*1000),
(2, '정하다', 'to decide, determine', strftime('%s','now')*1000),
(2, '정확', 'accuracy', strftime('%s','now')*1000),
(2, '젖다', 'to get wet', strftime('%s','now')*1000),
(2, '제목', 'title, subject', strftime('%s','now')*1000),
(2, '조금씩', 'little by little', strftime('%s','now')*1000),
(2, '조심', 'caution, care', strftime('%s','now')*1000),
(2, '조용히', 'quietly', strftime('%s','now')*1000),
(2, '조카', 'nephew, niece', strftime('%s','now')*1000),
(2, '졸다', 'to doze', strftime('%s','now')*1000),
(2, '좁다', 'narrow, cramped', strftime('%s','now')*1000),
(2, '종류', 'kind, type', strftime('%s','now')*1000),
(2, '종이', 'paper', strftime('%s','now')*1000),
(2, '주머니', 'pocket', strftime('%s','now')*1000),
(2, '주문', 'order', strftime('%s','now')*1000),
(2, '주변', 'surroundings, vicinity', strftime('%s','now')*1000),
(2, '주사', 'injection', strftime('%s','now')*1000),
(2, '주위', 'around, surroundings', strftime('%s','now')*1000),
(2, '주차', 'parking', strftime('%s','now')*1000),
(2, '주차장', 'parking lot', strftime('%s','now')*1000),
(2, '주황색', 'orange (color)', strftime('%s','now')*1000),
(2, '죽다', 'to die', strftime('%s','now')*1000),
(2, '줄', 'rope, line, row', strftime('%s','now')*1000),
(2, '줄다', 'to decrease', strftime('%s','now')*1000),
(2, '줄이다', 'to reduce', strftime('%s','now')*1000),
(2, '줍다', 'to pick up', strftime('%s','now')*1000),
(2, '중간', 'middle', strftime('%s','now')*1000),
(2, '중국집', 'Chinese restaurant', strftime('%s','now')*1000),
(2, '중심', 'center, core', strftime('%s','now')*1000),
(2, '중앙', 'center', strftime('%s','now')*1000),
(2, '중요', 'importance', strftime('%s','now')*1000),
(2, '중학교', 'middle school', strftime('%s','now')*1000),
(2, '중학생', 'middle school student', strftime('%s','now')*1000),
(2, '즐거워하다', 'to feel happy, delight', strftime('%s','now')*1000),
(2, '즐겁다', 'pleasant, joyful', strftime('%s','now')*1000),
(2, '즐기다', 'to enjoy', strftime('%s','now')*1000),
(2, '지각', 'tardiness', strftime('%s','now')*1000),
(2, '지나가다', 'to pass by', strftime('%s','now')*1000),
(2, '지난번', 'last time', strftime('%s','now')*1000),
(2, '지다', 'to lose, (sun) set', strftime('%s','now')*1000),
(2, '지도', 'map', strftime('%s','now')*1000),
(2, '지루하다', 'boring', strftime('%s','now')*1000),
(2, '지르다', 'to shout, yell', strftime('%s','now')*1000),
(2, '지방', 'region, area', strftime('%s','now')*1000),
(2, '지우다', 'to erase, delete', strftime('%s','now')*1000),
(2, '지키다', 'to protect, keep', strftime('%s','now')*1000),
(2, '지하', 'underground', strftime('%s','now')*1000),
(2, '지하도', 'underpass', strftime('%s','now')*1000),
(2, '직장', 'workplace, job', strftime('%s','now')*1000),
(2, '직접', 'directly, in person', strftime('%s','now')*1000),
(2, '진짜', 'real, really', strftime('%s','now')*1000),
(2, '진하다', 'thick, rich', strftime('%s','now')*1000),
(2, '짐', 'baggage, stuff', strftime('%s','now')*1000),
(2, '집들이', 'housewarming', strftime('%s','now')*1000),
(2, '집안일', 'housework', strftime('%s','now')*1000),
(2, '짓다', 'to build, compose', strftime('%s','now')*1000),
(2, '짜증', 'irritation', strftime('%s','now')*1000),
(2, '짝', 'pair, partner', strftime('%s','now')*1000),
(2, '짧다', 'short', strftime('%s','now')*1000),
(2, '짬뽕', 'jjamppong (noodles)', strftime('%s','now')*1000),
(2, '찌개', 'stew (jjigae)', strftime('%s','now')*1000),
(2, '찌다', 'to steam, to gain weight', strftime('%s','now')*1000),
(2, '차', 'car, tea', strftime('%s','now')*1000),
(2, '차갑다', 'cold (to the touch)', strftime('%s','now')*1000),
(2, '차다', 'to be full, to kick, to wear', strftime('%s','now')*1000),
(2, '차례', 'turn, order', strftime('%s','now')*1000),
(2, '착하다', 'kind', strftime('%s','now')*1000),
(2, '찬물', 'cold water', strftime('%s','now')*1000),
(2, '참다', 'to endure', strftime('%s','now')*1000),
(2, '찾아가다', 'to go visit', strftime('%s','now')*1000),
(2, '찾아오다', 'to come visit', strftime('%s','now')*1000),
(2, '채소', 'vegetables', strftime('%s','now')*1000),
(2, '책장', 'bookcase', strftime('%s','now')*1000),
(2, '첫', 'first', strftime('%s','now')*1000),
(2, '첫날', 'first day', strftime('%s','now')*1000),
(2, '첫째', 'first, eldest', strftime('%s','now')*1000),
(2, '청년', 'youth, young man', strftime('%s','now')*1000),
(2, '청바지', 'jeans', strftime('%s','now')*1000),
(2, '청소년', 'adolescent, teenager', strftime('%s','now')*1000),
(2, '체육관', 'gymnasium', strftime('%s','now')*1000),
(2, '쳐다보다', 'to look up at, gaze at', strftime('%s','now')*1000),
(2, '초', 'beginning, candle, second', strftime('%s','now')*1000),
(2, '초대장', 'invitation card', strftime('%s','now')*1000),
(2, '초등학교', 'elementary school', strftime('%s','now')*1000),
(2, '초등학생', 'elementary school student', strftime('%s','now')*1000),
(2, '초록색', 'green (color)', strftime('%s','now')*1000),
(2, '최고', 'the best, highest', strftime('%s','now')*1000),
(2, '최근', 'recently, lately', strftime('%s','now')*1000),
(2, '추석', 'Chuseok (harvest festival)', strftime('%s','now')*1000),
(2, '축구공', 'soccer ball', strftime('%s','now')*1000),
(2, '출구', 'exit', strftime('%s','now')*1000),
(2, '출근', 'going to work', strftime('%s','now')*1000),
(2, '출석', 'attendance', strftime('%s','now')*1000),
(2, '출입', 'entry and exit', strftime('%s','now')*1000),
(2, '출입국', 'immigration (in/out of country)', strftime('%s','now')*1000),
(2, '출장', 'business trip', strftime('%s','now')*1000),
(2, '출퇴근', 'commuting', strftime('%s','now')*1000),
(2, '충분하다', 'sufficient', strftime('%s','now')*1000),
(2, '취소', 'cancellation', strftime('%s','now')*1000),
(2, '취직', 'getting a job', strftime('%s','now')*1000),
(2, '치과', 'dentistry, dental clinic', strftime('%s','now')*1000),
(2, '치료', 'treatment', strftime('%s','now')*1000),
(2, '치약', 'toothpaste', strftime('%s','now')*1000),
(2, '치킨', 'fried chicken', strftime('%s','now')*1000),
(2, '친척', 'relative', strftime('%s','now')*1000),
(2, '침실', 'bedroom', strftime('%s','now')*1000),
(2, '칫솔', 'toothbrush', strftime('%s','now')*1000),
(2, '칭찬', 'praise', strftime('%s','now')*1000),
(2, '카레', 'curry', strftime('%s','now')*1000),
(2, '카페', 'cafe', strftime('%s','now')*1000),
(2, '칼', 'knife', strftime('%s','now')*1000),
(2, '칼국수', 'kalguksu (noodles)', strftime('%s','now')*1000),
(2, '켜다', 'to turn on', strftime('%s','now')*1000),
(2, '켤레', 'pair (shoes, socks)', strftime('%s','now')*1000),
(2, '코끼리', 'elephant', strftime('%s','now')*1000),
(2, '콧물', 'snot, runny nose', strftime('%s','now')*1000),
(2, '콩', 'bean', strftime('%s','now')*1000),
(2, '크기', 'size', strftime('%s','now')*1000),
(2, '크리스마스', 'Christmas', strftime('%s','now')*1000),
(2, '큰소리', 'loud voice', strftime('%s','now')*1000),
(2, '키우다', 'to raise, grow', strftime('%s','now')*1000),
(2, '킬로그램', 'kilogram', strftime('%s','now')*1000),
(2, '킬로미터', 'kilometer', strftime('%s','now')*1000),
(2, '타다', 'to ride, get on', strftime('%s','now')*1000),
(2, '탕수육', 'tangsuyuk', strftime('%s','now')*1000),
(2, '태극기', 'Taegeukgi (Korean flag)', strftime('%s','now')*1000),
(2, '태도', 'attitude, behavior', strftime('%s','now')*1000),
(2, '태어나다', 'to be born', strftime('%s','now')*1000),
(2, '태풍', 'typhoon', strftime('%s','now')*1000),
(2, '택배', 'parcel delivery', strftime('%s','now')*1000),
(2, '테니스장', 'tennis court', strftime('%s','now')*1000),
(2, '테이블', 'table', strftime('%s','now')*1000),
(2, '토끼', 'rabbit', strftime('%s','now')*1000),
(2, '토마토', 'tomato', strftime('%s','now')*1000),
(2, '통장', 'bankbook', strftime('%s','now')*1000),
(2, '통화', 'phone call, currency', strftime('%s','now')*1000),
(2, '퇴원', 'discharge from hospital', strftime('%s','now')*1000),
(2, '튀기다', 'to deep-fry', strftime('%s','now')*1000),
(2, '튀김', 'fried food', strftime('%s','now')*1000),
(2, '트럭', 'truck', strftime('%s','now')*1000),
(2, '특별히', 'especially, particularly', strftime('%s','now')*1000),
(2, '튼튼하다', 'strong, sturdy', strftime('%s','now')*1000),
(2, '틀다', 'to turn on, turn', strftime('%s','now')*1000),
(2, '틀리다', 'to be wrong', strftime('%s','now')*1000),
(2, '팀', 'team', strftime('%s','now')*1000),
(2, '파란색', 'blue (color)', strftime('%s','now')*1000),
(2, '파랗다', 'to be blue', strftime('%s','now')*1000),
(2, '팔리다', 'to be sold', strftime('%s','now')*1000),
(2, '펴다', 'to open, spread out', strftime('%s','now')*1000),
(2, '편리', 'convenience', strftime('%s','now')*1000),
(2, '편안', 'comfort, peace', strftime('%s','now')*1000),
(2, '편찮다', 'to be ill (hon.)', strftime('%s','now')*1000),
(2, '편하다', 'comfortable, easy', strftime('%s','now')*1000),
(2, '평소', 'ordinary times, usually', strftime('%s','now')*1000),
(2, '평일', 'weekday', strftime('%s','now')*1000),
(2, '포장', 'packaging', strftime('%s','now')*1000),
(2, '푸르다', 'blue, green', strftime('%s','now')*1000),
(2, '푹', 'deeply, fully', strftime('%s','now')*1000),
(2, '풀다', 'to untie, solve', strftime('%s','now')*1000),
(2, '풍경', 'scenery, landscape', strftime('%s','now')*1000),
(2, '프라이팬', 'frying pan', strftime('%s','now')*1000),
(2, '피', 'blood', strftime('%s','now')*1000),
(2, '피다', 'to bloom', strftime('%s','now')*1000),
(2, '하늘', 'sky', strftime('%s','now')*1000),
(2, '하늘색', 'sky blue', strftime('%s','now')*1000),
(2, '-하다', 'verb-forming suffix “-hada”', strftime('%s','now')*1000),
(2, '하숙비', 'boarding fee', strftime('%s','now')*1000),
(2, '하얀색', 'white (color)', strftime('%s','now')*1000),
(2, '하얗다', 'to be white', strftime('%s','now')*1000),
(2, '학기', 'semester', strftime('%s','now')*1000),
(2, '학년', 'grade, year (school)', strftime('%s','now')*1000),
(2, '학원', 'private academy', strftime('%s','now')*1000),
(2, '한강', 'Han River', strftime('%s','now')*1000),
(2, '한글', 'Hangeul', strftime('%s','now')*1000),
(2, '한두', 'one or two', strftime('%s','now')*1000),
(2, '한번', 'once, sometime', strftime('%s','now')*1000),
(2, '한식', 'Korean cuisine', strftime('%s','now')*1000),
(2, '한식집', 'Korean restaurant', strftime('%s','now')*1000),
(2, '한옥', 'traditional Korean house', strftime('%s','now')*1000),
(2, '한잔', 'one drink, have a drink', strftime('%s','now')*1000),
(2, '한턱', 'treat (one’s shout)', strftime('%s','now')*1000),
(2, '할인', 'discount', strftime('%s','now')*1000),
(2, '항공', 'aviation, air', strftime('%s','now')*1000),
(2, '항공권', 'air ticket', strftime('%s','now')*1000),
(2, '항상', 'always', strftime('%s','now')*1000),
(2, '해', 'sun, year', strftime('%s','now')*1000),
(2, '해마다', 'every year', strftime('%s','now')*1000),
(2, '해외', 'overseas, abroad', strftime('%s','now')*1000),
(2, '해외여행', 'overseas trip', strftime('%s','now')*1000),
(2, '햄버거', 'hamburger', strftime('%s','now')*1000),
(2, '햇빛', 'sunlight', strftime('%s','now')*1000),
(2, '행동', 'behavior, action', strftime('%s','now')*1000),
(2, '행복', 'happiness', strftime('%s','now')*1000),
(2, '행사', 'event', strftime('%s','now')*1000),
(2, '허리', 'waist, lower back', strftime('%s','now')*1000),
(2, '헤어지다', 'to part, break up', strftime('%s','now')*1000),
(2, '헬스클럽', 'fitness club', strftime('%s','now')*1000),
(2, '혀', 'tongue (organ)', strftime('%s','now')*1000),
(2, '현금', 'cash', strftime('%s','now')*1000),
(2, '현재', 'present, current', strftime('%s','now')*1000),
(2, '형제', 'brothers, siblings', strftime('%s','now')*1000),
(2, '호랑이', 'tiger', strftime('%s','now')*1000),
(2, '호수', 'lake', strftime('%s','now')*1000),
(2, '혹시', 'by any chance, perhaps', strftime('%s','now')*1000),
(2, '홍차', 'black tea', strftime('%s','now')*1000),
(2, '화', 'anger', strftime('%s','now')*1000),
(2, '화가', 'painter (artist)', strftime('%s','now')*1000),
(2, '화나다', 'to get angry', strftime('%s','now')*1000),
(2, '화내다', 'to express anger', strftime('%s','now')*1000),
(2, '화려하다', 'splendid, luxurious', strftime('%s','now')*1000),
(2, '화장품', 'cosmetics', strftime('%s','now')*1000),
(2, '환영', 'welcome, warm reception', strftime('%s','now')*1000),
(2, '환자', 'patient', strftime('%s','now')*1000),
(2, '환전', 'currency exchange', strftime('%s','now')*1000),
(2, '회', 'meeting, time (counter)', strftime('%s','now')*1000),
(2, '회색', 'gray (color)', strftime('%s','now')*1000),
(2, '회원', 'member', strftime('%s','now')*1000),
(2, '횡단보도', 'crosswalk', strftime('%s','now')*1000),
(2, '후배', 'junior (at school/work)', strftime('%s','now')*1000),
(2, '훌륭하다', 'excellent, outstanding', strftime('%s','now')*1000),
(2, '훨씬', 'much, far more', strftime('%s','now')*1000),
(2, '휴게실', 'lounge, break room', strftime('%s','now')*1000),
(2, '휴대폰', 'mobile phone', strftime('%s','now')*1000),
(2, '휴일', 'day off, holiday', strftime('%s','now')*1000),
(2, '휴지', 'tissue, paper', strftime('%s','now')*1000),
(2, '휴지통', 'trash can', strftime('%s','now')*1000),
(2, '흐르다', 'to flow', strftime('%s','now')*1000),
(2, '흔들다', 'to shake, swing', strftime('%s','now')*1000),
(2, '흘리다', 'to drop, spill', strftime('%s','now')*1000),
(2, '희망', 'hope', strftime('%s','now')*1000),
(2, '흰색', 'white (color)', strftime('%s','now')*1000),
(2, '힘', 'strength, power', strftime('%s','now')*1000)
/


