PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(7, '동그랗다', 'round', strftime('%s','now')*1000),
(7, '동료', 'colleague / coworker', strftime('%s','now')*1000),
(7, '동부', 'eastern part', strftime('%s','now')*1000),
(7, '동아리', 'club / circle', strftime('%s','now')*1000),
(7, '동양', 'the East / Asia', strftime('%s','now')*1000),
(7, '동작', 'movement / motion', strftime('%s','now')*1000),
(7, '동창', 'schoolmate', strftime('%s','now')*1000),
(7, '동창회', 'alumni meeting', strftime('%s','now')*1000),
(7, '동호회', 'club / association', strftime('%s','now')*1000),
(7, '되돌아오다', 'come back / return', strftime('%s','now')*1000),
(7, '되찾다', 'recover / regain', strftime('%s','now')*1000),
(7, '두께', 'thickness', strftime('%s','now')*1000),
(7, '두통약', 'headache medicine', strftime('%s','now')*1000),
(7, '둥글다', 'round / circular', strftime('%s','now')*1000),
(7, '드라이', 'dry cleaning', strftime('%s','now')*1000),
(7, '드라이브', 'drive', strftime('%s','now')*1000),
(7, '드라이어', 'dryer', strftime('%s','now')*1000),
(7, '드레스', 'dress', strftime('%s','now')*1000),
(7, '듣기', 'listening', strftime('%s','now')*1000),
(7, '들려주다', 'play for / tell to someone', strftime('%s','now')*1000),
(7, '들어서다', 'enter / step into', strftime('%s','now')*1000),
(7, '들어주다', 'listen to / accept', strftime('%s','now')*1000),
(7, '등', 'back / etc.', strftime('%s','now')*1000),
(7, '등록', 'registration', strftime('%s','now')*1000),
(7, '등록금', 'tuition fee', strftime('%s','now')*1000),
(7, '등록증', 'registration card', strftime('%s','now')*1000),
(7, '등산복', 'hiking clothes', strftime('%s','now')*1000),
(7, '디지털', 'digital', strftime('%s','now')*1000),
(7, '따다', 'pick / open / win', strftime('%s','now')*1000),
(7, '따라가다', 'follow / go along', strftime('%s','now')*1000),
(7, '따라서', 'therefore / accordingly', strftime('%s','now')*1000),
(7, '따라오다', 'come along / follow', strftime('%s','now')*1000),
(7, '따로따로', 'separately / individually', strftime('%s','now')*1000),
(7, '따르다', 'follow / pour', strftime('%s','now')*1000),
(7, '따르릉', 'ring-ring (sound)', strftime('%s','now')*1000),
(7, '딱', 'exactly / tightly', strftime('%s','now')*1000),
(7, '딱딱하다', 'hard / stiff', strftime('%s','now')*1000),
(7, '땅속', 'underground / under the earth', strftime('%s','now')*1000),
(7, '때때로', 'sometimes / occasionally', strftime('%s','now')*1000),
(7, '떠나가다', 'leave / depart', strftime('%s','now')*1000),
(7, '떠오르다', 'rise / come to mind', strftime('%s','now')*1000),
(7, '떠올리다', 'recall / remember', strftime('%s','now')*1000),
(7, '떨다', 'tremble / shake', strftime('%s','now')*1000),
(7, '떨리다', 'tremble / quiver', strftime('%s','now')*1000),
(7, '떨어뜨리다', 'drop / let fall', strftime('%s','now')*1000),
(7, '또한', 'also / moreover', strftime('%s','now')*1000),
(7, '똑똑히', 'clearly / distinctly', strftime('%s','now')*1000),
(7, '뚫다', 'pierce / penetrate', strftime('%s','now')*1000),
(7, '뛰다', 'run / jump', strftime('%s','now')*1000),
(7, '뛰어나다', 'excel / outstanding', strftime('%s','now')*1000),
(7, '뛰어내리다', 'jump down / leap off', strftime('%s','now')*1000),
(7, '뛰어넘다', 'jump over / surpass', strftime('%s','now')*1000),
(7, '뜨다', 'float / rise / open eyes', strftime('%s','now')*1000),
(7, '띠', 'belt / ribbon / band', strftime('%s','now')*1000),
(7, '레몬', 'lemon', strftime('%s','now')*1000),
(7, '렌터카', 'rental car', strftime('%s','now')*1000),
(7, '로그인', 'login', strftime('%s','now')*1000),
(7, '로봇', 'robot', strftime('%s','now')*1000),
(7, '-률', 'rate / ratio (suffix)', strftime('%s','now')*1000),
(7, '리듬', 'rhythm', strftime('%s','now')*1000),
(7, '리본', 'ribbon', strftime('%s','now')*1000),
(7, '마늘', 'garlic', strftime('%s','now')*1000),
(7, '마라톤', 'marathon', strftime('%s','now')*1000),
(7, '마사지', 'massage', strftime('%s','now')*1000),
(7, '마우스', 'mouse', strftime('%s','now')*1000),
(7, '마음대로', 'as one pleases', strftime('%s','now')*1000),
(7, '마음씨', 'disposition / nature', strftime('%s','now')*1000),
(7, '마이크', 'microphone', strftime('%s','now')*1000),
(7, '마침', 'just / exactly / finally', strftime('%s','now')*1000),
(7, '막', 'just / randomly / film', strftime('%s','now')*1000),
(7, '막내', 'youngest child', strftime('%s','now')*1000),
(7, '막다', 'block / stop', strftime('%s','now')*1000),
(7, '막대기', 'stick / rod', strftime('%s','now')*1000),
(7, '막차', 'last train / last bus', strftime('%s','now')*1000),
(7, '만', 'only / just / ten thousand', strftime('%s','now')*1000),
(7, '만남', 'meeting / encounter', strftime('%s','now')*1000),
(7, '만족', 'satisfaction', strftime('%s','now')*1000),
(7, '만족스럽다', 'satisfying / satisfactory', strftime('%s','now')*1000),
(7, '많아지다', 'increase / grow in number', strftime('%s','now')*1000),
(7, '말다', 'stop doing / roll up', strftime('%s','now')*1000),
(7, '말리다', 'dry / dissuade', strftime('%s','now')*1000),
(7, '말하기', 'speaking', strftime('%s','now')*1000),
(7, '맞다', 'fit / be right / get hit', strftime('%s','now')*1000),
(7, '맞은편', 'opposite side', strftime('%s','now')*1000),
(7, '맞이하다', 'greet / welcome', strftime('%s','now')*1000),
(7, '맡기다', 'entrust / leave with', strftime('%s','now')*1000),
(7, '맡다', 'take charge / be responsible for', strftime('%s','now')*1000),
(7, '매', 'every / hawk / counter for times', strftime('%s','now')*1000),
(7, '매달다', 'hang / suspend', strftime('%s','now')*1000),
(7, '매운맛', 'spicy taste', strftime('%s','now')*1000),
(7, '매운탕', 'spicy fish stew', strftime('%s','now')*1000),
(7, '매장', 'store / burial', strftime('%s','now')*1000),
(7, '매점', 'snack bar / school shop', strftime('%s','now')*1000),
(7, '매진', 'sellout / be sold out', strftime('%s','now')*1000),
(7, '맨발', 'bare feet', strftime('%s','now')*1000),
(7, '먼지', 'dust', strftime('%s','now')*1000),
(7, '멀미', 'motion sickness', strftime('%s','now')*1000),
(7, '멋지다', 'cool / stylish', strftime('%s','now')*1000),
(7, '멍', 'bruise', strftime('%s','now')*1000),
(7, '메뉴판', 'menu board', strftime('%s','now')*1000),
(7, '메모지', 'notepad', strftime('%s','now')*1000),
(7, '멜로디', 'melody', strftime('%s','now')*1000),
(7, '면', 'noodles / cotton / face', strftime('%s','now')*1000),
(7, '면적', 'area / surface', strftime('%s','now')*1000),
(7, '면접', 'interview', strftime('%s','now')*1000),
(7, '면허증', 'license card', strftime('%s','now')*1000),
(7, '멸치', 'anchovy', strftime('%s','now')*1000),
(7, '명단', 'list of names', strftime('%s','now')*1000),
(7, '명함', 'business card', strftime('%s','now')*1000),
(7, '몇몇', 'several / a few', strftime('%s','now')*1000),
(7, '모니터', 'monitor', strftime('%s','now')*1000),
(7, '모델', 'model', strftime('%s','now')*1000),
(7, '모래', 'sand', strftime('%s','now')*1000),
(7, '모범', 'exemplary / model', strftime('%s','now')*1000),
(7, '모자', 'hat / cap', strftime('%s','now')*1000),
(7, '모집', 'recruitment', strftime('%s','now')*1000),
(7, '목', 'neck / throat', strftime('%s','now')*1000),
(7, '목록', 'list / catalog', strftime('%s','now')*1000),
(7, '목적지', 'destination', strftime('%s','now')*1000),
(7, '목표', 'goal / target', strftime('%s','now')*1000),
(7, '몰래', 'secretly / quietly', strftime('%s','now')*1000),
(7, '몸무게', 'body weight', strftime('%s','now')*1000),
(7, '몸살', 'fatigue / body ache', strftime('%s','now')*1000),
(7, '몸짓', 'gesture', strftime('%s','now')*1000),
(7, '묘사', 'description / portrayal', strftime('%s','now')*1000),
(7, '무늬', 'pattern / design', strftime('%s','now')*1000),
(7, '무대', 'stage', strftime('%s','now')*1000),
(7, '무더위', 'sweltering heat', strftime('%s','now')*1000),
(7, '무덤', 'grave / tomb', strftime('%s','now')*1000),
(7, '무서워하다', 'be afraid of', strftime('%s','now')*1000),
(7, '무역', 'trade', strftime('%s','now')*1000),
(7, '무용', 'dance', strftime('%s','now')*1000),
(7, '무조건', 'unconditionally / absolutely', strftime('%s','now')*1000),
(7, '묵다', 'stay / lodge', strftime('%s','now')*1000),
(7, '묶다', 'tie / bind', strftime('%s','now')*1000),
(7, '문구점', 'stationery store', strftime('%s','now')*1000),
(7, '문방구', 'stationery store', strftime('%s','now')*1000),
(7, '문법', 'grammar', strftime('%s','now')*1000),
(7, '문병', 'visit a patient', strftime('%s','now')*1000),
(7, '문의', 'inquiry / question', strftime('%s','now')*1000),
(7, '문자', 'text message / letter', strftime('%s','now')*1000),
(7, '문장', 'sentence', strftime('%s','now')*1000),
(7, '문학', 'literature', strftime('%s','now')*1000),
(7, '문화재', 'cultural asset', strftime('%s','now')*1000),
(7, '묻다', 'ask / bury', strftime('%s','now')*1000),
(7, '물', 'water', strftime('%s','now')*1000),
(7, '물가', 'price level / waterfront', strftime('%s','now')*1000),
(7, '물다', 'bite', strftime('%s','now')*1000),
(7, '물러나다', 'retreat / resign', strftime('%s','now')*1000),
(7, '물러서다', 'step back / retreat', strftime('%s','now')*1000),
(7, '물리다', 'be bitten / fed up', strftime('%s','now')*1000),
(7, '물소리', 'sound of water', strftime('%s','now')*1000),
(7, '물약', 'liquid medicine', strftime('%s','now')*1000),
(7, '물음', 'question / inquiry', strftime('%s','now')*1000),
(7, '뮤지컬', 'musical', strftime('%s','now')*1000),
(7, '미국인', 'American (person)', strftime('%s','now')*1000),
(7, '미끄럽다', 'slippery', strftime('%s','now')*1000),
(7, '미루다', 'postpone / delay', strftime('%s','now')*1000),
(7, '미만', 'under / below', strftime('%s','now')*1000),
(7, '미성년자', 'minor / underage person', strftime('%s','now')*1000),
(7, '미소', 'smile', strftime('%s','now')*1000),
(7, '미술', 'art / fine arts', strftime('%s','now')*1000),
(7, '미용사', 'hairdresser / beautician', strftime('%s','now')*1000),
(7, '미인', 'beautiful person', strftime('%s','now')*1000),
(7, '미장원', 'beauty salon', strftime('%s','now')*1000),
(7, '미팅', 'meeting / blind date', strftime('%s','now')*1000),
(7, '민속놀이', 'folk game', strftime('%s','now')*1000),
(7, '밀리다', 'be delayed / piled up', strftime('%s','now')*1000),
(7, '밉다', 'ugly / hateful', strftime('%s','now')*1000),
(7, '및', 'and / as well as', strftime('%s','now')*1000),
(7, '밑줄', 'underline', strftime('%s','now')*1000),
(7, '바', 'bar / thing / way', strftime('%s','now')*1000),
(7, '바구니', 'basket', strftime('%s','now')*1000),
(7, '바늘', 'needle', strftime('%s','now')*1000),
(7, '바닷물', 'sea water', strftime('%s','now')*1000),
(7, '바둑', 'go (board game)', strftime('%s','now')*1000),
(7, '바보', 'fool / idiot', strftime('%s','now')*1000),
(7, '바위', 'rock / boulder', strftime('%s','now')*1000),
(7, '바퀴', 'wheel / insect', strftime('%s','now')*1000),
(7, '바탕', 'basis / background', strftime('%s','now')*1000),
(7, '박', 'gourd / surname Park', strftime('%s','now')*1000),
(7, '박사', 'doctor / PhD', strftime('%s','now')*1000),
(7, '반납', 'return', strftime('%s','now')*1000),
(7, '반달', 'half moon', strftime('%s','now')*1000),
(7, '반대말', 'antonym', strftime('%s','now')*1000),
(7, '반대쪽', 'opposite side', strftime('%s','now')*1000),
(7, '반말', 'informal speech', strftime('%s','now')*1000),
(7, '반면', 'on the other hand', strftime('%s','now')*1000),
(7, '반복', 'repetition', strftime('%s','now')*1000),
(7, '반죽', 'dough / mixture', strftime('%s','now')*1000),
(7, '반창고', 'band-aid / plaster', strftime('%s','now')*1000),
(7, '반팔', 'short sleeves', strftime('%s','now')*1000),
(7, '반하다', 'fall in love / be charmed', strftime('%s','now')*1000),
(7, '발급', 'issue / issuance', strftime('%s','now')*1000),
(7, '발달', 'development / growth', strftime('%s','now')*1000),
(7, '발명', 'invention', strftime('%s','now')*1000),
(7, '발목', 'ankle', strftime('%s','now')*1000),
(7, '발음', 'pronunciation', strftime('%s','now')*1000),
(7, '발전', 'development / progress', strftime('%s','now')*1000),
(7, '발표', 'presentation / announcement', strftime('%s','now')*1000),
(7, '발행', 'publication / issue', strftime('%s','now')*1000),
(7, '밝히다', 'reveal / brighten', strftime('%s','now')*1000),
(7, '밟다', 'step on / tread', strftime('%s','now')*1000),
(7, '밤', 'night / chestnut', strftime('%s','now')*1000),
(7, '밤늦다', 'late at night', strftime('%s','now')*1000),
(7, '밤새', 'all night long', strftime('%s','now')*1000),
(7, '밤색', 'brown color', strftime('%s','now')*1000),
(7, '밥그릇', 'rice bowl', strftime('%s','now')*1000),
(7, '밥솥', 'rice cooker', strftime('%s','now')*1000),
(7, '방송사', 'broadcasting company', strftime('%s','now')*1000),
(7, '방식', 'method / style', strftime('%s','now')*1000),
(7, '방울', 'drop / small ball', strftime('%s','now')*1000),
(7, '방해', 'disturbance / obstruction', strftime('%s','now')*1000),
(7, '배고프다', 'be hungry', strftime('%s','now')*1000),
(7, '배구', 'volleyball', strftime('%s','now')*1000),
(7, '배낭', 'backpack', strftime('%s','now')*1000),
(7, '배낭여행', 'backpacking trip', strftime('%s','now')*1000),
(7, '배웅', 'see off / escort', strftime('%s','now')*1000),
(7, '배치', 'arrangement / placement', strftime('%s','now')*1000),
(7, '배터리', 'battery', strftime('%s','now')*1000),
(7, '배편', 'by ship / sea mail', strftime('%s','now')*1000),
(7, '백', 'hundred / white / background', strftime('%s','now')*1000),
(7, '뱃속', 'inside the stomach', strftime('%s','now')*1000),
(7, '버섯', 'mushroom', strftime('%s','now')*1000),
(7, '버터', 'butter', strftime('%s','now')*1000),
(7, '버튼', 'button', strftime('%s','now')*1000),
(7, '번개', 'lightning', strftime('%s','now')*1000),
(7, '번역', 'translation', strftime('%s','now')*1000),
(7, '번지', 'lot number / address number', strftime('%s','now')*1000),
(7, '번호표', 'number ticket', strftime('%s','now')*1000),
(7, '벌', 'bee / punishment', strftime('%s','now')*1000),
(7, '벌금', 'fine / penalty', strftime('%s','now')*1000),
(7, '범죄', 'crime', strftime('%s','now')*1000),
(7, '법', 'law', strftime('%s','now')*1000),
(7, '법칙', 'rule / law', strftime('%s','now')*1000),
(7, '벗기다', 'peel off / strip', strftime('%s','now')*1000),
(7, '베란다', 'balcony / veranda', strftime('%s','now')*1000),
(7, '벤치', 'bench', strftime('%s','now')*1000),
(7, '벨', 'bell', strftime('%s','now')*1000),
(7, '벨트', 'belt', strftime('%s','now')*1000),
(7, '벽시계', 'wall clock', strftime('%s','now')*1000),
(7, '벽지', 'wallpaper', strftime('%s','now')*1000),
(7, '변경', 'change / modification', strftime('%s','now')*1000),
(7, '변비', 'constipation', strftime('%s','now')*1000),
(7, '변화', 'change / transformation', strftime('%s','now')*1000),
(7, '별', 'star / special', strftime('%s','now')*1000),
(7, '별말씀', 'no need for thanks', strftime('%s','now')*1000),
(7, '별명', 'nickname', strftime('%s','now')*1000),
(7, '별일', 'particular thing / matter', strftime('%s','now')*1000),
(7, '병실', 'hospital room', strftime('%s','now')*1000),
(7, '보고', 'report', strftime('%s','now')*1000),
(7, '보고서', 'written report', strftime('%s','now')*1000),
(7, '보관', 'storage / keeping', strftime('%s','now')*1000),
(7, '보기', 'example / instance', strftime('%s','now')*1000),
(7, '보너스', 'bonus', strftime('%s','now')*1000),
(7, '보람', 'worth / reward', strftime('%s','now')*1000),
(7, '보름', 'fifteen days', strftime('%s','now')*1000),
(7, '보름달', 'full moon', strftime('%s','now')*1000),
(7, '보리', 'barley', strftime('%s','now')*1000),
(7, '보석', 'jewel / gem', strftime('%s','now')*1000),
(7, '보행자', 'pedestrian', strftime('%s','now')*1000),
(7, '보험', 'insurance', strftime('%s','now')*1000),
(7, '보호', 'protection / care', strftime('%s','now')*1000),
(7, '복', 'luck / blessing', strftime('%s','now')*1000),
(7, '복도', 'corridor / hallway', strftime('%s','now')*1000),
(7, '복사', 'copy / duplication', strftime('%s','now')*1000),
(7, '복사기', 'copy machine', strftime('%s','now')*1000),
(7, '복숭아', 'peach', strftime('%s','now')*1000),
(7, '복용', 'dosage / taking medicine', strftime('%s','now')*1000),
(7, '복통', 'stomachache', strftime('%s','now')*1000),
(7, '본인', 'oneself / the person concerned', strftime('%s','now')*1000),
(7, '볼거리', 'sight to see / attraction', strftime('%s','now')*1000),
(7, '볼링', 'bowling', strftime('%s','now')*1000),
(7, '볼일', 'business / things to do', strftime('%s','now')*1000),
(7, '봉사', 'service / volunteer work', strftime('%s','now')*1000),
(7, '봉지', 'bag / packet', strftime('%s','now')*1000),
(7, '뵈다', 'see (honorific)', strftime('%s','now')*1000),
(7, '부', 'department / part / wealth', strftime('%s','now')*1000),
(7, '부담', 'burden / pressure', strftime('%s','now')*1000),
(7, '부동산', 'real estate', strftime('%s','now')*1000),
(7, '부러워하다', 'envy / admire', strftime('%s','now')*1000),
(7, '부러지다', 'be broken / snapped', strftime('%s','now')*1000),
(7, '부리다', 'handle / display (emotion)', strftime('%s','now')*1000),
(7, '부모', 'parents', strftime('%s','now')*1000),
(7, '부인', 'wife / deny', strftime('%s','now')*1000),
(7, '부자', 'rich person / father and son', strftime('%s','now')*1000),
(7, '부잣집', 'rich family', strftime('%s','now')*1000),
(7, '부채', 'fan / debt', strftime('%s','now')*1000),
(7, '부츠', 'boots', strftime('%s','now')*1000),
(7, '부친', 'father', strftime('%s','now')*1000),
(7, '북', 'drum / north', strftime('%s','now')*1000),
(7, '북부', 'northern region', strftime('%s','now')*1000),
(7, '분단', 'division / separation', strftime('%s','now')*1000),
(7, '분리', 'separation / division', strftime('%s','now')*1000),
(7, '분명히', 'clearly / definitely', strftime('%s','now')*1000),
(7, '분실', 'loss (of something)', strftime('%s','now')*1000),
(7, '분실물', 'lost item', strftime('%s','now')*1000),
(7, '분필', 'chalk', strftime('%s','now')*1000),
(7, '불', 'fire / not-', strftime('%s','now')*1000),
(7, '불규칙', 'irregularity', strftime('%s','now')*1000),
(7, '불균형', 'imbalance', strftime('%s','now')*1000),
(7, '불만', 'dissatisfaction / complaint', strftime('%s','now')*1000),
(7, '불만족', 'discontent / dissatisfaction', strftime('%s','now')*1000),
(7, '불만족스럽다', 'unsatisfactory', strftime('%s','now')*1000),
(7, '불어', 'French language', strftime('%s','now')*1000),
(7, '불완전', 'incomplete / imperfect', strftime('%s','now')*1000),
(7, '불평', 'complaint / grievance', strftime('%s','now')*1000),
(7, '붐비다', 'be crowded', strftime('%s','now')*1000),
(7, '붓다', 'swell / pour', strftime('%s','now')*1000),
(7, '뷔페', 'buffet', strftime('%s','now')*1000),
(7, '비', 'rain / ratio / fee', strftime('%s','now')*1000),
(7, '비밀번호', 'password', strftime('%s','now')*1000),
(7, '비비다', 'rub / mix', strftime('%s','now')*1000),
(7, '비상구', 'emergency exit', strftime('%s','now')*1000),
(7, '비용', 'cost / expense', strftime('%s','now')*1000),
(7, '비자', 'visa', strftime('%s','now')*1000),
(7, '비키다', 'step aside / move away', strftime('%s','now')*1000),
(7, '비타민', 'vitamin', strftime('%s','now')*1000),
(7, '비하다', 'compare with', strftime('%s','now')*1000),
(7, '비행', 'flight / aviation', strftime('%s','now')*1000),
(7, '비행장', 'airfield / airport', strftime('%s','now')*1000),
(7, '빈자리', 'empty seat / vacancy', strftime('%s','now')*1000),
(7, '빌다', 'wish / pray', strftime('%s','now')*1000),
(7, '빗다', 'comb hair', strftime('%s','now')*1000),
(7, '빛', 'light / color / glow', strftime('%s','now')*1000),
(7, '빠지다', 'fall / sink / be absent', strftime('%s','now')*1000),
(7, '빨강', 'red color', strftime('%s','now')*1000),
(7, '빨개지다', 'turn red / blush', strftime('%s','now')*1000),
(7, '빨다', 'wash / suck', strftime('%s','now')*1000),
(7, '뺏다', 'take away / deprive', strftime('%s','now')*1000),
(7, '뼈', 'bone', strftime('%s','now')*1000),
(7, '뽀뽀', 'kiss (childish)', strftime('%s','now')*1000),
(7, '뿌리', 'root / origin', strftime('%s','now')*1000),
(7, '뿌리다', 'sprinkle / scatter', strftime('%s','now')*1000),
(7, '삐다', 'sprain / twist', strftime('%s','now')*1000),
(7, '사건', 'incident / case', strftime('%s','now')*1000),
(7, '사과', 'apple / apology', strftime('%s','now')*1000),
(7, '사교적', 'sociable', strftime('%s','now')*1000),
(7, '사나이', 'man / guy', strftime('%s','now')*1000),
(7, '사라지다', 'disappear / vanish', strftime('%s','now')*1000),
(7, '사무', 'office work', strftime('%s','now')*1000),
(7, '사무소', 'office', strftime('%s','now')*1000),
(7, '사물', 'thing / object', strftime('%s','now')*1000),
(7, '사생활', 'private life', strftime('%s','now')*1000),
(7, '사업가', 'businessperson', strftime('%s','now')*1000),
(7, '사용법', 'how to use / instructions', strftime('%s','now')*1000),
(7, '사우나', 'sauna', strftime('%s','now')*1000),
(7, '사이트', 'website', strftime('%s','now')*1000),
(7, '사인', 'signature / autograph', strftime('%s','now')*1000),
(7, '사자', 'lion / messenger', strftime('%s','now')*1000),
(7, '사적', 'personal / private', strftime('%s','now')*1000);