PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(12, '날리다01', 'to fly, to make something fly', strftime('%s','now')*1000),
(12, '날리다02', 'to become famous, to be spread widely', strftime('%s','now')*1000),
(12, '날아다니다', 'to fly around', strftime('%s','now')*1000),
(12, '날아오다', 'to fly towards, to come flying', strftime('%s','now')*1000),
(12, '날카롭다', 'sharp, keen, acute', strftime('%s','now')*1000),
(12, '남매', 'brother and sister', strftime('%s','now')*1000),
(12, '남북', 'South and North (Korea)', strftime('%s','now')*1000),
(12, '낭비', 'waste, extravagance', strftime('%s','now')*1000),
(12, '낮추다', 'to lower, to reduce', strftime('%s','now')*1000),
(12, '내놓다', 'to put out, to offer, to release', strftime('%s','now')*1000),
(12, '내다보다', 'to look out, to foresee', strftime('%s','now')*1000),
(12, '내려다보다', 'to look down at', strftime('%s','now')*1000),
(12, '내려앉다', 'to settle down, to collapse', strftime('%s','now')*1000),
(12, '내밀다', 'to stick out, to extend, to push forward', strftime('%s','now')*1000),
(12, '내버리다', 'to leave alone, to abandon', strftime('%s','now')*1000),
(12, '내부', 'inside, interior', strftime('%s','now')*1000),
(12, '내세우다', 'to assert, to put forward', strftime('%s','now')*1000),
(12, '내외01', 'husband and wife, couple', strftime('%s','now')*1000),
(12, '내쫓다', 'to expel, to drive out', strftime('%s','now')*1000),
(12, '냉수', 'cold water', strftime('%s','now')*1000),
(12, '너그럽다', 'generous, broad-minded', strftime('%s','now')*1000),
(12, '너머', 'beyond, on the other side', strftime('%s','now')*1000),
(12, '너무나', 'too much, very, extremely', strftime('%s','now')*1000),
(12, '넉넉하다', 'plenty, sufficient, generous', strftime('%s','now')*1000),
(12, '넓어지다', 'to become wide, to expand', strftime('%s','now')*1000),
(12, '넓히다', 'to widen, to broaden', strftime('%s','now')*1000),
(12, '넘겨주다', 'to hand over, to transfer', strftime('%s','now')*1000),
(12, '넘기다', 'to pass, to skip, to hand over', strftime('%s','now')*1000),
(12, '넘어뜨리다', 'to knock down, to overthrow', strftime('%s','now')*1000),
(12, '넘어오다', 'to cross over, to come across', strftime('%s','now')*1000),
(12, '넘치다', 'to overflow, to spill over', strftime('%s','now')*1000),
(12, '네모', 'square (shape)', strftime('%s','now')*1000),
(12, '네티즌', 'netizen, internet user', strftime('%s','now')*1000),
(12, '녀석', 'fellow, guy, brat', strftime('%s','now')*1000),
(12, '년도', 'year (counter)', strftime('%s','now')*1000),
(12, '노동', 'labor, work', strftime('%s','now')*1000),
(12, '노동자', 'laborer, worker', strftime('%s','now')*1000),
(12, '노려보다', 'to glare at, to stare fiercely', strftime('%s','now')*1000),
(12, '녹이다', 'to melt, to thaw, to dissolve', strftime('%s','now')*1000),
(12, '녹화02', 'video recording', strftime('%s','now')*1000),
(12, '논리', 'logic, reasoning', strftime('%s','now')*1000),
(12, '논리적01∙논리적02', 'logical, reasonable', strftime('%s','now')*1000),
(12, '논의', 'discussion, debate', strftime('%s','now')*1000),
(12, '논쟁', 'argument, dispute', strftime('%s','now')*1000),
(12, '놀랍다', 'surprising, astonishing', strftime('%s','now')*1000),
(12, '놀리다01', 'to tease, to make fun of', strftime('%s','now')*1000),
(12, '놀리다02', 'to use skillfully, to handle', strftime('%s','now')*1000),
(12, '농민', 'farmer, peasant', strftime('%s','now')*1000),
(12, '농사일', 'farming work', strftime('%s','now')*1000),
(12, '농산물', 'agricultural product', strftime('%s','now')*1000),
(12, '농업', 'agriculture', strftime('%s','now')*1000),
(12, '농촌', 'farm village, rural area', strftime('%s','now')*1000),
(12, '놓아두다', 'to put down, to leave behind', strftime('%s','now')*1000),
(12, '놔두다', 'to leave alone, to let be', strftime('%s','now')*1000),
(12, '뇌', 'brain', strftime('%s','now')*1000),
(12, '누님', 'elder sister (honorific)', strftime('%s','now')*1000),
(12, '눈감다', 'to close eyes, to die', strftime('%s','now')*1000),
(12, '눈길01', 'glance, gaze', strftime('%s','now')*1000),
(12, '눈동자', 'pupil (of the eye)', strftime('%s','now')*1000),
(12, '눈뜨다', 'to open one’s eyes, to awaken', strftime('%s','now')*1000),
(12, '눈빛01', 'look in one’s eyes, expression', strftime('%s','now')*1000),
(12, '눈썹', 'eyebrow', strftime('%s','now')*1000),
(12, '눈앞', 'in front of one’s eyes', strftime('%s','now')*1000),
(12, '눈치', 'tact, sense, intuition', strftime('%s','now')*1000),
(12, '눕히다', 'to lay down, to put someone to bed', strftime('%s','now')*1000),
(12, '느긋하다', 'relaxed, easygoing', strftime('%s','now')*1000),
(12, '느끼하다', 'greasy, rich, cheesy (feeling)', strftime('%s','now')*1000),
(12, '늘어놓다', 'to spread out, to lay out', strftime('%s','now')*1000),
(12, '늘어서다', 'to stand in a line, to line up', strftime('%s','now')*1000),
(12, '늘이다01', 'to stretch, to lengthen', strftime('%s','now')*1000),
(12, '늦가을', 'late autumn', strftime('%s','now')*1000),
(12, '늦겨울', 'late winter', strftime('%s','now')*1000),
(12, '늦봄', 'late spring', strftime('%s','now')*1000),
(12, '늦어지다', 'to be delayed, to be late', strftime('%s','now')*1000),
(12, '늦여름', 'late summer', strftime('%s','now')*1000),
(12, '늦추다', 'to delay, to postpone, to slow down', strftime('%s','now')*1000),
(12, '님', 'sir, dear (honorific suffix)', strftime('%s','now')*1000),
(12, '다가가다', 'to approach, to go near', strftime('%s','now')*1000),
(12, '다가서다', 'to step closer, to come near', strftime('%s','now')*1000),
(12, '다가오다', 'to approach, to draw near', strftime('%s','now')*1000),
(12, '다녀가다', 'to stop by, to visit and leave', strftime('%s','now')*1000),
(12, '다듬다', 'to trim, to refine, to polish', strftime('%s','now')*1000),
(12, '다루다', 'to handle, to deal with', strftime('%s','now')*1000),
(12, '다름없다', 'to be no different, same as', strftime('%s','now')*1000),
(12, '다리다', 'to iron (clothes)', strftime('%s','now')*1000),
(12, '다만', 'only, merely, just', strftime('%s','now')*1000),
(12, '다물다', 'to close (mouth, lips)', strftime('%s','now')*1000),
(12, '다소02/다소01', 'somewhat, more or less', strftime('%s','now')*1000),
(12, '다수', 'majority, a large number', strftime('%s','now')*1000),
(12, '다짐', 'resolution, pledge', strftime('%s','now')*1000),
(12, '다투다', 'to argue, to compete', strftime('%s','now')*1000),
(12, '다행스럽다', 'fortunate, lucky', strftime('%s','now')*1000),
(12, '단04', 'section, paragraph, stage', strftime('%s','now')*1000),
(12, '단계', 'step, phase, stage', strftime('%s','now')*1000),
(12, '단골', 'regular customer', strftime('%s','now')*1000),
(12, '단기01', 'short term', strftime('%s','now')*1000),
(12, '단독', 'independent, exclusive', strftime('%s','now')*1000),
(12, '단속', 'crackdown, control, supervision', strftime('%s','now')*1000),
(12, '단순히', 'simply, merely', strftime('%s','now')*1000),
(12, '단지02', 'only, merely', strftime('%s','now')*1000),
(12, '달래다', 'to soothe, to comfort', strftime('%s','now')*1000),
(12, '달려가다', 'to run toward', strftime('%s','now')*1000),
(12, '달려들다', 'to rush at, to attack', strftime('%s','now')*1000),
(12, '달려오다', 'to run up, to run toward', strftime('%s','now')*1000),
(12, '달리', 'differently, otherwise', strftime('%s','now')*1000),
(12, '달리다01', 'to run, to hang, to be attached', strftime('%s','now')*1000),
(12, '달빛', 'moonlight', strftime('%s','now')*1000),
(12, '달성', 'achievement, accomplishment', strftime('%s','now')*1000),
(12, '달아나다', 'to flee, to escape', strftime('%s','now')*1000),
(12, '달하다', 'to reach, to amount to', strftime('%s','now')*1000),
(12, '닳다', 'to wear out, to be worn', strftime('%s','now')*1000),
(12, '담01', 'wall, fence', strftime('%s','now')*1000),
(12, '담02', 'bile, gall', strftime('%s','now')*1000),
(12, '담당', 'charge, responsibility', strftime('%s','now')*1000),
(12, '담당자', 'person in charge', strftime('%s','now')*1000),
(12, '담백하다', 'plain, light, honest', strftime('%s','now')*1000),
(12, '담요', 'blanket', strftime('%s','now')*1000),
(12, '담임', 'homeroom teacher', strftime('%s','now')*1000),
(12, '답변', 'answer, reply', strftime('%s','now')*1000),
(12, '-당', 'party, group (suffix)', strftime('%s','now')*1000),
(12, '당기다', 'to pull, to attract', strftime('%s','now')*1000),
(12, '당당하다', 'dignified, confident', strftime('%s','now')*1000),
(12, '당분간02/당분간01', 'for the time being, temporarily', strftime('%s','now')*1000),
(12, '당시', 'at that time, then', strftime('%s','now')*1000),
(12, '당일', 'the same day', strftime('%s','now')*1000),
(12, '당첨', 'winning, being selected', strftime('%s','now')*1000),
(12, '당하다', 'to suffer, to experience', strftime('%s','now')*1000),
(12, '대-', 'great, large (prefix)', strftime('%s','now')*1000),
(12, '대가02', 'price, cost, master', strftime('%s','now')*1000),
(12, '대강02/대강01', 'roughly, approximately', strftime('%s','now')*1000),
(12, '대개02/대개01', 'mostly, generally', strftime('%s','now')*1000),
(12, '대규모', 'large-scale, massive', strftime('%s','now')*1000),
(12, '대기01', 'atmosphere, air', strftime('%s','now')*1000),
(12, '대기02', 'waiting', strftime('%s','now')*1000),
(12, '대기업', 'large company, conglomerate', strftime('%s','now')*1000),
(12, '대낮', 'broad daylight', strftime('%s','now')*1000),
(12, '대다수', 'majority, most', strftime('%s','now')*1000),
(12, '대단히', 'greatly, very much', strftime('%s','now')*1000),
(12, '대략02/대략01', 'approximately, roughly', strftime('%s','now')*1000),
(12, '대량', 'large quantity, bulk', strftime('%s','now')*1000),
(12, '대로02', 'as, according to', strftime('%s','now')*1000),
(12, '대리', 'proxy, acting for someone', strftime('%s','now')*1000),
(12, '대립', 'confrontation, opposition', strftime('%s','now')*1000),
(12, '대비01', 'contrast, comparison', strftime('%s','now')*1000),
(12, '대비02', 'preparation', strftime('%s','now')*1000),
(12, '대사02', 'ambassador', strftime('%s','now')*1000),
(12, '대사03', 'dialogue, lines (in play/movie)', strftime('%s','now')*1000),
(12, '대상자', 'subject, candidate, target person', strftime('%s','now')*1000),
(12, '대응', 'response, reaction, coping', strftime('%s','now')*1000),
(12, '대접02', 'treatment, reception', strftime('%s','now')*1000),
(12, '대조', 'contrast, comparison', strftime('%s','now')*1000),
(12, '대중문화', 'popular culture', strftime('%s','now')*1000),
(12, '대책', 'measure, countermeasure', strftime('%s','now')*1000),
(12, '대처02', 'handling, dealing with', strftime('%s','now')*1000),
(12, '대체02', 'replacement, substitution', strftime('%s','now')*1000),
(12, '대출', 'loan, lending', strftime('%s','now')*1000),
(12, '대충', 'roughly, approximately', strftime('%s','now')*1000),
(12, '댐', 'dam', strftime('%s','now')*1000),
(12, '더구나', 'moreover, besides', strftime('%s','now')*1000),
(12, '더럽히다', 'to make dirty, to soil', strftime('%s','now')*1000),
(12, '더불다', 'together with, along with', strftime('%s','now')*1000),
(12, '더욱더', 'even more', strftime('%s','now')*1000),
(12, '더욱이', 'what is more, moreover', strftime('%s','now')*1000),
(12, '더위', 'heat, hot weather', strftime('%s','now')*1000),
(12, '덕', 'virtue, kindness, favor', strftime('%s','now')*1000),
(12, '덕택', 'thanks to, due to', strftime('%s','now')*1000),
(12, '덧붙이다', 'to add, to attach', strftime('%s','now')*1000),
(12, '덩어리', 'lump, chunk, mass', strftime('%s','now')*1000),
(12, '덮이다', 'to be covered', strftime('%s','now')*1000),
(12, '데우다', 'to heat, to warm up', strftime('%s','now')*1000),
(12, '도난', 'theft, robbery', strftime('%s','now')*1000),
(12, '도대체', 'on earth, what the heck, at all', strftime('%s','now')*1000),
(12, '도로01', 'road, street', strftime('%s','now')*1000),
(12, '도리어', 'on the contrary, instead', strftime('%s','now')*1000),
(12, '도마', 'chopping board', strftime('%s','now')*1000),
(12, '도망', 'escape, flight', strftime('%s','now')*1000),
(12, '도망치다', 'to run away, to flee', strftime('%s','now')*1000),
(12, '도무지', 'not at all, by no means', strftime('%s','now')*1000),
(12, '도입', 'introduction, adoption', strftime('%s','now')*1000),
(12, '도저히', '(not) possibly, absolutely (not)', strftime('%s','now')*1000),
(12, '도전', 'challenge, defiance', strftime('%s','now')*1000),
(12, '독02', 'poison', strftime('%s','now')*1000),
(12, '독립', 'independence', strftime('%s','now')*1000),
(12, '독자03', 'reader', strftime('%s','now')*1000),
(12, '독특하다', 'unique, distinctive', strftime('%s','now')*1000),
(12, '독하다', 'strong, toxic, harsh', strftime('%s','now')*1000),
(12, '돌려보내다', 'to send back, to return', strftime('%s','now')*1000),
(12, '돌멩이', 'stone, pebble', strftime('%s','now')*1000),
(12, '돌아보다', 'to look back, to reflect', strftime('%s','now')*1000),
(12, '돌아서다', 'to turn around, to turn one’s back', strftime('%s','now')*1000),
(12, '동기02', 'motive, reason', strftime('%s','now')*1000),
(12, '동기03', 'colleague, classmate, peer', strftime('%s','now')*1000),
(12, '동남아', 'Southeast Asia', strftime('%s','now')*1000),
(12, '동서남북', 'east, west, south, and north', strftime('%s','now')*1000),
(12, '동양인', 'Asian person', strftime('%s','now')*1000),
(12, '동영상', 'video clip', strftime('%s','now')*1000),
(12, '동요02', 'children’s song, instability', strftime('%s','now')*1000),
(12, '동의01', 'agreement, consent', strftime('%s','now')*1000),
(12, '동일', 'same, identical', strftime('%s','now')*1000),
(12, '동포', 'compatriot, fellow countryman', strftime('%s','now')*1000),
(12, '동화02', 'fairy tale, assimilation', strftime('%s','now')*1000),
(12, '동화책', 'storybook, fairy-tale book', strftime('%s','now')*1000),
(12, '되게', 'very, extremely', strftime('%s','now')*1000),
(12, '되도록', 'as much as possible', strftime('%s','now')*1000),
(12, '되돌리다', 'to turn back, to return', strftime('%s','now')*1000),
(12, '되돌아가다', 'to go back, to return', strftime('%s','now')*1000),
(12, '되살리다', 'to revive, to restore', strftime('%s','now')*1000),
(12, '되살아나다', 'to come back to life, to revive', strftime('%s','now')*1000),
(12, '되풀이', 'repetition, recurrence', strftime('%s','now')*1000),
(12, '두뇌', 'brain, intellect', strftime('%s','now')*1000),
(12, '두드러지다01', 'prominent, outstanding', strftime('%s','now')*1000),
(12, '두드리다', 'to knock, to hit, to beat', strftime('%s','now')*1000),
(12, '두려움', 'fear, dread', strftime('%s','now')*1000),
(12, '두려워하다', 'to fear, to be afraid of', strftime('%s','now')*1000),
(12, '두렵다', 'fearful, scared', strftime('%s','now')*1000),
(12, '두르다', 'to wrap around, to put on', strftime('%s','now')*1000),
(12, '두리번거리다', 'to look around, to glance about', strftime('%s','now')*1000),
(12, '두어', 'a few, several', strftime('%s','now')*1000),
(12, '둘러보다', 'to look around', strftime('%s','now')*1000),
(12, '둘러싸다', 'to surround, to encircle', strftime('%s','now')*1000),
(12, '둘러싸이다', 'to be surrounded, to be encircled', strftime('%s','now')*1000),
(12, '둘레', 'circumference, surroundings', strftime('%s','now')*1000),
(12, '둥지', 'nest', strftime('%s','now')*1000),
(12, '뒤늦다', 'belated, late', strftime('%s','now')*1000),
(12, '뒤따르다', 'to follow, to come after', strftime('%s','now')*1000),
(12, '뒤떨어지다', 'to fall behind, to lag', strftime('%s','now')*1000),
(12, '뒤지다01', 'to search, to rummage', strftime('%s','now')*1000),
(12, '뒤지다02', 'to be beaten, to fall behind', strftime('%s','now')*1000),
(12, '뒤집다', 'to turn over, to reverse', strftime('%s','now')*1000),
(12, '뒤편', 'back side, rear', strftime('%s','now')*1000),
(12, '뒷골목', 'back alley', strftime('%s','now')*1000),
(12, '뒷모습', 'appearance from behind', strftime('%s','now')*1000),
(12, '뒷문', 'back door', strftime('%s','now')*1000),
(12, '뒷산', 'hill behind, back mountain', strftime('%s','now')*1000),
(12, '드나들다', 'to go in and out frequently', strftime('%s','now')*1000),
(12, '드라이클리닝', 'dry cleaning', strftime('%s','now')*1000),
(12, '드러나다', 'to be revealed, to appear', strftime('%s','now')*1000),
(12, '드러내다', 'to reveal, to expose', strftime('%s','now')*1000),
(12, '드물다', 'rare, uncommon', strftime('%s','now')*1000),
(12, '든든하다', 'reliable, reassuring', strftime('%s','now')*1000),
(12, '들려오다', 'to be heard, to come to one’s ear', strftime('%s','now')*1000),
(12, '들리다01', 'to be heard', strftime('%s','now')*1000),
(12, '들리다03', 'to drop in, to visit', strftime('%s','now')*1000),
(12, '들여다보다', 'to look into, to peer in', strftime('%s','now')*1000),
(12, '들이다', 'to let in, to admit', strftime('%s','now')*1000),
(12, '들키다', 'to get caught, to be discovered', strftime('%s','now')*1000),
(12, '등기', 'registration, certified mail', strftime('%s','now')*1000),
(12, '등장', 'appearance, emergence', strftime('%s','now')*1000),
(12, '디자이너', 'designer', strftime('%s','now')*1000),
(12, '따님', 'daughter (honorific)', strftime('%s','now')*1000),
(12, '따라다니다', 'to follow around', strftime('%s','now')*1000),
(12, '따르다02', 'to follow', strftime('%s','now')*1000),
(12, '따지다', 'to inquire into, to nitpick', strftime('%s','now')*1000),
(12, '딴02', 'other, different', strftime('%s','now')*1000),
(12, '땅바닥', 'ground, floor', strftime('%s','now')*1000),
(12, '땅콩', 'peanut', strftime('%s','now')*1000),
(12, '때02', 'time, occasion', strftime('%s','now')*1000),
(12, '때로', 'at times, sometimes', strftime('%s','now')*1000),
(12, '때리다', 'to hit, to strike', strftime('%s','now')*1000),
(12, '떠나오다', 'to leave and come (back)', strftime('%s','now')*1000),
(12, '떼01', 'group, crowd', strftime('%s','now')*1000),
(12, '떼다', 'to detach, to remove', strftime('%s','now')*1000),
(12, '또다시', 'again, once again', strftime('%s','now')*1000),
(12, '똥', 'feces', strftime('%s','now')*1000),
(12, '뚜껑', 'lid, cap', strftime('%s','now')*1000),
(12, '뚜렷하다', 'clear, distinct', strftime('%s','now')*1000),
(12, '뚫리다', 'to be pierced, to be opened', strftime('%s','now')*1000),
(12, '뛰어나오다', 'to run out', strftime('%s','now')*1000),
(12, '뛰어놀다', 'to romp, to frolic', strftime('%s','now')*1000),
(12, '뛰어다니다', 'to run around', strftime('%s','now')*1000),
(12, '뛰어들다', 'to jump into, to dash into', strftime('%s','now')*1000),
(12, '뜨다04', 'to float, to rise', strftime('%s','now')*1000),
(12, '뜯다', 'to tear, to rip', strftime('%s','now')*1000),
(12, '뜰01', 'yard, garden', strftime('%s','now')*1000),
(12, '뜻대로', 'as one wishes', strftime('%s','now')*1000),
(12, '뜻밖', 'unexpectedness', strftime('%s','now')*1000),
(12, '뜻밖에', 'unexpectedly', strftime('%s','now')*1000),
(12, '띄다01', 'to be seen, to catch the eye', strftime('%s','now')*1000),
(12, '띠01', 'belt, band', strftime('%s','now')*1000),
(12, '띠다', 'to have, to carry, to show', strftime('%s','now')*1000),
(12, '량01', 'quantity, amount', strftime('%s','now')*1000),
(12, '렌즈', 'lens', strftime('%s','now')*1000),
(12, '-력01', '-power, ability (suffix)', strftime('%s','now')*1000),
(12, '-료', 'fee, charge (suffix)', strftime('%s','now')*1000),
(12, '리모컨', 'remote control', strftime('%s','now')*1000),
(12, '리터', 'liter', strftime('%s','now')*1000),
(12, '마구', 'recklessly, wildly', strftime('%s','now')*1000),
(12, '마냥01', 'just, as it is, very', strftime('%s','now')*1000),
(12, '마디', 'joint, node, section', strftime('%s','now')*1000),
(12, '마땅하다', 'proper, suitable', strftime('%s','now')*1000),
(12, '마땅히', 'rightly, duly', strftime('%s','now')*1000),
(12, '마련01/마련02', 'arrangement, preparation', strftime('%s','now')*1000),
(12, '마루02', 'ridge (of a roof)', strftime('%s','now')*1000),
(12, '마무리', 'finishing, wrap-up', strftime('%s','now')*1000),
(12, '마약', 'narcotics, drug', strftime('%s','now')*1000),
(12, '마음가짐', 'mindset, attitude', strftime('%s','now')*1000),
(12, '마음껏', 'to one’s heart’s content, freely', strftime('%s','now')*1000),
(12, '마음먹다', 'to make up one’s mind, to decide', strftime('%s','now')*1000),
(12, '마음속', 'in one’s heart, in mind', strftime('%s','now')*1000),
(12, '마주', 'face to face, opposite', strftime('%s','now')*1000),
(12, '마주치다', 'to encounter, to meet, to bump into', strftime('%s','now')*1000),
(12, '마찬가지', 'the same, alike', strftime('%s','now')*1000),
(12, '마찰', 'friction, conflict', strftime('%s','now')*1000),
(12, '마치', 'as if, as though', strftime('%s','now')*1000),
(12, '마침내', 'finally, at last', strftime('%s','now')*1000),
(12, '막상', 'when it actually happens, really', strftime('%s','now')*1000),
(12, '막연하다', 'vague, obscure', strftime('%s','now')*1000),
(12, '만만하다01', 'easy, mild, not difficult', strftime('%s','now')*1000),
(12, '만원', 'ten thousand won, full (capacity)', strftime('%s','now')*1000),
(12, '만점', 'perfect score, full marks', strftime('%s','now')*1000),
(12, '말기', 'last stage, terminal stage', strftime('%s','now')*1000),
(12, '말끔히', 'neatly, cleanly', strftime('%s','now')*1000),
(12, '말다02', 'to stop doing, to give up', strftime('%s','now')*1000),
(12, '말다툼', 'argument, quarrel', strftime('%s','now')*1000),
(12, '말리다02', 'to stop someone, to dissuade', strftime('%s','now')*1000),
(12, '말없이', 'silently, without words', strftime('%s','now')*1000),
(12, '말투', 'tone of speech, manner of speaking', strftime('%s','now')*1000),
(12, '맘', 'mind, heart (informal)', strftime('%s','now')*1000),
(12, '맘껏', 'to one’s heart’s content', strftime('%s','now')*1000),
(12, '맘대로', 'as one pleases, freely', strftime('%s','now')*1000),
(12, '망가지다', 'to break down, to be ruined', strftime('%s','now')*1000),
(12, '망설이다', 'to hesitate, to be indecisive', strftime('%s','now')*1000),
(12, '망치다', 'to spoil, to ruin', strftime('%s','now')*1000),
(12, '망하다', 'to fail, to go bankrupt', strftime('%s','now')*1000),
(12, '맞벌이', 'dual-income family, both working', strftime('%s','now')*1000),
(12, '맞서다', 'to confront, to oppose', strftime('%s','now')*1000),
(12, '맞춤법', 'spelling, orthography', strftime('%s','now')*1000),
(12, '맞히다01', 'to guess right, to hit the mark', strftime('%s','now')*1000),
(12, '매달리다', 'to hang on, to cling to', strftime('%s','now')*1000),
(12, '매력', 'charm, attraction', strftime('%s','now')*1000),
(12, '매번02/매번01', 'every time', strftime('%s','now')*1000),
(12, '매체', 'medium, media', strftime('%s','now')*1000),
(12, '맨01', 'bare, pure, just', strftime('%s','now')*1000),
(12, '맺다', 'to tie, to form, to conclude', strftime('%s','now')*1000),
(12, '머리칼', 'hair', strftime('%s','now')*1000),
(12, '머릿속', 'in the head, in one’s mind', strftime('%s','now')*1000),
(12, '머무르다', 'to stay, to remain', strftime('%s','now')*1000),
(12, '머물다', 'to stay, to lodge', strftime('%s','now')*1000),
(12, '머뭇거리다', 'to hesitate, to waver', strftime('%s','now')*1000),
(12, '먹고살다', 'to make a living', strftime('%s','now')*1000),
(12, '먹이', 'feed, food (for animals)', strftime('%s','now')*1000),
(12, '먹이다', 'to feed (someone)', strftime('%s','now')*1000),
(12, '먹히다', 'to be eaten, to be effective', strftime('%s','now')*1000),
(12, '멀어지다', 'to become distant, to drift apart', strftime('%s','now')*1000),
(12, '멀쩡하다', 'fine, sound, unscathed', strftime('%s','now')*1000),
(12, '멋대로', 'as one likes, at will', strftime('%s','now')*1000),
(12, '멍멍', 'bow-wow, barking sound', strftime('%s','now')*1000),
(12, '멎다', 'to stop (rain, wind, sound)', strftime('%s','now')*1000),
(12, '메달', 'medal', strftime('%s','now')*1000),
(12, '메우다', 'to fill up, to cover', strftime('%s','now')*1000),
(12, '며느리', 'daughter-in-law', strftime('%s','now')*1000);