PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(2, '시키다', 'to order/make someone do', strftime('%s','now')*1000),
(2, '시험', 'exam/test', strftime('%s','now')*1000),
(2, '식당', 'restaurant', strftime('%s','now')*1000),
(2, '식사', 'meal', strftime('%s','now')*1000),
(2, '신다', 'to wear (shoes)', strftime('%s','now')*1000),
(2, '신문', 'newspaper', strftime('%s','now')*1000),
(2, '신발', 'shoes', strftime('%s','now')*1000),
(2, '실례', 'excuse me', strftime('%s','now')*1000),
(2, '싫다', 'to dislike', strftime('%s','now')*1000),
(2, '싫어하다', 'to hate/dislike', strftime('%s','now')*1000),
(2, '십', 'ten', strftime('%s','now')*1000),
(2, '십만', 'hundred thousand', strftime('%s','now')*1000),
(2, '십이월', 'December', strftime('%s','now')*1000),
(2, '십일월', 'November', strftime('%s','now')*1000),
(2, '싱겁다', 'to be bland', strftime('%s','now')*1000),
(2, '싸다', 'to be cheap', strftime('%s','now')*1000),
(2, '쓰다', 'to write/use', strftime('%s','now')*1000),
(2, '씨', 'Mr./Ms.', strftime('%s','now')*1000),
(2, '씻다', 'to wash', strftime('%s','now')*1000),
(2, '아', 'ah/oh', strftime('%s','now')*1000),
(2, '아기', 'baby', strftime('%s','now')*1000),
(2, '아내', 'wife', strftime('%s','now')*1000),
(2, '아니다', 'to not be', strftime('%s','now')*1000),
(2, '아니요', 'no', strftime('%s','now')*1000),
(2, '아래', 'below', strftime('%s','now')*1000),
(2, '아르바이트', 'part-time job', strftime('%s','now')*1000),
(2, '아름답다', 'to be beautiful', strftime('%s','now')*1000),
(2, '아버지', 'father', strftime('%s','now')*1000),
(2, '아이', 'child', strftime('%s','now')*1000),
(2, '아이스크림', 'ice cream', strftime('%s','now')*1000),
(2, '아저씨', 'mister', strftime('%s','now')*1000),
(2, '아주', 'very', strftime('%s','now')*1000),
(2, '아주머니', 'madam', strftime('%s','now')*1000),
(2, '아직', 'still/yet', strftime('%s','now')*1000),
(2, '아침', 'morning/breakfast', strftime('%s','now')*1000),
(2, '아파트', 'apartment', strftime('%s','now')*1000),
(2, '아프다', 'to be sick/hurt', strftime('%s','now')*1000),
(2, '아홉', 'nine', strftime('%s','now')*1000),
(2, '아흔', 'ninety', strftime('%s','now')*1000),
(2, '안', 'inside/not', strftime('%s','now')*1000),
(2, '안경', 'glasses', strftime('%s','now')*1000),
(2, '안내', 'information/guide', strftime('%s','now')*1000),
(2, '안녕', 'hello/peace', strftime('%s','now')*1000),
(2, '안녕히', 'peacefully', strftime('%s','now')*1000),
(2, '앉다', 'to sit', strftime('%s','now')*1000),
(2, '알다', 'to know', strftime('%s','now')*1000),
(2, '알리다', 'to inform', strftime('%s','now')*1000),
(2, '앞', 'front', strftime('%s','now')*1000),
(2, '야구', 'baseball', strftime('%s','now')*1000),
(2, '약', 'medicine/about', strftime('%s','now')*1000),
(2, '약국', 'pharmacy', strftime('%s','now')*1000),
(2, '약속', 'promise/appointment', strftime('%s','now')*1000),
(2, '어느', 'which', strftime('%s','now')*1000),
(2, '어디', 'where', strftime('%s','now')*1000),
(2, '어떤', 'what kind', strftime('%s','now')*1000),
(2, '어떻다', 'how', strftime('%s','now')*1000),
(2, '어렵다', 'to be difficult', strftime('%s','now')*1000),
(2, '어머니', 'mother', strftime('%s','now')*1000),
(2, '어서', 'quickly/please', strftime('%s','now')*1000),
(2, '어제', 'yesterday', strftime('%s','now')*1000),
(2, '언니', 'older sister (for female)', strftime('%s','now')*1000),
(2, '언제', 'when', strftime('%s','now')*1000),
(2, '얼굴', 'face', strftime('%s','now')*1000),
(2, '얼마', 'how much', strftime('%s','now')*1000),
(2, '얼마나', 'how much/how long', strftime('%s','now')*1000),
(2, '없다', 'to not exist', strftime('%s','now')*1000),
(2, '에어컨', 'air conditioner', strftime('%s','now')*1000),
(2, '여권', 'passport', strftime('%s','now')*1000),
(2, '여기', 'here', strftime('%s','now')*1000),
(2, '여덟', 'eight', strftime('%s','now')*1000),
(2, '여동생', 'younger sister', strftime('%s','now')*1000),
(2, '여든', 'eighty', strftime('%s','now')*1000),
(2, '여러', 'several/many', strftime('%s','now')*1000),
(2, '여러분', 'everyone', strftime('%s','now')*1000),
(2, '여름', 'summer', strftime('%s','now')*1000),
(2, '여보세요', 'hello (on phone)', strftime('%s','now')*1000),
(2, '여섯', 'six', strftime('%s','now')*1000),
(2, '여자', 'woman', strftime('%s','now')*1000),
(2, '여행', 'travel', strftime('%s','now')*1000),
(2, '여행사', 'travel agency', strftime('%s','now')*1000),
(2, '역', 'station', strftime('%s','now')*1000),
(2, '연극', 'play/theater', strftime('%s','now')*1000),
(2, '연습', 'practice', strftime('%s','now')*1000),
(2, '연필', 'pencil', strftime('%s','now')*1000),
(2, '열', 'ten/fever', strftime('%s','now')*1000),
(2, '열다', 'to open', strftime('%s','now')*1000),
(2, '열쇠', 'key', strftime('%s','now')*1000),
(2, '열심히', 'diligently', strftime('%s','now')*1000),
(2, '영', 'zero', strftime('%s','now')*1000),
(2, '영국', 'England', strftime('%s','now')*1000),
(2, '영어', 'English (language)', strftime('%s','now')*1000),
(2, '영화', 'movie', strftime('%s','now')*1000),
(2, '영화관', 'cinema', strftime('%s','now')*1000),
(2, '영화배우', 'movie actor', strftime('%s','now')*1000),
(2, '옆', 'beside/next to', strftime('%s','now')*1000),
(2, '예', 'yes/example', strftime('%s','now')*1000),
(2, '예쁘다', 'to be pretty', strftime('%s','now')*1000),
(2, '오', 'five', strftime('%s','now')*1000),
(2, '오늘', 'today', strftime('%s','now')*1000),
(2, '오다', 'to come', strftime('%s','now')*1000),
(2, '오렌지', 'orange', strftime('%s','now')*1000),
(2, '오른쪽', 'right side', strftime('%s','now')*1000),
(2, '오빠', 'older brother (for female)', strftime('%s','now')*1000),
(2, '오십', 'fifty', strftime('%s','now')*1000),
(2, '오월', 'May', strftime('%s','now')*1000),
(2, '오전', 'morning (a.m.)', strftime('%s','now')*1000),
(2, '오후', 'afternoon (p.m.)', strftime('%s','now')*1000),
(2, '올라가다', 'to go up', strftime('%s','now')*1000),
(2, '올해', 'this year', strftime('%s','now')*1000),
(2, '옷', 'clothes', strftime('%s','now')*1000),
(2, '와', 'and/wow', strftime('%s','now')*1000),
(2, '왜', 'why', strftime('%s','now')*1000),
(2, '외국', 'foreign country', strftime('%s','now')*1000),
(2, '외국어', 'foreign language', strftime('%s','now')*1000),
(2, '외국인', 'foreigner', strftime('%s','now')*1000),
(2, '왼쪽', 'left side', strftime('%s','now')*1000),
(2, '요리', 'cooking/dish', strftime('%s','now')*1000),
(2, '요일', 'day of the week', strftime('%s','now')*1000),
(2, '요즘', 'these days', strftime('%s','now')*1000),
(2, '우리', 'we/our', strftime('%s','now')*1000),
(2, '우산', 'umbrella', strftime('%s','now')*1000),
(2, '우유', 'milk', strftime('%s','now')*1000),
(2, '우체국', 'post office', strftime('%s','now')*1000),
(2, '우표', 'stamp', strftime('%s','now')*1000),
(2, '운동', 'exercise', strftime('%s','now')*1000),
(2, '운동장', 'schoolyard/playground', strftime('%s','now')*1000),
(2, '운동화', 'sneakers', strftime('%s','now')*1000),
(2, '운전', 'driving', strftime('%s','now')*1000),
(2, '울다', 'to cry', strftime('%s','now')*1000),
(2, '웃다', 'to laugh/smile', strftime('%s','now')*1000),
(2, '원', 'won (currency)', strftime('%s','now')*1000),
(2, '월', 'month', strftime('%s','now')*1000),
(2, '월요일', 'Monday', strftime('%s','now')*1000),
(2, '위', 'above/on', strftime('%s','now')*1000),
(2, '유명', 'famous', strftime('%s','now')*1000),
(2, '유월', 'June', strftime('%s','now')*1000),
(2, '육', 'six', strftime('%s','now')*1000),
(2, '육십', 'sixty', strftime('%s','now')*1000),
(2, '은행', 'bank', strftime('%s','now')*1000),
(2, '음', 'sound', strftime('%s','now')*1000),
(2, '음료수', 'beverage', strftime('%s','now')*1000),
(2, '음식', 'food', strftime('%s','now')*1000),
(2, '음악', 'music', strftime('%s','now')*1000),
(2, '의사', 'doctor', strftime('%s','now')*1000),
(2, '의자', 'chair', strftime('%s','now')*1000),
(2, '이', 'two/this', strftime('%s','now')*1000),
(2, '이것', 'this thing', strftime('%s','now')*1000),
(2, '이따가', 'later (soon)', strftime('%s','now')*1000),
(2, '이름', 'name', strftime('%s','now')*1000),
(2, '이번', 'this time', strftime('%s','now')*1000),
(2, '이십', 'twenty', strftime('%s','now')*1000),
(2, '이야기', 'story/talk', strftime('%s','now')*1000),
(2, '이월', 'February', strftime('%s','now')*1000),
(2, '이유', 'reason', strftime('%s','now')*1000),
(2, '이쪽', 'this side', strftime('%s','now')*1000),
(2, '인도네시아', 'Indonesia', strftime('%s','now')*1000),
(2, '인분', 'portion (food)', strftime('%s','now')*1000),
(2, '인사', 'greeting', strftime('%s','now')*1000),
(2, '인천', 'Incheon', strftime('%s','now')*1000),
(2, '인터넷', 'internet', strftime('%s','now')*1000),
(2, '일', 'day/work', strftime('%s','now')*1000),
(2, '일곱', 'seven', strftime('%s','now')*1000),
(2, '일본', 'Japan', strftime('%s','now')*1000),
(2, '일어나다', 'to get up', strftime('%s','now')*1000),
(2, '일요일', 'Sunday', strftime('%s','now')*1000),
(2, '일월', 'January', strftime('%s','now')*1000),
(2, '일주일', 'one week', strftime('%s','now')*1000),
(2, '일찍', 'early', strftime('%s','now')*1000),
(2, '일흔', 'seventy', strftime('%s','now')*1000),
(2, '읽다', 'to read', strftime('%s','now')*1000),
(2, '입', 'mouth', strftime('%s','now')*1000),
(2, '입다', 'to wear/put on', strftime('%s','now')*1000),
(2, '있다', 'to exist/have', strftime('%s','now')*1000),
(2, '자다', 'to sleep', strftime('%s','now')*1000),
(2, '자동차', 'car', strftime('%s','now')*1000),
(2, '자전거', 'bicycle', strftime('%s','now')*1000),
(2, '자주', 'often', strftime('%s','now')*1000),
(2, '작년', 'last year', strftime('%s','now')*1000),
(2, '작다', 'to be small', strftime('%s','now')*1000),
(2, '잔', 'cup/glass', strftime('%s','now')*1000),
(2, '잘', 'well', strftime('%s','now')*1000),
(2, '잘못', 'mistake', strftime('%s','now')*1000),
(2, '잘하다', 'to do well', strftime('%s','now')*1000),
(2, '잠', 'sleep', strftime('%s','now')*1000),
(2, '잠깐', 'a moment', strftime('%s','now')*1000),
(2, '잠시', 'a while', strftime('%s','now')*1000),
(2, '잡수시다', 'to eat (honorific)', strftime('%s','now')*1000),
(2, '잡채', 'japchae', strftime('%s','now')*1000),
(2, '장소', 'place/location', strftime('%s','now')*1000),
(2, '재미없다', 'to be boring', strftime('%s','now')*1000),
(2, '재미있다', 'to be interesting', strftime('%s','now')*1000),
(2, '저', 'I/me (humble)', strftime('%s','now')*1000),
(2, '저것', 'that thing', strftime('%s','now')*1000),
(2, '저기', 'there', strftime('%s','now')*1000),
(2, '저녁', 'evening/dinner', strftime('%s','now')*1000),
(2, '저쪽', 'that way', strftime('%s','now')*1000),
(2, '적다', 'to write down/be few', strftime('%s','now')*1000),
(2, '전', 'before/ago', strftime('%s','now')*1000),
(2, '전공', 'major (study)', strftime('%s','now')*1000),
(2, '전화', 'telephone', strftime('%s','now')*1000),
(2, '전화번호', 'phone number', strftime('%s','now')*1000),
(2, '점심', 'lunch', strftime('%s','now')*1000),
(2, '정류장', 'bus stop', strftime('%s','now')*1000),
(2, '정말', 'really', strftime('%s','now')*1000),
(2, '제', 'my (humble)', strftime('%s','now')*1000),
(2, '제일', 'most/best', strftime('%s','now')*1000),
(2, '제주도', 'Jeju Island', strftime('%s','now')*1000),
(2, '조금', 'a little', strftime('%s','now')*1000),
(2, '조용하다', 'to be quiet', strftime('%s','now')*1000),
(2, '졸업', 'graduation', strftime('%s','now')*1000),
(2, '좀', 'a bit', strftime('%s','now')*1000),
(2, '종업원', 'employee/staff', strftime('%s','now')*1000),
(2, '좋다', 'to be good', strftime('%s','now')*1000),
(2, '좋아하다', 'to like', strftime('%s','now')*1000),
(2, '죄송하다', 'to be sorry', strftime('%s','now')*1000),
(2, '주', 'week', strftime('%s','now')*1000),
(2, '주다', 'to give', strftime('%s','now')*1000),
(2, '주로', 'mainly', strftime('%s','now')*1000),
(2, '주말', 'weekend', strftime('%s','now')*1000),
(2, '주무시다', 'to sleep (honorific)', strftime('%s','now')*1000),
(2, '주부', 'housewife', strftime('%s','now')*1000),
(2, '주소', 'address', strftime('%s','now')*1000),
(2, '주스', 'juice', strftime('%s','now')*1000),
(2, '주인', 'owner', strftime('%s','now')*1000),
(2, '주일', 'week (period)', strftime('%s','now')*1000),
(2, '준비', 'preparation', strftime('%s','now')*1000),
(2, '중', 'middle', strftime('%s','now')*1000),
(2, '중국', 'China', strftime('%s','now')*1000),
(2, '지갑', 'wallet', strftime('%s','now')*1000),
(2, '지금', 'now', strftime('%s','now')*1000),
(2, '지나다', 'to pass', strftime('%s','now')*1000),
(2, '지난달', 'last month', strftime('%s','now')*1000),
(2, '지난주', 'last week', strftime('%s','now')*1000),
(2, '지난해', 'last year', strftime('%s','now')*1000),
(2, '지내다', 'to spend time', strftime('%s','now')*1000),
(2, '지우개', 'eraser', strftime('%s','now')*1000),
(2, '지하철', 'subway', strftime('%s','now')*1000),
(2, '지하철역', 'subway station', strftime('%s','now')*1000),
(2, '직업', 'occupation', strftime('%s','now')*1000),
(2, '직원', 'employee', strftime('%s','now')*1000),
(2, '질문', 'question', strftime('%s','now')*1000),
(2, '집', 'house/home', strftime('%s','now')*1000),
(2, '짜다', 'to be salty', strftime('%s','now')*1000),
(2, '쪽', 'side/page', strftime('%s','now')*1000),
(2, '찍다', 'to take (photo)', strftime('%s','now')*1000),
(2, '참', 'really/truly', strftime('%s','now')*1000),
(2, '참외', 'oriental melon', strftime('%s','now')*1000),
(2, '창문', 'window', strftime('%s','now')*1000),
(2, '찾다', 'to find', strftime('%s','now')*1000),
(2, '찾아보다', 'to look for', strftime('%s','now')*1000),
(2, '책', 'book', strftime('%s','now')*1000),
(2, '책상', 'desk', strftime('%s','now')*1000),
(2, '처음', 'first/time', strftime('%s','now')*1000),
(2, '천', 'thousand', strftime('%s','now')*1000),
(2, '천만', 'ten million', strftime('%s','now')*1000),
(2, '천천히', 'slowly', strftime('%s','now')*1000),
(2, '청소', 'cleaning', strftime('%s','now')*1000),
(2, '초대', 'invitation', strftime('%s','now')*1000),
(2, '초콜릿', 'chocolate', strftime('%s','now')*1000),
(2, '추다', 'to dance', strftime('%s','now')*1000),
(2, '축구', 'soccer', strftime('%s','now')*1000),
(2, '축하', 'congratulation', strftime('%s','now')*1000),
(2, '출발', 'departure', strftime('%s','now')*1000),
(2, '춤', 'dance', strftime('%s','now')*1000),
(2, '춤추다', 'to dance', strftime('%s','now')*1000),
(2, '춥다', 'to be cold (weather)', strftime('%s','now')*1000),
(2, '취미', 'hobby', strftime('%s','now')*1000),
(2, '층', 'floor (building)', strftime('%s','now')*1000),
(2, '치다', 'to hit/play', strftime('%s','now')*1000),
(2, '치마', 'skirt', strftime('%s','now')*1000),
(2, '친구', 'friend', strftime('%s','now')*1000),
(2, '친절', 'kindness', strftime('%s','now')*1000),
(2, '친하다', 'to be close (relation)', strftime('%s','now')*1000),
(2, '칠', 'seven', strftime('%s','now')*1000),
(2, '칠십', 'seventy', strftime('%s','now')*1000),
(2, '칠월', 'July', strftime('%s','now')*1000),
(2, '칠판', 'blackboard', strftime('%s','now')*1000),
(2, '침대', 'bed', strftime('%s','now')*1000),
(2, '카드', 'card', strftime('%s','now')*1000),
(2, '카메라', 'camera', strftime('%s','now')*1000),
(2, '캐나다', 'Canada', strftime('%s','now')*1000),
(2, '커피', 'coffee', strftime('%s','now')*1000),
(2, '커피숍', 'coffee shop', strftime('%s','now')*1000),
(2, '컴퓨터', 'computer', strftime('%s','now')*1000),
(2, '컵', 'cup', strftime('%s','now')*1000),
(2, '케이크', 'cake', strftime('%s','now')*1000),
(2, '켜다', 'to turn on', strftime('%s','now')*1000),
(2, '코', 'nose', strftime('%s','now')*1000),
(2, '콘서트', 'concert', strftime('%s','now')*1000),
(2, '콜라', 'cola', strftime('%s','now')*1000),
(2, '크다', 'to be big', strftime('%s','now')*1000),
(2, '키', 'height', strftime('%s','now')*1000),
(2, '타다', 'to ride', strftime('%s','now')*1000),
(2, '탁구', 'ping-pong', strftime('%s','now')*1000),
(2, '태국', 'Thailand', strftime('%s','now')*1000),
(2, '태권도', 'taekwondo', strftime('%s','now')*1000),
(2, '택시', 'taxi', strftime('%s','now')*1000),
(2, '터미널', 'terminal', strftime('%s','now')*1000),
(2, '테니스', 'tennis', strftime('%s','now')*1000),
(2, '텔레비전', 'television', strftime('%s','now')*1000),
(2, '토요일', 'Saturday', strftime('%s','now')*1000),
(2, '퇴근', 'getting off work', strftime('%s','now')*1000),
(2, '특별하다', 'to be special', strftime('%s','now')*1000),
(2, '특히', 'especially', strftime('%s','now')*1000),
(2, '티셔츠', 't-shirt', strftime('%s','now')*1000),
(2, '파티', 'party', strftime('%s','now')*1000),
(2, '팔', 'arm/eight', strftime('%s','now')*1000),
(2, '팔다', 'to sell', strftime('%s','now')*1000),
(2, '팔십', 'eighty', strftime('%s','now')*1000),
(2, '팔월', 'August', strftime('%s','now')*1000),
(2, '편의점', 'convenience store', strftime('%s','now')*1000),
(2, '편지', 'letter', strftime('%s','now')*1000),
(2, '포도', 'grape', strftime('%s','now')*1000),
(2, '표', 'ticket/table', strftime('%s','now')*1000),
(2, '프랑스', 'France', strftime('%s','now')*1000),
(2, '프로그램', 'program', strftime('%s','now')*1000),
(2, '피곤', 'tiredness', strftime('%s','now')*1000),
(2, '피아노', 'piano', strftime('%s','now')*1000),
(2, '피우다', 'to smoke', strftime('%s','now')*1000),
(2, '필요', 'need/necessity', strftime('%s','now')*1000),
(2, '필통', 'pencil case', strftime('%s','now')*1000),
(2, '하나', 'one', strftime('%s','now')*1000),
(2, '하다', 'to do', strftime('%s','now')*1000),
(2, '하루', 'one day', strftime('%s','now')*1000),
(2, '하숙집', 'boarding house', strftime('%s','now')*1000),
(2, '하지만', 'but/however', strftime('%s','now')*1000),
(2, '학교', 'school', strftime('%s','now')*1000),
(2, '학생', 'student', strftime('%s','now')*1000),
(2, '학생증', 'student ID', strftime('%s','now')*1000),
(2, '한', 'one/Korean', strftime('%s','now')*1000),
(2, '한가하다', 'to be free (not busy)', strftime('%s','now')*1000),
(2, '한국', 'Korea', strftime('%s','now')*1000),
(2, '한복', 'hanbok (traditional clothes)', strftime('%s','now')*1000),
(2, '할머니', 'grandmother', strftime('%s','now')*1000),
(2, '할아버지', 'grandfather', strftime('%s','now')*1000),
(2, '함께', 'together', strftime('%s','now')*1000),
(2, '형', 'older brother (for male)', strftime('%s','now')*1000),
(2, '호', 'number/lake', strftime('%s','now')*1000),
(2, '호텔', 'hotel', strftime('%s','now')*1000),
(2, '혼자', 'alone', strftime('%s','now')*1000),
(2, '화요일', 'Tuesday', strftime('%s','now')*1000),
(2, '화장실', 'bathroom', strftime('%s','now')*1000),
(2, '회사', 'company', strftime('%s','now')*1000),
(2, '회사원', 'office worker', strftime('%s','now')*1000),
(2, '회의', 'meeting', strftime('%s','now')*1000),
(2, '후', 'after', strftime('%s','now')*1000),
(2, '휴가', 'vacation', strftime('%s','now')*1000),
(2, '흐리다', 'to be cloudy', strftime('%s','now')*1000),
(2, '힘들다', 'to be hard/difficult', strftime('%s','now')*1000)

;

