PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(11, '-가02', 'family name suffix', strftime('%s','now')*1000),
(11, '가능성', 'possibility', strftime('%s','now')*1000),
(11, '가라앉다', 'to sink', strftime('%s','now')*1000),
(11, '-가량', 'approximately, about', strftime('%s','now')*1000),
(11, '가로등', 'streetlight', strftime('%s','now')*1000),
(11, '가로막다', 'to block, to obstruct', strftime('%s','now')*1000),
(11, '가르다', 'to divide, to separate', strftime('%s','now')*1000),
(11, '가리다03', 'to distinguish, to cover', strftime('%s','now')*1000),
(11, '가만01', 'quietly, still', strftime('%s','now')*1000),
(11, '가만있다', 'to stay still, to remain calm', strftime('%s','now')*1000),
(11, '가만히', 'quietly, still', strftime('%s','now')*1000),
(11, '가뭄', 'drought', strftime('%s','now')*1000),
(11, '가사03', 'lyrics', strftime('%s','now')*1000),
(11, '가장02', 'head of a family', strftime('%s','now')*1000),
(11, '가정02', 'assumption, hypothesis', strftime('%s','now')*1000),
(11, '가정주부', 'housewife', strftime('%s','now')*1000),
(11, '가져다주다', 'to bring and give', strftime('%s','now')*1000),
(11, '가지01', 'branch', strftime('%s','now')*1000),
(11, '가짜', 'fake, imitation', strftime('%s','now')*1000),
(11, '가치', 'value', strftime('%s','now')*1000),
(11, '가치관', 'values, sense of values', strftime('%s','now')*1000),
(11, '가톨릭', 'Catholicism', strftime('%s','now')*1000),
(11, '각국', 'each country, every nation', strftime('%s','now')*1000),
(11, '각오', 'resolution, determination', strftime('%s','now')*1000),
(11, '각종', 'various kinds', strftime('%s','now')*1000),
(11, '-간', 'between, interval', strftime('%s','now')*1000),
(11, '간03', 'liver', strftime('%s','now')*1000),
(11, '간04', 'between, among', strftime('%s','now')*1000),
(11, '간격', 'space, interval, gap', strftime('%s','now')*1000),
(11, '간섭', 'interference, meddling', strftime('%s','now')*1000),
(11, '간신히', 'barely, with difficulty', strftime('%s','now')*1000),
(11, '간절하다', 'earnest, ardent, desperate', strftime('%s','now')*1000),
(11, '간접적01∙간접적02', 'indirect', strftime('%s','now')*1000),
(11, '간지럽다', 'to be ticklish, to feel itchy', strftime('%s','now')*1000),
(11, '간편하다', 'simple, convenient, handy', strftime('%s','now')*1000),
(11, '간혹02/간혹01', 'occasionally, sometimes', strftime('%s','now')*1000),
(11, '갇히다', 'to be locked up, to be trapped', strftime('%s','now')*1000),
(11, '갈등', 'conflict, strife', strftime('%s','now')*1000),
(11, '갈라지다', 'to split, to crack, to separate', strftime('%s','now')*1000),
(11, '갈수록', 'increasingly, more and more', strftime('%s','now')*1000),
(11, '감상문', 'review, report, appreciation essay', strftime('%s','now')*1000),
(11, '감소', 'decrease, reduction', strftime('%s','now')*1000),
(11, '감시', 'surveillance, monitoring', strftime('%s','now')*1000),
(11, '감싸다', 'to wrap, to protect, to cover', strftime('%s','now')*1000),
(11, '감옥', 'prison, jail', strftime('%s','now')*1000),
(11, '감추다', 'to hide, to conceal', strftime('%s','now')*1000),
(11, '감히', 'dare to, boldly', strftime('%s','now')*1000),
(11, '갑작스럽다', 'sudden, unexpected', strftime('%s','now')*1000),
(11, '값싸다', 'cheap, inexpensive', strftime('%s','now')*1000),
(11, '강도03', 'robber, burglar', strftime('%s','now')*1000),
(11, '강수량', 'precipitation, rainfall amount', strftime('%s','now')*1000),
(11, '강요', 'pressure, coercion', strftime('%s','now')*1000),
(11, '강의', 'lecture, class', strftime('%s','now')*1000),
(11, '강의실', 'lecture room, classroom', strftime('%s','now')*1000),
(11, '강제', 'force, compulsion', strftime('%s','now')*1000),
(11, '강조', 'emphasis, stress', strftime('%s','now')*1000),
(11, '갖가지', 'various kinds, all sorts', strftime('%s','now')*1000),
(11, '갖추다', 'to prepare, to equip, to possess', strftime('%s','now')*1000),
(11, '개구리', 'frog', strftime('%s','now')*1000),
(11, '개념', 'concept, idea, notion', strftime('%s','now')*1000),
(11, '개다03', 'to fold (laundry), to clear up (weather)', strftime('%s','now')*1000),
(11, '개미', 'ant', strftime('%s','now')*1000),
(11, '개발', 'development', strftime('%s','now')*1000),
(11, '개방', 'opening, liberalization', strftime('%s','now')*1000),
(11, '개별', 'individual, separate', strftime('%s','now')*1000),
(11, '개선01', 'improvement', strftime('%s','now')*1000),
(11, '개성', 'individuality, personality', strftime('%s','now')*1000),
(11, '개최', 'holding (a meeting/event)', strftime('%s','now')*1000),
(11, '개혁', 'reform, innovation', strftime('%s','now')*1000),
(11, '-객', 'guest, visitor suffix', strftime('%s','now')*1000),
(11, '객관적01∙객관적02', 'objective', strftime('%s','now')*1000),
(11, '거대', 'huge, gigantic', strftime('%s','now')*1000),
(11, '거두다', 'to collect, to achieve, to gather', strftime('%s','now')*1000),
(11, '거들다', 'to help, to assist', strftime('%s','now')*1000),
(11, '거래', 'deal, transaction, trade', strftime('%s','now')*1000),
(11, '거래처', 'business partner, client', strftime('%s','now')*1000),
(11, '거미', 'spider', strftime('%s','now')*1000),
(11, '거북이', 'turtle', strftime('%s','now')*1000),
(11, '거지', 'beggar', strftime('%s','now')*1000),
(11, '거짓', 'lie, falsehood', strftime('%s','now')*1000),
(11, '거치다', 'to go through, to pass through', strftime('%s','now')*1000),
(11, '거칠다', 'rough, coarse', strftime('%s','now')*1000),
(11, '걱정스럽다', 'worrisome, anxious', strftime('%s','now')*1000),
(11, '건너', 'across, over', strftime('%s','now')*1000),
(11, '건네다', 'to hand over, to pass', strftime('%s','now')*1000),
(11, '건네주다', 'to hand to someone, to deliver', strftime('%s','now')*1000),
(11, '건드리다', 'to touch, to provoke', strftime('%s','now')*1000),
(11, '건설', 'construction, building', strftime('%s','now')*1000),
(11, '건전지', 'battery', strftime('%s','now')*1000),
(11, '건지다', 'to pick up, to rescue, to save', strftime('%s','now')*1000),
(11, '건축', 'architecture, construction', strftime('%s','now')*1000),
(11, '걷다03', 'to roll up, to fold (sleeves, cloth)', strftime('%s','now')*1000),
(11, '걷다04', 'to collect, to harvest', strftime('%s','now')*1000),
(11, '걸치다', 'to hang, to wear, to span', strftime('%s','now')*1000),
(11, '검사01', 'inspection, test, examination', strftime('%s','now')*1000),
(11, '겁나다', 'to be scared, to feel afraid', strftime('%s','now')*1000),
(11, '겉모습', 'appearance, exterior look', strftime('%s','now')*1000),
(11, '게01', 'crab', strftime('%s','now')*1000),
(11, '게다가01', 'besides, moreover', strftime('%s','now')*1000),
(11, '겨울철', 'winter season', strftime('%s','now')*1000),
(11, '격려', 'encouragement, cheering', strftime('%s','now')*1000),
(11, '겪다', 'to experience, to undergo', strftime('%s','now')*1000),
(11, '견디다', 'to endure, to bear', strftime('%s','now')*1000),
(11, '견학', 'field trip, observation tour', strftime('%s','now')*1000),
(11, '견해', 'opinion, view, standpoint', strftime('%s','now')*1000),
(11, '결근', 'absence from work', strftime('%s','now')*1000),
(11, '결론', 'conclusion', strftime('%s','now')*1000),
(11, '결승', 'final match, finals', strftime('%s','now')*1000),
(11, '결코', 'never, by no means', strftime('%s','now')*1000),
(11, '결합', 'union, combination, fusion', strftime('%s','now')*1000),
(11, '결혼식장', 'wedding hall', strftime('%s','now')*1000),
(11, '겸손', 'humility, modesty', strftime('%s','now')*1000),
(11, '겹치다', 'to overlap, to coincide', strftime('%s','now')*1000),
(11, '경계01', 'boundary, border, vigilance', strftime('%s','now')*1000),
(11, '경고', 'warning, caution', strftime('%s','now')*1000),
(11, '경기01', 'game, match, contest', strftime('%s','now')*1000),
(11, '경력', 'career, experience', strftime('%s','now')*1000),
(11, '경영', 'management, administration', strftime('%s','now')*1000),
(11, '경쟁', 'competition, rivalry', strftime('%s','now')*1000),
(11, '경쟁력', 'competitiveness', strftime('%s','now')*1000),
(11, '경제력', 'economic power, financial ability', strftime('%s','now')*1000),
(11, '경향', 'tendency, trend', strftime('%s','now')*1000),
(11, '계기01', 'opportunity, chance, trigger', strftime('%s','now')*1000),
(11, '계산기', 'calculator', strftime('%s','now')*1000),
(11, '계산대', 'cash register counter', strftime('%s','now')*1000),
(11, '계층', 'class, social stratum', strftime('%s','now')*1000),
(11, '고국', 'hometown, native country', strftime('%s','now')*1000),
(11, '고급', 'high class, luxury, premium', strftime('%s','now')*1000),
(11, '고급스럽다', 'luxurious, classy', strftime('%s','now')*1000),
(11, '고대01', 'ancient times, antiquity', strftime('%s','now')*1000),
(11, '고독', 'loneliness, solitude', strftime('%s','now')*1000),
(11, '고등', 'high, advanced', strftime('%s','now')*1000),
(11, '고등어', 'mackerel', strftime('%s','now')*1000),
(11, '고래01', 'whale', strftime('%s','now')*1000),
(11, '고려01', 'consideration, regard', strftime('%s','now')*1000),
(11, '고마워하다', 'to thank, to be grateful', strftime('%s','now')*1000),
(11, '고무01', 'rubber', strftime('%s','now')*1000),
(11, '고소하다01', 'to sue, to bring a charge', strftime('%s','now')*1000),
(11, '고요', 'silence, stillness', strftime('%s','now')*1000),
(11, '고유', 'unique, inherent, characteristic', strftime('%s','now')*1000),
(11, '고장01', 'breakdown, failure', strftime('%s','now')*1000),
(11, '고전01', 'classic, old literature', strftime('%s','now')*1000),
(11, '고정', 'fixation, fastening', strftime('%s','now')*1000),
(11, '고집', 'stubbornness, persistence', strftime('%s','now')*1000),
(11, '고층', 'high-rise, upper floor', strftime('%s','now')*1000),
(11, '고통', 'pain, suffering, agony', strftime('%s','now')*1000),
(11, '고통스럽다', 'painful, distressing', strftime('%s','now')*1000),
(11, '곡01', 'song, tune, melody', strftime('%s','now')*1000),
(11, '곡식', 'grain, cereals', strftime('%s','now')*1000),
(11, '곧다', 'straight, upright', strftime('%s','now')*1000),
(11, '곧바로', 'immediately, right away', strftime('%s','now')*1000),
(11, '곧잘', 'often, fairly well', strftime('%s','now')*1000),
(11, '골04', 'goal (sports)', strftime('%s','now')*1000),
(11, '골다', 'to be bony, to have bones', strftime('%s','now')*1000),
(11, '공감', 'sympathy, empathy', strftime('%s','now')*1000),
(11, '공개', 'opening to the public, disclosure', strftime('%s','now')*1000),
(11, '공격', 'attack, assault', strftime('%s','now')*1000),
(11, '공급', 'supply, provision', strftime('%s','now')*1000),
(11, '공기03', 'air, atmosphere', strftime('%s','now')*1000),
(11, '공동체', 'community, collective body', strftime('%s','now')*1000),
(11, '공손하다', 'polite, courteous', strftime('%s','now')*1000),
(11, '공업', 'industry, manufacturing', strftime('%s','now')*1000),
(11, '공적01∙공적02', 'public, official', strftime('%s','now')*1000),
(11, '공지01', 'announcement, notice', strftime('%s','now')*1000),
(11, '공해01', 'pollution', strftime('%s','now')*1000),
(11, '과소비', 'overconsumption', strftime('%s','now')*1000),
(11, '과속', 'speeding', strftime('%s','now')*1000),
(11, '과연', 'indeed, really, as expected', strftime('%s','now')*1000),
(11, '과외', 'private tutoring', strftime('%s','now')*1000),
(11, '과제', 'task, assignment, project', strftime('%s','now')*1000),
(11, '과학적01∙과학적02', 'scientific', strftime('%s','now')*1000),
(11, '-관02', 'related to, concerning (suffix)', strftime('%s','now')*1000),
(11, '-관03', 'hall, building (suffix)', strftime('%s','now')*1000),
(11, '관계자', 'person concerned, related party', strftime('%s','now')*1000),
(11, '관심사', 'interest, concern', strftime('%s','now')*1000),
(11, '관점', 'viewpoint, perspective', strftime('%s','now')*1000),
(11, '괜히', 'in vain, for nothing', strftime('%s','now')*1000),
(11, '괴로움', 'pain, suffering, agony', strftime('%s','now')*1000),
(11, '괴로워하다', 'to suffer, to feel pain', strftime('%s','now')*1000),
(11, '괴롭다', 'painful, distressing', strftime('%s','now')*1000),
(11, '괴롭히다', 'to torment, to harass', strftime('%s','now')*1000),
(11, '굉장하다', 'great, tremendous, awesome', strftime('%s','now')*1000),
(11, '교내', 'inside the school, on campus', strftime('%s','now')*1000),
(11, '교대01', 'shift, alternation', strftime('%s','now')*1000),
(11, '교류', 'exchange, interchange', strftime('%s','now')*1000),
(11, '교복', 'school uniform', strftime('%s','now')*1000),
(11, '교양', 'culture, refinement, education', strftime('%s','now')*1000),
(11, '교육비', 'education expenses', strftime('%s','now')*1000),
(11, '교육자', 'educator, teacher', strftime('%s','now')*1000),
(11, '교장', 'school principal', strftime('%s','now')*1000),
(11, '교재', 'textbook, teaching material', strftime('%s','now')*1000),
(11, '교체', 'replacement, substitution', strftime('%s','now')*1000),
(11, '교훈02', 'lesson, moral, teaching', strftime('%s','now')*1000),
(11, '구르다01', 'to roll, to tumble', strftime('%s','now')*1000),
(11, '구매', 'purchase, buying', strftime('%s','now')*1000),
(11, '구별', 'distinction, differentiation', strftime('%s','now')*1000),
(11, '구부리다', 'to bend, to curve', strftime('%s','now')*1000),
(11, '구분', 'division, classification', strftime('%s','now')*1000),
(11, '구석', 'corner, nook', strftime('%s','now')*1000),
(11, '구성', 'composition, structure', strftime('%s','now')*1000),
(11, '구세대', 'older generation', strftime('%s','now')*1000),
(11, '구속01', 'restraint, confinement', strftime('%s','now')*1000),
(11, '구조01', 'structure, construction', strftime('%s','now')*1000),
(11, '구하다02', 'to seek, to obtain, to save', strftime('%s','now')*1000),
(11, '국경일', 'national holiday', strftime('%s','now')*1000),
(11, '국산', 'domestic product', strftime('%s','now')*1000),
(11, '국외', 'foreign, abroad', strftime('%s','now')*1000),
(11, '국제결혼', 'international marriage', strftime('%s','now')*1000),
(11, '국제선', 'international route', strftime('%s','now')*1000),
(11, '국제화', 'globalization, internationalization', strftime('%s','now')*1000),
(11, '국화02', 'chrysanthemum', strftime('%s','now')*1000),
(11, '국회', 'National Assembly, parliament', strftime('%s','now')*1000),
(11, '군04', 'county, district', strftime('%s','now')*1000),
(11, '군데', 'place, spot', strftime('%s','now')*1000),
(11, '군사01', 'military, soldier', strftime('%s','now')*1000),
(11, '굳다01', 'hard, stiff, firm', strftime('%s','now')*1000),
(11, '굳어지다', 'to harden, to become firm', strftime('%s','now')*1000),
(11, '굳이', 'by all means, stubbornly, intentionally', strftime('%s','now')*1000),
(11, '굴02', 'cave', strftime('%s','now')*1000),
(11, '굽히다', 'to bend, to stoop', strftime('%s','now')*1000),
(11, '-권03', 'volume, book (counter)', strftime('%s','now')*1000),
(11, '권력', 'power, authority', strftime('%s','now')*1000),
(11, '권리', 'right, privilege', strftime('%s','now')*1000),
(11, '권위', 'authority, dignity', strftime('%s','now')*1000),
(11, '권유', 'recommendation, suggestion', strftime('%s','now')*1000),
(11, '귀가', 'return home', strftime('%s','now')*1000),
(11, '귀국', 'return to one’s country', strftime('%s','now')*1000),
(11, '귀신', 'ghost, spirit', strftime('%s','now')*1000),
(11, '귀중하다', 'precious, valuable', strftime('%s','now')*1000),
(11, '귀하다', 'precious, rare, noble', strftime('%s','now')*1000),
(11, '규모', 'scale, size, scope', strftime('%s','now')*1000),
(11, '규정', 'regulation, rule, provision', strftime('%s','now')*1000),
(11, '균형', 'balance, equilibrium', strftime('%s','now')*1000),
(11, '그나마', 'still, at least', strftime('%s','now')*1000),
(11, '그네01', 'swing', strftime('%s','now')*1000),
(11, '그늘', 'shade, shadow', strftime('%s','now')*1000),
(11, '그다지', 'not so much, not particularly', strftime('%s','now')*1000),
(11, '그대', 'you (poetic/formal)', strftime('%s','now')*1000),
(11, '그래프', 'graph, chart', strftime('%s','now')*1000),
(11, '그러게02', 'indeed, that’s right', strftime('%s','now')*1000),
(11, '그럭저럭', 'somehow, passably, tolerably', strftime('%s','now')*1000),
(11, '그런대로', 'as it is, fairly, tolerably', strftime('%s','now')*1000),
(11, '그렇지01', 'that’s right, exactly', strftime('%s','now')*1000),
(11, '그리01', 'that way, so', strftime('%s','now')*1000),
(11, '그리움', 'longing, yearning', strftime('%s','now')*1000),
(11, '그림자', 'shadow, silhouette', strftime('%s','now')*1000),
(11, '그림책', 'picture book', strftime('%s','now')*1000),
(11, '그만큼01/그만큼02', 'that much, to that extent', strftime('%s','now')*1000),
(11, '그야말로', 'indeed, literally, truly', strftime('%s','now')*1000),
(11, '그제야', 'not until then, only then', strftime('%s','now')*1000),
(11, '그토록', 'so much, to that degree', strftime('%s','now')*1000),
(11, '극복', 'overcoming, conquest', strftime('%s','now')*1000),
(11, '극히', 'extremely, very', strftime('%s','now')*1000),
(11, '근거', 'basis, ground, reason', strftime('%s','now')*1000),
(11, '근교', 'suburbs, outskirts', strftime('%s','now')*1000),
(11, '근대', 'modern times', strftime('%s','now')*1000),
(11, '근래', 'recently, lately', strftime('%s','now')*1000),
(11, '근로자', 'worker, laborer', strftime('%s','now')*1000),
(11, '근본', 'foundation, root, origin', strftime('%s','now')*1000),
(11, '근본적01∙근본적02', 'fundamental, basic', strftime('%s','now')*1000),
(11, '근심', 'worry, anxiety', strftime('%s','now')*1000),
(11, '긁다', 'to scratch', strftime('%s','now')*1000),
(11, '금년', 'this year', strftime('%s','now')*1000),
(11, '금융', 'finance, financial affairs', strftime('%s','now')*1000),
(11, '금하다', 'to forbid, to prohibit', strftime('%s','now')*1000),
(11, '급격히', 'rapidly, drastically', strftime('%s','now')*1000),
(11, '급속히', 'quickly, fast, swiftly', strftime('%s','now')*1000),
(11, '급증', 'sudden increase, surge', strftime('%s','now')*1000),
(11, '급히', 'hurriedly, hastily', strftime('%s','now')*1000),
(11, '기념일', 'anniversary, commemorative day', strftime('%s','now')*1000),
(11, '기독교', 'Christianity', strftime('%s','now')*1000),
(11, '기둥', 'pillar, column', strftime('%s','now')*1000),
(11, '기록', 'record, documentation', strftime('%s','now')*1000),
(11, '기반', 'foundation, base', strftime('%s','now')*1000),
(11, '기본', 'basis, foundation, fundamental', strftime('%s','now')*1000),
(11, '기본적01∙기본적02', 'basic, fundamental', strftime('%s','now')*1000),
(11, '기부', 'donation, contribution', strftime('%s','now')*1000),
(11, '기술01', 'skill, technique, technology', strftime('%s','now')*1000),
(11, '기업가', 'entrepreneur, businessman', strftime('%s','now')*1000),
(11, '기여', 'contribution, devotion', strftime('%s','now')*1000),
(11, '기운01', 'energy, strength, spirit', strftime('%s','now')*1000),
(11, '기울다', 'to tilt, to lean, to decline', strftime('%s','now')*1000),
(11, '기울이다', 'to tilt, to devote (effort)', strftime('%s','now')*1000),
(11, '기원02', 'origin, beginning', strftime('%s','now')*1000),
(11, '기적', 'miracle, wonder', strftime('%s','now')*1000),
(11, '기존', 'existing, established', strftime('%s','now')*1000),
(11, '기지개', 'stretching (of the body)', strftime('%s','now')*1000),
(11, '기혼', 'married (status)', strftime('%s','now')*1000),
(11, '기획', 'planning, project design', strftime('%s','now')*1000),
(11, '기후', 'climate, weather', strftime('%s','now')*1000),
(11, '길가', 'roadside, edge of the street', strftime('%s','now')*1000),
(11, '길거리', 'street, road', strftime('%s','now')*1000),
(11, '깊이01', 'depth, deeply', strftime('%s','now')*1000),
(11, '까다롭다', 'complicated, fussy, picky', strftime('%s','now')*1000),
(11, '까닭', 'reason, cause', strftime('%s','now')*1000),
(11, '까먹다', 'to forget, to eat up', strftime('%s','now')*1000),
(11, '깔다', 'to spread, to lay', strftime('%s','now')*1000),
(11, '깔리다', 'to be spread, to be laid', strftime('%s','now')*1000),
(11, '깜깜하다', 'pitch-dark, ignorant', strftime('%s','now')*1000),
(11, '깜박하다', 'to blink, to forget momentarily', strftime('%s','now')*1000),
(11, '깨', 'sesame seed', strftime('%s','now')*1000),
(11, '깨다02', 'to wake up, to become sober', strftime('%s','now')*1000),
(11, '깨닫다', 'to realize, to become aware', strftime('%s','now')*1000),
(11, '깨뜨리다', 'to break, to smash, to shatter', strftime('%s','now')*1000),
(11, '깨물다', 'to bite', strftime('%s','now')*1000),
(11, '깨어나다', 'to wake up, to regain consciousness', strftime('%s','now')*1000),
(11, '깨우다', 'to wake someone up', strftime('%s','now')*1000),
(11, '꺾다', 'to break, to snap, to bend', strftime('%s','now')*1000),
(11, '껴안다', 'to hug, to embrace', strftime('%s','now')*1000),
(11, '꼭01', 'surely, tightly, exactly', strftime('%s','now')*1000),
(11, '꼭대기', 'top, summit, peak', strftime('%s','now')*1000),
(11, '꼼꼼하다', 'meticulous, thorough, careful', strftime('%s','now')*1000),
(11, '꼼꼼히', 'carefully, meticulously', strftime('%s','now')*1000),
(11, '꼽다', 'to count, to point out', strftime('%s','now')*1000),
(11, '꼽히다', 'to be counted as, to be considered', strftime('%s','now')*1000),
(11, '꽂히다', 'to be stuck, to be inserted', strftime('%s','now')*1000),
(11, '꽃꽂이', 'flower arrangement', strftime('%s','now')*1000),
(11, '꽃잎', 'petal', strftime('%s','now')*1000),
(11, '꾸다02', 'to dream', strftime('%s','now')*1000),
(11, '꾸리다', 'to pack, to organize', strftime('%s','now')*1000),
(11, '꾸미다', 'to decorate, to embellish', strftime('%s','now')*1000),
(11, '꾸준하다', 'steady, consistent', strftime('%s','now')*1000),
(11, '꾸중', 'scolding, reprimand', strftime('%s','now')*1000),
(11, '꿇다', 'to kneel, to bow down', strftime('%s','now')*1000),
(11, '꿈꾸다', 'to dream, to aspire', strftime('%s','now')*1000),
(11, '꿈속', 'in a dream', strftime('%s','now')*1000),
(11, '끄덕이다', 'to nod', strftime('%s','now')*1000),
(11, '끊임없다', 'unceasing, endless', strftime('%s','now')*1000),
(11, '끊임없이', 'constantly, continuously', strftime('%s','now')*1000),
(11, '끌리다', 'to be attracted, to be drawn', strftime('%s','now')*1000),
(11, '끌어당기다', 'to pull, to drag', strftime('%s','now')*1000),
(11, '끌어안다', 'to embrace, to hug', strftime('%s','now')*1000),
(11, '끝없다', 'endless, infinite', strftime('%s','now')*1000),
(11, '끝없이', 'endlessly, infinitely', strftime('%s','now')*1000),
(11, '끼다01', 'to wear (accessories), to insert', strftime('%s','now')*1000),
(11, '끼어들다', 'to interrupt, to cut in', strftime('%s','now')*1000),
(11, '끼우다', 'to insert, to put in', strftime('%s','now')*1000),
(11, '끼이다', 'to be stuck, to be caught between', strftime('%s','now')*1000),
(11, '끼치다01', 'to cause, to give (influence)', strftime('%s','now')*1000),
(11, '끼치다02', 'to have goosebumps, to be affected', strftime('%s','now')*1000),
(11, '나뉘다', 'to be divided, to be split', strftime('%s','now')*1000),
(11, '나란히', 'side by side, in line', strftime('%s','now')*1000),
(11, '나름', 'according to, depending on', strftime('%s','now')*1000),
(11, '나무라다', 'to scold, to reproach', strftime('%s','now')*1000),
(11, '나뭇가지', 'tree branch, twig', strftime('%s','now')*1000),
(11, '나비03', 'butterfly', strftime('%s','now')*1000),
(11, '나서다', 'to step forward, to take initiative', strftime('%s','now')*1000),
(11, '나아가다', 'to advance, to go forward', strftime('%s','now')*1000),
(11, '난리', 'disturbance, chaos, mess', strftime('%s','now')*1000),
(11, '난처하다', 'embarrassed, awkward', strftime('%s','now')*1000),
(11, '날개', 'wing', strftime('%s','now')*1000);