PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(13, '면담', 'interview, meeting', strftime('%s','now')*1000),
(13, '면도', 'shaving', strftime('%s','now')*1000),
(13, '면하다01', 'to avoid, to escape', strftime('%s','now')*1000),
(13, '면허', 'license, permit', strftime('%s','now')*1000),
(13, '명01', 'person, people (counter)', strftime('%s','now')*1000),
(13, '명령', 'order, command', strftime('%s','now')*1000),
(13, '명예01', 'honor, dignity', strftime('%s','now')*1000),
(13, '명확하다', 'clear, definite, distinct', strftime('%s','now')*1000),
(13, '모06/모07', 'model, pattern', strftime('%s','now')*1000),
(13, '모금02', 'fundraising, collection of money', strftime('%s','now')*1000),
(13, '모여들다', 'to gather, to crowd', strftime('%s','now')*1000),
(13, '모처럼', 'for the first time in a while', strftime('%s','now')*1000),
(13, '모험', 'adventure', strftime('%s','now')*1000),
(13, '목구멍', 'throat', strftime('%s','now')*1000),
(13, '목마르다01', 'to be thirsty', strftime('%s','now')*1000),
(13, '목사', 'pastor, minister', strftime('%s','now')*1000),
(13, '목숨', 'life', strftime('%s','now')*1000),
(13, '몫', 'share, portion, part', strftime('%s','now')*1000),
(13, '몰다', 'to drive, to steer', strftime('%s','now')*1000),
(13, '몰라보다', 'to fail to recognize, to be ignorant of', strftime('%s','now')*1000),
(13, '몰려들다', 'to crowd in, to flock', strftime('%s','now')*1000),
(13, '몰려오다', 'to rush in, to flock toward', strftime('%s','now')*1000),
(13, '몰리다', 'to be cornered, to be driven', strftime('%s','now')*1000),
(13, '몸매', 'figure, body shape', strftime('%s','now')*1000),
(13, '몸속', 'inside the body', strftime('%s','now')*1000),
(13, '몸통', 'trunk, torso, body', strftime('%s','now')*1000),
(13, '몹시', 'very, extremely', strftime('%s','now')*1000),
(13, '못01', 'nail', strftime('%s','now')*1000),
(13, '못나다', 'ugly, bad, foolish', strftime('%s','now')*1000),
(13, '못되다', 'bad, wicked, ill-natured', strftime('%s','now')*1000),
(13, '못지않다', 'not inferior to, just as good as', strftime('%s','now')*1000),
(13, '몽땅01', 'entirely, all together', strftime('%s','now')*1000),
(13, '무-01', 'non-, un-, without (prefix)', strftime('%s','now')*1000),
(13, '무관심', 'indifference, apathy', strftime('%s','now')*1000),
(13, '무관하다', 'to be unrelated, to be irrelevant', strftime('%s','now')*1000),
(13, '무기', 'weapon', strftime('%s','now')*1000),
(13, '무너지다', 'to collapse, to fall down', strftime('%s','now')*1000),
(13, '무덥다', 'hot, humid', strftime('%s','now')*1000),
(13, '무려', 'as much as, no less than', strftime('%s','now')*1000),
(13, '무렵', 'around, about (time)', strftime('%s','now')*1000),
(13, '무리02', 'group, crowd, unreasonable act', strftime('%s','now')*1000),
(13, '무사히', 'safely, without incident', strftime('%s','now')*1000),
(13, '무시', 'neglect, disregard', strftime('%s','now')*1000),
(13, '무의미', 'meaningless, pointless', strftime('%s','now')*1000),
(13, '무지개', 'rainbow', strftime('%s','now')*1000),
(13, '무책임', 'irresponsibility', strftime('%s','now')*1000),
(13, '묵묵히', 'silently, quietly', strftime('%s','now')*1000),
(13, '묶이다', 'to be tied, to be bound', strftime('%s','now')*1000),
(13, '-문', 'problem, question, issue (suffix)', strftime('%s','now')*1000),
(13, '문득', 'suddenly, unexpectedly', strftime('%s','now')*1000),
(13, '문명', 'civilization', strftime('%s','now')*1000),
(13, '문서', 'document, paper', strftime('%s','now')*1000),
(13, '문제점', 'problematic point, issue', strftime('%s','now')*1000),
(13, '문화적01∙문화적02', 'cultural', strftime('%s','now')*1000),
(13, '묻다02', 'to bury', strftime('%s','now')*1000),
(13, '묻히다01', 'to be buried', strftime('%s','now')*1000),
(13, '묻히다02', 'to be smeared with', strftime('%s','now')*1000),
(13, '물감', 'paint, coloring', strftime('%s','now')*1000),
(13, '물결', 'wave, flow', strftime('%s','now')*1000),
(13, '물기', 'moisture, wetness', strftime('%s','now')*1000),
(13, '물들다', 'to be dyed, to be influenced', strftime('%s','now')*1000),
(13, '물속', 'underwater, in the water', strftime('%s','now')*1000),
(13, '물질', 'matter, substance, material', strftime('%s','now')*1000),
(13, '물질적01∙물질적02', 'material, physical', strftime('%s','now')*1000),
(13, '뭉치다', 'to stick together, to unite', strftime('%s','now')*1000),
(13, '뭘', 'what (informal)', strftime('%s','now')*1000),
(13, '미니', 'mini, small', strftime('%s','now')*1000),
(13, '미디어', 'media', strftime('%s','now')*1000),
(13, '미련02', 'regret, lingering attachment', strftime('%s','now')*1000),
(13, '미움', 'hatred, dislike', strftime('%s','now')*1000),
(13, '미지근하다', 'lukewarm, tepid', strftime('%s','now')*1000),
(13, '미처', 'not yet, unable to (before doing)', strftime('%s','now')*1000),
(13, '미치다01', 'to reach, to extend to', strftime('%s','now')*1000),
(13, '미치다02', 'to go crazy, to be insane', strftime('%s','now')*1000),
(13, '미혼', 'unmarried, single', strftime('%s','now')*1000),
(13, '민족', 'ethnic group, nation', strftime('%s','now')*1000),
(13, '민주주의', 'democracy', strftime('%s','now')*1000),
(13, '믿음', 'faith, belief, trust', strftime('%s','now')*1000),
(13, '밀리다02', 'to be pushed, to be overdue', strftime('%s','now')*1000),
(13, '밀리미터', 'millimeter', strftime('%s','now')*1000),
(13, '밑바닥', 'bottom, base, foundation', strftime('%s','now')*1000),
(13, '바가지', 'bowl, overcharge', strftime('%s','now')*1000),
(13, '바람03', 'wish, desire', strftime('%s','now')*1000),
(13, '바람직하다', 'desirable, proper', strftime('%s','now')*1000),
(13, '바래다주다', 'to see someone off', strftime('%s','now')*1000),
(13, '바로잡다', 'to correct, to fix', strftime('%s','now')*1000),
(13, '바르다03', 'to apply, to spread (on a surface)', strftime('%s','now')*1000),
(13, '바싹', 'completely, closely', strftime('%s','now')*1000),
(13, '바치다', 'to dedicate, to offer', strftime('%s','now')*1000),
(13, '박다', 'to drive in, to hammer in', strftime('%s','now')*1000),
(13, '박스', 'box', strftime('%s','now')*1000),
(13, '박히다', 'to be stuck, to be embedded', strftime('%s','now')*1000),
(13, '반값', 'half price', strftime('%s','now')*1000),
(13, '반기다', 'to welcome, to be glad to see', strftime('%s','now')*1000),
(13, '반발', 'resistance, rebellion', strftime('%s','now')*1000),
(13, '반성', 'self-reflection, introspection', strftime('%s','now')*1000),
(13, '반영', 'reflection, influence', strftime('%s','now')*1000),
(13, '반응', 'reaction, response', strftime('%s','now')*1000),
(13, '반장', 'class president, team leader', strftime('%s','now')*1000),
(13, '반짝거리다', 'to sparkle, to twinkle', strftime('%s','now')*1000),
(13, '반짝반짝01', 'sparklingly, twinklingly', strftime('%s','now')*1000),
(13, '반짝이다', 'to shine, to glitter', strftime('%s','now')*1000),
(13, '반품', 'return (of goods)', strftime('%s','now')*1000),
(13, '받아들이다', 'to accept, to receive, to embrace', strftime('%s','now')*1000),
(13, '받침', 'final consonant (Korean)', strftime('%s','now')*1000),
(13, '발걸음', 'footstep, pace', strftime('%s','now')*1000),
(13, '발견', 'discovery, finding', strftime('%s','now')*1000),
(13, '발길', 'step, foot movement', strftime('%s','now')*1000),
(13, '발꿈치', 'heel', strftime('%s','now')*1000),
(13, '발끝', 'tip of the foot, toe', strftime('%s','now')*1000),
(13, '발등', 'top of the foot', strftime('%s','now')*1000),
(13, '발생', 'occurrence, outbreak', strftime('%s','now')*1000),
(13, '발자국', 'footprint, step mark', strftime('%s','now')*1000),
(13, '발톱', 'toe nail, claw', strftime('%s','now')*1000),
(13, '발표회', 'presentation, recital', strftime('%s','now')*1000),
(13, '밝혀내다', 'to reveal, to disclose', strftime('%s','now')*1000),
(13, '밝혀지다', 'to be revealed, to be clarified', strftime('%s','now')*1000),
(13, '밟히다', 'to be stepped on', strftime('%s','now')*1000),
(13, '밤낮01/밤낮02', 'day and night, always', strftime('%s','now')*1000),
(13, '밤새다', 'to stay up all night', strftime('%s','now')*1000),
(13, '밤새우다', 'to spend the night awake', strftime('%s','now')*1000),
(13, '밤중', 'midnight, middle of the night', strftime('%s','now')*1000),
(13, '밥맛', 'appetite, taste for food', strftime('%s','now')*1000),
(13, '방면01', 'direction, aspect, side', strftime('%s','now')*1000),
(13, '방바닥', 'floor, room floor', strftime('%s','now')*1000),
(13, '방안', 'plan, proposal, measure', strftime('%s','now')*1000),
(13, '방지', 'prevention, protection', strftime('%s','now')*1000),
(13, '배경', 'background', strftime('%s','now')*1000),
(13, '배꼽', 'navel, belly button', strftime('%s','now')*1000),
(13, '배다01', 'to soak into, to permeate', strftime('%s','now')*1000),
(13, '배려02', 'consideration, care', strftime('%s','now')*1000),
(13, '배부르다', 'to be full (from eating)', strftime('%s','now')*1000),
(13, '배송04', 'delivery, shipping', strftime('%s','now')*1000),
(13, '배우자02', 'spouse, partner', strftime('%s','now')*1000),
(13, '뱉다', 'to spit out', strftime('%s','now')*1000),
(13, '버티다', 'to endure, to resist', strftime('%s','now')*1000),
(13, '번갈다', 'to alternate, to take turns', strftime('%s','now')*1000),
(13, '번거롭다', 'complicated, cumbersome', strftime('%s','now')*1000),
(13, '번화하다', 'busy, bustling', strftime('%s','now')*1000),
(13, '벌03', 'bee', strftime('%s','now')*1000),
(13, '벌떡', 'suddenly, abruptly (standing up)', strftime('%s','now')*1000),
(13, '벌레', 'insect, bug', strftime('%s','now')*1000),
(13, '벌리다', 'to open (mouth, arms), to spread', strftime('%s','now')*1000),
(13, '벌어지다01', 'to happen, to occur', strftime('%s','now')*1000),
(13, '벌어지다02', 'to widen, to spread apart', strftime('%s','now')*1000),
(13, '벌이다', 'to start, to set up, to wage', strftime('%s','now')*1000),
(13, '범위', 'scope, range, extent', strftime('%s','now')*1000),
(13, '범인02', 'criminal, culprit', strftime('%s','now')*1000),
(13, '법률', 'law, statute', strftime('%s','now')*1000),
(13, '법원01', 'court (of law)', strftime('%s','now')*1000),
(13, '법적01∙법적02', 'legal, judicial', strftime('%s','now')*1000),
(13, '벗어나다', 'to get out, to free oneself', strftime('%s','now')*1000),
(13, '베개', 'pillow', strftime('%s','now')*1000),
(13, '베풀다', 'to give, to hold (an event), to do kindness', strftime('%s','now')*1000),
(13, '벼', 'rice plant', strftime('%s','now')*1000),
(13, '변덕스럽다', 'fickle, changeable', strftime('%s','now')*1000),
(13, '변동', 'change, fluctuation', strftime('%s','now')*1000),
(13, '변명', 'excuse, justification', strftime('%s','now')*1000),
(13, '별다르다', 'special, particular', strftime('%s','now')*1000),
(13, '별도', 'separate, additional', strftime('%s','now')*1000),
(13, '병들다', 'to get sick', strftime('%s','now')*1000),
(13, '보급01', 'supply, distribution', strftime('%s','now')*1000),
(13, '보도02', 'news report, pavement', strftime('%s','now')*1000),
(13, '보리차', 'barley tea', strftime('%s','now')*1000),
(13, '보물', 'treasure', strftime('%s','now')*1000),
(13, '보살피다', 'to take care of, to look after', strftime('%s','now')*1000),
(13, '보상01', 'compensation, reward', strftime('%s','now')*1000),
(13, '보수02', 'conservative, maintenance, repair', strftime('%s','now')*1000),
(13, '보안', 'security, protection', strftime('%s','now')*1000),
(13, '보완', 'supplement, complement', strftime('%s','now')*1000),
(13, '보장', 'guarantee, assurance', strftime('%s','now')*1000),
(13, '보전', 'preservation, conservation', strftime('%s','now')*1000),
(13, '보조02', 'assistance, aid, subsidy', strftime('%s','now')*1000),
(13, '보존', 'preservation, keeping', strftime('%s','now')*1000),
(13, '보충', 'supplement, replenishment', strftime('%s','now')*1000),
(13, '복수01', 'revenge, multiple, plural', strftime('%s','now')*1000),
(13, '볶음', 'fried dish, stir-fry', strftime('%s','now')*1000),
(13, '본능', 'instinct', strftime('%s','now')*1000),
(13, '본래', 'originally, inherently', strftime('%s','now')*1000),
(13, '본부', 'headquarters', strftime('%s','now')*1000),
(13, '본질02', 'essence, nature', strftime('%s','now')*1000),
(13, '볼01', 'cheek', strftime('%s','now')*1000),
(13, '부-01', 'sub-, vice-, deputy (prefix)', strftime('%s','now')*1000),
(13, '부03', 'department, section', strftime('%s','now')*1000),
(13, '부근03', 'vicinity, nearby area', strftime('%s','now')*1000),
(13, '부끄러움', 'shame, embarrassment', strftime('%s','now')*1000),
(13, '부끄러워하다', 'to feel shy, to be embarrassed', strftime('%s','now')*1000),
(13, '부담스럽다', 'burdensome, heavy', strftime('%s','now')*1000),
(13, '부대03', 'unit, troop', strftime('%s','now')*1000),
(13, '부딪치다', 'to bump into, to collide', strftime('%s','now')*1000),
(13, '부딪히다', 'to bump, to crash, to be hit', strftime('%s','now')*1000),
(13, '부문', 'sector, field, division', strftime('%s','now')*1000),
(13, '부분적01∙부분적02', 'partial', strftime('%s','now')*1000),
(13, '부상01', 'injury, wound', strftime('%s','now')*1000),
(13, '부서', 'department, division', strftime('%s','now')*1000),
(13, '부서지다', 'to be broken, to shatter', strftime('%s','now')*1000),
(13, '부수다', 'to break, to destroy', strftime('%s','now')*1000),
(13, '부위04', 'part, region, area (of body)', strftime('%s','now')*1000),
(13, '부작용', 'side effect', strftime('%s','now')*1000),
(13, '부정01', 'denial, negation', strftime('%s','now')*1000),
(13, '부정06', 'illegality, corruption', strftime('%s','now')*1000),
(13, '부정적01∙부정적02', 'negative', strftime('%s','now')*1000),
(13, '부정확', 'inaccuracy, incorrectness', strftime('%s','now')*1000),
(13, '부족02', 'shortage, lack', strftime('%s','now')*1000),
(13, '부주의', 'carelessness, negligence', strftime('%s','now')*1000),
(13, '부지런히', 'diligently, industriously', strftime('%s','now')*1000),
(13, '부처01', 'Buddha, government department', strftime('%s','now')*1000),
(13, '부치다04', 'to send (by mail)', strftime('%s','now')*1000),
(13, '부품', 'part, component', strftime('%s','now')*1000),
(13, '북미', 'North America', strftime('%s','now')*1000),
(13, '분노', 'anger, rage', strftime('%s','now')*1000),
(13, '분량', 'amount, quantity, portion', strftime('%s','now')*1000),
(13, '분류', 'classification, sorting', strftime('%s','now')*1000),
(13, '분명', 'clear, obvious', strftime('%s','now')*1000),
(13, '분석', 'analysis', strftime('%s','now')*1000),
(13, '분수01', 'fountain', strftime('%s','now')*1000),
(13, '분수03', 'duty, one’s place', strftime('%s','now')*1000),
(13, '분야', 'field, area, sector', strftime('%s','now')*1000),
(13, '분포', 'distribution, spread', strftime('%s','now')*1000),
(13, '불가', 'impossibility, prohibition', strftime('%s','now')*1000),
(13, '불가능', 'impossibility', strftime('%s','now')*1000),
(13, '불가피하다', 'inevitable, unavoidable', strftime('%s','now')*1000),
(13, '불교', 'Buddhism', strftime('%s','now')*1000),
(13, '불구하다', 'to disregard, to be regardless of', strftime('%s','now')*1000),
(13, '불꽃', 'flame, spark, fireworks', strftime('%s','now')*1000),
(13, '불러일으키다', 'to cause, to arouse', strftime('%s','now')*1000),
(13, '불리', 'disadvantage, handicap', strftime('%s','now')*1000),
(13, '불리다02', 'to be called, to be sung', strftime('%s','now')*1000),
(13, '불법01', 'illegal, unlawful', strftime('%s','now')*1000),
(13, '불빛', 'light, glow', strftime('%s','now')*1000),
(13, '불어오다', 'to blow (wind)', strftime('%s','now')*1000),
(13, '불이익', 'disadvantage, loss', strftime('%s','now')*1000),
(13, '불충분', 'insufficiency, inadequacy', strftime('%s','now')*1000),
(13, '불친절', 'unkindness, rudeness', strftime('%s','now')*1000),
(13, '불쾌', 'unpleasantness, discomfort', strftime('%s','now')*1000),
(13, '불평등', 'inequality', strftime('%s','now')*1000),
(13, '불필요', 'unnecessary', strftime('%s','now')*1000),
(13, '불행', 'misfortune, unhappiness', strftime('%s','now')*1000),
(13, '불확실', 'uncertainty', strftime('%s','now')*1000),
(13, '붙들다', 'to hold, to grab tightly', strftime('%s','now')*1000),
(13, '붙잡다', 'to hold onto, to seize', strftime('%s','now')*1000),
(13, '붙잡히다', 'to be caught, to be arrested', strftime('%s','now')*1000),
(13, '비-01', 'non-, un-, not (prefix)', strftime('%s','now')*1000),
(13, '비결', 'secret, key, know-how', strftime('%s','now')*1000),
(13, '비교적01/비교적02∙비교적03', 'comparatively, relatively', strftime('%s','now')*1000),
(13, '비극', 'tragedy', strftime('%s','now')*1000),
(13, '비기다01', 'to end in a tie', strftime('%s','now')*1000),
(13, '비난', 'criticism, blame', strftime('%s','now')*1000),
(13, '비닐', 'vinyl', strftime('%s','now')*1000),
(13, '비로소', 'at last, only then', strftime('%s','now')*1000),
(13, '비록01', 'although, though', strftime('%s','now')*1000),
(13, '비롯되다', 'to originate, to begin', strftime('%s','now')*1000),
(13, '비롯하다', 'to start, to originate', strftime('%s','now')*1000),
(13, '비만01', 'obesity', strftime('%s','now')*1000),
(13, '비명02', 'scream, shriek', strftime('%s','now')*1000),
(13, '비바람', 'wind and rain', strftime('%s','now')*1000),
(13, '비법', 'secret method', strftime('%s','now')*1000),
(13, '비상01', 'emergency', strftime('%s','now')*1000),
(13, '비상하다', 'to be extraordinary', strftime('%s','now')*1000),
(13, '비우다', 'to empty', strftime('%s','now')*1000),
(13, '비웃다', 'to sneer at, to ridicule', strftime('%s','now')*1000),
(13, '비유', 'metaphor, simile', strftime('%s','now')*1000),
(13, '비율', 'ratio, proportion', strftime('%s','now')*1000),
(13, '비중', 'relative importance, weight', strftime('%s','now')*1000),
(13, '비추다', 'to shine on, to reflect', strftime('%s','now')*1000),
(13, '비치다', 'to be reflected, to be seen', strftime('%s','now')*1000),
(13, '비틀거리다', 'to stagger, to reel', strftime('%s','now')*1000),
(13, '비판', 'criticism, critique', strftime('%s','now')*1000),
(13, '비판적01∙비판적02', 'critical', strftime('%s','now')*1000),
(13, '빗', 'comb', strftime('%s','now')*1000),
(13, '빗물', 'rainwater', strftime('%s','now')*1000),
(13, '빗방울', 'raindrop', strftime('%s','now')*1000),
(13, '빚', 'debt', strftime('%s','now')*1000),
(13, '빚다', 'to make; to knead', strftime('%s','now')*1000),
(13, '빛깔', 'color, hue', strftime('%s','now')*1000),
(13, '빛나다', 'to shine, to sparkle', strftime('%s','now')*1000),
(13, '빠뜨리다', 'to drop; to omit', strftime('%s','now')*1000),
(13, '빠져나가다', 'to slip out, to escape', strftime('%s','now')*1000),
(13, '빠져나오다', 'to get out, to escape', strftime('%s','now')*1000),
(13, '빠짐없이', 'without omission, completely', strftime('%s','now')*1000),
(13, '빼놓다', 'to leave out; to set aside', strftime('%s','now')*1000),
(13, '빼앗기다', 'to be taken away, to be deprived', strftime('%s','now')*1000),
(13, '빼앗다', 'to take away, to deprive', strftime('%s','now')*1000),
(13, '뺨', 'cheek', strftime('%s','now')*1000),
(13, '뻗다', 'to stretch out, to extend', strftime('%s','now')*1000),
(13, '뽑히다', 'to be chosen; to be pulled out', strftime('%s','now')*1000),
(13, '뿌리치다', 'to shake off, to reject', strftime('%s','now')*1000),
(13, '-사05', 'suffix: person; specialist', strftime('%s','now')*1000),
(13, '-사06', 'suffix: company; firm', strftime('%s','now')*1000),
(13, '사고방식', 'way of thinking', strftime('%s','now')*1000),
(13, '사기03', 'fraud, swindle', strftime('%s','now')*1000),
(13, '사내01', 'in-house; inside the company', strftime('%s','now')*1000),
(13, '사냥', 'hunting', strftime('%s','now')*1000),
(13, '사들이다', 'to buy up, to purchase', strftime('%s','now')*1000),
(13, '사랑스럽다', 'lovely, lovable', strftime('%s','now')*1000),
(13, '사례01', 'example, case', strftime('%s','now')*1000),
(13, '사로잡다', 'to captivate, to seize', strftime('%s','now')*1000),
(13, '사립', 'private (established privately)', strftime('%s','now')*1000),
(13, '사막', 'desert', strftime('%s','now')*1000),
(13, '사망', 'death', strftime('%s','now')*1000),
(13, '사무직', 'office work, clerical job', strftime('%s','now')*1000),
(13, '사방', 'on all sides, everywhere', strftime('%s','now')*1000),
(13, '사상01', 'thought, ideology', strftime('%s','now')*1000),
(13, '사설02', 'editorial', strftime('%s','now')*1000),
(13, '사소하다', 'trivial, insignificant', strftime('%s','now')*1000),
(13, '사업자', 'business operator', strftime('%s','now')*1000),
(13, '사연04', 'story, circumstances', strftime('%s','now')*1000),
(13, '사용자', 'user', strftime('%s','now')*1000),
(13, '사위', 'son-in-law', strftime('%s','now')*1000),
(13, '사이버00', 'cyber', strftime('%s','now')*1000),
(13, '사이좋다', 'to be on good terms', strftime('%s','now')*1000),
(13, '사정01', 'circumstances, situation', strftime('%s','now')*1000),
(13, '사진첩', 'photo album', strftime('%s','now')*1000),
(13, '사춘기', 'puberty, adolescence', strftime('%s','now')*1000),
(13, '사태02', 'situation, state of affairs', strftime('%s','now')*1000),
(13, '사투리', 'dialect', strftime('%s','now')*1000),
(13, '사표02', 'letter of resignation', strftime('%s','now')*1000),
(13, '사회생활', 'social life', strftime('%s','now')*1000),
(13, '산길', 'mountain path', strftime('%s','now')*1000),
(13, '산불', 'forest fire', strftime('%s','now')*1000),
(13, '산속', 'in the mountains', strftime('%s','now')*1000),
(13, '살리다', 'to save, to revive', strftime('%s','now')*1000),
(13, '살림', 'household, living', strftime('%s','now')*1000),
(13, '살아가다', 'to live, to make a living', strftime('%s','now')*1000),
(13, '살아남다', 'to survive', strftime('%s','now')*1000),
(13, '살아오다', 'to have lived', strftime('%s','now')*1000),
(13, '삼다', 'to make; to regard as', strftime('%s','now')*1000),
(13, '삼키다', 'to swallow', strftime('%s','now')*1000),
(13, '상가01', 'shopping arcade, mall', strftime('%s','now')*1000),
(13, '상관02', 'relation, concern', strftime('%s','now')*1000),
(13, '상관없이', 'regardless of', strftime('%s','now')*1000),
(13, '상금', 'prize money', strftime('%s','now')*1000),
(13, '상담실00', 'counseling room', strftime('%s','now')*1000),
(13, '상담원', 'counselor, operator', strftime('%s','now')*1000),
(13, '상당하다', 'considerable, significant', strftime('%s','now')*1000),
(13, '상당히', 'considerably, quite', strftime('%s','now')*1000),
(13, '상대', 'counterpart, opponent', strftime('%s','now')*1000),
(13, '상대적01·상대적02', 'relative', strftime('%s','now')*1000),
(13, '상대편', 'the other party, the opposite side', strftime('%s','now')*1000),
(13, '상류', 'upper class; upstream', strftime('%s','now')*1000),
(13, '상반기', 'first half (of the year)', strftime('%s','now')*1000),
(13, '상사00', 'boss, superior', strftime('%s','now')*1000),
(13, '상상', 'imagination', strftime('%s','now')*1000),
(13, '상상력', 'imagination, creativity', strftime('%s','now')*1000),
(13, '상승', 'rise, increase', strftime('%s','now')*1000),
(13, '상업', 'commerce, business', strftime('%s','now')*1000),
(13, '상징', 'symbol', strftime('%s','now')*1000),
(13, '상쾌하다', 'to be refreshing', strftime('%s','now')*1000),
(13, '상하', 'up and down; upper and lower', strftime('%s','now')*1000),
(13, '새01', 'bird', strftime('%s','now')*1000);