PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(6, '가게', 'store', strftime('%s','now')*1000),
(6, '가꾸다', 'cultivate', strftime('%s','now')*1000),
(6, '가난', 'poverty', strftime('%s','now')*1000),
(6, '가능', 'possibility', strftime('%s','now')*1000),
(6, '가득하다', 'be full', strftime('%s','now')*1000),
(6, '가득히', 'fully', strftime('%s','now')*1000),
(6, '가렵다', 'itchy', strftime('%s','now')*1000),
(6, '가로', 'width / street', strftime('%s','now')*1000),
(6, '가루', 'powder', strftime('%s','now')*1000),
(6, '가리다', 'cover / distinguish', strftime('%s','now')*1000),
(6, '가스', 'gas', strftime('%s','now')*1000),
(6, '가스레인지', 'gas stove', strftime('%s','now')*1000),
(6, '가습기', 'humidifier', strftime('%s','now')*1000),
(6, '가입', 'subscription / joining', strftime('%s','now')*1000),
(6, '가입자', 'subscriber', strftime('%s','now')*1000),
(6, '가전제품', 'home appliance', strftime('%s','now')*1000),
(6, '가정', 'home / family', strftime('%s','now')*1000),
(6, '가죽', 'leather', strftime('%s','now')*1000),
(6, '각', 'each / angle', strftime('%s','now')*1000),
(6, '각자', 'each person / respectively', strftime('%s','now')*1000),
(6, '간', 'liver / relationship', strftime('%s','now')*1000),
(6, '간판', 'signboard', strftime('%s','now')*1000),
(6, '간호', 'nursing', strftime('%s','now')*1000),
(6, '갈다', 'change / sharpen', strftime('%s','now')*1000),
(6, '갈증', 'thirst', strftime('%s','now')*1000),
(6, '-감', 'feeling / sense (suffix)', strftime('%s','now')*1000),
(6, '감각', 'sense', strftime('%s','now')*1000),
(6, '감다', 'close eyes / wind up', strftime('%s','now')*1000),
(6, '감독', 'director / supervision', strftime('%s','now')*1000),
(6, '감동', 'emotion / impression', strftime('%s','now')*1000),
(6, '감동적', 'moving / touching', strftime('%s','now')*1000),
(6, '감상', 'appreciation', strftime('%s','now')*1000),
(6, '감정', 'emotion / feeling', strftime('%s','now')*1000),
(6, '강물', 'river water', strftime('%s','now')*1000),
(6, '강사', 'instructor', strftime('%s','now')*1000),
(6, '개나리', 'forsythia', strftime('%s','now')*1000),
(6, '개다', 'clear up / fold', strftime('%s','now')*1000),
(6, '개인', 'individual', strftime('%s','now')*1000),
(6, '개인적', 'personal', strftime('%s','now')*1000),
(6, '걔', 'that kid', strftime('%s','now')*1000),
(6, '거꾸로', 'upside down / backward', strftime('%s','now')*1000),
(6, '거스름돈', 'change (money)', strftime('%s','now')*1000),
(6, '거품', 'foam / bubble', strftime('%s','now')*1000),
(6, '건널목', 'crosswalk / railroad crossing', strftime('%s','now')*1000),
(6, '건조', 'dryness', strftime('%s','now')*1000),
(6, '걸레', 'rag / mop', strftime('%s','now')*1000),
(6, '검다', 'black / dark', strftime('%s','now')*1000),
(6, '검색', 'search', strftime('%s','now')*1000),
(6, '검토', 'review / examination', strftime('%s','now')*1000),
(6, '겁', 'fear', strftime('%s','now')*1000),
(6, '겉옷', 'outerwear', strftime('%s','now')*1000),
(6, '게시', 'posting', strftime('%s','now')*1000),
(6, '게시판', 'bulletin board', strftime('%s','now')*1000),
(6, '겨우', 'barely / only', strftime('%s','now')*1000),
(6, '결국', 'eventually / after all', strftime('%s','now')*1000),
(6, '결제', 'payment', strftime('%s','now')*1000),
(6, '경기장', 'stadium', strftime('%s','now')*1000),
(6, '경복궁', 'Gyeongbok Palace', strftime('%s','now')*1000),
(6, '경비', 'expense / guard', strftime('%s','now')*1000),
(6, '경비실', 'security office', strftime('%s','now')*1000),
(6, '경우', 'case / situation', strftime('%s','now')*1000),
(6, '경제', 'economy', strftime('%s','now')*1000),
(6, '경제적', 'economic', strftime('%s','now')*1000),
(6, '경찰관', 'police officer', strftime('%s','now')*1000),
(6, '곁', 'beside / side', strftime('%s','now')*1000),
(6, '계곡', 'valley', strftime('%s','now')*1000),
(6, '계약', 'contract', strftime('%s','now')*1000),
(6, '계약금', 'deposit / down payment', strftime('%s','now')*1000),
(6, '계좌', 'bank account', strftime('%s','now')*1000),
(6, '고객', 'customer', strftime('%s','now')*1000),
(6, '고구마', 'sweet potato', strftime('%s','now')*1000),
(6, '고궁', 'ancient palace', strftime('%s','now')*1000),
(6, '고백', 'confession', strftime('%s','now')*1000),
(6, '고생', 'hardship', strftime('%s','now')*1000),
(6, '고속', 'high-speed', strftime('%s','now')*1000),
(6, '고추', 'chili pepper', strftime('%s','now')*1000),
(6, '고춧가루', 'chili powder', strftime('%s','now')*1000),
(6, '곤란', 'difficulty / trouble', strftime('%s','now')*1000),
(6, '곧이어', 'immediately after', strftime('%s','now')*1000),
(6, '곧장', 'straight / directly', strftime('%s','now')*1000),
(6, '골고루', 'evenly', strftime('%s','now')*1000),
(6, '골목', 'alley', strftime('%s','now')*1000),
(6, '골목길', 'narrow alleyway', strftime('%s','now')*1000),
(6, '골프', 'golf', strftime('%s','now')*1000),
(6, '곰', 'bear', strftime('%s','now')*1000),
(6, '곱다', 'beautiful / soft', strftime('%s','now')*1000),
(6, '곱하다', 'multiply', strftime('%s','now')*1000),
(6, '곳곳', 'everywhere / in many places', strftime('%s','now')*1000),
(6, '공', 'ball / zero', strftime('%s','now')*1000),
(6, '공간', 'space', strftime('%s','now')*1000),
(6, '공공', 'public', strftime('%s','now')*1000),
(6, '공공장소', 'public place', strftime('%s','now')*1000),
(6, '공과금', 'utility bill', strftime('%s','now')*1000),
(6, '공기', 'air', strftime('%s','now')*1000),
(6, '공동', 'joint / shared', strftime('%s','now')*1000),
(6, '공사', 'construction', strftime('%s','now')*1000),
(6, '공식', 'formula / official', strftime('%s','now')*1000),
(6, '공연', 'performance', strftime('%s','now')*1000),
(6, '공연장', 'theater / concert hall', strftime('%s','now')*1000),
(6, '공주', 'princess', strftime('%s','now')*1000),
(6, '공중전화', 'public phone', strftime('%s','now')*1000),
(6, '공통', 'common', strftime('%s','now')*1000),
(6, '공통점', 'common point', strftime('%s','now')*1000),
(6, '공포', 'fear / horror', strftime('%s','now')*1000),
(6, '과', 'department / lesson / subject', strftime('%s','now')*1000),
(6, '과로', 'overwork', strftime('%s','now')*1000),
(6, '과목', 'subject', strftime('%s','now')*1000),
(6, '과식', 'overeating', strftime('%s','now')*1000),
(6, '과장', 'manager / exaggeration', strftime('%s','now')*1000),
(6, '과정', 'process / course', strftime('%s','now')*1000),
(6, '과학', 'science', strftime('%s','now')*1000),
(6, '과학자', 'scientist', strftime('%s','now')*1000),
(6, '관객', 'audience / spectator', strftime('%s','now')*1000),
(6, '관계없다', 'be unrelated', strftime('%s','now')*1000),
(6, '관계없이', 'regardless of', strftime('%s','now')*1000),
(6, '관계있다', 'be related', strftime('%s','now')*1000),
(6, '관람', 'viewing / watching', strftime('%s','now')*1000),
(6, '관람객', 'spectator / visitor', strftime('%s','now')*1000),
(6, '관련', 'relation / connection', strftime('%s','now')*1000),
(6, '관리', 'management', strftime('%s','now')*1000),
(6, '관찰', 'observation', strftime('%s','now')*1000),
(6, '광경', 'scene / sight', strftime('%s','now')*1000),
(6, '굉장히', 'very / extremely', strftime('%s','now')*1000),
(6, '교시', 'class period', strftime('%s','now')*1000),
(6, '교외', 'suburbs', strftime('%s','now')*1000),
(6, '교통수단', 'means of transportation', strftime('%s','now')*1000),
(6, '교통편', 'transportation', strftime('%s','now')*1000),
(6, '교포', 'Korean living abroad', strftime('%s','now')*1000),
(6, '구', 'district / section', strftime('%s','now')*1000),
(6, '구경거리', 'sight / attraction', strftime('%s','now')*1000),
(6, '구멍', 'hole', strftime('%s','now')*1000),
(6, '구수하다', 'savory / tasty', strftime('%s','now')*1000),
(6, '구역', 'zone / area', strftime('%s','now')*1000),
(6, '구입', 'purchase', strftime('%s','now')*1000),
(6, '구조', 'structure / rescue', strftime('%s','now')*1000),
(6, '구체적', 'concrete / specific', strftime('%s','now')*1000),
(6, '구하다', 'seek / obtain / save', strftime('%s','now')*1000),
(6, '국가', 'nation / country', strftime('%s','now')*1000),
(6, '국기', 'national flag', strftime('%s','now')*1000),
(6, '국내선', 'domestic flight', strftime('%s','now')*1000),
(6, '국립', 'national (institution)', strftime('%s','now')*1000),
(6, '국물', 'soup / broth', strftime('%s','now')*1000),
(6, '국민', 'citizen / people', strftime('%s','now')*1000),
(6, '국어', 'Korean language', strftime('%s','now')*1000),
(6, '군대', 'military / army', strftime('%s','now')*1000),
(6, '굶다', 'starve / skip a meal', strftime('%s','now')*1000),
(6, '굽', 'heel (of a shoe)', strftime('%s','now')*1000),
(6, '권하다', 'recommend / advise', strftime('%s','now')*1000),
(6, '귀하', 'dear / sir or madam', strftime('%s','now')*1000),
(6, '규칙적', 'regular / systematic', strftime('%s','now')*1000),
(6, '그녀', 'she / her', strftime('%s','now')*1000),
(6, '그래도', 'nevertheless / still', strftime('%s','now')*1000),
(6, '그램', 'gram', strftime('%s','now')*1000),
(6, '그러다', 'do so / act like that', strftime('%s','now')*1000),
(6, '그룹', 'group', strftime('%s','now')*1000),
(6, '그만하다', 'stop / quit', strftime('%s','now')*1000),
(6, '그저', 'just / merely', strftime('%s','now')*1000),
(6, '그제', 'the day before yesterday', strftime('%s','now')*1000),
(6, '그중', 'among them', strftime('%s','now')*1000),
(6, '근데', 'by the way / however', strftime('%s','now')*1000),
(6, '근무', 'duty / work', strftime('%s','now')*1000),
(6, '근육', 'muscle', strftime('%s','now')*1000),
(6, '금', 'gold / Friday', strftime('%s','now')*1000),
(6, '금액', 'amount of money', strftime('%s','now')*1000),
(6, '금연', 'no smoking', strftime('%s','now')*1000),
(6, '긋다', 'draw a line / strike', strftime('%s','now')*1000),
(6, '긍정적', 'positive / affirmative', strftime('%s','now')*1000),
(6, '-기', 'nominalizing suffix', strftime('%s','now')*1000),
(6, '기계', 'machine', strftime('%s','now')*1000),
(6, '기관', 'organization / institution', strftime('%s','now')*1000),
(6, '기구', 'equipment / organization', strftime('%s','now')*1000),
(6, '기념', 'commemoration', strftime('%s','now')*1000),
(6, '기념품', 'souvenir', strftime('%s','now')*1000),
(6, '기능', 'function', strftime('%s','now')*1000),
(6, '기다', 'expect / wait (archaic verb)', strftime('%s','now')*1000),
(6, '기대', 'expectation', strftime('%s','now')*1000),
(6, '기대다', 'lean on / rely on', strftime('%s','now')*1000),
(6, '기도', 'prayer', strftime('%s','now')*1000),
(6, '기말시험', 'final exam', strftime('%s','now')*1000),
(6, '기사', 'article / driver', strftime('%s','now')*1000),
(6, '기술자', 'technician / engineer', strftime('%s','now')*1000),
(6, '기억력', 'memory ability', strftime('%s','now')*1000),
(6, '기업', 'enterprise / company', strftime('%s','now')*1000),
(6, '기준', 'standard / criterion', strftime('%s','now')*1000),
(6, '기초', 'basic / foundation', strftime('%s','now')*1000),
(6, '기타', 'guitar / others', strftime('%s','now')*1000),
(6, '긴급', 'urgent', strftime('%s','now')*1000),
(6, '긴팔', 'long sleeves', strftime('%s','now')*1000),
(6, '길다', 'long', strftime('%s','now')*1000),
(6, '김', 'seaweed', strftime('%s','now')*1000),
(6, '까다', 'peel / scrape', strftime('%s','now')*1000),
(6, '깔끔하다', 'neat / tidy', strftime('%s','now')*1000),
(6, '깜빡', 'momentarily / blink', strftime('%s','now')*1000),
(6, '깨지다', 'break / shatter', strftime('%s','now')*1000),
(6, '꺼지다', 'go out / be turned off', strftime('%s','now')*1000),
(6, '껍질', 'peel / shell / skin', strftime('%s','now')*1000),
(6, '꼬리', 'tail', strftime('%s','now')*1000),
(6, '꼼짝', 'movement / motion', strftime('%s','now')*1000),
(6, '꽂다', 'stick in / plug in', strftime('%s','now')*1000),
(6, '꽃무늬', 'floral pattern', strftime('%s','now')*1000),
(6, '꽉', 'tightly / firmly', strftime('%s','now')*1000),
(6, '꽤', 'quite / fairly', strftime('%s','now')*1000),
(6, '꾸준히', 'steadily / consistently', strftime('%s','now')*1000),
(6, '꿀', 'honey', strftime('%s','now')*1000),
(6, '끈', 'string / cord', strftime('%s','now')*1000),
(6, '끊기다', 'be cut off / disconnected', strftime('%s','now')*1000),
(6, '끊어지다', 'snap / break', strftime('%s','now')*1000),
(6, '끌다', 'pull / drag', strftime('%s','now')*1000),
(6, '끝내', 'finally / in the end', strftime('%s','now')*1000),
(6, '끼', 'talent / natural gift', strftime('%s','now')*1000),
(6, '끼다', 'wear / be stuck / foggy', strftime('%s','now')*1000),
(6, '나르다', 'carry / transport', strftime('%s','now')*1000),
(6, '나물', 'seasoned vegetables', strftime('%s','now')*1000),
(6, '나뭇잎', 'leaf', strftime('%s','now')*1000),
(6, '나빠지다', 'get worse', strftime('%s','now')*1000),
(6, '나아지다', 'improve / get better', strftime('%s','now')*1000),
(6, '나이프', 'knife', strftime('%s','now')*1000),
(6, '나타내다', 'show / express', strftime('%s','now')*1000),
(6, '낙엽', 'fallen leaves', strftime('%s','now')*1000),
(6, '난로', 'heater', strftime('%s','now')*1000),
(6, '난방', 'heating', strftime('%s','now')*1000),
(6, '날아가다', 'fly away', strftime('%s','now')*1000),
(6, '낡다', 'old / worn-out', strftime('%s','now')*1000),
(6, '남', 'man / others', strftime('%s','now')*1000),
(6, '남미', 'South America', strftime('%s','now')*1000),
(6, '남부', 'southern part', strftime('%s','now')*1000),
(6, '낯설다', 'unfamiliar', strftime('%s','now')*1000),
(6, '낳다', 'give birth / produce', strftime('%s','now')*1000),
(6, '내', 'inside / my / river', strftime('%s','now')*1000),
(6, '내내', 'all the time / throughout', strftime('%s','now')*1000),
(6, '내달', 'next month', strftime('%s','now')*1000),
(6, '내려놓다', 'put down / lay down', strftime('%s','now')*1000),
(6, '내보내다', 'send out / expel', strftime('%s','now')*1000),
(6, '내성적', 'introverted', strftime('%s','now')*1000),
(6, '내주다', 'give / hand over', strftime('%s','now')*1000),
(6, '내후년', 'the year after next', strftime('%s','now')*1000),
(6, '낼모레', 'in two days', strftime('%s','now')*1000),
(6, '냉동', 'freezing / frozen', strftime('%s','now')*1000),
(6, '냉방', 'air conditioning', strftime('%s','now')*1000),
(6, '냉정하다', 'cold-hearted / calm', strftime('%s','now')*1000),
(6, '널다', 'hang / spread', strftime('%s','now')*1000),
(6, '널리', 'widely', strftime('%s','now')*1000),
(6, '넓이', 'width / area', strftime('%s','now')*1000),
(6, '넘어가다', 'cross / move on', strftime('%s','now')*1000),
(6, '넘어서다', 'go beyond / exceed', strftime('%s','now')*1000),
(6, '년대', 'era / decade', strftime('%s','now')*1000),
(6, '노랑', 'yellow', strftime('%s','now')*1000),
(6, '노선', 'route / line', strftime('%s','now')*1000),
(6, '노선도', 'route map', strftime('%s','now')*1000),
(6, '노약자', 'elderly and weak people', strftime('%s','now')*1000),
(6, '노트북', 'laptop', strftime('%s','now')*1000),
(6, '녹다', 'melt / dissolve', strftime('%s','now')*1000),
(6, '녹음', 'recording', strftime('%s','now')*1000),
(6, '녹음기', 'recorder', strftime('%s','now')*1000),
(6, '놀이공원', 'amusement park', strftime('%s','now')*1000),
(6, '놀이터', 'playground', strftime('%s','now')*1000),
(6, '농부', 'farmer', strftime('%s','now')*1000),
(6, '농사', 'farming', strftime('%s','now')*1000),
(6, '높아지다', 'rise / increase', strftime('%s','now')*1000),
(6, '높이다', 'raise / heighten', strftime('%s','now')*1000),
(6, '높임말', 'honorific language', strftime('%s','now')*1000),
(6, '놓이다', 'be placed / laid', strftime('%s','now')*1000),
(6, '놓치다', 'miss / lose', strftime('%s','now')*1000),
(6, '눈가', 'area around eyes', strftime('%s','now')*1000),
(6, '눈병', 'eye disease', strftime('%s','now')*1000),
(6, '눈부시다', 'dazzling / radiant', strftime('%s','now')*1000),
(6, '눈사람', 'snowman', strftime('%s','now')*1000),
(6, '눈싸움', 'snowball fight', strftime('%s','now')*1000),
(6, '늘리다', 'increase / expand', strftime('%s','now')*1000),
(6, '늘어나다', 'grow / stretch', strftime('%s','now')*1000),
(6, '늦잠', 'oversleep', strftime('%s','now')*1000),
(6, '-님', 'honorific suffix', strftime('%s','now')*1000),
(6, '다리미', 'iron', strftime('%s','now')*1000),
(6, '다림질', 'ironing', strftime('%s','now')*1000),
(6, '다방', 'coffeehouse', strftime('%s','now')*1000),
(6, '다운로드', 'download', strftime('%s','now')*1000),
(6, '다정', 'kind / affectionate', strftime('%s','now')*1000),
(6, '다지다', 'strengthen / chop finely', strftime('%s','now')*1000),
(6, '다행', 'good fortune / relief', strftime('%s','now')*1000),
(6, '다행히', 'fortunately', strftime('%s','now')*1000),
(6, '단단하다', 'hard / solid', strftime('%s','now')*1000),
(6, '단맛', 'sweet taste', strftime('%s','now')*1000),
(6, '단발머리', 'bobbed hair', strftime('%s','now')*1000),
(6, '단위', 'unit', strftime('%s','now')*1000),
(6, '단점', 'weakness / flaw', strftime('%s','now')*1000),
(6, '단정하다', 'neat / tidy', strftime('%s','now')*1000),
(6, '단지', 'only / complex', strftime('%s','now')*1000),
(6, '단체', 'organization / group', strftime('%s','now')*1000),
(6, '닫히다', 'be closed', strftime('%s','now')*1000),
(6, '달다', 'sweet / attach / hang', strftime('%s','now')*1000),
(6, '달라지다', 'change / become different', strftime('%s','now')*1000),
(6, '달러', 'dollar', strftime('%s','now')*1000),
(6, '달콤하다', 'sweet / honeyed', strftime('%s','now')*1000),
(6, '담그다', 'soak / pickle', strftime('%s','now')*1000),
(6, '담기다', 'be put into', strftime('%s','now')*1000),
(6, '담다', 'put in / include', strftime('%s','now')*1000),
(6, '닷새', 'five days', strftime('%s','now')*1000),
(6, '당근', 'carrot', strftime('%s','now')*1000),
(6, '당신', 'you (formal)', strftime('%s','now')*1000),
(6, '당연하다', 'natural / reasonable', strftime('%s','now')*1000),
(6, '당연히', 'naturally / of course', strftime('%s','now')*1000),
(6, '당장', 'immediately', strftime('%s','now')*1000),
(6, '당황', 'embarrassment / confusion', strftime('%s','now')*1000),
(6, '닿다', 'touch / reach', strftime('%s','now')*1000),
(6, '대', 'generation / counter for vehicles', strftime('%s','now')*1000),
(6, '대다', 'touch / put against', strftime('%s','now')*1000),
(6, '대단하다', 'great / amazing', strftime('%s','now')*1000),
(6, '대도시', 'metropolitan city', strftime('%s','now')*1000),
(6, '대문', 'main gate', strftime('%s','now')*1000),
(6, '대변', 'stool / excretion', strftime('%s','now')*1000),
(6, '대상', 'target / subject', strftime('%s','now')*1000),
(6, '대신', 'instead of', strftime('%s','now')*1000),
(6, '대여섯', 'about six', strftime('%s','now')*1000),
(6, '대중', 'public / mass', strftime('%s','now')*1000),
(6, '대중가요', 'popular song', strftime('%s','now')*1000),
(6, '대중교통', 'public transportation', strftime('%s','now')*1000),
(6, '대청소', 'big cleaning', strftime('%s','now')*1000),
(6, '대체로', 'generally / mostly', strftime('%s','now')*1000),
(6, '대통령', 'president', strftime('%s','now')*1000),
(6, '대표', 'representative', strftime('%s','now')*1000),
(6, '대표적', 'typical / representative', strftime('%s','now')*1000),
(6, '대하다', 'deal with / face', strftime('%s','now')*1000),
(6, '대한민국', 'Republic of Korea', strftime('%s','now')*1000),
(6, '대형', 'large-scale', strftime('%s','now')*1000),
(6, '더러워지다', 'become dirty', strftime('%s','now')*1000),
(6, '더하다', 'add / increase', strftime('%s','now')*1000),
(6, '덜', 'less', strftime('%s','now')*1000),
(6, '덜다', 'reduce / lessen', strftime('%s','now')*1000),
(6, '덮다', 'cover', strftime('%s','now')*1000),
(6, '데', 'place / situation', strftime('%s','now')*1000),
(6, '데다', 'get burned', strftime('%s','now')*1000),
(6, '데리다', 'bring / take someone', strftime('%s','now')*1000),
(6, '데치다', 'parboil / blanch', strftime('%s','now')*1000),
(6, '도', 'province / also', strftime('%s','now')*1000),
(6, '도구', 'tool / instrument', strftime('%s','now')*1000),
(6, '도둑', 'thief', strftime('%s','now')*1000),
(6, '도망가다', 'run away / escape', strftime('%s','now')*1000),
(6, '도서', 'book / publication', strftime('%s','now')*1000),
(6, '도시락', 'lunch box', strftime('%s','now')*1000),
(6, '도심', 'downtown / city center', strftime('%s','now')*1000),
(6, '도자기', 'ceramics / pottery', strftime('%s','now')*1000),
(6, '도장', 'stamp / seal', strftime('%s','now')*1000),
(6, '도중', 'on the way / in the middle', strftime('%s','now')*1000),
(6, '독감', 'flu / influenza', strftime('%s','now')*1000),
(6, '독일어', 'German language', strftime('%s','now')*1000),
(6, '돌', 'stone / first birthday', strftime('%s','now')*1000),
(6, '돌려받다', 'get back / take back', strftime('%s','now')*1000),
(6, '돌보다', 'take care of / look after', strftime('%s','now')*1000),
(6, '돌아다니다', 'go around / wander', strftime('%s','now')*1000),
(6, '동', 'east / neighborhood', strftime('%s','now')*1000),
(6, '동그라미', 'circle', strftime('%s','now')*1000);