PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(1, '가게', 'store', strftime('%s','now')*1000),
(1, '가격', 'price', strftime('%s','now')*1000),
(1, '가다', 'to go', strftime('%s','now')*1000),
(1, '가르치다', 'to teach', strftime('%s','now')*1000),
(1, '가방', 'bag', strftime('%s','now')*1000),
(1, '가볍다', 'to be light', strftime('%s','now')*1000),
(1, '가수', 'singer', strftime('%s','now')*1000),
(1, '가요', 'song', strftime('%s','now')*1000),
(1, '가운데', 'middle', strftime('%s','now')*1000),
(1, '가을', 'autumn', strftime('%s','now')*1000),
(1, '가장', 'the most', strftime('%s','now')*1000),
(1, '가족', 'family', strftime('%s','now')*1000),
(1, '가지', 'branch', strftime('%s','now')*1000),
(1, '가지다', 'to have', strftime('%s','now')*1000),
(1, '갈비', 'ribs', strftime('%s','now')*1000),
(1, '갈비탕', 'beef rib soup', strftime('%s','now')*1000),
(1, '갈아타다', 'to transfer', strftime('%s','now')*1000),
(1, '감', 'persimmon', strftime('%s','now')*1000),
(1, '감기', 'cold (illness)', strftime('%s','now')*1000),
(1, '감사', 'thanks', strftime('%s','now')*1000),
(1, '값', 'price (value)', strftime('%s','now')*1000),
(1, '같다', 'to be same', strftime('%s','now')*1000),
(1, '같이', 'together', strftime('%s','now')*1000),
(1, '개', 'dog', strftime('%s','now')*1000),
(1, '거기', 'there', strftime('%s','now')*1000),
(1, '거실', 'living room', strftime('%s','now')*1000),
(1, '건강', 'health', strftime('%s','now')*1000),
(1, '건너편', 'opposite side', strftime('%s','now')*1000),
(1, '건물', 'building', strftime('%s','now')*1000),
(1, '걷다', 'to walk', strftime('%s','now')*1000),
(1, '걸다', 'to hang/call', strftime('%s','now')*1000),
(1, '걸리다', 'to take (time)/to get caught', strftime('%s','now')*1000),
(1, '것', 'thing', strftime('%s','now')*1000),
(1, '게임', 'game', strftime('%s','now')*1000),
(1, '겨울', 'winter', strftime('%s','now')*1000),
(1, '계속', 'continuously', strftime('%s','now')*1000),
(1, '계시다', 'to stay (honorific)', strftime('%s','now')*1000),
(1, '계절', 'season', strftime('%s','now')*1000),
(1, '계획', 'plan', strftime('%s','now')*1000),
(1, '고기', 'meat', strftime('%s','now')*1000),
(1, '고르다', 'to choose', strftime('%s','now')*1000),
(1, '고맙다', 'to be thankful', strftime('%s','now')*1000),
(1, '고양이', 'cat', strftime('%s','now')*1000),
(1, '고프다', 'to be hungry', strftime('%s','now')*1000),
(1, '고향', 'hometown', strftime('%s','now')*1000),
(1, '곳', 'place', strftime('%s','now')*1000),
(1, '공부', 'study', strftime('%s','now')*1000),
(1, '공원', 'park', strftime('%s','now')*1000),
(1, '공책', 'notebook', strftime('%s','now')*1000),
(1, '공항', 'airport', strftime('%s','now')*1000),
(1, '과일', 'fruit', strftime('%s','now')*1000),
(1, '괜찮다', 'to be okay', strftime('%s','now')*1000),
(1, '교실', 'classroom', strftime('%s','now')*1000),
(1, '교통', 'traffic', strftime('%s','now')*1000),
(1, '구경', 'sightseeing', strftime('%s','now')*1000),
(1, '구두', 'shoes', strftime('%s','now')*1000),
(1, '구월', 'September', strftime('%s','now')*1000),
(1, '국적', 'nationality', strftime('%s','now')*1000),
(1, '귀', 'ear', strftime('%s','now')*1000),
(1, '귤', 'mandarin', strftime('%s','now')*1000),
(1, '그것', 'that thing', strftime('%s','now')*1000),
(1, '그래서', 'so/therefore', strftime('%s','now')*1000),
(1, '그러니까', 'so/that means', strftime('%s','now')*1000),
(1, '그렇다', 'to be so', strftime('%s','now')*1000),
(1, '그릇', 'bowl', strftime('%s','now')*1000),
(1, '그리고', 'and', strftime('%s','now')*1000),
(1, '그리다', 'to draw', strftime('%s','now')*1000),
(1, '그림', 'picture', strftime('%s','now')*1000),
(1, '그저께', 'the day before yesterday', strftime('%s','now')*1000),
(1, '그쪽', 'that side', strftime('%s','now')*1000),
(1, '극장', 'theater', strftime('%s','now')*1000),
(1, '근처', 'nearby', strftime('%s','now')*1000),
(1, '글', 'writing', strftime('%s','now')*1000),
(1, '글쎄요', 'well.../let me see', strftime('%s','now')*1000),
(1, '금요일', 'Friday', strftime('%s','now')*1000),
(1, '기간', 'period', strftime('%s','now')*1000),
(1, '기다리다', 'to wait', strftime('%s','now')*1000),
(1, '기분', 'feeling/mood', strftime('%s','now')*1000),
(1, '기쁘다', 'to be glad', strftime('%s','now')*1000),
(1, '기숙사', 'dormitory', strftime('%s','now')*1000),
(1, '기차', 'train', strftime('%s','now')*1000),
(1, '길', 'road', strftime('%s','now')*1000),
(1, '길다', 'to be long', strftime('%s','now')*1000),
(1, '김밥', 'gimbap', strftime('%s','now')*1000),
(1, '김치', 'kimchi', strftime('%s','now')*1000),
(1, '김치찌개', 'kimchi stew', strftime('%s','now')*1000),
(1, '깨끗하다', 'to be clean', strftime('%s','now')*1000),
(1, '꼭', 'surely/must', strftime('%s','now')*1000),
(1, '꽃', 'flower', strftime('%s','now')*1000),
(1, '끄다', 'to turn off', strftime('%s','now')*1000),
(1, '끝나다', 'to end', strftime('%s','now')*1000),
(1, '나', 'I/me', strftime('%s','now')*1000),
(1, '나가다', 'to go out', strftime('%s','now')*1000),
(1, '나다', 'to occur/arise', strftime('%s','now')*1000),
(1, '나라', 'country', strftime('%s','now')*1000),
(1, '나무', 'tree/wood', strftime('%s','now')*1000),
(1, '나쁘다', 'to be bad', strftime('%s','now')*1000),
(1, '나오다', 'to come out', strftime('%s','now')*1000),
(1, '나중', 'later', strftime('%s','now')*1000),
(1, '날', 'day', strftime('%s','now')*1000),
(1, '날씨', 'weather', strftime('%s','now')*1000),
(1, '날짜', 'date', strftime('%s','now')*1000),
(1, '남대문', 'Namdaemun Gate', strftime('%s','now')*1000),
(1, '남동생', 'younger brother', strftime('%s','now')*1000),
(1, '남산', 'Namsan Mountain', strftime('%s','now')*1000),
(1, '남자', 'man', strftime('%s','now')*1000),
(1, '남편', 'husband', strftime('%s','now')*1000),
(1, '낮', 'daytime', strftime('%s','now')*1000),
(1, '낮다', 'to be low', strftime('%s','now')*1000),
(1, '내', 'my', strftime('%s','now')*1000),
(1, '내년', 'next year', strftime('%s','now')*1000),
(1, '내리다', 'to get off/fall', strftime('%s','now')*1000),
(1, '내일', 'tomorrow', strftime('%s','now')*1000),
(1, '냉면', 'cold noodles', strftime('%s','now')*1000),
(1, '너', 'you', strftime('%s','now')*1000),
(1, '너무', 'too/very', strftime('%s','now')*1000),
(1, '넓다', 'to be wide', strftime('%s','now')*1000),
(1, '넣다', 'to put in', strftime('%s','now')*1000),
(1, '네', 'yes', strftime('%s','now')*1000),
(1, '넷', 'four', strftime('%s','now')*1000),
(1, '년', 'year', strftime('%s','now')*1000),
(1, '노래', 'song', strftime('%s','now')*1000),
(1, '노래방', 'karaoke room', strftime('%s','now')*1000),
(1, '놀다', 'to play/hang out', strftime('%s','now')*1000),
(1, '농구', 'basketball', strftime('%s','now')*1000),
(1, '높다', 'to be high', strftime('%s','now')*1000),
(1, '누구', 'who', strftime('%s','now')*1000),
(1, '누나', 'older sister (for male)', strftime('%s','now')*1000),
(1, '눈', 'eye/snow', strftime('%s','now')*1000),
(1, '뉴스', 'news', strftime('%s','now')*1000),
(1, '늦다', 'to be late', strftime('%s','now')*1000),
(1, '다', 'all/everything', strftime('%s','now')*1000),
(1, '다녀오다', 'to go and come back', strftime('%s','now')*1000),
(1, '다니다', 'to attend/go regularly', strftime('%s','now')*1000),
(1, '다르다', 'to be different', strftime('%s','now')*1000),
(1, '다리', 'leg/bridge', strftime('%s','now')*1000),
(1, '다섯', 'five', strftime('%s','now')*1000),
(1, '다시', 'again', strftime('%s','now')*1000),
(1, '다음', 'next', strftime('%s','now')*1000),
(1, '단어', 'word/vocabulary', strftime('%s','now')*1000),
(1, '닫다', 'to close', strftime('%s','now')*1000),
(1, '달', 'moon/month', strftime('%s','now')*1000),
(1, '달다', 'to be sweet', strftime('%s','now')*1000),
(1, '담배', 'cigarette', strftime('%s','now')*1000),
(1, '대답', 'answer', strftime('%s','now')*1000),
(1, '대사관', 'embassy', strftime('%s','now')*1000),
(1, '대학', 'college', strftime('%s','now')*1000),
(1, '대학교', 'university', strftime('%s','now')*1000),
(1, '대학생', 'university student', strftime('%s','now')*1000),
(1, '대화', 'conversation', strftime('%s','now')*1000),
(1, '더', 'more', strftime('%s','now')*1000),
(1, '덥다', 'to be hot (weather)', strftime('%s','now')*1000),
(1, '도서관', 'library', strftime('%s','now')*1000),
(1, '도와주다', 'to help', strftime('%s','now')*1000),
(1, '도착', 'arrival', strftime('%s','now')*1000),
(1, '독일', 'Germany', strftime('%s','now')*1000),
(1, '돈', 'money', strftime('%s','now')*1000),
(1, '돌아가다', 'to return/go back', strftime('%s','now')*1000),
(1, '돌아오다', 'to come back', strftime('%s','now')*1000),
(1, '돕다', 'to help (assist)', strftime('%s','now')*1000),
(1, '동대문', 'Dongdaemun Gate', strftime('%s','now')*1000),
(1, '동생', 'younger sibling', strftime('%s','now')*1000),
(1, '동안', 'during/for (time)', strftime('%s','now')*1000),
(1, '되다', 'to become', strftime('%s','now')*1000),
(1, '된장찌개', 'soybean paste stew', strftime('%s','now')*1000),
(1, '두', 'two', strftime('%s','now')*1000),
(1, '둘', 'two', strftime('%s','now')*1000),
(1, '뒤', 'behind', strftime('%s','now')*1000),
(1, '드라마', 'drama', strftime('%s','now')*1000),
(1, '드리다', 'to give (honorific)', strftime('%s','now')*1000),
(1, '듣다', 'to listen/hear', strftime('%s','now')*1000),
(1, '들다', 'to lift/hold', strftime('%s','now')*1000),
(1, '들어가다', 'to enter/go in', strftime('%s','now')*1000),
(1, '들어오다', 'to come in', strftime('%s','now')*1000),
(1, '등산', 'hiking', strftime('%s','now')*1000),
(1, '따뜻하다', 'to be warm', strftime('%s','now')*1000),
(1, '딸', 'daughter', strftime('%s','now')*1000),
(1, '딸기', 'strawberry', strftime('%s','now')*1000),
(1, '때', 'time/moment', strftime('%s','now')*1000),
(1, '떡볶이', 'tteokbokki', strftime('%s','now')*1000),
(1, '또', 'again/also', strftime('%s','now')*1000),
(1, '라면', 'ramen/noodles', strftime('%s','now')*1000),
(1, '러시아', 'Russia', strftime('%s','now')*1000),
(1, '마리', 'counter for animals', strftime('%s','now')*1000),
(1, '마시다', 'to drink', strftime('%s','now')*1000),
(1, '마음', 'heart/mind', strftime('%s','now')*1000),
(1, '마흔', 'forty', strftime('%s','now')*1000),
(1, '만', 'ten thousand', strftime('%s','now')*1000),
(1, '만나다', 'to meet', strftime('%s','now')*1000),
(1, '만들다', 'to make', strftime('%s','now')*1000),
(1, '많다', 'to be many', strftime('%s','now')*1000),
(1, '많이', 'a lot/much', strftime('%s','now')*1000),
(1, '말', 'word/speech', strftime('%s','now')*1000),
(1, '말다', 'to stop doing', strftime('%s','now')*1000),
(1, '말레이시아', 'Malaysia', strftime('%s','now')*1000),
(1, '말씀', 'speech (honorific)', strftime('%s','now')*1000),
(1, '맑다', 'to be clear (weather)', strftime('%s','now')*1000),
(1, '맛', 'taste', strftime('%s','now')*1000),
(1, '맛없다', 'to taste bad', strftime('%s','now')*1000),
(1, '맛있다', 'to be delicious', strftime('%s','now')*1000),
(1, '맞다', 'to be correct', strftime('%s','now')*1000),
(1, '매일', 'every day', strftime('%s','now')*1000),
(1, '맵다', 'to be spicy', strftime('%s','now')*1000),
(1, '머리', 'head/hair', strftime('%s','now')*1000),
(1, '먹다', 'to eat', strftime('%s','now')*1000),
(1, '먼저', 'first', strftime('%s','now')*1000),
(1, '멀다', 'to be far', strftime('%s','now')*1000),
(1, '멋있다', 'to be cool/stylish', strftime('%s','now')*1000),
(1, '메뉴', 'menu', strftime('%s','now')*1000),
(1, '며칠', 'how many days', strftime('%s','now')*1000),
(1, '명', 'counter for people', strftime('%s','now')*1000),
(1, '몇', 'how many', strftime('%s','now')*1000),
(1, '모두', 'all/everyone', strftime('%s','now')*1000),
(1, '모레', 'the day after tomorrow', strftime('%s','now')*1000),
(1, '모르다', 'to not know', strftime('%s','now')*1000),
(1, '모자', 'hat', strftime('%s','now')*1000),
(1, '목', 'neck', strftime('%s','now')*1000),
(1, '목요일', 'Thursday', strftime('%s','now')*1000),
(1, '목욕탕', 'bathhouse', strftime('%s','now')*1000),
(1, '몸', 'body', strftime('%s','now')*1000),
(1, '못', 'cannot', strftime('%s','now')*1000),
(1, '못하다', 'to be unable to', strftime('%s','now')*1000),
(1, '몽골', 'Mongolia', strftime('%s','now')*1000),
(1, '무겁다', 'to be heavy', strftime('%s','now')*1000),
(1, '무슨', 'what/kind of', strftime('%s','now')*1000),
(1, '무엇', 'what', strftime('%s','now')*1000),
(1, '문', 'door', strftime('%s','now')*1000),
(1, '문화', 'culture', strftime('%s','now')*1000),
(1, '묻다', 'to ask', strftime('%s','now')*1000),
(1, '물', 'water', strftime('%s','now')*1000),
(1, '물건', 'thing/object', strftime('%s','now')*1000),
(1, '뭐', 'what (informal)', strftime('%s','now')*1000),
(1, '미국', 'USA', strftime('%s','now')*1000),
(1, '미안', 'sorry', strftime('%s','now')*1000),
(1, '미용실', 'hair salon', strftime('%s','now')*1000),
(1, '밑', 'under/below', strftime('%s','now')*1000),
(1, '바꾸다', 'to change', strftime('%s','now')*1000),
(1, '바나나', 'banana', strftime('%s','now')*1000),
(1, '바다', 'sea', strftime('%s','now')*1000),
(1, '바람', 'wind', strftime('%s','now')*1000),
(1, '바로', 'right away', strftime('%s','now')*1000),
(1, '바쁘다', 'to be busy', strftime('%s','now')*1000),
(1, '바지', 'pants', strftime('%s','now')*1000),
(1, '박물관', 'museum', strftime('%s','now')*1000),
(1, '밖', 'outside', strftime('%s','now')*1000),
(1, '반', 'half/class', strftime('%s','now')*1000),
(1, '반갑다', 'to be glad to see', strftime('%s','now')*1000),
(1, '받다', 'to receive', strftime('%s','now')*1000),
(1, '발', 'foot', strftime('%s','now')*1000),
(1, '밤', 'night/chestnut', strftime('%s','now')*1000),
(1, '밥', 'rice/meal', strftime('%s','now')*1000),
(1, '방', 'room', strftime('%s','now')*1000),
(1, '방학', 'vacation (school)', strftime('%s','now')*1000),
(1, '배', 'stomach/boat/pear', strftime('%s','now')*1000),
(1, '배우', 'actor', strftime('%s','now')*1000),
(1, '배우다', 'to learn', strftime('%s','now')*1000),
(1, '백', 'hundred', strftime('%s','now')*1000),
(1, '백만', 'million', strftime('%s','now')*1000),
(1, '백화점', 'department store', strftime('%s','now')*1000),
(1, '버스', 'bus', strftime('%s','now')*1000),
(1, '번', 'number/time', strftime('%s','now')*1000),
(1, '번호', 'number', strftime('%s','now')*1000),
(1, '베트남', 'Vietnam', strftime('%s','now')*1000),
(1, '별로', 'not really', strftime('%s','now')*1000),
(1, '병', 'bottle/disease', strftime('%s','now')*1000),
(1, '병원', 'hospital', strftime('%s','now')*1000),
(1, '보내다', 'to send', strftime('%s','now')*1000),
(1, '보다', 'to see/look', strftime('%s','now')*1000),
(1, '보통', 'usually', strftime('%s','now')*1000),
(1, '볼펜', 'ballpoint pen', strftime('%s','now')*1000),
(1, '봄', 'spring', strftime('%s','now')*1000),
(1, '부르다', 'to call/sing', strftime('%s','now')*1000),
(1, '부모님', 'parents', strftime('%s','now')*1000),
(1, '부산', 'Busan', strftime('%s','now')*1000),
(1, '부엌', 'kitchen', strftime('%s','now')*1000),
(1, '부탁', 'request', strftime('%s','now')*1000),
(1, '분', 'minute/person (honorific)', strftime('%s','now')*1000),
(1, '불', 'fire', strftime('%s','now')*1000),
(1, '불고기', 'bulgogi', strftime('%s','now')*1000),
(1, '불다', 'to blow', strftime('%s','now')*1000),
(1, '비', 'rain', strftime('%s','now')*1000),
(1, '비빔밥', 'bibimbap', strftime('%s','now')*1000),
(1, '비싸다', 'to be expensive', strftime('%s','now')*1000),
(1, '비행기', 'airplane', strftime('%s','now')*1000),
(1, '빌리다', 'to borrow/lend', strftime('%s','now')*1000),
(1, '빠르다', 'to be fast', strftime('%s','now')*1000),
(1, '빨리', 'quickly', strftime('%s','now')*1000),
(1, '빵', 'bread', strftime('%s','now')*1000),
(1, '사', 'four', strftime('%s','now')*1000),
(1, '사과', 'apple/apology', strftime('%s','now')*1000),
(1, '사귀다', 'to make friends/date', strftime('%s','now')*1000),
(1, '사다', 'to buy', strftime('%s','now')*1000),
(1, '사람', 'person', strftime('%s','now')*1000),
(1, '사랑', 'love', strftime('%s','now')*1000),
(1, '사무실', 'office', strftime('%s','now')*1000),
(1, '사십', 'forty', strftime('%s','now')*1000),
(1, '사용', 'use', strftime('%s','now')*1000),
(1, '사월', 'April', strftime('%s','now')*1000),
(1, '사이', 'between/relationship', strftime('%s','now')*1000),
(1, '사이다', 'soda', strftime('%s','now')*1000),
(1, '사전', 'dictionary', strftime('%s','now')*1000),
(1, '사진', 'photo', strftime('%s','now')*1000),
(1, '산', 'mountain', strftime('%s','now')*1000),
(1, '산책', 'walk/stroll', strftime('%s','now')*1000),
(1, '살', 'flesh/age', strftime('%s','now')*1000),
(1, '살다', 'to live', strftime('%s','now')*1000),
(1, '삼', 'three', strftime('%s','now')*1000),
(1, '삼계탕', 'ginseng chicken soup', strftime('%s','now')*1000),
(1, '삼십', 'thirty', strftime('%s','now')*1000),
(1, '삼월', 'March', strftime('%s','now')*1000),
(1, '생각', 'thought', strftime('%s','now')*1000),
(1, '생신', 'birthday (honorific)', strftime('%s','now')*1000),
(1, '생일', 'birthday', strftime('%s','now')*1000),
(1, '생활', 'life/daily living', strftime('%s','now')*1000),
(1, '샤워', 'shower', strftime('%s','now')*1000),
(1, '서른', 'thirty', strftime('%s','now')*1000),
(1, '서울', 'Seoul', strftime('%s','now')*1000),
(1, '서점', 'bookstore', strftime('%s','now')*1000),
(1, '선물', 'gift', strftime('%s','now')*1000),
(1, '선생님', 'teacher', strftime('%s','now')*1000),
(1, '설명', 'explanation', strftime('%s','now')*1000),
(1, '세', 'three (counter)', strftime('%s','now')*1000),
(1, '세수', 'washing face', strftime('%s','now')*1000),
(1, '셋', 'three', strftime('%s','now')*1000),
(1, '소개', 'introduction', strftime('%s','now')*1000),
(1, '소금', 'salt', strftime('%s','now')*1000),
(1, '손', 'hand', strftime('%s','now')*1000),
(1, '손님', 'guest/customer', strftime('%s','now')*1000),
(1, '쇼핑', 'shopping', strftime('%s','now')*1000),
(1, '수박', 'watermelon', strftime('%s','now')*1000),
(1, '수업', 'class/lesson', strftime('%s','now')*1000),
(1, '수영', 'swimming', strftime('%s','now')*1000),
(1, '수영장', 'swimming pool', strftime('%s','now')*1000),
(1, '수요일', 'Wednesday', strftime('%s','now')*1000),
(1, '수첩', 'notebook/schedule book', strftime('%s','now')*1000),
(1, '숙제', 'homework', strftime('%s','now')*1000),
(1, '술', 'alcohol', strftime('%s','now')*1000),
(1, '쉬다', 'to rest', strftime('%s','now')*1000),
(1, '쉽다', 'to be easy', strftime('%s','now')*1000),
(1, '슈퍼마켓', 'supermarket', strftime('%s','now')*1000),
(1, '스물', 'twenty', strftime('%s','now')*1000),
(1, '스키', 'ski', strftime('%s','now')*1000),
(1, '슬프다', 'to be sad', strftime('%s','now')*1000),
(1, '시', 'hour/poem/city', strftime('%s','now')*1000),
(1, '시간', 'time/hour', strftime('%s','now')*1000),
(1, '시다', 'to be sour', strftime('%s','now')*1000),
(1, '시원하다', 'to be cool (refreshing)', strftime('%s','now')*1000),
(1, '시월', 'October', strftime('%s','now')*1000),
(1, '시작', 'start/beginning', strftime('%s','now')*1000),
(1, '시장', 'market/mayor', strftime('%s','now')*1000),
(1, '시청', 'city hall', strftime('%s','now')*1000),
(1, '시키다', 'to order/make someone do', strftime('%s','now')*1000),
(1, '시험', 'exam/test', strftime('%s','now')*1000),
(1, '식당', 'restaurant', strftime('%s','now')*1000),
(1, '식사', 'meal', strftime('%s','now')*1000),
(1, '신다', 'to wear (shoes)', strftime('%s','now')*1000),
(1, '신문', 'newspaper', strftime('%s','now')*1000),
(1, '신발', 'shoes', strftime('%s','now')*1000),
(1, '실례', 'excuse me', strftime('%s','now')*1000),
(1, '싫다', 'to dislike', strftime('%s','now')*1000),
(1, '싫어하다', 'to hate/dislike', strftime('%s','now')*1000),
(1, '십', 'ten', strftime('%s','now')*1000),
(1, '십만', 'hundred thousand', strftime('%s','now')*1000),
(1, '십이월', 'December', strftime('%s','now')*1000),
(1, '십일월', 'November', strftime('%s','now')*1000),
(1, '싱겁다', 'to be bland', strftime('%s','now')*1000),
(1, '싸다', 'to be cheap', strftime('%s','now')*1000),
(1, '쓰다', 'to write/use', strftime('%s','now')*1000),
(1, '씨', 'Mr./Ms.', strftime('%s','now')*1000),
(1, '씻다', 'to wash', strftime('%s','now')*1000),
(1, '아', 'ah/oh', strftime('%s','now')*1000),
(1, '아기', 'baby', strftime('%s','now')*1000),
(1, '아내', 'wife', strftime('%s','now')*1000),
(1, '아니다', 'to not be', strftime('%s','now')*1000),
(1, '아니요', 'no', strftime('%s','now')*1000),
(1, '아래', 'below', strftime('%s','now')*1000),
(1, '아르바이트', 'part-time job', strftime('%s','now')*1000),
(1, '아름답다', 'to be beautiful', strftime('%s','now')*1000),
(1, '아버지', 'father', strftime('%s','now')*1000),
(1, '아이', 'child', strftime('%s','now')*1000),
(1, '아이스크림', 'ice cream', strftime('%s','now')*1000),
(1, '아저씨', 'mister', strftime('%s','now')*1000),
(1, '아주', 'very', strftime('%s','now')*1000),
(1, '아주머니', 'madam', strftime('%s','now')*1000),
(1, '아직', 'still/yet', strftime('%s','now')*1000),
(1, '아침', 'morning/breakfast', strftime('%s','now')*1000),
(1, '아파트', 'apartment', strftime('%s','now')*1000),
(1, '아프다', 'to be sick/hurt', strftime('%s','now')*1000),
(1, '아홉', 'nine', strftime('%s','now')*1000),
(1, '아흔', 'ninety', strftime('%s','now')*1000),
(1, '안', 'inside/not', strftime('%s','now')*1000),
(1, '안경', 'glasses', strftime('%s','now')*1000),
(1, '안내', 'information/guide', strftime('%s','now')*1000),
(1, '안녕', 'hello/peace', strftime('%s','now')*1000),
(1, '안녕히', 'peacefully', strftime('%s','now')*1000),
(1, '앉다', 'to sit', strftime('%s','now')*1000),
(1, '알다', 'to know', strftime('%s','now')*1000),
(1, '알리다', 'to inform', strftime('%s','now')*1000),
(1, '앞', 'front', strftime('%s','now')*1000),
(1, '야구', 'baseball', strftime('%s','now')*1000),
(1, '약', 'medicine/about', strftime('%s','now')*1000),
(1, '약국', 'pharmacy', strftime('%s','now')*1000),
(1, '약속', 'promise/appointment', strftime('%s','now')*1000),
(1, '어느', 'which', strftime('%s','now')*1000),
(1, '어디', 'where', strftime('%s','now')*1000),
(1, '어떤', 'what kind', strftime('%s','now')*1000),
(1, '어떻다', 'how', strftime('%s','now')*1000),
(1, '어렵다', 'to be difficult', strftime('%s','now')*1000),
(1, '어머니', 'mother', strftime('%s','now')*1000),
(1, '어서', 'quickly/please', strftime('%s','now')*1000),
(1, '어제', 'yesterday', strftime('%s','now')*1000),
(1, '언니', 'older sister (for female)', strftime('%s','now')*1000),
(1, '언제', 'when', strftime('%s','now')*1000),
(1, '얼굴', 'face', strftime('%s','now')*1000),
(1, '얼마', 'how much', strftime('%s','now')*1000),
(1, '얼마나', 'how much/how long', strftime('%s','now')*1000),
(1, '없다', 'to not exist', strftime('%s','now')*1000),
(1, '에어컨', 'air conditioner', strftime('%s','now')*1000),
(1, '여권', 'passport', strftime('%s','now')*1000),
(1, '여기', 'here', strftime('%s','now')*1000),
(1, '여덟', 'eight', strftime('%s','now')*1000),
(1, '여동생', 'younger sister', strftime('%s','now')*1000),
(1, '여든', 'eighty', strftime('%s','now')*1000),
(1, '여러', 'several/many', strftime('%s','now')*1000),
(1, '여러분', 'everyone', strftime('%s','now')*1000),
(1, '여름', 'summer', strftime('%s','now')*1000),
(1, '여보세요', 'hello (on phone)', strftime('%s','now')*1000),
(1, '여섯', 'six', strftime('%s','now')*1000),
(1, '여자', 'woman', strftime('%s','now')*1000),
(1, '여행', 'travel', strftime('%s','now')*1000),
(1, '여행사', 'travel agency', strftime('%s','now')*1000),
(1, '역', 'station', strftime('%s','now')*1000),
(1, '연극', 'play/theater', strftime('%s','now')*1000),
(1, '연습', 'practice', strftime('%s','now')*1000),
(1, '연필', 'pencil', strftime('%s','now')*1000),
(1, '열', 'ten/fever', strftime('%s','now')*1000),
(1, '열다', 'to open', strftime('%s','now')*1000),
(1, '열쇠', 'key', strftime('%s','now')*1000),
(1, '열심히', 'diligently', strftime('%s','now')*1000),
(1, '영', 'zero', strftime('%s','now')*1000),
(1, '영국', 'England', strftime('%s','now')*1000),
(1, '영어', 'English (language)', strftime('%s','now')*1000),
(1, '영화', 'movie', strftime('%s','now')*1000),
(1, '영화관', 'cinema', strftime('%s','now')*1000),
(1, '영화배우', 'movie actor', strftime('%s','now')*1000),
(1, '옆', 'beside/next to', strftime('%s','now')*1000),
(1, '예', 'yes/example', strftime('%s','now')*1000),
(1, '예쁘다', 'to be pretty', strftime('%s','now')*1000),
(1, '오', 'five', strftime('%s','now')*1000),
(1, '오늘', 'today', strftime('%s','now')*1000),
(1, '오다', 'to come', strftime('%s','now')*1000),
(1, '오렌지', 'orange', strftime('%s','now')*1000),
(1, '오른쪽', 'right side', strftime('%s','now')*1000),
(1, '오빠', 'older brother (for female)', strftime('%s','now')*1000),
(1, '오십', 'fifty', strftime('%s','now')*1000),
(1, '오월', 'May', strftime('%s','now')*1000),
(1, '오전', 'morning (a.m.)', strftime('%s','now')*1000),
(1, '오후', 'afternoon (p.m.)', strftime('%s','now')*1000),
(1, '올라가다', 'to go up', strftime('%s','now')*1000),
(1, '올해', 'this year', strftime('%s','now')*1000),
(1, '옷', 'clothes', strftime('%s','now')*1000),
(1, '와', 'and/wow', strftime('%s','now')*1000),
(1, '왜', 'why', strftime('%s','now')*1000),
(1, '외국', 'foreign country', strftime('%s','now')*1000),
(1, '외국어', 'foreign language', strftime('%s','now')*1000),
(1, '외국인', 'foreigner', strftime('%s','now')*1000),
(1, '왼쪽', 'left side', strftime('%s','now')*1000),
(1, '요리', 'cooking/dish', strftime('%s','now')*1000),
(1, '요일', 'day of the week', strftime('%s','now')*1000),
(1, '요즘', 'these days', strftime('%s','now')*1000),
(1, '우리', 'we/our', strftime('%s','now')*1000),
(1, '우산', 'umbrella', strftime('%s','now')*1000),
(1, '우유', 'milk', strftime('%s','now')*1000),
(1, '우체국', 'post office', strftime('%s','now')*1000),
(1, '우표', 'stamp', strftime('%s','now')*1000),
(1, '운동', 'exercise', strftime('%s','now')*1000),
(1, '운동장', 'schoolyard/playground', strftime('%s','now')*1000),
(1, '운동화', 'sneakers', strftime('%s','now')*1000),
(1, '운전', 'driving', strftime('%s','now')*1000),
(1, '울다', 'to cry', strftime('%s','now')*1000),
(1, '웃다', 'to laugh/smile', strftime('%s','now')*1000),
(1, '원', 'won (currency)', strftime('%s','now')*1000),
(1, '월', 'month', strftime('%s','now')*1000),
(1, '월요일', 'Monday', strftime('%s','now')*1000),
(1, '위', 'above/on', strftime('%s','now')*1000),
(1, '유명', 'famous', strftime('%s','now')*1000),
(1, '유월', 'June', strftime('%s','now')*1000),
(1, '육', 'six', strftime('%s','now')*1000),
(1, '육십', 'sixty', strftime('%s','now')*1000),
(1, '은행', 'bank', strftime('%s','now')*1000),
(1, '음', 'sound', strftime('%s','now')*1000),
(1, '음료수', 'beverage', strftime('%s','now')*1000),
(1, '음식', 'food', strftime('%s','now')*1000),
(1, '음악', 'music', strftime('%s','now')*1000),
(1, '의사', 'doctor', strftime('%s','now')*1000),
(1, '의자', 'chair', strftime('%s','now')*1000),
(1, '이', 'two/this', strftime('%s','now')*1000),
(1, '이것', 'this thing', strftime('%s','now')*1000),
(1, '이따가', 'later (soon)', strftime('%s','now')*1000),
(1, '이름', 'name', strftime('%s','now')*1000),
(1, '이번', 'this time', strftime('%s','now')*1000),
(1, '이십', 'twenty', strftime('%s','now')*1000),
(1, '이야기', 'story/talk', strftime('%s','now')*1000),
(1, '이월', 'February', strftime('%s','now')*1000),
(1, '이유', 'reason', strftime('%s','now')*1000),
(1, '이쪽', 'this side', strftime('%s','now')*1000),
(1, '인도네시아', 'Indonesia', strftime('%s','now')*1000),
(1, '인분', 'portion (food)', strftime('%s','now')*1000),
(1, '인사', 'greeting', strftime('%s','now')*1000),
(1, '인천', 'Incheon', strftime('%s','now')*1000),
(1, '인터넷', 'internet', strftime('%s','now')*1000),
(1, '일', 'day/work', strftime('%s','now')*1000),
(1, '일곱', 'seven', strftime('%s','now')*1000),
(1, '일본', 'Japan', strftime('%s','now')*1000),
(1, '일어나다', 'to get up', strftime('%s','now')*1000),
(1, '일요일', 'Sunday', strftime('%s','now')*1000),
(1, '일월', 'January', strftime('%s','now')*1000),
(1, '일주일', 'one week', strftime('%s','now')*1000),
(1, '일찍', 'early', strftime('%s','now')*1000),
(1, '일흔', 'seventy', strftime('%s','now')*1000),
(1, '읽다', 'to read', strftime('%s','now')*1000),
(1, '입', 'mouth', strftime('%s','now')*1000),
(1, '입다', 'to wear/put on', strftime('%s','now')*1000),
(1, '있다', 'to exist/have', strftime('%s','now')*1000),
(1, '자다', 'to sleep', strftime('%s','now')*1000),
(1, '자동차', 'car', strftime('%s','now')*1000),
(1, '자전거', 'bicycle', strftime('%s','now')*1000),
(1, '자주', 'often', strftime('%s','now')*1000),
(1, '작년', 'last year', strftime('%s','now')*1000),
(1, '작다', 'to be small', strftime('%s','now')*1000),
(1, '잔', 'cup/glass', strftime('%s','now')*1000),
(1, '잘', 'well', strftime('%s','now')*1000),
(1, '잘못', 'mistake', strftime('%s','now')*1000),
(1, '잘하다', 'to do well', strftime('%s','now')*1000),
(1, '잠', 'sleep', strftime('%s','now')*1000),
(1, '잠깐', 'a moment', strftime('%s','now')*1000),
(1, '잠시', 'a while', strftime('%s','now')*1000),
(1, '잡수시다', 'to eat (honorific)', strftime('%s','now')*1000),
(1, '잡채', 'japchae', strftime('%s','now')*1000),
(1, '장소', 'place/location', strftime('%s','now')*1000),
(1, '재미없다', 'to be boring', strftime('%s','now')*1000),
(1, '재미있다', 'to be interesting', strftime('%s','now')*1000),
(1, '저', 'I/me (humble)', strftime('%s','now')*1000),
(1, '저것', 'that thing', strftime('%s','now')*1000),
(1, '저기', 'there', strftime('%s','now')*1000),
(1, '저녁', 'evening/dinner', strftime('%s','now')*1000),
(1, '저쪽', 'that way', strftime('%s','now')*1000),
(1, '적다', 'to write down/be few', strftime('%s','now')*1000),
(1, '전', 'before/ago', strftime('%s','now')*1000),
(1, '전공', 'major (study)', strftime('%s','now')*1000),
(1, '전화', 'telephone', strftime('%s','now')*1000),
(1, '전화번호', 'phone number', strftime('%s','now')*1000),
(1, '점심', 'lunch', strftime('%s','now')*1000),
(1, '정류장', 'bus stop', strftime('%s','now')*1000),
(1, '정말', 'really', strftime('%s','now')*1000),
(1, '제', 'my (humble)', strftime('%s','now')*1000),
(1, '제일', 'most/best', strftime('%s','now')*1000),
(1, '제주도', 'Jeju Island', strftime('%s','now')*1000),
(1, '조금', 'a little', strftime('%s','now')*1000),
(1, '조용하다', 'to be quiet', strftime('%s','now')*1000),
(1, '졸업', 'graduation', strftime('%s','now')*1000),
(1, '좀', 'a bit', strftime('%s','now')*1000),
(1, '종업원', 'employee/staff', strftime('%s','now')*1000),
(1, '좋다', 'to be good', strftime('%s','now')*1000),
(1, '좋아하다', 'to like', strftime('%s','now')*1000),
(1, '죄송하다', 'to be sorry', strftime('%s','now')*1000),
(1, '주', 'week', strftime('%s','now')*1000),
(1, '주다', 'to give', strftime('%s','now')*1000),
(1, '주로', 'mainly', strftime('%s','now')*1000),
(1, '주말', 'weekend', strftime('%s','now')*1000),
(1, '주무시다', 'to sleep (honorific)', strftime('%s','now')*1000),
(1, '주부', 'housewife', strftime('%s','now')*1000),
(1, '주소', 'address', strftime('%s','now')*1000),
(1, '주스', 'juice', strftime('%s','now')*1000),
(1, '주인', 'owner', strftime('%s','now')*1000),
(1, '주일', 'week (period)', strftime('%s','now')*1000),
(1, '준비', 'preparation', strftime('%s','now')*1000),
(1, '중', 'middle', strftime('%s','now')*1000),
(1, '중국', 'China', strftime('%s','now')*1000),
(1, '지갑', 'wallet', strftime('%s','now')*1000),
(1, '지금', 'now', strftime('%s','now')*1000),
(1, '지나다', 'to pass', strftime('%s','now')*1000),
(1, '지난달', 'last month', strftime('%s','now')*1000),
(1, '지난주', 'last week', strftime('%s','now')*1000),
(1, '지난해', 'last year', strftime('%s','now')*1000),
(1, '지내다', 'to spend time', strftime('%s','now')*1000),
(1, '지우개', 'eraser', strftime('%s','now')*1000),
(1, '지하철', 'subway', strftime('%s','now')*1000),
(1, '지하철역', 'subway station', strftime('%s','now')*1000),
(1, '직업', 'occupation', strftime('%s','now')*1000),
(1, '직원', 'employee', strftime('%s','now')*1000),
(1, '질문', 'question', strftime('%s','now')*1000),
(1, '집', 'house/home', strftime('%s','now')*1000),
(1, '짜다', 'to be salty', strftime('%s','now')*1000),
(1, '쪽', 'side/page', strftime('%s','now')*1000),
(1, '찍다', 'to take (photo)', strftime('%s','now')*1000),
(1, '참', 'really/truly', strftime('%s','now')*1000),
(1, '참외', 'oriental melon', strftime('%s','now')*1000),
(1, '창문', 'window', strftime('%s','now')*1000),
(1, '찾다', 'to find', strftime('%s','now')*1000),
(1, '찾아보다', 'to look for', strftime('%s','now')*1000),
(1, '책', 'book', strftime('%s','now')*1000),
(1, '책상', 'desk', strftime('%s','now')*1000),
(1, '처음', 'first/time', strftime('%s','now')*1000),
(1, '천', 'thousand', strftime('%s','now')*1000),
(1, '천만', 'ten million', strftime('%s','now')*1000),
(1, '천천히', 'slowly', strftime('%s','now')*1000),
(1, '청소', 'cleaning', strftime('%s','now')*1000),
(1, '초대', 'invitation', strftime('%s','now')*1000),
(1, '초콜릿', 'chocolate', strftime('%s','now')*1000),
(1, '추다', 'to dance', strftime('%s','now')*1000),
(1, '축구', 'soccer', strftime('%s','now')*1000),
(1, '축하', 'congratulation', strftime('%s','now')*1000),
(1, '출발', 'departure', strftime('%s','now')*1000),
(1, '춤', 'dance', strftime('%s','now')*1000),
(1, '춤추다', 'to dance', strftime('%s','now')*1000),
(1, '춥다', 'to be cold (weather)', strftime('%s','now')*1000),
(1, '취미', 'hobby', strftime('%s','now')*1000),
(1, '층', 'floor (building)', strftime('%s','now')*1000),
(1, '치다', 'to hit/play', strftime('%s','now')*1000),
(1, '치마', 'skirt', strftime('%s','now')*1000),
(1, '친구', 'friend', strftime('%s','now')*1000),
(1, '친절', 'kindness', strftime('%s','now')*1000),
(1, '친하다', 'to be close (relation)', strftime('%s','now')*1000),
(1, '칠', 'seven', strftime('%s','now')*1000),
(1, '칠십', 'seventy', strftime('%s','now')*1000),
(1, '칠월', 'July', strftime('%s','now')*1000),
(1, '칠판', 'blackboard', strftime('%s','now')*1000),
(1, '침대', 'bed', strftime('%s','now')*1000),
(1, '카드', 'card', strftime('%s','now')*1000),
(1, '카메라', 'camera', strftime('%s','now')*1000),
(1, '캐나다', 'Canada', strftime('%s','now')*1000),
(1, '커피', 'coffee', strftime('%s','now')*1000),
(1, '커피숍', 'coffee shop', strftime('%s','now')*1000),
(1, '컴퓨터', 'computer', strftime('%s','now')*1000),
(1, '컵', 'cup', strftime('%s','now')*1000),
(1, '케이크', 'cake', strftime('%s','now')*1000),
(1, '켜다', 'to turn on', strftime('%s','now')*1000),
(1, '코', 'nose', strftime('%s','now')*1000),
(1, '콘서트', 'concert', strftime('%s','now')*1000),
(1, '콜라', 'cola', strftime('%s','now')*1000),
(1, '크다', 'to be big', strftime('%s','now')*1000),
(1, '키', 'height', strftime('%s','now')*1000),
(1, '타다', 'to ride', strftime('%s','now')*1000),
(1, '탁구', 'ping-pong', strftime('%s','now')*1000),
(1, '태국', 'Thailand', strftime('%s','now')*1000),
(1, '태권도', 'taekwondo', strftime('%s','now')*1000),
(1, '택시', 'taxi', strftime('%s','now')*1000),
(1, '터미널', 'terminal', strftime('%s','now')*1000),
(1, '테니스', 'tennis', strftime('%s','now')*1000),
(1, '텔레비전', 'television', strftime('%s','now')*1000),
(1, '토요일', 'Saturday', strftime('%s','now')*1000),
(1, '퇴근', 'getting off work', strftime('%s','now')*1000),
(1, '특별하다', 'to be special', strftime('%s','now')*1000),
(1, '특히', 'especially', strftime('%s','now')*1000),
(1, '티셔츠', 't-shirt', strftime('%s','now')*1000),
(1, '파티', 'party', strftime('%s','now')*1000),
(1, '팔', 'arm/eight', strftime('%s','now')*1000),
(1, '팔다', 'to sell', strftime('%s','now')*1000),
(1, '팔십', 'eighty', strftime('%s','now')*1000),
(1, '팔월', 'August', strftime('%s','now')*1000),
(1, '편의점', 'convenience store', strftime('%s','now')*1000),
(1, '편지', 'letter', strftime('%s','now')*1000),
(1, '포도', 'grape', strftime('%s','now')*1000),
(1, '표', 'ticket/table', strftime('%s','now')*1000),
(1, '프랑스', 'France', strftime('%s','now')*1000),
(1, '프로그램', 'program', strftime('%s','now')*1000),
(1, '피곤', 'tiredness', strftime('%s','now')*1000),
(1, '피아노', 'piano', strftime('%s','now')*1000),
(1, '피우다', 'to smoke', strftime('%s','now')*1000),
(1, '필요', 'need/necessity', strftime('%s','now')*1000),
(1, '필통', 'pencil case', strftime('%s','now')*1000),
(1, '하나', 'one', strftime('%s','now')*1000),
(1, '하다', 'to do', strftime('%s','now')*1000),
(1, '하루', 'one day', strftime('%s','now')*1000),
(1, '하숙집', 'boarding house', strftime('%s','now')*1000),
(1, '하지만', 'but/however', strftime('%s','now')*1000),
(1, '학교', 'school', strftime('%s','now')*1000),
(1, '학생', 'student', strftime('%s','now')*1000),
(1, '학생증', 'student ID', strftime('%s','now')*1000),
(1, '한', 'one/Korean', strftime('%s','now')*1000),
(1, '한가하다', 'to be free (not busy)', strftime('%s','now')*1000),
(1, '한국', 'Korea', strftime('%s','now')*1000),
(1, '한복', 'hanbok (traditional clothes)', strftime('%s','now')*1000),
(1, '할머니', 'grandmother', strftime('%s','now')*1000),
(1, '할아버지', 'grandfather', strftime('%s','now')*1000),
(1, '함께', 'together', strftime('%s','now')*1000),
(1, '형', 'older brother (for male)', strftime('%s','now')*1000),
(1, '호', 'number/lake', strftime('%s','now')*1000),
(1, '호텔', 'hotel', strftime('%s','now')*1000),
(1, '혼자', 'alone', strftime('%s','now')*1000),
(1, '화요일', 'Tuesday', strftime('%s','now')*1000),
(1, '화장실', 'bathroom', strftime('%s','now')*1000),
(1, '회사', 'company', strftime('%s','now')*1000),
(1, '회사원', 'office worker', strftime('%s','now')*1000),
(1, '회의', 'meeting', strftime('%s','now')*1000),
(1, '후', 'after', strftime('%s','now')*1000),
(1, '휴가', 'vacation', strftime('%s','now')*1000),
(1, '흐리다', 'to be cloudy', strftime('%s','now')*1000),
(1, '힘들다', 'to be hard/difficult', strftime('%s','now')*1000)

;
