PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(3, '가게', 'store', strftime('%s','now')*1000),
(3, '가꾸다', 'cultivate', strftime('%s','now')*1000),
(3, '가난', 'poverty', strftime('%s','now')*1000),
(3, '가능', 'possibility', strftime('%s','now')*1000),
(3, '가득하다', 'be full', strftime('%s','now')*1000),
(3, '가득히', 'fully', strftime('%s','now')*1000),
(3, '가렵다', 'itchy', strftime('%s','now')*1000),
(3, '가로', 'width / street', strftime('%s','now')*1000),
(3, '가루', 'powder', strftime('%s','now')*1000),
(3, '가리다', 'cover / distinguish', strftime('%s','now')*1000),
(3, '가스', 'gas', strftime('%s','now')*1000),
(3, '가스레인지', 'gas stove', strftime('%s','now')*1000),
(3, '가습기', 'humidifier', strftime('%s','now')*1000),
(3, '가입', 'subscription / joining', strftime('%s','now')*1000),
(3, '가입자', 'subscriber', strftime('%s','now')*1000),
(3, '가전제품', 'home appliance', strftime('%s','now')*1000),
(3, '가정', 'home / family', strftime('%s','now')*1000),
(3, '가죽', 'leather', strftime('%s','now')*1000),
(3, '각', 'each / angle', strftime('%s','now')*1000),
(3, '각자', 'each person / respectively', strftime('%s','now')*1000),
(3, '간', 'liver / relationship', strftime('%s','now')*1000),
(3, '간판', 'signboard', strftime('%s','now')*1000),
(3, '간호', 'nursing', strftime('%s','now')*1000),
(3, '갈다', 'change / sharpen', strftime('%s','now')*1000),
(3, '갈증', 'thirst', strftime('%s','now')*1000),
(3, '-감', 'feeling / sense (suffix)', strftime('%s','now')*1000),
(3, '감각', 'sense', strftime('%s','now')*1000),
(3, '감다', 'close eyes / wind up', strftime('%s','now')*1000),
(3, '감독', 'director / supervision', strftime('%s','now')*1000),
(3, '감동', 'emotion / impression', strftime('%s','now')*1000),
(3, '감동적', 'moving / touching', strftime('%s','now')*1000),
(3, '감상', 'appreciation', strftime('%s','now')*1000),
(3, '감정', 'emotion / feeling', strftime('%s','now')*1000),
(3, '강물', 'river water', strftime('%s','now')*1000),
(3, '강사', 'instructor', strftime('%s','now')*1000),
(3, '개나리', 'forsythia', strftime('%s','now')*1000),
(3, '개다', 'clear up / fold', strftime('%s','now')*1000),
(3, '개인', 'individual', strftime('%s','now')*1000),
(3, '개인적', 'personal', strftime('%s','now')*1000),
(3, '걔', 'that kid', strftime('%s','now')*1000),
(3, '거꾸로', 'upside down / backward', strftime('%s','now')*1000),
(3, '거스름돈', 'change (money)', strftime('%s','now')*1000),
(3, '거품', 'foam / bubble', strftime('%s','now')*1000),
(3, '건널목', 'crosswalk / railroad crossing', strftime('%s','now')*1000),
(3, '건조', 'dryness', strftime('%s','now')*1000),
(3, '걸레', 'rag / mop', strftime('%s','now')*1000),
(3, '검다', 'black / dark', strftime('%s','now')*1000),
(3, '검색', 'search', strftime('%s','now')*1000),
(3, '검토', 'review / examination', strftime('%s','now')*1000),
(3, '겁', 'fear', strftime('%s','now')*1000),
(3, '겉옷', 'outerwear', strftime('%s','now')*1000),
(3, '게시', 'posting', strftime('%s','now')*1000),
(3, '게시판', 'bulletin board', strftime('%s','now')*1000),
(3, '겨우', 'barely / only', strftime('%s','now')*1000),
(3, '결국', 'eventually / after all', strftime('%s','now')*1000),
(3, '결제', 'payment', strftime('%s','now')*1000),
(3, '경기장', 'stadium', strftime('%s','now')*1000),
(3, '경복궁', 'Gyeongbok Palace', strftime('%s','now')*1000),
(3, '경비', 'expense / guard', strftime('%s','now')*1000),
(3, '경비실', 'security office', strftime('%s','now')*1000),
(3, '경우', 'case / situation', strftime('%s','now')*1000),
(3, '경제', 'economy', strftime('%s','now')*1000),
(3, '경제적', 'economic', strftime('%s','now')*1000),
(3, '경찰관', 'police officer', strftime('%s','now')*1000),
(3, '곁', 'beside / side', strftime('%s','now')*1000),
(3, '계곡', 'valley', strftime('%s','now')*1000),
(3, '계약', 'contract', strftime('%s','now')*1000),
(3, '계약금', 'deposit / down payment', strftime('%s','now')*1000),
(3, '계좌', 'bank account', strftime('%s','now')*1000),
(3, '고객', 'customer', strftime('%s','now')*1000),
(3, '고구마', 'sweet potato', strftime('%s','now')*1000),
(3, '고궁', 'ancient palace', strftime('%s','now')*1000),
(3, '고백', 'confession', strftime('%s','now')*1000),
(3, '고생', 'hardship', strftime('%s','now')*1000),
(3, '고속', 'high-speed', strftime('%s','now')*1000),
(3, '고추', 'chili pepper', strftime('%s','now')*1000),
(3, '고춧가루', 'chili powder', strftime('%s','now')*1000),
(3, '곤란', 'difficulty / trouble', strftime('%s','now')*1000),
(3, '곧이어', 'immediately after', strftime('%s','now')*1000),
(3, '곧장', 'straight / directly', strftime('%s','now')*1000),
(3, '골고루', 'evenly', strftime('%s','now')*1000),
(3, '골목', 'alley', strftime('%s','now')*1000),
(3, '골목길', 'narrow alleyway', strftime('%s','now')*1000),
(3, '골프', 'golf', strftime('%s','now')*1000),
(3, '곰', 'bear', strftime('%s','now')*1000),
(3, '곱다', 'beautiful / soft', strftime('%s','now')*1000),
(3, '곱하다', 'multiply', strftime('%s','now')*1000),
(3, '곳곳', 'everywhere / in many places', strftime('%s','now')*1000),
(3, '공', 'ball / zero', strftime('%s','now')*1000),
(3, '공간', 'space', strftime('%s','now')*1000),
(3, '공공', 'public', strftime('%s','now')*1000),
(3, '공공장소', 'public place', strftime('%s','now')*1000),
(3, '공과금', 'utility bill', strftime('%s','now')*1000),
(3, '공기', 'air', strftime('%s','now')*1000),
(3, '공동', 'joint / shared', strftime('%s','now')*1000),
(3, '공사', 'construction', strftime('%s','now')*1000),
(3, '공식', 'formula / official', strftime('%s','now')*1000),
(3, '공연', 'performance', strftime('%s','now')*1000),
(3, '공연장', 'theater / concert hall', strftime('%s','now')*1000),
(3, '공주', 'princess', strftime('%s','now')*1000),
(3, '공중전화', 'public phone', strftime('%s','now')*1000),
(3, '공통', 'common', strftime('%s','now')*1000),
(3, '공통점', 'common point', strftime('%s','now')*1000),
(3, '공포', 'fear / horror', strftime('%s','now')*1000),
(3, '과', 'department / lesson / subject', strftime('%s','now')*1000),
(3, '과로', 'overwork', strftime('%s','now')*1000),
(3, '과목', 'subject', strftime('%s','now')*1000),
(3, '과식', 'overeating', strftime('%s','now')*1000),
(3, '과장', 'manager / exaggeration', strftime('%s','now')*1000),
(3, '과정', 'process / course', strftime('%s','now')*1000),
(3, '과학', 'science', strftime('%s','now')*1000),
(3, '과학자', 'scientist', strftime('%s','now')*1000),
(3, '관객', 'audience / spectator', strftime('%s','now')*1000),
(3, '관계없다', 'be unrelated', strftime('%s','now')*1000),
(3, '관계없이', 'regardless of', strftime('%s','now')*1000),
(3, '관계있다', 'be related', strftime('%s','now')*1000),
(3, '관람', 'viewing / watching', strftime('%s','now')*1000),
(3, '관람객', 'spectator / visitor', strftime('%s','now')*1000),
(3, '관련', 'relation / connection', strftime('%s','now')*1000),
(3, '관리', 'management', strftime('%s','now')*1000),
(3, '관찰', 'observation', strftime('%s','now')*1000),
(3, '광경', 'scene / sight', strftime('%s','now')*1000),
(3, '굉장히', 'very / extremely', strftime('%s','now')*1000),
(3, '교시', 'class period', strftime('%s','now')*1000),
(3, '교외', 'suburbs', strftime('%s','now')*1000),
(3, '교통수단', 'means of transportation', strftime('%s','now')*1000),
(3, '교통편', 'transportation', strftime('%s','now')*1000),
(3, '교포', 'Korean living abroad', strftime('%s','now')*1000),
(3, '구', 'district / section', strftime('%s','now')*1000),
(3, '구경거리', 'sight / attraction', strftime('%s','now')*1000),
(3, '구멍', 'hole', strftime('%s','now')*1000),
(3, '구수하다', 'savory / tasty', strftime('%s','now')*1000),
(3, '구역', 'zone / area', strftime('%s','now')*1000),
(3, '구입', 'purchase', strftime('%s','now')*1000),
(3, '구조', 'structure / rescue', strftime('%s','now')*1000),
(3, '구체적', 'concrete / specific', strftime('%s','now')*1000),
(3, '구하다', 'seek / obtain / save', strftime('%s','now')*1000),
(3, '국가', 'nation / country', strftime('%s','now')*1000),
(3, '국기', 'national flag', strftime('%s','now')*1000),
(3, '국내선', 'domestic flight', strftime('%s','now')*1000),
(3, '국립', 'national (institution)', strftime('%s','now')*1000),
(3, '국물', 'soup / broth', strftime('%s','now')*1000),
(3, '국민', 'citizen / people', strftime('%s','now')*1000),
(3, '국어', 'Korean language', strftime('%s','now')*1000),
(3, '군대', 'military / army', strftime('%s','now')*1000),
(3, '굶다', 'starve / skip a meal', strftime('%s','now')*1000),
(3, '굽', 'heel (of a shoe)', strftime('%s','now')*1000),
(3, '권하다', 'recommend / advise', strftime('%s','now')*1000),
(3, '귀하', 'dear / sir or madam', strftime('%s','now')*1000),
(3, '규칙적', 'regular / systematic', strftime('%s','now')*1000),
(3, '그녀', 'she / her', strftime('%s','now')*1000),
(3, '그래도', 'nevertheless / still', strftime('%s','now')*1000),
(3, '그램', 'gram', strftime('%s','now')*1000),
(3, '그러다', 'do so / act like that', strftime('%s','now')*1000),
(3, '그룹', 'group', strftime('%s','now')*1000),
(3, '그만하다', 'stop / quit', strftime('%s','now')*1000),
(3, '그저', 'just / merely', strftime('%s','now')*1000),
(3, '그제', 'the day before yesterday', strftime('%s','now')*1000),
(3, '그중', 'among them', strftime('%s','now')*1000),
(3, '근데', 'by the way / however', strftime('%s','now')*1000),
(3, '근무', 'duty / work', strftime('%s','now')*1000),
(3, '근육', 'muscle', strftime('%s','now')*1000),
(3, '금', 'gold / Friday', strftime('%s','now')*1000),
(3, '금액', 'amount of money', strftime('%s','now')*1000),
(3, '금연', 'no smoking', strftime('%s','now')*1000),
(3, '긋다', 'draw a line / strike', strftime('%s','now')*1000),
(3, '긍정적', 'positive / affirmative', strftime('%s','now')*1000),
(3, '-기', 'nominalizing suffix', strftime('%s','now')*1000),
(3, '기계', 'machine', strftime('%s','now')*1000),
(3, '기관', 'organization / institution', strftime('%s','now')*1000),
(3, '기구', 'equipment / organization', strftime('%s','now')*1000),
(3, '기념', 'commemoration', strftime('%s','now')*1000),
(3, '기념품', 'souvenir', strftime('%s','now')*1000),
(3, '기능', 'function', strftime('%s','now')*1000),
(3, '기다', 'expect / wait (archaic verb)', strftime('%s','now')*1000),
(3, '기대', 'expectation', strftime('%s','now')*1000),
(3, '기대다', 'lean on / rely on', strftime('%s','now')*1000),
(3, '기도', 'prayer', strftime('%s','now')*1000),
(3, '기말시험', 'final exam', strftime('%s','now')*1000),
(3, '기사', 'article / driver', strftime('%s','now')*1000),
(3, '기술자', 'technician / engineer', strftime('%s','now')*1000),
(3, '기억력', 'memory ability', strftime('%s','now')*1000),
(3, '기업', 'enterprise / company', strftime('%s','now')*1000),
(3, '기준', 'standard / criterion', strftime('%s','now')*1000),
(3, '기초', 'basic / foundation', strftime('%s','now')*1000),
(3, '기타', 'guitar / others', strftime('%s','now')*1000),
(3, '긴급', 'urgent', strftime('%s','now')*1000),
(3, '긴팔', 'long sleeves', strftime('%s','now')*1000),
(3, '길다', 'long', strftime('%s','now')*1000),
(3, '김', 'seaweed', strftime('%s','now')*1000),
(3, '까다', 'peel / scrape', strftime('%s','now')*1000),
(3, '깔끔하다', 'neat / tidy', strftime('%s','now')*1000),
(3, '깜빡', 'momentarily / blink', strftime('%s','now')*1000),
(3, '깨지다', 'break / shatter', strftime('%s','now')*1000),
(3, '꺼지다', 'go out / be turned off', strftime('%s','now')*1000),
(3, '껍질', 'peel / shell / skin', strftime('%s','now')*1000),
(3, '꼬리', 'tail', strftime('%s','now')*1000),
(3, '꼼짝', 'movement / motion', strftime('%s','now')*1000),
(3, '꽂다', 'stick in / plug in', strftime('%s','now')*1000),
(3, '꽃무늬', 'floral pattern', strftime('%s','now')*1000),
(3, '꽉', 'tightly / firmly', strftime('%s','now')*1000),
(3, '꽤', 'quite / fairly', strftime('%s','now')*1000),
(3, '꾸준히', 'steadily / consistently', strftime('%s','now')*1000),
(3, '꿀', 'honey', strftime('%s','now')*1000),
(3, '끈', 'string / cord', strftime('%s','now')*1000),
(3, '끊기다', 'be cut off / disconnected', strftime('%s','now')*1000),
(3, '끊어지다', 'snap / break', strftime('%s','now')*1000),
(3, '끌다', 'pull / drag', strftime('%s','now')*1000),
(3, '끝내', 'finally / in the end', strftime('%s','now')*1000),
(3, '끼', 'talent / natural gift', strftime('%s','now')*1000),
(3, '끼다', 'wear / be stuck / foggy', strftime('%s','now')*1000),
(3, '나르다', 'carry / transport', strftime('%s','now')*1000),
(3, '나물', 'seasoned vegetables', strftime('%s','now')*1000),
(3, '나뭇잎', 'leaf', strftime('%s','now')*1000),
(3, '나빠지다', 'get worse', strftime('%s','now')*1000),
(3, '나아지다', 'improve / get better', strftime('%s','now')*1000),
(3, '나이프', 'knife', strftime('%s','now')*1000),
(3, '나타내다', 'show / express', strftime('%s','now')*1000),
(3, '낙엽', 'fallen leaves', strftime('%s','now')*1000),
(3, '난로', 'heater', strftime('%s','now')*1000),
(3, '난방', 'heating', strftime('%s','now')*1000),
(3, '날아가다', 'fly away', strftime('%s','now')*1000),
(3, '낡다', 'old / worn-out', strftime('%s','now')*1000),
(3, '남', 'man / others', strftime('%s','now')*1000),
(3, '남미', 'South America', strftime('%s','now')*1000),
(3, '남부', 'southern part', strftime('%s','now')*1000),
(3, '낯설다', 'unfamiliar', strftime('%s','now')*1000),
(3, '낳다', 'give birth / produce', strftime('%s','now')*1000),
(3, '내', 'inside / my / river', strftime('%s','now')*1000),
(3, '내내', 'all the time / throughout', strftime('%s','now')*1000),
(3, '내달', 'next month', strftime('%s','now')*1000),
(3, '내려놓다', 'put down / lay down', strftime('%s','now')*1000),
(3, '내보내다', 'send out / expel', strftime('%s','now')*1000),
(3, '내성적', 'introverted', strftime('%s','now')*1000),
(3, '내주다', 'give / hand over', strftime('%s','now')*1000),
(3, '내후년', 'the year after next', strftime('%s','now')*1000),
(3, '낼모레', 'in two days', strftime('%s','now')*1000),
(3, '냉동', 'freezing / frozen', strftime('%s','now')*1000),
(3, '냉방', 'air conditioning', strftime('%s','now')*1000),
(3, '냉정하다', 'cold-hearted / calm', strftime('%s','now')*1000),
(3, '널다', 'hang / spread', strftime('%s','now')*1000),
(3, '널리', 'widely', strftime('%s','now')*1000),
(3, '넓이', 'width / area', strftime('%s','now')*1000),
(3, '넘어가다', 'cross / move on', strftime('%s','now')*1000),
(3, '넘어서다', 'go beyond / exceed', strftime('%s','now')*1000),
(3, '년대', 'era / decade', strftime('%s','now')*1000),
(3, '노랑', 'yellow', strftime('%s','now')*1000),
(3, '노선', 'route / line', strftime('%s','now')*1000),
(3, '노선도', 'route map', strftime('%s','now')*1000),
(3, '노약자', 'elderly and weak people', strftime('%s','now')*1000),
(3, '노트북', 'laptop', strftime('%s','now')*1000),
(3, '녹다', 'melt / dissolve', strftime('%s','now')*1000),
(3, '녹음', 'recording', strftime('%s','now')*1000),
(3, '녹음기', 'recorder', strftime('%s','now')*1000),
(3, '놀이공원', 'amusement park', strftime('%s','now')*1000),
(3, '놀이터', 'playground', strftime('%s','now')*1000),
(3, '농부', 'farmer', strftime('%s','now')*1000),
(3, '농사', 'farming', strftime('%s','now')*1000),
(3, '높아지다', 'rise / increase', strftime('%s','now')*1000),
(3, '높이다', 'raise / heighten', strftime('%s','now')*1000),
(3, '높임말', 'honorific language', strftime('%s','now')*1000),
(3, '놓이다', 'be placed / laid', strftime('%s','now')*1000),
(3, '놓치다', 'miss / lose', strftime('%s','now')*1000),
(3, '눈가', 'area around eyes', strftime('%s','now')*1000),
(3, '눈병', 'eye disease', strftime('%s','now')*1000),
(3, '눈부시다', 'dazzling / radiant', strftime('%s','now')*1000),
(3, '눈사람', 'snowman', strftime('%s','now')*1000),
(3, '눈싸움', 'snowball fight', strftime('%s','now')*1000),
(3, '늘리다', 'increase / expand', strftime('%s','now')*1000),
(3, '늘어나다', 'grow / stretch', strftime('%s','now')*1000),
(3, '늦잠', 'oversleep', strftime('%s','now')*1000),
(3, '-님', 'honorific suffix', strftime('%s','now')*1000),
(3, '다리미', 'iron', strftime('%s','now')*1000),
(3, '다림질', 'ironing', strftime('%s','now')*1000),
(3, '다방', 'coffeehouse', strftime('%s','now')*1000),
(3, '다운로드', 'download', strftime('%s','now')*1000),
(3, '다정', 'kind / affectionate', strftime('%s','now')*1000),
(3, '다지다', 'strengthen / chop finely', strftime('%s','now')*1000),
(3, '다행', 'good fortune / relief', strftime('%s','now')*1000),
(3, '다행히', 'fortunately', strftime('%s','now')*1000),
(3, '단단하다', 'hard / solid', strftime('%s','now')*1000),
(3, '단맛', 'sweet taste', strftime('%s','now')*1000),
(3, '단발머리', 'bobbed hair', strftime('%s','now')*1000),
(3, '단위', 'unit', strftime('%s','now')*1000),
(3, '단점', 'weakness / flaw', strftime('%s','now')*1000),
(3, '단정하다', 'neat / tidy', strftime('%s','now')*1000),
(3, '단지', 'only / complex', strftime('%s','now')*1000),
(3, '단체', 'organization / group', strftime('%s','now')*1000),
(3, '닫히다', 'be closed', strftime('%s','now')*1000),
(3, '달다', 'sweet / attach / hang', strftime('%s','now')*1000),
(3, '달라지다', 'change / become different', strftime('%s','now')*1000),
(3, '달러', 'dollar', strftime('%s','now')*1000),
(3, '달콤하다', 'sweet / honeyed', strftime('%s','now')*1000),
(3, '담그다', 'soak / pickle', strftime('%s','now')*1000),
(3, '담기다', 'be put into', strftime('%s','now')*1000),
(3, '담다', 'put in / include', strftime('%s','now')*1000),
(3, '닷새', 'five days', strftime('%s','now')*1000),
(3, '당근', 'carrot', strftime('%s','now')*1000),
(3, '당신', 'you (formal)', strftime('%s','now')*1000),
(3, '당연하다', 'natural / reasonable', strftime('%s','now')*1000),
(3, '당연히', 'naturally / of course', strftime('%s','now')*1000),
(3, '당장', 'immediately', strftime('%s','now')*1000),
(3, '당황', 'embarrassment / confusion', strftime('%s','now')*1000),
(3, '닿다', 'touch / reach', strftime('%s','now')*1000),
(3, '대', 'generation / counter for vehicles', strftime('%s','now')*1000),
(3, '대다', 'touch / put against', strftime('%s','now')*1000),
(3, '대단하다', 'great / amazing', strftime('%s','now')*1000),
(3, '대도시', 'metropolitan city', strftime('%s','now')*1000),
(3, '대문', 'main gate', strftime('%s','now')*1000),
(3, '대변', 'stool / excretion', strftime('%s','now')*1000),
(3, '대상', 'target / subject', strftime('%s','now')*1000),
(3, '대신', 'instead of', strftime('%s','now')*1000),
(3, '대여섯', 'about six', strftime('%s','now')*1000),
(3, '대중', 'public / mass', strftime('%s','now')*1000),
(3, '대중가요', 'popular song', strftime('%s','now')*1000),
(3, '대중교통', 'public transportation', strftime('%s','now')*1000),
(3, '대청소', 'big cleaning', strftime('%s','now')*1000),
(3, '대체로', 'generally / mostly', strftime('%s','now')*1000),
(3, '대통령', 'president', strftime('%s','now')*1000),
(3, '대표', 'representative', strftime('%s','now')*1000),
(3, '대표적', 'typical / representative', strftime('%s','now')*1000),
(3, '대하다', 'deal with / face', strftime('%s','now')*1000),
(3, '대한민국', 'Republic of Korea', strftime('%s','now')*1000),
(3, '대형', 'large-scale', strftime('%s','now')*1000),
(3, '더러워지다', 'become dirty', strftime('%s','now')*1000),
(3, '더하다', 'add / increase', strftime('%s','now')*1000),
(3, '덜', 'less', strftime('%s','now')*1000),
(3, '덜다', 'reduce / lessen', strftime('%s','now')*1000),
(3, '덮다', 'cover', strftime('%s','now')*1000),
(3, '데', 'place / situation', strftime('%s','now')*1000),
(3, '데다', 'get burned', strftime('%s','now')*1000),
(3, '데리다', 'bring / take someone', strftime('%s','now')*1000),
(3, '데치다', 'parboil / blanch', strftime('%s','now')*1000),
(3, '도', 'province / also', strftime('%s','now')*1000),
(3, '도구', 'tool / instrument', strftime('%s','now')*1000),
(3, '도둑', 'thief', strftime('%s','now')*1000),
(3, '도망가다', 'run away / escape', strftime('%s','now')*1000),
(3, '도서', 'book / publication', strftime('%s','now')*1000),
(3, '도시락', 'lunch box', strftime('%s','now')*1000),
(3, '도심', 'downtown / city center', strftime('%s','now')*1000),
(3, '도자기', 'ceramics / pottery', strftime('%s','now')*1000),
(3, '도장', 'stamp / seal', strftime('%s','now')*1000),
(3, '도중', 'on the way / in the middle', strftime('%s','now')*1000),
(3, '독감', 'flu / influenza', strftime('%s','now')*1000),
(3, '독일어', 'German language', strftime('%s','now')*1000),
(3, '돌', 'stone / first birthday', strftime('%s','now')*1000),
(3, '돌려받다', 'get back / take back', strftime('%s','now')*1000),
(3, '돌보다', 'take care of / look after', strftime('%s','now')*1000),
(3, '돌아다니다', 'go around / wander', strftime('%s','now')*1000),
(3, '동', 'east / neighborhood', strftime('%s','now')*1000),
(3, '동그라미', 'circle', strftime('%s','now')*1000),
(3, '동그랗다', 'round', strftime('%s','now')*1000),
(3, '동료', 'colleague / coworker', strftime('%s','now')*1000),
(3, '동부', 'eastern part', strftime('%s','now')*1000),
(3, '동아리', 'club / circle', strftime('%s','now')*1000),
(3, '동양', 'the East / Asia', strftime('%s','now')*1000),
(3, '동작', 'movement / motion', strftime('%s','now')*1000),
(3, '동창', 'schoolmate', strftime('%s','now')*1000),
(3, '동창회', 'alumni meeting', strftime('%s','now')*1000),
(3, '동호회', 'club / association', strftime('%s','now')*1000),
(3, '되돌아오다', 'come back / return', strftime('%s','now')*1000),
(3, '되찾다', 'recover / regain', strftime('%s','now')*1000),
(3, '두께', 'thickness', strftime('%s','now')*1000),
(3, '두통약', 'headache medicine', strftime('%s','now')*1000),
(3, '둥글다', 'round / circular', strftime('%s','now')*1000),
(3, '드라이', 'dry cleaning', strftime('%s','now')*1000),
(3, '드라이브', 'drive', strftime('%s','now')*1000),
(3, '드라이어', 'dryer', strftime('%s','now')*1000),
(3, '드레스', 'dress', strftime('%s','now')*1000),
(3, '듣기', 'listening', strftime('%s','now')*1000),
(3, '들려주다', 'play for / tell to someone', strftime('%s','now')*1000),
(3, '들어서다', 'enter / step into', strftime('%s','now')*1000),
(3, '들어주다', 'listen to / accept', strftime('%s','now')*1000),
(3, '등', 'back / etc.', strftime('%s','now')*1000),
(3, '등록', 'registration', strftime('%s','now')*1000),
(3, '등록금', 'tuition fee', strftime('%s','now')*1000),
(3, '등록증', 'registration card', strftime('%s','now')*1000),
(3, '등산복', 'hiking clothes', strftime('%s','now')*1000),
(3, '디지털', 'digital', strftime('%s','now')*1000),
(3, '따다', 'pick / open / win', strftime('%s','now')*1000),
(3, '따라가다', 'follow / go along', strftime('%s','now')*1000),
(3, '따라서', 'therefore / accordingly', strftime('%s','now')*1000),
(3, '따라오다', 'come along / follow', strftime('%s','now')*1000),
(3, '따로따로', 'separately / individually', strftime('%s','now')*1000),
(3, '따르다', 'follow / pour', strftime('%s','now')*1000),
(3, '따르릉', 'ring-ring (sound)', strftime('%s','now')*1000),
(3, '딱', 'exactly / tightly', strftime('%s','now')*1000),
(3, '딱딱하다', 'hard / stiff', strftime('%s','now')*1000),
(3, '땅속', 'underground / under the earth', strftime('%s','now')*1000),
(3, '때때로', 'sometimes / occasionally', strftime('%s','now')*1000),
(3, '떠나가다', 'leave / depart', strftime('%s','now')*1000),
(3, '떠오르다', 'rise / come to mind', strftime('%s','now')*1000),
(3, '떠올리다', 'recall / remember', strftime('%s','now')*1000),
(3, '떨다', 'tremble / shake', strftime('%s','now')*1000),
(3, '떨리다', 'tremble / quiver', strftime('%s','now')*1000),
(3, '떨어뜨리다', 'drop / let fall', strftime('%s','now')*1000),
(3, '또한', 'also / moreover', strftime('%s','now')*1000),
(3, '똑똑히', 'clearly / distinctly', strftime('%s','now')*1000),
(3, '뚫다', 'pierce / penetrate', strftime('%s','now')*1000),
(3, '뛰다', 'run / jump', strftime('%s','now')*1000),
(3, '뛰어나다', 'excel / outstanding', strftime('%s','now')*1000),
(3, '뛰어내리다', 'jump down / leap off', strftime('%s','now')*1000),
(3, '뛰어넘다', 'jump over / surpass', strftime('%s','now')*1000),
(3, '뜨다', 'float / rise / open eyes', strftime('%s','now')*1000),
(3, '띠', 'belt / ribbon / band', strftime('%s','now')*1000),
(3, '레몬', 'lemon', strftime('%s','now')*1000),
(3, '렌터카', 'rental car', strftime('%s','now')*1000),
(3, '로그인', 'login', strftime('%s','now')*1000),
(3, '로봇', 'robot', strftime('%s','now')*1000),
(3, '-률', 'rate / ratio (suffix)', strftime('%s','now')*1000),
(3, '리듬', 'rhythm', strftime('%s','now')*1000),
(3, '리본', 'ribbon', strftime('%s','now')*1000),
(3, '마늘', 'garlic', strftime('%s','now')*1000),
(3, '마라톤', 'marathon', strftime('%s','now')*1000),
(3, '마사지', 'massage', strftime('%s','now')*1000),
(3, '마우스', 'mouse', strftime('%s','now')*1000),
(3, '마음대로', 'as one pleases', strftime('%s','now')*1000),
(3, '마음씨', 'disposition / nature', strftime('%s','now')*1000),
(3, '마이크', 'microphone', strftime('%s','now')*1000),
(3, '마침', 'just / exactly / finally', strftime('%s','now')*1000),
(3, '막', 'just / randomly / film', strftime('%s','now')*1000),
(3, '막내', 'youngest child', strftime('%s','now')*1000),
(3, '막다', 'block / stop', strftime('%s','now')*1000),
(3, '막대기', 'stick / rod', strftime('%s','now')*1000),
(3, '막차', 'last train / last bus', strftime('%s','now')*1000),
(3, '만', 'only / just / ten thousand', strftime('%s','now')*1000),
(3, '만남', 'meeting / encounter', strftime('%s','now')*1000),
(3, '만족', 'satisfaction', strftime('%s','now')*1000),
(3, '만족스럽다', 'satisfying / satisfactory', strftime('%s','now')*1000),
(3, '많아지다', 'increase / grow in number', strftime('%s','now')*1000),
(3, '말다', 'stop doing / roll up', strftime('%s','now')*1000),
(3, '말리다', 'dry / dissuade', strftime('%s','now')*1000),
(3, '말하기', 'speaking', strftime('%s','now')*1000),
(3, '맞다', 'fit / be right / get hit', strftime('%s','now')*1000),
(3, '맞은편', 'opposite side', strftime('%s','now')*1000),
(3, '맞이하다', 'greet / welcome', strftime('%s','now')*1000),
(3, '맡기다', 'entrust / leave with', strftime('%s','now')*1000),
(3, '맡다', 'take charge / be responsible for', strftime('%s','now')*1000),
(3, '매', 'every / hawk / counter for times', strftime('%s','now')*1000),
(3, '매달다', 'hang / suspend', strftime('%s','now')*1000),
(3, '매운맛', 'spicy taste', strftime('%s','now')*1000),
(3, '매운탕', 'spicy fish stew', strftime('%s','now')*1000),
(3, '매장', 'store / burial', strftime('%s','now')*1000),
(3, '매점', 'snack bar / school shop', strftime('%s','now')*1000),
(3, '매진', 'sellout / be sold out', strftime('%s','now')*1000),
(3, '맨발', 'bare feet', strftime('%s','now')*1000),
(3, '먼지', 'dust', strftime('%s','now')*1000),
(3, '멀미', 'motion sickness', strftime('%s','now')*1000),
(3, '멋지다', 'cool / stylish', strftime('%s','now')*1000),
(3, '멍', 'bruise', strftime('%s','now')*1000),
(3, '메뉴판', 'menu board', strftime('%s','now')*1000),
(3, '메모지', 'notepad', strftime('%s','now')*1000),
(3, '멜로디', 'melody', strftime('%s','now')*1000),
(3, '면', 'noodles / cotton / face', strftime('%s','now')*1000),
(3, '면적', 'area / surface', strftime('%s','now')*1000),
(3, '면접', 'interview', strftime('%s','now')*1000),
(3, '면허증', 'license card', strftime('%s','now')*1000),
(3, '멸치', 'anchovy', strftime('%s','now')*1000),
(3, '명단', 'list of names', strftime('%s','now')*1000),
(3, '명함', 'business card', strftime('%s','now')*1000),
(3, '몇몇', 'several / a few', strftime('%s','now')*1000),
(3, '모니터', 'monitor', strftime('%s','now')*1000),
(3, '모델', 'model', strftime('%s','now')*1000),
(3, '모래', 'sand', strftime('%s','now')*1000),
(3, '모범', 'exemplary / model', strftime('%s','now')*1000),
(3, '모자', 'hat / cap', strftime('%s','now')*1000),
(3, '모집', 'recruitment', strftime('%s','now')*1000),
(3, '목', 'neck / throat', strftime('%s','now')*1000),
(3, '목록', 'list / catalog', strftime('%s','now')*1000),
(3, '목적지', 'destination', strftime('%s','now')*1000),
(3, '목표', 'goal / target', strftime('%s','now')*1000),
(3, '몰래', 'secretly / quietly', strftime('%s','now')*1000),
(3, '몸무게', 'body weight', strftime('%s','now')*1000),
(3, '몸살', 'fatigue / body ache', strftime('%s','now')*1000),
(3, '몸짓', 'gesture', strftime('%s','now')*1000),
(3, '묘사', 'description / portrayal', strftime('%s','now')*1000),
(3, '무늬', 'pattern / design', strftime('%s','now')*1000),
(3, '무대', 'stage', strftime('%s','now')*1000),
(3, '무더위', 'sweltering heat', strftime('%s','now')*1000),
(3, '무덤', 'grave / tomb', strftime('%s','now')*1000),
(3, '무서워하다', 'be afraid of', strftime('%s','now')*1000),
(3, '무역', 'trade', strftime('%s','now')*1000),
(3, '무용', 'dance', strftime('%s','now')*1000),
(3, '무조건', 'unconditionally / absolutely', strftime('%s','now')*1000),
(3, '묵다', 'stay / lodge', strftime('%s','now')*1000),
(3, '묶다', 'tie / bind', strftime('%s','now')*1000),
(3, '문구점', 'stationery store', strftime('%s','now')*1000),
(3, '문방구', 'stationery store', strftime('%s','now')*1000),
(3, '문법', 'grammar', strftime('%s','now')*1000),
(3, '문병', 'visit a patient', strftime('%s','now')*1000),
(3, '문의', 'inquiry / question', strftime('%s','now')*1000),
(3, '문자', 'text message / letter', strftime('%s','now')*1000),
(3, '문장', 'sentence', strftime('%s','now')*1000),
(3, '문학', 'literature', strftime('%s','now')*1000),
(3, '문화재', 'cultural asset', strftime('%s','now')*1000),
(3, '묻다', 'ask / bury', strftime('%s','now')*1000),
(3, '물', 'water', strftime('%s','now')*1000),
(3, '물가', 'price level / waterfront', strftime('%s','now')*1000),
(3, '물다', 'bite', strftime('%s','now')*1000),
(3, '물러나다', 'retreat / resign', strftime('%s','now')*1000),
(3, '물러서다', 'step back / retreat', strftime('%s','now')*1000),
(3, '물리다', 'be bitten / fed up', strftime('%s','now')*1000),
(3, '물소리', 'sound of water', strftime('%s','now')*1000),
(3, '물약', 'liquid medicine', strftime('%s','now')*1000),
(3, '물음', 'question / inquiry', strftime('%s','now')*1000),
(3, '뮤지컬', 'musical', strftime('%s','now')*1000),
(3, '미국인', 'American (person)', strftime('%s','now')*1000),
(3, '미끄럽다', 'slippery', strftime('%s','now')*1000),
(3, '미루다', 'postpone / delay', strftime('%s','now')*1000),
(3, '미만', 'under / below', strftime('%s','now')*1000),
(3, '미성년자', 'minor / underage person', strftime('%s','now')*1000),
(3, '미소', 'smile', strftime('%s','now')*1000),
(3, '미술', 'art / fine arts', strftime('%s','now')*1000),
(3, '미용사', 'hairdresser / beautician', strftime('%s','now')*1000),
(3, '미인', 'beautiful person', strftime('%s','now')*1000),
(3, '미장원', 'beauty salon', strftime('%s','now')*1000),
(3, '미팅', 'meeting / blind date', strftime('%s','now')*1000),
(3, '민속놀이', 'folk game', strftime('%s','now')*1000),
(3, '밀리다', 'be delayed / piled up', strftime('%s','now')*1000),
(3, '밉다', 'ugly / hateful', strftime('%s','now')*1000),
(3, '및', 'and / as well as', strftime('%s','now')*1000),
(3, '밑줄', 'underline', strftime('%s','now')*1000),
(3, '바', 'bar / thing / way', strftime('%s','now')*1000),
(3, '바구니', 'basket', strftime('%s','now')*1000),
(3, '바늘', 'needle', strftime('%s','now')*1000),
(3, '바닷물', 'sea water', strftime('%s','now')*1000),
(3, '바둑', 'go (board game)', strftime('%s','now')*1000),
(3, '바보', 'fool / idiot', strftime('%s','now')*1000),
(3, '바위', 'rock / boulder', strftime('%s','now')*1000),
(3, '바퀴', 'wheel / insect', strftime('%s','now')*1000),
(3, '바탕', 'basis / background', strftime('%s','now')*1000),
(3, '박', 'gourd / surname Park', strftime('%s','now')*1000),
(3, '박사', 'doctor / PhD', strftime('%s','now')*1000),
(3, '반납', 'return', strftime('%s','now')*1000),
(3, '반달', 'half moon', strftime('%s','now')*1000),
(3, '반대말', 'antonym', strftime('%s','now')*1000),
(3, '반대쪽', 'opposite side', strftime('%s','now')*1000),
(3, '반말', 'informal speech', strftime('%s','now')*1000),
(3, '반면', 'on the other hand', strftime('%s','now')*1000),
(3, '반복', 'repetition', strftime('%s','now')*1000),
(3, '반죽', 'dough / mixture', strftime('%s','now')*1000),
(3, '반창고', 'band-aid / plaster', strftime('%s','now')*1000),
(3, '반팔', 'short sleeves', strftime('%s','now')*1000),
(3, '반하다', 'fall in love / be charmed', strftime('%s','now')*1000),
(3, '발급', 'issue / issuance', strftime('%s','now')*1000),
(3, '발달', 'development / growth', strftime('%s','now')*1000),
(3, '발명', 'invention', strftime('%s','now')*1000),
(3, '발목', 'ankle', strftime('%s','now')*1000),
(3, '발음', 'pronunciation', strftime('%s','now')*1000),
(3, '발전', 'development / progress', strftime('%s','now')*1000),
(3, '발표', 'presentation / announcement', strftime('%s','now')*1000),
(3, '발행', 'publication / issue', strftime('%s','now')*1000),
(3, '밝히다', 'reveal / brighten', strftime('%s','now')*1000),
(3, '밟다', 'step on / tread', strftime('%s','now')*1000),
(3, '밤', 'night / chestnut', strftime('%s','now')*1000),
(3, '밤늦다', 'late at night', strftime('%s','now')*1000),
(3, '밤새', 'all night long', strftime('%s','now')*1000),
(3, '밤색', 'brown color', strftime('%s','now')*1000),
(3, '밥그릇', 'rice bowl', strftime('%s','now')*1000),
(3, '밥솥', 'rice cooker', strftime('%s','now')*1000),
(3, '방송사', 'broadcasting company', strftime('%s','now')*1000),
(3, '방식', 'method / style', strftime('%s','now')*1000),
(3, '방울', 'drop / small ball', strftime('%s','now')*1000),
(3, '방해', 'disturbance / obstruction', strftime('%s','now')*1000),
(3, '배고프다', 'be hungry', strftime('%s','now')*1000),
(3, '배구', 'volleyball', strftime('%s','now')*1000),
(3, '배낭', 'backpack', strftime('%s','now')*1000),
(3, '배낭여행', 'backpacking trip', strftime('%s','now')*1000),
(3, '배웅', 'see off / escort', strftime('%s','now')*1000),
(3, '배치', 'arrangement / placement', strftime('%s','now')*1000),
(3, '배터리', 'battery', strftime('%s','now')*1000),
(3, '배편', 'by ship / sea mail', strftime('%s','now')*1000),
(3, '백', 'hundred / white / background', strftime('%s','now')*1000),
(3, '뱃속', 'inside the stomach', strftime('%s','now')*1000),
(3, '버섯', 'mushroom', strftime('%s','now')*1000),
(3, '버터', 'butter', strftime('%s','now')*1000),
(3, '버튼', 'button', strftime('%s','now')*1000),
(3, '번개', 'lightning', strftime('%s','now')*1000),
(3, '번역', 'translation', strftime('%s','now')*1000),
(3, '번지', 'lot number / address number', strftime('%s','now')*1000),
(3, '번호표', 'number ticket', strftime('%s','now')*1000),
(3, '벌', 'bee / punishment', strftime('%s','now')*1000),
(3, '벌금', 'fine / penalty', strftime('%s','now')*1000),
(3, '범죄', 'crime', strftime('%s','now')*1000),
(3, '법', 'law', strftime('%s','now')*1000),
(3, '법칙', 'rule / law', strftime('%s','now')*1000),
(3, '벗기다', 'peel off / strip', strftime('%s','now')*1000),
(3, '베란다', 'balcony / veranda', strftime('%s','now')*1000),
(3, '벤치', 'bench', strftime('%s','now')*1000),
(3, '벨', 'bell', strftime('%s','now')*1000),
(3, '벨트', 'belt', strftime('%s','now')*1000),
(3, '벽시계', 'wall clock', strftime('%s','now')*1000),
(3, '벽지', 'wallpaper', strftime('%s','now')*1000),
(3, '변경', 'change / modification', strftime('%s','now')*1000),
(3, '변비', 'constipation', strftime('%s','now')*1000),
(3, '변화', 'change / transformation', strftime('%s','now')*1000),
(3, '별', 'star / special', strftime('%s','now')*1000),
(3, '별말씀', 'no need for thanks', strftime('%s','now')*1000),
(3, '별명', 'nickname', strftime('%s','now')*1000),
(3, '별일', 'particular thing / matter', strftime('%s','now')*1000),
(3, '병실', 'hospital room', strftime('%s','now')*1000),
(3, '보고', 'report', strftime('%s','now')*1000),
(3, '보고서', 'written report', strftime('%s','now')*1000),
(3, '보관', 'storage / keeping', strftime('%s','now')*1000),
(3, '보기', 'example / instance', strftime('%s','now')*1000),
(3, '보너스', 'bonus', strftime('%s','now')*1000),
(3, '보람', 'worth / reward', strftime('%s','now')*1000),
(3, '보름', 'fifteen days', strftime('%s','now')*1000),
(3, '보름달', 'full moon', strftime('%s','now')*1000),
(3, '보리', 'barley', strftime('%s','now')*1000),
(3, '보석', 'jewel / gem', strftime('%s','now')*1000),
(3, '보행자', 'pedestrian', strftime('%s','now')*1000),
(3, '보험', 'insurance', strftime('%s','now')*1000),
(3, '보호', 'protection / care', strftime('%s','now')*1000),
(3, '복', 'luck / blessing', strftime('%s','now')*1000),
(3, '복도', 'corridor / hallway', strftime('%s','now')*1000),
(3, '복사', 'copy / duplication', strftime('%s','now')*1000),
(3, '복사기', 'copy machine', strftime('%s','now')*1000),
(3, '복숭아', 'peach', strftime('%s','now')*1000),
(3, '복용', 'dosage / taking medicine', strftime('%s','now')*1000),
(3, '복통', 'stomachache', strftime('%s','now')*1000),
(3, '본인', 'oneself / the person concerned', strftime('%s','now')*1000),
(3, '볼거리', 'sight to see / attraction', strftime('%s','now')*1000),
(3, '볼링', 'bowling', strftime('%s','now')*1000),
(3, '볼일', 'business / things to do', strftime('%s','now')*1000),
(3, '봉사', 'service / volunteer work', strftime('%s','now')*1000),
(3, '봉지', 'bag / packet', strftime('%s','now')*1000),
(3, '뵈다', 'see (honorific)', strftime('%s','now')*1000),
(3, '부', 'department / part / wealth', strftime('%s','now')*1000),
(3, '부담', 'burden / pressure', strftime('%s','now')*1000),
(3, '부동산', 'real estate', strftime('%s','now')*1000),
(3, '부러워하다', 'envy / admire', strftime('%s','now')*1000),
(3, '부러지다', 'be broken / snapped', strftime('%s','now')*1000),
(3, '부리다', 'handle / display (emotion)', strftime('%s','now')*1000),
(3, '부모', 'parents', strftime('%s','now')*1000),
(3, '부인', 'wife / deny', strftime('%s','now')*1000),
(3, '부자', 'rich person / father and son', strftime('%s','now')*1000),
(3, '부잣집', 'rich family', strftime('%s','now')*1000),
(3, '부채', 'fan / debt', strftime('%s','now')*1000),
(3, '부츠', 'boots', strftime('%s','now')*1000),
(3, '부친', 'father', strftime('%s','now')*1000),
(3, '북', 'drum / north', strftime('%s','now')*1000),
(3, '북부', 'northern region', strftime('%s','now')*1000),
(3, '분단', 'division / separation', strftime('%s','now')*1000),
(3, '분리', 'separation / division', strftime('%s','now')*1000),
(3, '분명히', 'clearly / definitely', strftime('%s','now')*1000),
(3, '분실', 'loss (of something)', strftime('%s','now')*1000),
(3, '분실물', 'lost item', strftime('%s','now')*1000),
(3, '분필', 'chalk', strftime('%s','now')*1000),
(3, '불', 'fire / not-', strftime('%s','now')*1000),
(3, '불규칙', 'irregularity', strftime('%s','now')*1000),
(3, '불균형', 'imbalance', strftime('%s','now')*1000),
(3, '불만', 'dissatisfaction / complaint', strftime('%s','now')*1000),
(3, '불만족', 'discontent / dissatisfaction', strftime('%s','now')*1000),
(3, '불만족스럽다', 'unsatisfactory', strftime('%s','now')*1000),
(3, '불어', 'French language', strftime('%s','now')*1000),
(3, '불완전', 'incomplete / imperfect', strftime('%s','now')*1000),
(3, '불평', 'complaint / grievance', strftime('%s','now')*1000),
(3, '붐비다', 'be crowded', strftime('%s','now')*1000),
(3, '붓다', 'swell / pour', strftime('%s','now')*1000),
(3, '뷔페', 'buffet', strftime('%s','now')*1000),
(3, '비', 'rain / ratio / fee', strftime('%s','now')*1000),
(3, '비밀번호', 'password', strftime('%s','now')*1000),
(3, '비비다', 'rub / mix', strftime('%s','now')*1000),
(3, '비상구', 'emergency exit', strftime('%s','now')*1000),
(3, '비용', 'cost / expense', strftime('%s','now')*1000),
(3, '비자', 'visa', strftime('%s','now')*1000),
(3, '비키다', 'step aside / move away', strftime('%s','now')*1000),
(3, '비타민', 'vitamin', strftime('%s','now')*1000),
(3, '비하다', 'compare with', strftime('%s','now')*1000),
(3, '비행', 'flight / aviation', strftime('%s','now')*1000),
(3, '비행장', 'airfield / airport', strftime('%s','now')*1000),
(3, '빈자리', 'empty seat / vacancy', strftime('%s','now')*1000),
(3, '빌다', 'wish / pray', strftime('%s','now')*1000),
(3, '빗다', 'comb hair', strftime('%s','now')*1000),
(3, '빛', 'light / color / glow', strftime('%s','now')*1000),
(3, '빠지다', 'fall / sink / be absent', strftime('%s','now')*1000),
(3, '빨강', 'red color', strftime('%s','now')*1000),
(3, '빨개지다', 'turn red / blush', strftime('%s','now')*1000),
(3, '빨다', 'wash / suck', strftime('%s','now')*1000),
(3, '뺏다', 'take away / deprive', strftime('%s','now')*1000),
(3, '뼈', 'bone', strftime('%s','now')*1000),
(3, '뽀뽀', 'kiss (childish)', strftime('%s','now')*1000),
(3, '뿌리', 'root / origin', strftime('%s','now')*1000),
(3, '뿌리다', 'sprinkle / scatter', strftime('%s','now')*1000),
(3, '삐다', 'sprain / twist', strftime('%s','now')*1000),
(3, '사건', 'incident / case', strftime('%s','now')*1000),
(3, '사과', 'apple / apology', strftime('%s','now')*1000),
(3, '사교적', 'sociable', strftime('%s','now')*1000),
(3, '사나이', 'man / guy', strftime('%s','now')*1000),
(3, '사라지다', 'disappear / vanish', strftime('%s','now')*1000),
(3, '사무', 'office work', strftime('%s','now')*1000),
(3, '사무소', 'office', strftime('%s','now')*1000),
(3, '사물', 'thing / object', strftime('%s','now')*1000),
(3, '사생활', 'private life', strftime('%s','now')*1000),
(3, '사업가', 'businessperson', strftime('%s','now')*1000),
(3, '사용법', 'how to use / instructions', strftime('%s','now')*1000),
(3, '사우나', 'sauna', strftime('%s','now')*1000),
(3, '사이트', 'website', strftime('%s','now')*1000),
(3, '사인', 'signature / autograph', strftime('%s','now')*1000),
(3, '사자', 'lion / messenger', strftime('%s','now')*1000),
(3, '사적', 'personal / private', strftime('%s','now')*1000),
(3, '사전', 'dictionary / beforehand', strftime('%s','now')*1000),
(3, '사진관', 'photo studio', strftime('%s','now')*1000),
(3, '사촌', 'cousin', strftime('%s','now')*1000),
(3, '사항', 'matter / item / detail', strftime('%s','now')*1000),
(3, '사회', 'society / hosting', strftime('%s','now')*1000),
(3, '사회자', 'MC / host', strftime('%s','now')*1000),
(3, '사회적', 'social', strftime('%s','now')*1000),
(3, '삭제', 'deletion / remove', strftime('%s','now')*1000),
(3, '산꼭대기', 'mountaintop', strftime('%s','now')*1000),
(3, '산업', 'industry', strftime('%s','now')*1000),
(3, '살아나다', 'come back to life / survive', strftime('%s','now')*1000),
(3, '살인', 'murder', strftime('%s','now')*1000),
(3, '살짝', 'lightly / slightly', strftime('%s','now')*1000),
(3, '살찌다', 'gain weight', strftime('%s','now')*1000),
(3, '살펴보다', 'look over / examine', strftime('%s','now')*1000),
(3, '살피다', 'check / inspect', strftime('%s','now')*1000),
(3, '삶', 'life / living', strftime('%s','now')*1000),
(3, '삶다', 'boil / cook', strftime('%s','now')*1000),
(3, '상', 'prize / award / top', strftime('%s','now')*1000),
(3, '상관없다', 'doesn’t matter / irrelevant', strftime('%s','now')*1000),
(3, '상담', 'counseling / consultation', strftime('%s','now')*1000),
(3, '상대방', 'the other party / counterpart', strftime('%s','now')*1000),
(3, '상식', 'common sense', strftime('%s','now')*1000),
(3, '상영', 'screening (film)', strftime('%s','now')*1000),
(3, '상점', 'store / shop', strftime('%s','now')*1000),
(3, '상태', 'state / condition', strftime('%s','now')*1000),
(3, '상하다', 'go bad / be damaged', strftime('%s','now')*1000),
(3, '상황', 'situation / circumstance', strftime('%s','now')*1000),
(3, '새로이', 'anew / afresh', strftime('%s','now')*1000),
(3, '새엄마', 'stepmother', strftime('%s','now')*1000),
(3, '새우', 'shrimp', strftime('%s','now')*1000),
(3, '새집', 'new house', strftime('%s','now')*1000),
(3, '샌들', 'sandals', strftime('%s','now')*1000),
(3, '생년월일', 'date of birth', strftime('%s','now')*1000),
(3, '생머리', 'straight hair', strftime('%s','now')*1000),
(3, '생활비', 'living expenses', strftime('%s','now')*1000),
(3, '생활용품', 'daily necessities', strftime('%s','now')*1000),
(3, '샴푸', 'shampoo', strftime('%s','now')*1000),
(3, '서', 'west / book / stand', strftime('%s','now')*1000),
(3, '서넛', 'three or four', strftime('%s','now')*1000),
(3, '서명', 'signature', strftime('%s','now')*1000),
(3, '서부', 'western region', strftime('%s','now')*1000),
(3, '서투르다', 'clumsy / unskilled', strftime('%s','now')*1000),
(3, '석유', 'oil / petroleum', strftime('%s','now')*1000),
(3, '선', 'line / wire / selection', strftime('%s','now')*1000),
(3, '선글라스', 'sunglasses', strftime('%s','now')*1000),
(3, '선약', 'prior appointment', strftime('%s','now')*1000),
(3, '설', 'Lunar New Year', strftime('%s','now')*1000),
(3, '설명서', 'manual / instruction book', strftime('%s','now')*1000),
(3, '설문', 'survey / questionnaire', strftime('%s','now')*1000),
(3, '설문지', 'survey form', strftime('%s','now')*1000),
(3, '설사', 'diarrhea', strftime('%s','now')*1000),
(3, '성당', 'cathedral / church', strftime('%s','now')*1000),
(3, '성명', 'full name', strftime('%s','now')*1000),
(3, '성별', 'gender', strftime('%s','now')*1000),
(3, '성실', 'sincerity / diligence', strftime('%s','now')*1000),
(3, '성인', 'adult', strftime('%s','now')*1000),
(3, '세기', 'century', strftime('%s','now')*1000),
(3, '세다', 'strong / count', strftime('%s','now')*1000),
(3, '세련되다', 'sophisticated / polished', strftime('%s','now')*1000),
(3, '세로', 'vertical / lengthwise', strftime('%s','now')*1000),
(3, '세월', 'time / years', strftime('%s','now')*1000),
(3, '세일', 'sale / discount', strftime('%s','now')*1000),
(3, '세제', 'detergent', strftime('%s','now')*1000),
(3, '세차', 'car wash', strftime('%s','now')*1000),
(3, '세탁물', 'laundry', strftime('%s','now')*1000),
(3, '세트', 'set', strftime('%s','now')*1000),
(3, '센티', 'centimeter', strftime('%s','now')*1000),
(3, '셔츠', 'shirt', strftime('%s','now')*1000),
(3, '소', 'cow / small / rumor', strftime('%s','now')*1000),
(3, '소감', 'impression / thoughts', strftime('%s','now')*1000),
(3, '소개팅', 'blind date', strftime('%s','now')*1000),
(3, '소극장', 'small theater', strftime('%s','now')*1000),
(3, '소금물', 'salt water', strftime('%s','now')*1000),
(3, '소나기', 'shower / rainstorm', strftime('%s','now')*1000),
(3, '소독', 'disinfection', strftime('%s','now')*1000),
(3, '소독약', 'disinfectant', strftime('%s','now')*1000),
(3, '소매', 'sleeve / retail', strftime('%s','now')*1000),
(3, '소문', 'rumor', strftime('%s','now')*1000),
(3, '소방관', 'firefighter', strftime('%s','now')*1000),
(3, '소방서', 'fire station', strftime('%s','now')*1000),
(3, '소변', 'urine', strftime('%s','now')*1000),
(3, '소설가', 'novelist', strftime('%s','now')*1000),
(3, '소설책', 'novel book', strftime('%s','now')*1000),
(3, '소시지', 'sausage', strftime('%s','now')*1000),
(3, '소아과', 'pediatrics', strftime('%s','now')*1000),
(3, '소요', 'requirement / need', strftime('%s','now')*1000),
(3, '소원', 'wish / desire', strftime('%s','now')*1000),
(3, '소화', 'digestion / extinguish', strftime('%s','now')*1000),
(3, '속담', 'proverb / saying', strftime('%s','now')*1000),
(3, '속상하다', 'upset / distressed', strftime('%s','now')*1000),
(3, '손가방', 'handbag', strftime('%s','now')*1000),
(3, '손등', 'back of the hand', strftime('%s','now')*1000),
(3, '손목', 'wrist', strftime('%s','now')*1000),
(3, '손목시계', 'wristwatch', strftime('%s','now')*1000),
(3, '손발', 'hands and feet', strftime('%s','now')*1000),
(3, '손뼉', 'clap / palm', strftime('%s','now')*1000),
(3, '손자', 'grandson', strftime('%s','now')*1000),
(3, '솜씨', 'skill / ability', strftime('%s','now')*1000),
(3, '송별회', 'farewell party', strftime('%s','now')*1000),
(3, '송이', 'counter for flowers or grapes', strftime('%s','now')*1000),
(3, '쇠고기', 'beef', strftime('%s','now')*1000),
(3, '쇼', 'show', strftime('%s','now')*1000),
(3, '쇼핑몰', 'shopping mall', strftime('%s','now')*1000),
(3, '쇼핑센터', 'shopping center', strftime('%s','now')*1000),
(3, '수', 'number / water / ability', strftime('%s','now')*1000),
(3, '수다', 'chatter / talk', strftime('%s','now')*1000),
(3, '수단', 'means / method', strftime('%s','now')*1000),
(3, '수도', 'capital city / water supply', strftime('%s','now')*1000),
(3, '수량', 'quantity / amount of water', strftime('%s','now')*1000),
(3, '수리', 'repair', strftime('%s','now')*1000),
(3, '수면', 'sleep', strftime('%s','now')*1000),
(3, '수면제', 'sleeping pill', strftime('%s','now')*1000),
(3, '수선', 'mending / alteration', strftime('%s','now')*1000),
(3, '수수료', 'commission / fee', strftime('%s','now')*1000),
(3, '수입', 'income / import', strftime('%s','now')*1000),
(3, '수정', 'correction / revision', strftime('%s','now')*1000),
(3, '수집', 'collection / gathering', strftime('%s','now')*1000),
(3, '수출', 'export', strftime('%s','now')*1000),
(3, '수표', 'bank check', strftime('%s','now')*1000),
(3, '수학', 'mathematics', strftime('%s','now')*1000),
(3, '숙박', 'lodging / accommodation', strftime('%s','now')*1000),
(3, '숙박비', 'lodging fee', strftime('%s','now')*1000),
(3, '숙소', 'accommodation / place to stay', strftime('%s','now')*1000),
(3, '순간', 'moment / instant', strftime('%s','now')*1000),
(3, '술잔', 'drinking glass', strftime('%s','now')*1000),
(3, '숨다', 'hide', strftime('%s','now')*1000),
(3, '숲', 'forest / woods', strftime('%s','now')*1000),
(3, '쉬다', 'rest', strftime('%s','now')*1000),
(3, '쉿', 'shh (be quiet)', strftime('%s','now')*1000),
(3, '슈퍼', 'supermarket', strftime('%s','now')*1000),
(3, '스무째', 'twentieth (ordinal)', strftime('%s','now')*1000),
(3, '스커트', 'skirt', strftime('%s','now')*1000),
(3, '스타일', 'style', strftime('%s','now')*1000),
(3, '스타킹', 'stockings', strftime('%s','now')*1000),
(3, '슬리퍼', 'slippers', strftime('%s','now')*1000),
(3, '습기', 'humidity / dampness', strftime('%s','now')*1000),
(3, '습도', 'humidity level', strftime('%s','now')*1000),
(3, '습하다', 'humid / damp', strftime('%s','now')*1000),
(3, '승객', 'passenger', strftime('%s','now')*1000),
(3, '승무원', 'crew member / flight attendant', strftime('%s','now')*1000),
(3, '승진', 'promotion / advancement', strftime('%s','now')*1000),
(3, '승차', 'boarding', strftime('%s','now')*1000),
(3, '승차권', 'boarding ticket', strftime('%s','now')*1000),
(3, '시', 'city / poetry / time', strftime('%s','now')*1000),
(3, '시각', 'time / viewpoint', strftime('%s','now')*1000),
(3, '시기', 'time period / opportunity', strftime('%s','now')*1000),
(3, '시내버스', 'city bus', strftime('%s','now')*1000),
(3, '시대', 'era / age / period', strftime('%s','now')*1000),
(3, '시디', 'CD / compact disc', strftime('%s','now')*1000),
(3, '시설', 'facility / installation', strftime('%s','now')*1000),
(3, '시아버지', 'father-in-law (husband’s father)', strftime('%s','now')*1000),
(3, '시외', 'suburbs / outside the city', strftime('%s','now')*1000),
(3, '시외버스', 'intercity bus', strftime('%s','now')*1000),
(3, '시장', 'market / mayor', strftime('%s','now')*1000),
(3, '시집', 'married woman’s new home / poetry book', strftime('%s','now')*1000),
(3, '시험지', 'exam paper', strftime('%s','now')*1000),
(3, '식기', 'tableware / dishes', strftime('%s','now')*1000),
(3, '식당가', 'restaurant area / food court', strftime('%s','now')*1000),
(3, '식료품', 'groceries / foodstuffs', strftime('%s','now')*1000),
(3, '식비', 'meal expenses', strftime('%s','now')*1000),
(3, '식사량', 'amount of food intake', strftime('%s','now')*1000),
(3, '식용유', 'cooking oil', strftime('%s','now')*1000),
(3, '식중독', 'food poisoning', strftime('%s','now')*1000),
(3, '식품점', 'food store / grocery store', strftime('%s','now')*1000),
(3, '식후', 'after a meal', strftime('%s','now')*1000),
(3, '식히다', 'cool down / let cool', strftime('%s','now')*1000),
(3, '신경', 'nerve / concern / care', strftime('%s','now')*1000),
(3, '신고', 'report / declaration', strftime('%s','now')*1000),
(3, '신기하다', 'amazing / marvelous', strftime('%s','now')*1000),
(3, '신나다', 'be excited / have fun', strftime('%s','now')*1000),
(3, '신문사', 'newspaper company', strftime('%s','now')*1000),
(3, '신문지', 'newspaper paper', strftime('%s','now')*1000),
(3, '신부', 'bride / Catholic priest', strftime('%s','now')*1000),
(3, '신분', 'social status / identity', strftime('%s','now')*1000),
(3, '신사', 'gentleman', strftime('%s','now')*1000),
(3, '신용', 'credit / trust', strftime('%s','now')*1000),
(3, '신입', 'newcomer / beginner', strftime('%s','now')*1000),
(3, '신입생', 'new student / freshman', strftime('%s','now')*1000),
(3, '신청서', 'application form', strftime('%s','now')*1000),
(3, '신체', 'body / physique', strftime('%s','now')*1000),
(3, '신혼', 'newlywed life', strftime('%s','now')*1000),
(3, '신혼부부', 'newlywed couple', strftime('%s','now')*1000),
(3, '실', 'room / thread / cord', strftime('%s','now')*1000),
(3, '실내', 'indoor / inside', strftime('%s','now')*1000),
(3, '실력', 'ability / skill', strftime('%s','now')*1000),
(3, '실리다', 'be put / be loaded', strftime('%s','now')*1000),
(3, '실망', 'disappointment', strftime('%s','now')*1000),
(3, '실제로', 'in reality / actually', strftime('%s','now')*1000),
(3, '실종', 'disappearance / missing', strftime('%s','now')*1000),
(3, '실컷', 'to one’s heart’s content / fully', strftime('%s','now')*1000),
(3, '싫증', 'boredom / disinterest', strftime('%s','now')*1000),
(3, '심각하다', 'serious / severe', strftime('%s','now')*1000),
(3, '심리', 'psychology / mentality', strftime('%s','now')*1000),
(3, '싱싱하다', 'fresh / lively', strftime('%s','now')*1000),
(3, '싸다', 'cheap / pack', strftime('%s','now')*1000),
(3, '쌍', 'pair / couple / twin', strftime('%s','now')*1000),
(3, '쌍둥이', 'twins', strftime('%s','now')*1000),
(3, '쌓이다', 'pile up / accumulate', strftime('%s','now')*1000),
(3, '썩다', 'rot / spoil', strftime('%s','now')*1000),
(3, '쏟다', 'pour / devote', strftime('%s','now')*1000),
(3, '쏟아지다', 'pour down / fall heavily', strftime('%s','now')*1000),
(3, '쓰기', 'writing / use', strftime('%s','now')*1000),
(3, '쓰이다', 'be used / be written', strftime('%s','now')*1000),
(3, '쓸다', 'sweep / brush', strftime('%s','now')*1000),
(3, '씨', 'seed / Mr.', strftime('%s','now')*1000),
(3, '아가', 'baby', strftime('%s','now')*1000),
(3, '아끼다', 'save / cherish', strftime('%s','now')*1000),
(3, '아래층', 'lower floor', strftime('%s','now')*1000),
(3, '아랫사람', 'junior / subordinate', strftime('%s','now')*1000),
(3, '아랫집', 'downstairs neighbor', strftime('%s','now')*1000),
(3, '아쉽다', 'feel sorry / regretful', strftime('%s','now')*1000),
(3, '아시아', 'Asia', strftime('%s','now')*1000),
(3, '아이', 'child / kid', strftime('%s','now')*1000),
(3, '아이고', 'oh my! / dear me', strftime('%s','now')*1000),
(3, '아이디어', 'idea', strftime('%s','now')*1000),
(3, '아침밥', 'breakfast', strftime('%s','now')*1000),
(3, '아침저녁', 'morning and evening', strftime('%s','now')*1000),
(3, '아프리카', 'Africa', strftime('%s','now')*1000),
(3, '아픔', 'pain / ache', strftime('%s','now')*1000),
(3, '아홉째', 'ninth (ordinal)', strftime('%s','now')*1000),
(3, '악수', 'handshake', strftime('%s','now')*1000),
(3, '안과', 'ophthalmology / eye clinic', strftime('%s','now')*1000),
(3, '안내서', 'guidebook / brochure', strftime('%s','now')*1000),
(3, '안내원', 'guide / attendant', strftime('%s','now')*1000),
(3, '안내판', 'information board / sign', strftime('%s','now')*1000),
(3, '안방', 'main room / master bedroom', strftime('%s','now')*1000),
(3, '안부', 'regards / well-being', strftime('%s','now')*1000),
(3, '안색', 'complexion', strftime('%s','now')*1000),
(3, '안심', 'relief / reassurance', strftime('%s','now')*1000),
(3, '안약', 'eye drops', strftime('%s','now')*1000),
(3, '안전띠', 'seat belt', strftime('%s','now')*1000),
(3, '안정', 'stability / calmness', strftime('%s','now')*1000),
(3, '않다', 'not do', strftime('%s','now')*1000),
(3, '알', 'egg / grain / unit', strftime('%s','now')*1000),
(3, '알레르기', 'allergy', strftime('%s','now')*1000),
(3, '알려지다', 'be known / be informed', strftime('%s','now')*1000),
(3, '알아내다', 'find out / discover', strftime('%s','now')*1000),
(3, '알아듣다', 'understand (spoken)', strftime('%s','now')*1000),
(3, '암', 'cancer', strftime('%s','now')*1000),
(3, '앞날', 'future / days ahead', strftime('%s','now')*1000),
(3, '앞뒤', 'front and back / order', strftime('%s','now')*1000),
(3, '앞머리', 'bangs / front hair', strftime('%s','now')*1000),
(3, '앞집', 'house in front', strftime('%s','now')*1000),
(3, '애기', 'baby / infant (casual)', strftime('%s','now')*1000),
(3, '애완동물', 'pet', strftime('%s','now')*1000),
(3, '액세서리', 'accessory', strftime('%s','now')*1000),
(3, '액자', 'frame', strftime('%s','now')*1000),
(3, '야경', 'night view', strftime('%s','now')*1000),
(3, '야근', 'night shift / overtime', strftime('%s','now')*1000),
(3, '야외', 'outdoors', strftime('%s','now')*1000),
(3, '약도', 'map / sketch map', strftime('%s','now')*1000),
(3, '약품', 'medicine / drug', strftime('%s','now')*1000),
(3, '양', 'amount / sheep', strftime('%s','now')*1000),
(3, '양념', 'seasoning / spice', strftime('%s','now')*1000),
(3, '양력', 'solar calendar', strftime('%s','now')*1000),
(3, '양배추', 'cabbage', strftime('%s','now')*1000),
(3, '양보', 'concession / yield', strftime('%s','now')*1000),
(3, '양산', 'parasol', strftime('%s','now')*1000),
(3, '양식', 'form / western food', strftime('%s','now')*1000),
(3, '양옆', 'both sides', strftime('%s','now')*1000),
(3, '양쪽', 'both sides', strftime('%s','now')*1000),
(3, '양파', 'onion', strftime('%s','now')*1000),
(3, '얘', 'this kid / child', strftime('%s','now')*1000),
(3, '어기다', 'break / violate', strftime('%s','now')*1000),
(3, '어느새', 'before one knows / already', strftime('%s','now')*1000),
(3, '어떡하다', 'what to do / how to act', strftime('%s','now')*1000),
(3, '어려움', 'difficulty / hardship', strftime('%s','now')*1000),
(3, '어머', 'oh my! (surprise)', strftime('%s','now')*1000),
(3, '어저께', 'yesterday', strftime('%s','now')*1000),
(3, '어지럽다', 'dizzy / chaotic', strftime('%s','now')*1000),
(3, '어휘', 'vocabulary', strftime('%s','now')*1000),
(3, '어휴', 'phew / sigh', strftime('%s','now')*1000),
(3, '언덕', 'hill / slope', strftime('%s','now')*1000),
(3, '얼룩', 'stain / spot', strftime('%s','now')*1000),
(3, '얼른', 'quickly / immediately', strftime('%s','now')*1000),
(3, '얼마간', 'for some time / somewhat', strftime('%s','now')*1000),
(3, '업다', 'carry on the back', strftime('%s','now')*1000),
(3, '업무', 'business / duty / task', strftime('%s','now')*1000),
(3, '없애다', 'remove / eliminate', strftime('%s','now')*1000),
(3, '없어지다', 'disappear / vanish', strftime('%s','now')*1000),
(3, '없이', 'without', strftime('%s','now')*1000),
(3, '엊그제', 'a few days ago / recently', strftime('%s','now')*1000),
(3, '에스컬레이터', 'escalator', strftime('%s','now')*1000),
(3, '여가', 'leisure time', strftime('%s','now')*1000),
(3, '여관', 'inn / small hotel', strftime('%s','now')*1000),
(3, '여기다', 'regard / consider', strftime('%s','now')*1000),
(3, '여드름', 'pimple / acne', strftime('%s','now')*1000),
(3, '여름철', 'summer season', strftime('%s','now')*1000),
(3, '여름휴가', 'summer vacation', strftime('%s','now')*1000),
(3, '여보', 'honey / dear (spouse)', strftime('%s','now')*1000),
(3, '여유', 'spare time / composure', strftime('%s','now')*1000),
(3, '여유롭다', 'relaxed / easygoing', strftime('%s','now')*1000),
(3, '여인', 'woman / lady', strftime('%s','now')*1000),
(3, '여쭈다', 'ask (honorific)', strftime('%s','now')*1000),
(3, '역사가', 'historian', strftime('%s','now')*1000),
(3, '역사적', 'historical', strftime('%s','now')*1000),
(3, '역할', 'role / part', strftime('%s','now')*1000),
(3, '연', 'kite / connection / relationship', strftime('%s','now')*1000),
(3, '연고', 'ointment', strftime('%s','now')*1000),
(3, '연구', 'research / study', strftime('%s','now')*1000),
(3, '연기', 'smoke / acting / postponement', strftime('%s','now')*1000),
(3, '연두색', 'light green', strftime('%s','now')*1000),
(3, '연인', 'lover / couple', strftime('%s','now')*1000),
(3, '연장', 'extension / tool', strftime('%s','now')*1000),
(3, '연주', 'performance / play (music)', strftime('%s','now')*1000),
(3, '연주회', 'concert / recital', strftime('%s','now')*1000),
(3, '연하다', 'light / soft / mild', strftime('%s','now')*1000),
(3, '열리다', 'open / be held', strftime('%s','now')*1000),
(3, '열쇠고리', 'key ring', strftime('%s','now')*1000),
(3, '열째', 'tenth (ordinal)', strftime('%s','now')*1000),
(3, '영', 'zero / spirit / young', strftime('%s','now')*1000),
(3, '영리하다', 'clever / intelligent', strftime('%s','now')*1000),
(3, '영상', 'image / video', strftime('%s','now')*1000),
(3, '영양', 'nutrition', strftime('%s','now')*1000),
(3, '영양제', 'nutrient supplement', strftime('%s','now')*1000),
(3, '영웅', 'hero', strftime('%s','now')*1000),
(3, '영원히', 'forever / eternally', strftime('%s','now')*1000),
(3, '영향', 'influence / effect', strftime('%s','now')*1000),
(3, '예', 'example / case / manners', strftime('%s','now')*1000),
(3, '예금', 'deposit / savings', strftime('%s','now')*1000),
(3, '예방', 'prevention', strftime('%s','now')*1000),
(3, '예보', 'forecast / prediction', strftime('%s','now')*1000),
(3, '예상', 'expectation / anticipation', strftime('%s','now')*1000),
(3, '예식장', 'wedding hall', strftime('%s','now')*1000),
(3, '예의', 'manners / courtesy', strftime('%s','now')*1000),
(3, '예절', 'etiquette / decorum', strftime('%s','now')*1000),
(3, '예정', 'schedule / plan', strftime('%s','now')*1000),
(3, '예측', 'prediction / forecast', strftime('%s','now')*1000),
(3, '예컨대', 'for example / for instance', strftime('%s','now')*1000),
(3, '옛날이야기', 'old story / folktale', strftime('%s','now')*1000),
(3, '오', 'five / oh / come', strftime('%s','now')*1000),
(3, '오락실', 'game arcade', strftime('%s','now')*1000),
(3, '오래오래', 'for a long long time', strftime('%s','now')*1000),
(3, '오랜', 'long / of long duration', strftime('%s','now')*1000),
(3, '오른편', 'right side', strftime('%s','now')*1000),
(3, '오리', 'duck', strftime('%s','now')*1000),
(3, '오징어', 'squid', strftime('%s','now')*1000),
(3, '오토바이', 'motorcycle', strftime('%s','now')*1000),
(3, '오페라', 'opera', strftime('%s','now')*1000),
(3, '오피스텔', 'studio apartment / officetel', strftime('%s','now')*1000),
(3, '오해', 'misunderstanding', strftime('%s','now')*1000),
(3, '온', 'all / entire / whole', strftime('%s','now')*1000),
(3, '온몸', 'whole body', strftime('%s','now')*1000),
(3, '온천', 'hot spring', strftime('%s','now')*1000),
(3, '올', 'this year / thread', strftime('%s','now')*1000),
(3, '올라서다', 'step up / rise onto', strftime('%s','now')*1000),
(3, '올려놓다', 'put up / place on', strftime('%s','now')*1000),
(3, '올바르다', 'right / correct / proper', strftime('%s','now')*1000),
(3, '올여름', 'this summer', strftime('%s','now')*1000),
(3, '옮기다', 'move / transfer / shift', strftime('%s','now')*1000),
(3, '옷차림', 'outfit / attire', strftime('%s','now')*1000),
(3, '와인', 'wine', strftime('%s','now')*1000),
(3, '완성', 'completion / perfection', strftime('%s','now')*1000),
(3, '왕복', 'round trip', strftime('%s','now')*1000),
(3, '외', 'outside / except / foreign', strftime('%s','now')*1000),
(3, '외과', 'surgery / surgical department', strftime('%s','now')*1000),
(3, '외교', 'diplomacy', strftime('%s','now')*1000),
(3, '외교관', 'diplomat', strftime('%s','now')*1000),
(3, '외모', 'appearance / looks', strftime('%s','now')*1000),
(3, '외박', 'sleep out / stay out overnight', strftime('%s','now')*1000),
(3, '외부', 'outside / exterior', strftime('%s','now')*1000),
(3, '외삼촌', 'maternal uncle', strftime('%s','now')*1000),
(3, '외숙모', 'maternal aunt (uncle’s wife)', strftime('%s','now')*1000),
(3, '외식', 'eating out', strftime('%s','now')*1000),
(3, '외투', 'coat / overcoat', strftime('%s','now')*1000),
(3, '외할머니', 'maternal grandmother', strftime('%s','now')*1000),
(3, '외할아버지', 'maternal grandfather', strftime('%s','now')*1000),
(3, '왼발', 'left foot', strftime('%s','now')*1000),
(3, '요', 'this / request ending particle', strftime('%s','now')*1000),
(3, '요가', 'yoga', strftime('%s','now')*1000),
(3, '요구르트', 'yogurt', strftime('%s','now')*1000),
(3, '요리법', 'recipe / cooking method', strftime('%s','now')*1000),
(3, '욕실', 'bathroom', strftime('%s','now')*1000),
(3, '용', 'dragon / usage', strftime('%s','now')*1000),
(3, '용기', 'courage / container', strftime('%s','now')*1000),
(3, '용돈', 'allowance / pocket money', strftime('%s','now')*1000),
(3, '용품', 'goods / items / supplies', strftime('%s','now')*1000),
(3, '우물', 'well (for water)', strftime('%s','now')*1000),
(3, '우선', 'first / priority', strftime('%s','now')*1000),
(3, '우수', 'excellent / superiority', strftime('%s','now')*1000),
(3, '우연히', 'by chance / accidentally', strftime('%s','now')*1000),
(3, '우울', 'depression / gloom', strftime('%s','now')*1000),
(3, '우정', 'friendship', strftime('%s','now')*1000),
(3, '우주', 'universe / space', strftime('%s','now')*1000),
(3, '우체통', 'mailbox', strftime('%s','now')*1000),
(3, '우측', 'right side', strftime('%s','now')*1000),
(3, '우편', 'mail / post', strftime('%s','now')*1000),
(3, '우편물', 'postal item / mail', strftime('%s','now')*1000),
(3, '우편함', 'mailbox / postbox', strftime('%s','now')*1000),
(3, '우회전', 'right turn', strftime('%s','now')*1000),
(3, '운', 'luck / fortune', strftime('%s','now')*1000),
(3, '운동량', 'amount of exercise', strftime('%s','now')*1000),
(3, '운동선수', 'athlete / sports player', strftime('%s','now')*1000),
(3, '운명', 'destiny / fate', strftime('%s','now')*1000),
(3, '운전면허', 'driver’s license', strftime('%s','now')*1000),
(3, '울리다', 'ring / make someone cry', strftime('%s','now')*1000),
(3, '웃어른', 'elder / senior', strftime('%s','now')*1000),
(3, '원래', 'originally / by nature', strftime('%s','now')*1000),
(3, '원룸', 'one-room apartment / studio', strftime('%s','now')*1000),
(3, '원숭이', 'monkey', strftime('%s','now')*1000),
(3, '원인', 'cause / reason', strftime('%s','now')*1000),
(3, '월', 'month', strftime('%s','now')*1000),
(3, '월드컵', 'World Cup', strftime('%s','now')*1000),
(3, '월세', 'monthly rent', strftime('%s','now')*1000),
(3, '웬일', 'what matter / what’s the occasion', strftime('%s','now')*1000),
(3, '위', 'above / stomach / position', strftime('%s','now')*1000),
(3, '위층', 'upstairs / upper floor', strftime('%s','now')*1000),
(3, '위하다', 'do for / care for', strftime('%s','now')*1000),
(3, '윗글', 'above text / preceding passage', strftime('%s','now')*1000),
(3, '윗사람', 'senior / superior', strftime('%s','now')*1000),
(3, '유람선', 'cruise ship / excursion boat', strftime('%s','now')*1000),
(3, '유럽', 'Europe', strftime('%s','now')*1000),
(3, '유료', 'paid / for a fee', strftime('%s','now')*1000),
(3, '유머', 'humor', strftime('%s','now')*1000),
(3, '유물', 'relic / artifact', strftime('%s','now')*1000),
(3, '유적', 'ruins / remains', strftime('%s','now')*1000),
(3, '유적지', 'historic site', strftime('%s','now')*1000),
(3, '은', 'silver / topic marker', strftime('%s','now')*1000),
(3, '음력', 'lunar calendar', strftime('%s','now')*1000),
(3, '음성', 'voice / sound', strftime('%s','now')*1000),
(3, '음식물', 'food waste / foodstuff', strftime('%s','now')*1000),
(3, '음악회', 'concert / music performance', strftime('%s','now')*1000),
(3, '음주', 'drinking alcohol', strftime('%s','now')*1000),
(3, '응급실', 'emergency room', strftime('%s','now')*1000),
(3, '응원', 'support / cheer', strftime('%s','now')*1000),
(3, '의견', 'opinion / view', strftime('%s','now')*1000),
(3, '의논', 'discussion / talk', strftime('%s','now')*1000),
(3, '이곳저곳', 'here and there', strftime('%s','now')*1000),
(3, '이국적', 'exotic / foreign-like', strftime('%s','now')*1000),
(3, '이끌다', 'lead / guide', strftime('%s','now')*1000),
(3, '이동', 'movement / transfer', strftime('%s','now')*1000),
(3, '이따', 'later', strftime('%s','now')*1000),
(3, '이래서', 'for this reason / that’s why', strftime('%s','now')*1000),
(3, '이러다', 'do this / act like this', strftime('%s','now')*1000),
(3, '이런저런', 'this and that', strftime('%s','now')*1000),
(3, '이력서', 'résumé / CV', strftime('%s','now')*1000),
(3, '이루다', 'achieve / accomplish', strftime('%s','now')*1000),
(3, '이루어지다', 'be achieved / be formed', strftime('%s','now')*1000),
(3, '이름표', 'name tag', strftime('%s','now')*1000),
(3, '이리', 'this way / here', strftime('%s','now')*1000),
(3, '이만', 'this much / to this extent', strftime('%s','now')*1000),
(3, '이메일', 'email', strftime('%s','now')*1000),
(3, '이미지', 'image', strftime('%s','now')*1000),
(3, '이비인후과', 'ear, nose, throat clinic (ENT)', strftime('%s','now')*1000),
(3, '이성', 'reason / opposite sex', strftime('%s','now')*1000),
(3, '이웃집', 'neighboring house', strftime('%s','now')*1000),
(3, '이자', 'interest (money)', strftime('%s','now')*1000),
(3, '이하', 'below / under', strftime('%s','now')*1000),
(3, '익히다', 'learn / master / cook', strftime('%s','now')*1000),
(3, '인구', 'population', strftime('%s','now')*1000),
(3, '인도', 'India / sidewalk', strftime('%s','now')*1000),
(3, '인삼차', 'ginseng tea', strftime('%s','now')*1000),
(3, '인상', 'impression / raise (in price)', strftime('%s','now')*1000),
(3, '인상적', 'impressive', strftime('%s','now')*1000),
(3, '인생', 'life', strftime('%s','now')*1000),
(3, '인쇄', 'printing', strftime('%s','now')*1000),
(3, '인스턴트', 'instant / ready-made', strftime('%s','now')*1000),
(3, '인심', 'kindness / generosity', strftime('%s','now')*1000),
(3, '인원', 'number of people', strftime('%s','now')*1000),
(3, '인터뷰', 'interview', strftime('%s','now')*1000),
(3, '일', 'work / day / event', strftime('%s','now')*1000),
(3, '일곱째', 'seventh (ordinal)', strftime('%s','now')*1000),
(3, '일반', 'general / common', strftime('%s','now')*1000),
(3, '일본어', 'Japanese language', strftime('%s','now')*1000),
(3, '일본인', 'Japanese person', strftime('%s','now')*1000),
(3, '일부러', 'on purpose / intentionally', strftime('%s','now')*1000),
(3, '일상생활', 'everyday life / daily living', strftime('%s','now')*1000),
(3, '일어', 'Japanese language (일본어) / arise', strftime('%s','now')*1000),
(3, '일자리', 'job / position', strftime('%s','now')*1000),
(3, '일정', 'schedule / fixed / certain', strftime('%s','now')*1000),
(3, '일정표', 'timetable / itinerary', strftime('%s','now')*1000),
(3, '일출', 'sunrise', strftime('%s','now')*1000),
(3, '일행', 'party / company', strftime('%s','now')*1000),
(3, '읽기', 'reading', strftime('%s','now')*1000),
(3, '입국', 'entry into a country', strftime('%s','now')*1000),
(3, '입맛', 'appetite / taste', strftime('%s','now')*1000),
(3, '입장료', 'admission fee', strftime('%s','now')*1000),
(3, '입학시험', 'entrance exam', strftime('%s','now')*1000),
(3, '입학식', 'entrance ceremony', strftime('%s','now')*1000),
(3, '잇다', 'connect / continue / link', strftime('%s','now')*1000),
(3, '자', 'person / self / ruler', strftime('%s','now')*1000),
(3, '자가용', 'private car', strftime('%s','now')*1000),
(3, '자격', 'qualification / eligibility', strftime('%s','now')*1000),
(3, '자기', 'oneself / self', strftime('%s','now')*1000),
(3, '자녀', 'children / offspring', strftime('%s','now')*1000),
(3, '자동', 'automatic', strftime('%s','now')*1000),
(3, '자료', 'data / material / reference', strftime('%s','now')*1000),
(3, '자리', 'seat / place / spot', strftime('%s','now')*1000),
(3, '자매', 'sisters', strftime('%s','now')*1000),
(3, '자세하다', 'detailed / specific', strftime('%s','now')*1000),
(3, '자신', 'confidence / oneself', strftime('%s','now')*1000),
(3, '자유롭다', 'free / unrestricted', strftime('%s','now')*1000),
(3, '자주색', 'purple', strftime('%s','now')*1000),
(3, '작성', 'writing / preparation (of doc)', strftime('%s','now')*1000),
(3, '작은아버지', 'uncle (father’s younger brother)', strftime('%s','now')*1000),
(3, '작은어머니', 'aunt (father’s younger brother’s wife)', strftime('%s','now')*1000),
(3, '작은집', 'uncle’s family (father’s younger brother’s)', strftime('%s','now')*1000),
(3, '잔돈', 'small change', strftime('%s','now')*1000),
(3, '잔디밭', 'lawn', strftime('%s','now')*1000),
(3, '잠그다', 'lock / fasten', strftime('%s','now')*1000),
(3, '잠기다', 'be locked / be fastened', strftime('%s','now')*1000),
(3, '잠옷', 'pajamas', strftime('%s','now')*1000),
(3, '잡아먹다', 'prey on / devour', strftime('%s','now')*1000),
(3, '잡히다', 'be caught / be captured', strftime('%s','now')*1000),
(3, '장', 'chapter / chief / place (suffix)', strftime('%s','now')*1000),
(3, '장단점', 'pros and cons', strftime('%s','now')*1000),
(3, '장래', 'future / prospects', strftime('%s','now')*1000),
(3, '장례식', 'funeral', strftime('%s','now')*1000),
(3, '장마철', 'rainy season', strftime('%s','now')*1000),
(3, '장면', 'scene', strftime('%s','now')*1000),
(3, '장미꽃', 'rose flower', strftime('%s','now')*1000),
(3, '장수', 'longevity / general', strftime('%s','now')*1000),
(3, '장식', 'decoration', strftime('%s','now')*1000),
(3, '장점', 'strength / advantage', strftime('%s','now')*1000),
(3, '장학금', 'scholarship', strftime('%s','now')*1000),
(3, '재다', 'measure / be quick', strftime('%s','now')*1000),
(3, '재킷', 'jacket', strftime('%s','now')*1000),
(3, '재학', 'be enrolled at school', strftime('%s','now')*1000),
(3, '재활용', 'recycling', strftime('%s','now')*1000),
(3, '잼', 'jam', strftime('%s','now')*1000),
(3, '쟤', 'that kid (over there)', strftime('%s','now')*1000),
(3, '저기', 'there / over there', strftime('%s','now')*1000),
(3, '저녁때', 'around dinner time', strftime('%s','now')*1000),
(3, '저러다', 'do like that', strftime('%s','now')*1000),
(3, '저렴하다', 'be inexpensive', strftime('%s','now')*1000),
(3, '저울', 'scale / balance', strftime('%s','now')*1000),
(3, '저자', 'author', strftime('%s','now')*1000),
(3, '저축', 'savings / deposit', strftime('%s','now')*1000),
(3, '적', 'enemy / record / past / suitable', strftime('%s','now')*1000),
(3, '적어도', 'at least', strftime('%s','now')*1000),
(3, '적응', 'adaptation / adjustment', strftime('%s','now')*1000),
(3, '적히다', 'be written / be recorded', strftime('%s','now')*1000),
(3, '전국', 'nationwide / the whole country', strftime('%s','now')*1000),
(3, '전국적', 'national / nationwide', strftime('%s','now')*1000),
(3, '전날', 'the previous day / the day before', strftime('%s','now')*1000),
(3, '전달', 'delivery / conveyance', strftime('%s','now')*1000),
(3, '전망', 'view / prospect / outlook', strftime('%s','now')*1000),
(3, '전문', 'specialty / expert field', strftime('%s','now')*1000),
(3, '전문가', 'expert / specialist', strftime('%s','now')*1000),
(3, '전문점', 'specialty store', strftime('%s','now')*1000),
(3, '전설', 'legend / myth', strftime('%s','now')*1000),
(3, '전세', 'lease / deposit rental', strftime('%s','now')*1000),
(3, '전시', 'exhibition / display', strftime('%s','now')*1000),
(3, '전시회', 'exhibition / exposition', strftime('%s','now')*1000),
(3, '전용', 'exclusive use / private use', strftime('%s','now')*1000),
(3, '전원', 'all members / power supply', strftime('%s','now')*1000),
(3, '전자', 'electronics / electronic', strftime('%s','now')*1000),
(3, '전자레인지', 'microwave oven', strftime('%s','now')*1000),
(3, '전자사전', 'electronic dictionary', strftime('%s','now')*1000),
(3, '전쟁', 'war', strftime('%s','now')*1000),
(3, '전통', 'tradition / custom', strftime('%s','now')*1000),
(3, '전통적', 'traditional', strftime('%s','now')*1000),
(3, '절', 'temple / bow / section', strftime('%s','now')*1000),
(3, '절대', 'absolutely / never', strftime('%s','now')*1000),
(3, '절대로', 'never / absolutely not', strftime('%s','now')*1000),
(3, '절약', 'saving / frugality', strftime('%s','now')*1000),
(3, '젊은이', 'young person / youth', strftime('%s','now')*1000),
(3, '점', 'dot / point / store', strftime('%s','now')*1000),
(3, '점원', 'store clerk / sales clerk', strftime('%s','now')*1000),
(3, '점차', 'gradually / step by step', strftime('%s','now')*1000),
(3, '점퍼', 'jumper / jacket', strftime('%s','now')*1000),
(3, '접수', 'receipt / registration / acceptance', strftime('%s','now')*1000),
(3, '젓다', 'stir / row', strftime('%s','now')*1000),
(3, '정', 'affection / sentiment / feeling', strftime('%s','now')*1000),
(3, '정답', 'correct answer', strftime('%s','now')*1000),
(3, '정말로', 'really / truly', strftime('%s','now')*1000),
(3, '정보', 'information', strftime('%s','now')*1000),
(3, '정수기', 'water purifier', strftime('%s','now')*1000),
(3, '정신', 'mind / spirit / sanity', strftime('%s','now')*1000),
(3, '정신없다', 'be hectic / be out of one’s mind', strftime('%s','now')*1000),
(3, '정신없이', 'frantically / in a rush', strftime('%s','now')*1000),
(3, '정오', 'noon', strftime('%s','now')*1000),
(3, '정원', 'garden / number of people / courtyard', strftime('%s','now')*1000),
(3, '정육점', 'butcher shop', strftime('%s','now')*1000),
(3, '정장', 'formal suit / formal wear', strftime('%s','now')*1000),
(3, '정치', 'politics', strftime('%s','now')*1000),
(3, '정형외과', 'orthopedics department', strftime('%s','now')*1000),
(3, '정확히', 'exactly / precisely', strftime('%s','now')*1000),
(3, '제공', 'offer / provide / supply', strftime('%s','now')*1000),
(3, '제과점', 'bakery / pastry shop', strftime('%s','now')*1000),
(3, '제대로', 'properly / correctly', strftime('%s','now')*1000),
(3, '제시간', 'on time', strftime('%s','now')*1000),
(3, '제안', 'suggestion / proposal', strftime('%s','now')*1000),
(3, '제출', 'submission / turn in', strftime('%s','now')*1000),
(3, '제품', 'product / manufactured goods', strftime('%s','now')*1000),
(3, '조건', 'condition / requirement', strftime('%s','now')*1000),
(3, '조깅', 'jogging', strftime('%s','now')*1000),
(3, '조끼', 'vest', strftime('%s','now')*1000),
(3, '조리', 'cooking / preparation', strftime('%s','now')*1000),
(3, '조미료', 'seasoning / condiment', strftime('%s','now')*1000),
(3, '조사', 'investigation / survey / grammar particle', strftime('%s','now')*1000),
(3, '조상', 'ancestor', strftime('%s','now')*1000),
(3, '조언', 'advice / counsel', strftime('%s','now')*1000),
(3, '존경', 'respect / admiration', strftime('%s','now')*1000),
(3, '졸리다', 'be sleepy', strftime('%s','now')*1000),
(3, '졸업생', 'graduate / alumnus', strftime('%s','now')*1000),
(3, '졸업식', 'graduation ceremony', strftime('%s','now')*1000),
(3, '종교', 'religion / faith', strftime('%s','now')*1000),
(3, '종이컵', 'paper cup', strftime('%s','now')*1000),
(3, '종일', 'all day long', strftime('%s','now')*1000),
(3, '종합', 'comprehensive / general', strftime('%s','now')*1000),
(3, '좌석', 'seat', strftime('%s','now')*1000),
(3, '좌측', 'left side', strftime('%s','now')*1000),
(3, '좌회전', 'left turn', strftime('%s','now')*1000),
(3, '주간', 'week / daytime', strftime('%s','now')*1000),
(3, '주고받다', 'give and take / exchange', strftime('%s','now')*1000),
(3, '주민', 'resident / inhabitant', strftime('%s','now')*1000),
(3, '주방', 'kitchen', strftime('%s','now')*1000),
(3, '주요', 'main / major', strftime('%s','now')*1000),
(3, '주유소', 'gas station', strftime('%s','now')*1000),
(3, '주의', 'caution / attention / warning', strftime('%s','now')*1000),
(3, '주인공', 'main character / hero', strftime('%s','now')*1000),
(3, '주제', 'subject / theme / topic', strftime('%s','now')*1000),
(3, '주차권', 'parking ticket', strftime('%s','now')*1000),
(3, '주차료', 'parking fee', strftime('%s','now')*1000),
(3, '죽', 'porridge', strftime('%s','now')*1000),
(3, '죽음', 'death', strftime('%s','now')*1000),
(3, '죽이다', 'kill', strftime('%s','now')*1000),
(3, '준비물', 'preparation items / supplies', strftime('%s','now')*1000),
(3, '줄넘기', 'jump rope', strftime('%s','now')*1000),
(3, '줄무늬', 'stripe pattern', strftime('%s','now')*1000),
(3, '중', 'middle / among / during', strftime('%s','now')*1000),
(3, '중고', 'used / secondhand', strftime('%s','now')*1000),
(3, '중고차', 'used car', strftime('%s','now')*1000),
(3, '중국어', 'Chinese language', strftime('%s','now')*1000),
(3, '중국인', 'Chinese person', strftime('%s','now')*1000),
(3, '중급', 'intermediate level', strftime('%s','now')*1000),
(3, '중단', 'halt / suspension', strftime('%s','now')*1000),
(3, '중부', 'central region', strftime('%s','now')*1000),
(3, '중순', 'middle of the month', strftime('%s','now')*1000),
(3, '중식', 'lunch / Chinese cuisine', strftime('%s','now')*1000),
(3, '중심지', 'center / core area', strftime('%s','now')*1000),
(3, '중형차', 'mid-sized car', strftime('%s','now')*1000),
(3, '쥐', 'mouse / rat', strftime('%s','now')*1000),
(3, '즉', 'that is / namely / in other words', strftime('%s','now')*1000),
(3, '즉시', 'immediately / right away', strftime('%s','now')*1000),
(3, '즐거움', 'joy / pleasure', strftime('%s','now')*1000),
(3, '증가', 'increase / growth', strftime('%s','now')*1000),
(3, '증명서', 'certificate / document of proof', strftime('%s','now')*1000),
(3, '증상', 'symptom', strftime('%s','now')*1000),
(3, '증세', 'condition / state (symptom)', strftime('%s','now')*1000),
(3, '지각', 'lateness / perception', strftime('%s','now')*1000),
(3, '지나치다', 'go too far / overdo', strftime('%s','now')*1000),
(3, '지난날', 'past days / old times', strftime('%s','now')*1000),
(3, '지다', 'lose / set (sun)', strftime('%s','now')*1000),
(3, '지도', 'map / guidance', strftime('%s','now')*1000),
(3, '지방', 'region / fat', strftime('%s','now')*1000),
(3, '지붕', 'roof', strftime('%s','now')*1000),
(3, '지역', 'area / region', strftime('%s','now')*1000),
(3, '지원', 'support / application', strftime('%s','now')*1000),
(3, '지저분하다', 'messy / dirty', strftime('%s','now')*1000),
(3, '지퍼', 'zipper', strftime('%s','now')*1000),
(3, '직장인', 'office worker / employee', strftime('%s','now')*1000),
(3, '직진', 'go straight', strftime('%s','now')*1000),
(3, '진단서', 'medical certificate', strftime('%s','now')*1000),
(3, '진심', 'sincerity / true heart', strftime('%s','now')*1000),
(3, '진찰', 'medical examination', strftime('%s','now')*1000),
(3, '진통제', 'painkiller', strftime('%s','now')*1000),
(3, '진학', 'entering higher education', strftime('%s','now')*1000),
(3, '진행', 'progress / proceed', strftime('%s','now')*1000),
(3, '진행자', 'host / MC / presenter', strftime('%s','now')*1000),
(3, '질', 'quality / texture / matter', strftime('%s','now')*1000),
(3, '집다', 'pick up / point out', strftime('%s','now')*1000),
(3, '집세', 'house rent', strftime('%s','now')*1000),
(3, '집안', 'family / household', strftime('%s','now')*1000),
(3, '집중', 'concentration / focus', strftime('%s','now')*1000),
(3, '짜다', 'make / plan / squeeze / salty', strftime('%s','now')*1000),
(3, '짜리', 'worth / valued at (counter suffix)', strftime('%s','now')*1000),
(3, '쪽', 'side / direction / piece', strftime('%s','now')*1000),
(3, '쭉', 'continuously / straight', strftime('%s','now')*1000),
(3, '찌르다', 'stab / pierce / poke', strftime('%s','now')*1000),
(3, '찜질', 'hot/cold pack / steaming therapy', strftime('%s','now')*1000),
(3, '찢다', 'tear / rip', strftime('%s','now')*1000),
(3, '찢어지다', 'be torn / ripped', strftime('%s','now')*1000),
(3, '차량', 'vehicle', strftime('%s','now')*1000),
(3, '차로', 'lane / by car', strftime('%s','now')*1000),
(3, '차리다', 'prepare / set (table) / compose oneself', strftime('%s','now')*1000),
(3, '차림표', 'menu', strftime('%s','now')*1000),
(3, '차이', 'difference / gap', strftime('%s','now')*1000),
(3, '차이점', 'difference point / distinction', strftime('%s','now')*1000),
(3, '찬성', 'agreement / approval', strftime('%s','now')*1000),
(3, '참가', 'participation', strftime('%s','now')*1000),
(3, '참고', 'reference / refer to', strftime('%s','now')*1000),
(3, '참기름', 'sesame oil', strftime('%s','now')*1000),
(3, '참석', 'attendance / participation', strftime('%s','now')*1000),
(3, '창', 'window', strftime('%s','now')*1000),
(3, '창가', 'by the window', strftime('%s','now')*1000),
(3, '창고', 'warehouse / storage', strftime('%s','now')*1000),
(3, '창구', 'counter / window (office)', strftime('%s','now')*1000),
(3, '창밖', 'outside the window', strftime('%s','now')*1000),
(3, '창피', 'embarrassment / shame', strftime('%s','now')*1000),
(3, '채우다', 'fill / fulfill / fasten', strftime('%s','now')*1000),
(3, '책가방', 'school bag', strftime('%s','now')*1000),
(3, '챙기다', 'pack / take care of / prepare', strftime('%s','now')*1000),
(3, '처녀', 'unmarried woman / virgin', strftime('%s','now')*1000),
(3, '처방', 'prescription', strftime('%s','now')*1000),
(3, '처방전', 'medical prescription slip', strftime('%s','now')*1000),
(3, '천둥', 'thunder', strftime('%s','now')*1000),
(3, '천사', 'angel', strftime('%s','now')*1000),
(3, '천장', 'ceiling', strftime('%s','now')*1000),
(3, '천재', 'genius', strftime('%s','now')*1000),
(3, '철', 'season / iron', strftime('%s','now')*1000),
(3, '철도', 'railroad / railway', strftime('%s','now')*1000),
(3, '첫눈', 'first snow / first sight', strftime('%s','now')*1000),
(3, '첫인상', 'first impression', strftime('%s','now')*1000),
(3, '청소기', 'vacuum cleaner', strftime('%s','now')*1000),
(3, '청혼', 'marriage proposal', strftime('%s','now')*1000),
(3, '체력', 'physical strength', strftime('%s','now')*1000),
(3, '체크무늬', 'check pattern / plaid', strftime('%s','now')*1000),
(3, '체하다', 'pretend / have indigestion', strftime('%s','now')*1000),
(3, '체험', 'experience (hands-on)', strftime('%s','now')*1000),
(3, '초급', 'beginner level', strftime('%s','now')*1000),
(3, '초록', 'green color', strftime('%s','now')*1000),
(3, '촌스럽다', 'old-fashioned / countrified', strftime('%s','now')*1000),
(3, '총', 'gun / total', strftime('%s','now')*1000),
(3, '촬영', 'filming / shooting', strftime('%s','now')*1000),
(3, '최고급', 'highest class / luxury', strftime('%s','now')*1000),
(3, '최선', 'the best / one’s best effort', strftime('%s','now')*1000),
(3, '최저', 'lowest / minimum', strftime('%s','now')*1000),
(3, '추억', 'memory / recollection', strftime('%s','now')*1000),
(3, '추천', 'recommendation', strftime('%s','now')*1000),
(3, '추측', 'guess / speculation', strftime('%s','now')*1000),
(3, '축구장', 'soccer field', strftime('%s','now')*1000),
(3, '축제', 'festival', strftime('%s','now')*1000),
(3, '출국', 'departure from a country', strftime('%s','now')*1000),
(3, '충분히', 'enough / sufficiently', strftime('%s','now')*1000),
(3, '취하다', 'get drunk / adopt / take', strftime('%s','now')*1000),
(3, '취향', 'preference / taste', strftime('%s','now')*1000),
(3, '치다', 'hit / play / strike', strftime('%s','now')*1000),
(3, '치료법', 'treatment method / therapy', strftime('%s','now')*1000),
(3, '치르다', 'pay / hold / undergo', strftime('%s','now')*1000),
(3, '치수', 'size / measurement', strftime('%s','now')*1000),
(3, '치우다', 'clean up / remove', strftime('%s','now')*1000),
(3, '치즈', 'cheese', strftime('%s','now')*1000),
(3, '친-', 'prefix meaning close / intimate', strftime('%s','now')*1000),
(3, '친딸', 'one’s own daughter', strftime('%s','now')*1000),
(3, '칸', 'space / compartment', strftime('%s','now')*1000),
(3, '커지다', 'grow / become larger', strftime('%s','now')*1000),
(3, '커튼', 'curtain', strftime('%s','now')*1000),
(3, '코너', 'corner / section', strftime('%s','now')*1000),
(3, '코미디', 'comedy', strftime('%s','now')*1000),
(3, '코스', 'course / route', strftime('%s','now')*1000),
(3, '코트', 'coat / court (tennis etc.)', strftime('%s','now')*1000),
(3, '코피', 'nosebleed', strftime('%s','now')*1000),
(3, '콘도', 'condominium / resort condo', strftime('%s','now')*1000),
(3, '콜록콜록', 'coughing sound', strftime('%s','now')*1000),
(3, '콧노래', 'humming / hum tune', strftime('%s','now')*1000),
(3, '큰길', 'main road', strftime('%s','now')*1000),
(3, '큰아버지', 'uncle (father’s older brother)', strftime('%s','now')*1000),
(3, '큰어머니', 'aunt (older uncle’s wife)', strftime('%s','now')*1000),
(3, '클래식', 'classical music / classic', strftime('%s','now')*1000),
(3, '키스', 'kiss', strftime('%s','now')*1000),
(3, '탁자', 'table', strftime('%s','now')*1000),
(3, '탑승', 'boarding', strftime('%s','now')*1000),
(3, '탑승객', 'passenger / boarding person', strftime('%s','now')*1000),
(3, '태우다', 'burn / give a ride', strftime('%s','now')*1000),
(3, '터뜨리다', 'burst / pop', strftime('%s','now')*1000),
(3, '털', 'hair / fur', strftime('%s','now')*1000),
(3, '털다', 'shake off / empty / clean out', strftime('%s','now')*1000),
(3, '테이프', 'tape / cassette', strftime('%s','now')*1000),
(3, '토', 'soil / Saturday / vomit', strftime('%s','now')*1000),
(3, '토론', 'discussion / debate', strftime('%s','now')*1000),
(3, '토하다', 'vomit', strftime('%s','now')*1000),
(3, '통', 'container / communication / pass', strftime('%s','now')*1000),
(3, '통신', 'communication / correspondence', strftime('%s','now')*1000),
(3, '통역', 'interpretation / translator', strftime('%s','now')*1000),
(3, '통일', 'unification', strftime('%s','now')*1000),
(3, '통통하다', 'chubby / plump', strftime('%s','now')*1000),
(3, '통하다', 'go through / communicate / flow', strftime('%s','now')*1000),
(3, '특기', 'special skill / specialty', strftime('%s','now')*1000),
(3, '특성', 'characteristic / property', strftime('%s','now')*1000),
(3, '특징', 'feature / trait', strftime('%s','now')*1000),
(3, '틀림없이', 'certainly / surely', strftime('%s','now')*1000),
(3, '틈틈이', 'in one’s spare time / from time to time', strftime('%s','now')*1000),
(3, '파', 'green onion / group / faction', strftime('%s','now')*1000),
(3, '파다', 'dig', strftime('%s','now')*1000),
(3, '파도', 'wave', strftime('%s','now')*1000),
(3, '파랑', 'blue color / wave', strftime('%s','now')*1000),
(3, '파마', 'perm (hairstyle)', strftime('%s','now')*1000),
(3, '파일', 'file', strftime('%s','now')*1000),
(3, '파출소', 'police substation', strftime('%s','now')*1000),
(3, '판매', 'sale / selling', strftime('%s','now')*1000),
(3, '패션', 'fashion', strftime('%s','now')*1000),
(3, '팬티', 'underpants', strftime('%s','now')*1000),
(3, '퍼센트', 'percent', strftime('%s','now')*1000),
(3, '페이지', 'page', strftime('%s','now')*1000),
(3, '편', 'side / direction / episode', strftime('%s','now')*1000),
(3, '편식', 'picky eating / unbalanced diet', strftime('%s','now')*1000),
(3, '평가', 'evaluation / assessment', strftime('%s','now')*1000),
(3, '포기', 'giving up / abandonment', strftime('%s','now')*1000),
(3, '포도주', 'wine', strftime('%s','now')*1000),
(3, '포크', 'fork', strftime('%s','now')*1000),
(3, '포함', 'inclusion / contain', strftime('%s','now')*1000),
(3, '폭포', 'waterfall', strftime('%s','now')*1000),
(3, '표', 'ticket / sign / table / chart', strftime('%s','now')*1000),
(3, '표시', 'mark / indication', strftime('%s','now')*1000),
(3, '표정', 'facial expression', strftime('%s','now')*1000),
(3, '표지판', 'signboard / notice', strftime('%s','now')*1000),
(3, '표현', 'expression / representation', strftime('%s','now')*1000),
(3, '풀', 'grass / glue', strftime('%s','now')*1000),
(3, '풀리다', 'be untied / be relieved', strftime('%s','now')*1000),
(3, '품질', 'quality of product', strftime('%s','now')*1000),
(3, '풍선', 'balloon', strftime('%s','now')*1000),
(3, '풍습', 'custom / practice', strftime('%s','now')*1000),
(3, '프린터', 'printer', strftime('%s','now')*1000),
(3, '플라스틱', 'plastic', strftime('%s','now')*1000),
(3, '피로', 'fatigue / tiredness', strftime('%s','now')*1000),
(3, '피부', 'skin', strftime('%s','now')*1000),
(3, '피서', 'summer vacation / escape from heat', strftime('%s','now')*1000),
(3, '피하다', 'avoid / escape', strftime('%s','now')*1000),
(3, '피해', 'damage / harm', strftime('%s','now')*1000),
(3, '피해자', 'victim', strftime('%s','now')*1000),
(3, '하나하나', 'one by one / each', strftime('%s','now')*1000),
(3, '하숙', 'boarding / lodging', strftime('%s','now')*1000),
(3, '하양', 'white color', strftime('%s','now')*1000),
(3, '하차', 'get off / disembark', strftime('%s','now')*1000),
(3, '하품', 'yawn', strftime('%s','now')*1000),
(3, '하하', 'haha / laughter', strftime('%s','now')*1000),
(3, '학과', 'department (university)', strftime('%s','now')*1000),
(3, '학습', 'learning / study', strftime('%s','now')*1000),
(3, '학자', 'scholar / academic', strftime('%s','now')*1000),
(3, '한국말', 'Korean language (spoken)', strftime('%s','now')*1000),
(3, '한국어', 'Korean language', strftime('%s','now')*1000),
(3, '한국인', 'Korean person', strftime('%s','now')*1000),
(3, '한동안', 'for a while / for some time', strftime('%s','now')*1000),
(3, '한때', 'once / at one time', strftime('%s','now')*1000),
(3, '한문', 'classical Chinese', strftime('%s','now')*1000),
(3, '한숨', 'sigh / rest', strftime('%s','now')*1000),
(3, '한자', 'Chinese character', strftime('%s','now')*1000),
(3, '한쪽', 'one side / one direction', strftime('%s','now')*1000),
(3, '한참', 'for quite a while / long time', strftime('%s','now')*1000),
(3, '할인점', 'discount store', strftime('%s','now')*1000),
(3, '합격', 'pass / success (exam)', strftime('%s','now')*1000),
(3, '합계', 'total / sum', strftime('%s','now')*1000),
(3, '합치다', 'combine / unite / match', strftime('%s','now')*1000),
(3, '항공료', 'airfare', strftime('%s','now')*1000),
(3, '해결', 'solution / resolution', strftime('%s','now')*1000),
(3, '해돋이', 'sunrise', strftime('%s','now')*1000),
(3, '해물', 'seafood', strftime('%s','now')*1000),
(3, '해변', 'beach / seaside', strftime('%s','now')*1000),
(3, '해산물', 'seafood / marine product', strftime('%s','now')*1000),
(3, '해수욕장', 'beach for swimming / seaside resort', strftime('%s','now')*1000),
(3, '핸드백', 'handbag / purse', strftime('%s','now')*1000),
(3, '햇볕', 'sunlight / sunshine', strftime('%s','now')*1000),
(3, '행사장', 'event hall / venue', strftime('%s','now')*1000),
(3, '행운', 'luck / good fortune', strftime('%s','now')*1000),
(3, '향수', 'perfume / nostalgia', strftime('%s','now')*1000),
(3, '향하다', 'head toward / face / aim', strftime('%s','now')*1000),
(3, '허락', 'permission / approval', strftime('%s','now')*1000),
(3, '허리띠', 'belt', strftime('%s','now')*1000),
(3, '허벅지', 'thigh', strftime('%s','now')*1000),
(3, '현관', 'entrance / doorway', strftime('%s','now')*1000),
(3, '현대', 'modern times / Hyundai (brand)', strftime('%s','now')*1000),
(3, '형태', 'form / shape / structure', strftime('%s','now')*1000),
(3, '호두', 'walnut', strftime('%s','now')*1000),
(3, '호박', 'pumpkin / amber', strftime('%s','now')*1000),
(3, '호실', 'room number', strftime('%s','now')*1000),
(3, '혹은', 'or / alternatively', strftime('%s','now')*1000),
(3, '혼나다', 'get scolded / have a hard time', strftime('%s','now')*1000),
(3, '홈페이지', 'homepage / website', strftime('%s','now')*1000),
(3, '화', 'anger / fire / Tuesday', strftime('%s','now')*1000),
(3, '화면', 'screen / display', strftime('%s','now')*1000),
(3, '화분', 'flower pot / potted plant', strftime('%s','now')*1000),
(3, '화장', 'makeup / cremation', strftime('%s','now')*1000),
(3, '화장대', 'dressing table / vanity', strftime('%s','now')*1000),
(3, '화재', 'fire (accident)', strftime('%s','now')*1000),
(3, '화폐', 'currency / money', strftime('%s','now')*1000),
(3, '화해', 'reconciliation / making up', strftime('%s','now')*1000),
(3, '확인', 'confirmation / check / verify', strftime('%s','now')*1000),
(3, '환불', 'refund', strftime('%s','now')*1000),
(3, '환상적', 'fantastic / dreamy', strftime('%s','now')*1000),
(3, '환승역', 'transfer station', strftime('%s','now')*1000),
(3, '환영회', 'welcome party', strftime('%s','now')*1000),
(3, '환율', 'exchange rate', strftime('%s','now')*1000),
(3, '환하다', 'bright / radiant / clear', strftime('%s','now')*1000),
(3, '활동', 'activity', strftime('%s','now')*1000),
(3, '활발하다', 'active / lively / vigorous', strftime('%s','now')*1000),
(3, '활짝', 'widely / brightly / fully (open)', strftime('%s','now')*1000),
(3, '회', 'meeting / society / sashimi', strftime('%s','now')*1000),
(3, '회비', 'membership fee / dues', strftime('%s','now')*1000),
(3, '회식', 'company dinner / staff meal', strftime('%s','now')*1000),
(3, '회의실', 'conference room / meeting room', strftime('%s','now')*1000),
(3, '회장', 'chairman / president / head', strftime('%s','now')*1000),
(3, '횟수', 'number of times / frequency', strftime('%s','now')*1000),
(3, '효과', 'effect / efficacy / result', strftime('%s','now')*1000),
(3, '후반', 'second half / latter part', strftime('%s','now')*1000),
(3, '후식', 'dessert', strftime('%s','now')*1000),
(3, '후추', 'black pepper', strftime('%s','now')*1000),
(3, '후회', 'regret / remorse', strftime('%s','now')*1000),
(3, '휴가철', 'vacation season / holiday period', strftime('%s','now')*1000),
(3, '휴대', 'carrying / portability', strftime('%s','now')*1000),
(3, '휴식', 'rest / break', strftime('%s','now')*1000),
(3, '휴학', 'leave of absence from school', strftime('%s','now')*1000),
(3, '흘러가다', 'flow / pass by', strftime('%s','now')*1000),
(3, '희다', 'be white / pure', strftime('%s','now')*1000),
(3, '희생', 'sacrifice', strftime('%s','now')*1000);