PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(7, '동그랗다', 'round', strftime('%s','now')*1000),
(7, '동료', 'colleague / coworker', strftime('%s','now')*1000),
(7, '동부', 'eastern part', strftime('%s','now')*1000),
(7, '동아리', 'club / circle', strftime('%s','now')*1000),
(7, '동양', 'the East / Asia', strftime('%s','now')*1000),
(7, '동작', 'movement / motion', strftime('%s','now')*1000),
(7, '동창', 'schoolmate', strftime('%s','now')*1000),
(7, '동창회', 'alumni meeting', strftime('%s','now')*1000),
(7, '동호회', 'club / association', strftime('%s','now')*1000),
(7, '되돌아오다', 'come back / return', strftime('%s','now')*1000),
(7, '되찾다', 'recover / regain', strftime('%s','now')*1000),
(7, '두께', 'thickness', strftime('%s','now')*1000),
(7, '두통약', 'headache medicine', strftime('%s','now')*1000),
(7, '둥글다', 'round / circular', strftime('%s','now')*1000),
(7, '드라이', 'dry cleaning', strftime('%s','now')*1000),
(7, '드라이브', 'drive', strftime('%s','now')*1000),
(7, '드라이어', 'dryer', strftime('%s','now')*1000),
(7, '드레스', 'dress', strftime('%s','now')*1000),
(7, '듣기', 'listening', strftime('%s','now')*1000),
(7, '들려주다', 'play for / tell to someone', strftime('%s','now')*1000),
(7, '들어서다', 'enter / step into', strftime('%s','now')*1000),
(7, '들어주다', 'listen to / accept', strftime('%s','now')*1000),
(7, '등', 'back / etc.', strftime('%s','now')*1000),
(7, '등록', 'registration', strftime('%s','now')*1000),
(7, '등록금', 'tuition fee', strftime('%s','now')*1000),
(7, '등록증', 'registration card', strftime('%s','now')*1000),
(7, '등산복', 'hiking clothes', strftime('%s','now')*1000),
(7, '디지털', 'digital', strftime('%s','now')*1000),
(7, '따다', 'pick / open / win', strftime('%s','now')*1000),
(7, '따라가다', 'follow / go along', strftime('%s','now')*1000),
(7, '따라서', 'therefore / accordingly', strftime('%s','now')*1000),
(7, '따라오다', 'come along / follow', strftime('%s','now')*1000),
(7, '따로따로', 'separately / individually', strftime('%s','now')*1000),
(7, '따르다', 'follow / pour', strftime('%s','now')*1000),
(7, '따르릉', 'ring-ring (sound)', strftime('%s','now')*1000),
(7, '딱', 'exactly / tightly', strftime('%s','now')*1000),
(7, '딱딱하다', 'hard / stiff', strftime('%s','now')*1000),
(7, '땅속', 'underground / under the earth', strftime('%s','now')*1000),
(7, '때때로', 'sometimes / occasionally', strftime('%s','now')*1000),
(7, '떠나가다', 'leave / depart', strftime('%s','now')*1000),
(7, '떠오르다', 'rise / come to mind', strftime('%s','now')*1000),
(7, '떠올리다', 'recall / remember', strftime('%s','now')*1000),
(7, '떨다', 'tremble / shake', strftime('%s','now')*1000),
(7, '떨리다', 'tremble / quiver', strftime('%s','now')*1000),
(7, '떨어뜨리다', 'drop / let fall', strftime('%s','now')*1000),
(7, '또한', 'also / moreover', strftime('%s','now')*1000),
(7, '똑똑히', 'clearly / distinctly', strftime('%s','now')*1000),
(7, '뚫다', 'протыкать / проникать', strftime('%s','now')*1000),
(7, '뛰다', 'бежать / прыгать', strftime('%s','now')*1000),
(7, '뛰어나다', 'превосходить / выдающийся', strftime('%s','now')*1000),
(7, '뛰어내리다', 'прыгать вниз', strftime('%s','now')*1000),
(7, '뛰어넘다', 'перепрыгивать / превосходить', strftime('%s','now')*1000),
(7, '뜨다', 'плавать / подниматься / открывать глаза', strftime('%s','now')*1000),
(7, '띠', 'ремень / лента / группа', strftime('%s','now')*1000),
(7, '레몬', 'лимон', strftime('%s','now')*1000),
(7, '렌터카', 'арендованный автомобиль', strftime('%s','now')*1000),
(7, '로그인', 'вход в систему', strftime('%s','now')*1000),
(7, '로봇', 'робот', strftime('%s','now')*1000),
(7, '-률', 'ставка / соотношение (суффикс)', strftime('%s','now')*1000),
(7, '리듬', 'ритм', strftime('%s','now')*1000),
(7, '리본', 'лента', strftime('%s','now')*1000),
(7, '마늘', 'чеснок', strftime('%s','now')*1000),
(7, '마라톤', 'марафон', strftime('%s','now')*1000),
(7, '마사지', 'массаж', strftime('%s','now')*1000),
(7, '마우스', 'мышь', strftime('%s','now')*1000),
(7, '마음대로', 'как угодно', strftime('%s','now')*1000),
(7, '마음씨', 'характер / натура', strftime('%s','now')*1000),
(7, '마이크', 'микрофон', strftime('%s','now')*1000),
(7, '마침', 'только что / точно / наконец', strftime('%s','now')*1000),
(7, '막', 'только / случайно / фильм', strftime('%s','now')*1000),
(7, '막내', 'младший ребенок', strftime('%s','now')*1000),
(7, '막다', 'блокировать / останавливать', strftime('%s','now')*1000),
(7, '막대기', 'палка / стержень', strftime('%s','now')*1000),
(7, '막차', 'последний поезд / последний автобус', strftime('%s','now')*1000),
(7, '만', 'только / всего лишь / десять тысяч', strftime('%s','now')*1000),
(7, '만남', 'встреча', strftime('%s','now')*1000),
(7, '만족', 'удовлетворение', strftime('%s','now')*1000),
(7, '만족스럽다', 'удовлетворяющий', strftime('%s','now')*1000),
(7, '많아지다', 'увеличиваться / расти в числе', strftime('%s','now')*1000),
(7, '말다', 'перестать делать / свернуть', strftime('%s','now')*1000),
(7, '말리다', 'сушить / отговаривать', strftime('%s','now')*1000),
(7, '말하기', 'говорение', strftime('%s','now')*1000),
(7, '맞다', 'подходить / быть правильным / быть ударенным', strftime('%s','now')*1000),
(7, '맞은편', 'противоположная сторона', strftime('%s','now')*1000),
(7, '맞이하다', 'приветствовать', strftime('%s','now')*1000),
(7, '맡기다', 'доверить / оставить с', strftime('%s','now')*1000),
(7, '맡다', 'взять на себя / отвечать за', strftime('%s','now')*1000),
(7, '매', 'каждый / ястреб / счетчик для раз', strftime('%s','now')*1000),
(7, '매달다', 'вешать / приостанавливать', strftime('%s','now')*1000),
(7, '매운맛', 'острый вкус', strftime('%s','now')*1000),
(7, '매운탕', 'острая рыбная похлебка', strftime('%s','now')*1000),
(7, '매장', 'магазин / погребение', strftime('%s','now')*1000),
(7, '매점', 'закусочная / школьный магазин', strftime('%s','now')*1000),
(7, '매진', 'распродажа / быть распроданным', strftime('%s','now')*1000),
(7, '맨발', 'босиком', strftime('%s','now')*1000),
(7, '먼지', 'пыль', strftime('%s','now')*1000),
(7, '멀미', 'укачивание', strftime('%s','now')*1000),
(7, '멋지다', 'крутой / стильный', strftime('%s','now')*1000),
(7, '멍', 'синяк', strftime('%s','now')*1000),
(7, '메뉴판', 'меню', strftime('%s','now')*1000),
(7, '메모지', 'блокнот', strftime('%s','now')*1000),
(7, '멜로디', 'мелодия', strftime('%s','now')*1000),
(7, '면', 'лапша / хлопок / лицо', strftime('%s','now')*1000),
(7, '면적', 'площадь / поверхность', strftime('%s','now')*1000),
(7, '면접', 'интервью', strftime('%s','now')*1000),
(7, '면허증', 'удостоверение', strftime('%s','now')*1000),
(7, '멸치', 'анчоус', strftime('%s','now')*1000),
(7, '명단', 'список имен', strftime('%s','now')*1000),
(7, '명함', 'визитка', strftime('%s','now')*1000),
(7, '몇몇', 'несколько', strftime('%s','now')*1000),
(7, '모니터', 'монитор', strftime('%s','now')*1000),
(7, '모델', 'модель', strftime('%s','now')*1000),
(7, '모래', 'песок', strftime('%s','now')*1000),
(7, '모범', 'примерный / модель', strftime('%s','now')*1000),
(7, '모자', 'шляпа / кепка', strftime('%s','now')*1000),
(7, '모집', 'набор', strftime('%s','now')*1000),
(7, '목', 'шея / горло', strftime('%s','now')*1000),
(7, '목록', 'список / каталог', strftime('%s','now')*1000),
(7, '목적지', 'пункт назначения', strftime('%s','now')*1000),
(7, '목표', 'цель', strftime('%s','now')*1000),
(7, '몰래', 'тайно / тихо', strftime('%s','now')*1000),
(7, '몸무게', 'вес тела', strftime('%s','now')*1000),
(7, '몸살', 'усталость / ломота', strftime('%s','now')*1000),
(7, '몸짓', 'жест', strftime('%s','now')*1000),
(7, '묘사', 'описание / изображение', strftime('%s','now')*1000),
(7, '무늬', 'узор / дизайн', strftime('%s','now')*1000),
(7, '무대', 'сцена', strftime('%s','now')*1000),
(7, '무더위', 'жара', strftime('%s','now')*1000),
(7, '무덤', 'могила', strftime('%s','now')*1000),
(7, '무서워하다', 'бояться', strftime('%s','now')*1000),
(7, '무역', 'торговля', strftime('%s','now')*1000),
(7, '무용', 'танец', strftime('%s','now')*1000),
(7, '무조건', 'безусловно / абсолютно', strftime('%s','now')*1000),
(7, '묵다', 'остановиться / жить', strftime('%s','now')*1000),
(7, '묶다', 'вязать / связывать', strftime('%s','now')*1000),
(7, '문구점', 'канцтовары', strftime('%s','now')*1000),
(7, '문방구', 'канцтовары', strftime('%s','now')*1000),
(7, '문법', 'грамматика', strftime('%s','now')*1000),
(7, '문병', 'навестить больного', strftime('%s','now')*1000),
(7, '문의', 'запрос / вопрос', strftime('%s','now')*1000),
(7, '문자', 'сообщение / письмо', strftime('%s','now')*1000),
(7, '문장', 'предложение', strftime('%s','now')*1000),
(7, '문학', 'литература', strftime('%s','now')*1000),
(7, '문화재', 'культурное наследие', strftime('%s','now')*1000),
(7, '묻다', 'спрашивать / закапывать', strftime('%s','now')*1000),
(7, '물', 'вода', strftime('%s','now')*1000),
(7, '물가', 'уровень цен / набережная', strftime('%s','now')*1000),
(7, '물다', 'кусать', strftime('%s','now')*1000),
(7, '물러나다', 'отступать / уходить в отставку', strftime('%s','now')*1000),
(7, '물러서다', 'отступать', strftime('%s','now')*1000),
(7, '물리다', 'быть укушенным / сытым по горло', strftime('%s','now')*1000),
(7, '물소리', 'звук воды', strftime('%s','now')*1000),
(7, '물약', 'жидкое лекарство', strftime('%s','now')*1000),
(7, '물음', 'вопрос / запрос', strftime('%s','now')*1000),
(7, '뮤지컬', 'мюзикл', strftime('%s','now')*1000),
(7, '미국인', 'американец', strftime('%s','now')*1000),
(7, '미끄럽다', 'скользкий', strftime('%s','now')*1000),
(7, '미루다', 'откладывать', strftime('%s','now')*1000),
(7, '미만', 'под / ниже', strftime('%s','now')*1000),
(7, '미성년자', 'несовершеннолетний', strftime('%s','now')*1000),
(7, '미소', 'улыбка', strftime('%s','now')*1000),
(7, '미술', 'искусство', strftime('%s','now')*1000),
(7, '미용사', 'парикмахер / косметолог', strftime('%s','now')*1000),
(7, '미인', 'красивая личность', strftime('%s','now')*1000),
(7, '미장원', 'салон красоты', strftime('%s','now')*1000),
(7, '미팅', 'встреча / свидание вслепую', strftime('%s','now')*1000),
(7, '민속놀이', 'народная игра', strftime('%s','now')*1000),
(7, '밀리다', 'задерживаться / накапливаться', strftime('%s','now')*1000),
(7, '밉다', 'уродливый / ненавистный', strftime('%s','now')*1000),
(7, '및', 'и / а также', strftime('%s','now')*1000),
(7, '밑줄', 'подчеркивание', strftime('%s','now')*1000),
(7, '바', 'бар / вещь / способ', strftime('%s','now')*1000),
(7, '바구니', 'корзина', strftime('%s','now')*1000),
(7, '바늘', 'игла', strftime('%s','now')*1000),
(7, '바닷물', 'морская вода', strftime('%s','now')*1000),
(7, '바둑', 'го (игра)', strftime('%s','now')*1000),
(7, '바보', 'дурак / идиот', strftime('%s','now')*1000),
(7, '바위', 'скала / валун', strftime('%s','now')*1000),
(7, '바퀴', 'колесо / насекомое', strftime('%s','now')*1000),
(7, '바탕', 'основа / фон', strftime('%s','now')*1000),
(7, '박', 'тыква / фамилия Пак', strftime('%s','now')*1000),
(7, '박사', 'доктор / кандидат наук', strftime('%s','now')*1000),
(7, '반납', 'возврат', strftime('%s','now')*1000),
(7, '반달', 'половина луны', strftime('%s','now')*1000),
(7, '반대말', 'антоним', strftime('%s','now')*1000),
(7, '반대쪽', 'противоположная сторона', strftime('%s','now')*1000),
(7, '반말', 'неформальная речь', strftime('%s','now')*1000),
(7, '반면', 'с другой стороны', strftime('%s','now')*1000),
(7, '반복', 'повторение', strftime('%s','now')*1000),
(7, '반죽', 'тесто / смесь', strftime('%s','now')*1000),
(7, '반창고', 'пластырь', strftime('%s','now')*1000),
(7, '반팔', 'короткие рукава', strftime('%s','now')*1000),
(7, '반하다', 'влюбиться / быть очарованным', strftime('%s','now')*1000),
(7, '발급', 'выпуск / выдача', strftime('%s','now')*1000),
(7, '발달', 'развитие / рост', strftime('%s','now')*1000),
(7, '발명', 'изобретение', strftime('%s','now')*1000),
(7, '발목', 'лодыжка', strftime('%s','now')*1000),
(7, '발음', 'произношение', strftime('%s','now')*1000),
(7, '발전', 'развитие / прогресс', strftime('%s','now')*1000),
(7, '발표', 'презентация / объявление', strftime('%s','now')*1000),
(7, '발행', 'публикация / выпуск', strftime('%s','now')*1000),
(7, '밝히다', 'раскрывать / освещать', strftime('%s','now')*1000),
(7, '밟다', 'наступать / топтать', strftime('%s','now')*1000),
(7, '밤', 'ночь / каштан', strftime('%s','now')*1000),
(7, '밤늦다', 'поздно ночью', strftime('%s','now')*1000),
(7, '밤새', 'всю ночь', strftime('%s','now')*1000),
(7, '밤색', 'коричневый цвет', strftime('%s','now')*1000),
(7, '밥그릇', 'чашка для риса', strftime('%s','now')*1000),
(7, '밥솥', 'рисоварка', strftime('%s','now')*1000),
(7, '방송사', 'телекомпания', strftime('%s','now')*1000),
(7, '방식', 'метод / стиль', strftime('%s','now')*1000),
(7, '방울', 'капля / маленький шар', strftime('%s','now')*1000),
(7, '방해', 'помеха / препятствие', strftime('%s','now')*1000),
(7, '배고프다', 'быть голодным', strftime('%s','now')*1000),
(7, '배구', 'волейбол', strftime('%s','now')*1000),
(7, '배낭', 'рюкзак', strftime('%s','now')*1000),
(7, '배낭여행', 'поход с рюкзаком', strftime('%s','now')*1000),
(7, '배웅', 'провожать', strftime('%s','now')*1000),
(7, '배치', 'расположение / размещение', strftime('%s','now')*1000),
(7, '배터리', 'батарея', strftime('%s','now')*1000),
(7, '배편', 'по морю / морская почта', strftime('%s','now')*1000),
(7, '백', 'сто / белый / фон', strftime('%s','now')*1000),
(7, '뱃속', 'внутри желудка', strftime('%s','now')*1000),
(7, '버섯', 'гриб', strftime('%s','now')*1000),
(7, '버터', 'масло', strftime('%s','now')*1000),
(7, '버튼', 'кнопка', strftime('%s','now')*1000),
(7, '번개', 'молния', strftime('%s','now')*1000),
(7, '번역', 'перевод', strftime('%s','now')*1000),
(7, '번지', 'номер участка / номер адреса', strftime('%s','now')*1000),
(7, '번호표', 'номерок', strftime('%s','now')*1000),
(7, '벌', 'пчела / наказание', strftime('%s','now')*1000),
(7, '벌금', 'штраф', strftime('%s','now')*1000),
(7, '범죄', 'преступление', strftime('%s','now')*1000),
(7, '법', 'закон', strftime('%s','now')*1000),
(7, '법칙', 'правило / закон', strftime('%s','now')*1000),
(7, '벗기다', 'снимать / раздевать', strftime('%s','now')*1000),
(7, '베란다', 'балкон / веранда', strftime('%s','now')*1000),
(7, '벤치', 'скамейка', strftime('%s','now')*1000),
(7, '벨', 'звонок', strftime('%s','now')*1000),
(7, '벨트', 'ремень', strftime('%s','now')*1000),
(7, '벽시계', 'настенные часы', strftime('%s','now')*1000),
(7, '벽지', 'обои', strftime('%s','now')*1000),
(7, '변경', 'изменение / модификация', strftime('%s','now')*1000),
(7, '변비', 'запор', strftime('%s','now')*1000),
(7, '변화', 'изменение / трансформация', strftime('%s','now')*1000),
(7, '별', 'звезда / особый', strftime('%s','now')*1000),
(7, '별말씀', 'не за что', strftime('%s','now')*1000),
(7, '별명', 'прозвище', strftime('%s','now')*1000),
(7, '별일', 'особая вещь / дело', strftime('%s','now')*1000),
(7, '병실', 'больничная палата', strftime('%s','now')*1000),
(7, '보고', 'отчет', strftime('%s','now')*1000),
(7, '보고서', 'письменный отчет', strftime('%s','now')*1000),
(7, '보관', 'хранение', strftime('%s','now')*1000),
(7, '보기', 'пример / экземпляр', strftime('%s','now')*1000),
(7, '보너스', 'бонус', strftime('%s','now')*1000),
(7, '보람', 'ценность / награда', strftime('%s','now')*1000),
(7, '보름', 'пятнадцать дней', strftime('%s','now')*1000),
(7, '보름달', 'полная луна', strftime('%s','now')*1000),
(7, '보리', 'ячмень', strftime('%s','now')*1000),
(7, '보석', 'драгоценность / камень', strftime('%s','now')*1000),
(7, '보행자', 'пешеход', strftime('%s','now')*1000),
(7, '보험', 'страховка', strftime('%s','now')*1000),
(7, '보호', 'защита / уход', strftime('%s','now')*1000),
(7, '복', 'удача / благословение', strftime('%s','now')*1000),
(7, '복도', 'коридор', strftime('%s','now')*1000),
(7, '복사', 'копия / дублирование', strftime('%s','now')*1000),
(7, '복사기', 'копировальный аппарат', strftime('%s','now')*1000),
(7, '복숭아', 'персик', strftime('%s','now')*1000),
(7, '복용', 'дозировка / прием лекарства', strftime('%s','now')*1000),
(7, '복통', 'боль в животе', strftime('%s','now')*1000),
(7, '본인', 'сам / заинтересованное лицо', strftime('%s','now')*1000),
(7, '볼거리', 'достопримечательность', strftime('%s','now')*1000),
(7, '볼링', 'боулинг', strftime('%s','now')*1000),
(7, '볼일', 'дело / дела', strftime('%s','now')*1000),
(7, '봉사', 'служба / волонтерская работа', strftime('%s','now')*1000),
(7, '봉지', 'сумка / пакет', strftime('%s','now')*1000),
(7, '뵈다', 'видеть (почтительно)', strftime('%s','now')*1000),
(7, '부', 'отдел / часть / богатство', strftime('%s','now')*1000),
(7, '부담', 'бремя / давление', strftime('%s','now')*1000),
(7, '부동산', 'недвижимость', strftime('%s','now')*1000),
(7, '부러워하다', 'завидовать / восхищаться', strftime('%s','now')*1000),
(7, '부러지다', 'сломаться / щелкнуть', strftime('%s','now')*1000),
(7, '부리다', 'управлять / проявлять (эмоцию)', strftime('%s','now')*1000),
(7, '부모', 'родители', strftime('%s','now')*1000),
(7, '부인', 'жена / отрицать', strftime('%s','now')*1000),
(7, '부자', 'богатый человек / отец и сын', strftime('%s','now')*1000),
(7, '부잣집', 'богатая семья', strftime('%s','now')*1000),
(7, '부채', 'вентилятор / долг', strftime('%s','now')*1000),
(7, '부츠', 'ботинки', strftime('%s','now')*1000),
(7, '부친', 'отец', strftime('%s','now')*1000),
(7, '북', 'барабан / север', strftime('%s','now')*1000),
(7, '북부', 'северный регион', strftime('%s','now')*1000),
(7, '분단', 'разделение', strftime('%s','now')*1000),
(7, '분리', 'разделение', strftime('%s','now')*1000),
(7, '분명히', 'ясно / определенно', strftime('%s','now')*1000),
(7, '분실', 'потеря', strftime('%s','now')*1000),
(7, '분실물', 'потерянная вещь', strftime('%s','now')*1000),
(7, '분필', 'мел', strftime('%s','now')*1000),
(7, '불', 'огонь / не-', strftime('%s','now')*1000),
(7, '불규칙', 'нерегулярность', strftime('%s','now')*1000),
(7, '불균형', 'дисбаланс', strftime('%s','now')*1000),
(7, '불만', 'недовольство / жалоба', strftime('%s','now')*1000),
(7, '불만족', 'недовольство', strftime('%s','now')*1000),
(7, '불만족스럽다', 'неудовлетворительный', strftime('%s','now')*1000),
(7, '불어', 'французский язык', strftime('%s','now')*1000),
(7, '불완전', 'неполный / несовершенный', strftime('%s','now')*1000),
(7, '불평', 'жалоба / обида', strftime('%s','now')*1000),
(7, '붐비다', 'быть переполненным', strftime('%s','now')*1000),
(7, '붓다', 'опухать / наливать', strftime('%s','now')*1000),
(7, '뷔페', 'буфет', strftime('%s','now')*1000),
(7, '비', 'дождь / соотношение / плата', strftime('%s','now')*1000),
(7, '비밀번호', 'пароль', strftime('%s','now')*1000),
(7, '비비다', 'тереть / смешивать', strftime('%s','now')*1000),
(7, '비상구', 'аварийный выход', strftime('%s','now')*1000),
(7, '비용', 'стоимость / расход', strftime('%s','now')*1000),
(7, '비자', 'виза', strftime('%s','now')*1000),
(7, '비키다', 'отойти / отодвинуться', strftime('%s','now')*1000),
(7, '비타민', 'витамин', strftime('%s','now')*1000),
(7, '비하다', 'сравнивать с', strftime('%s','now')*1000),
(7, '비행', 'полет / авиация', strftime('%s','now')*1000),
(7, '비행장', 'аэродром / аэропорт', strftime('%s','now')*1000),
(7, '빈자리', 'пустое место / вакансия', strftime('%s','now')*1000),
(7, '빌다', 'желать / молиться', strftime('%s','now')*1000),
(7, '빗다', 'расчесывать волосы', strftime('%s','now')*1000),
(7, '빛', 'свет / цвет / сияние', strftime('%s','now')*1000),
(7, '빠지다', 'падать / тонуть / отсутствовать', strftime('%s','now')*1000),
(7, '빨강', 'красный цвет', strftime('%s','now')*1000),
(7, '빨개지다', 'краснеть / краснеть', strftime('%s','now')*1000),
(7, '빨다', 'мыть / сосать', strftime('%s','now')*1000),
(7, '뺏다', 'забирать / лишать', strftime('%s','now')*1000),
(7, '뼈', 'кость', strftime('%s','now')*1000),
(7, '뽀뽀', 'поцелуй (детский)', strftime('%s','now')*1000),
(7, '뿌리', 'корень / происхождение', strftime('%s','now')*1000),
(7, '뿌리다', 'посыпать / рассыпать', strftime('%s','now')*1000),
(7, '삐다', 'растяжение / скручивание', strftime('%s','now')*1000),
(7, '사건', 'инцидент / дело', strftime('%s','now')*1000),
(7, '사과', 'яблоко / извинение', strftime('%s','now')*1000),
(7, '사교적', 'общительный', strftime('%s','now')*1000),
(7, '사나이', 'мужчина / парень', strftime('%s','now')*1000),
(7, '사라지다', 'исчезать', strftime('%s','now')*1000),
(7, '사무', 'офисная работа', strftime('%s','now')*1000),
(7, '사무소', 'офис', strftime('%s','now')*1000),
(7, '사물', 'вещь / объект', strftime('%s','now')*1000),
(7, '사생활', 'личная жизнь', strftime('%s','now')*1000),
(7, '사업가', 'бизнесмен', strftime('%s','now')*1000),
(7, '사용법', 'как использовать / инструкции', strftime('%s','now')*1000),
(7, '사우나', 'сауна', strftime('%s','now')*1000),
(7, '사이트', 'сайт', strftime('%s','now')*1000),
(7, '사인', 'подпись / автограф', strftime('%s','now')*1000),
(7, '사자', 'лев / посланник', strftime('%s','now')*1000),
(7, '사적', 'личный / частный', strftime('%s','now')*1000);