PRAGMA user_version = 1;

DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS review_state;
DROP TABLE IF EXISTS learned_state;
DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
  id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  deckId    INTEGER NOT NULL,
  front     TEXT    NOT NULL,
  back      TEXT    NOT NULL,
  createdAt INTEGER NOT NULL DEFAULT 0,
  excluded  INTEGER NOT NULL DEFAULT 0,
  learned   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(deckId, front, back)
);
CREATE UNIQUE INDEX IF NOT EXISTS index_cards_deckId_front_back ON cards(deckId, front, back);


DROP TABLE IF EXISTS review_state;

CREATE TABLE review_state(
  id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId       INTEGER NOT NULL,
  intervalDays INTEGER NOT NULL,
  ease         REAL    NOT NULL,
  step         INTEGER NOT NULL,
  dueAt        INTEGER NOT NULL,
  lastGrade    INTEGER,
  FOREIGN KEY(cardId) REFERENCES cards(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS index_review_state_cardId ON review_state(cardId);

CREATE TABLE review_log(
  id                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cardId              INTEGER NOT NULL,
  reviewedAt          INTEGER NOT NULL,
  grade               INTEGER NOT NULL,
  resultIntervalDays  INTEGER NOT NULL,
  resultEase          REAL    NOT NULL,
  resultStep          INTEGER NOT NULL,
  ts                  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS index_review_log_cardId ON review_log(cardId);

CREATE TABLE learned_state(
  cardId   INTEGER NOT NULL,
  learned  INTEGER NOT NULL,
  PRIMARY KEY(cardId)
);

INSERT INTO cards (deckId, front, back, createdAt) VALUES
(4, '모자라다', 'to be short of', strftime('%s','now')*1000),
(4, '목걸이', 'necklace', strftime('%s','now')*1000),
(4, '목도리', 'scarf', strftime('%s','now')*1000),
(4, '목소리', 'voice', strftime('%s','now')*1000),
(4, '목욕', 'bath', strftime('%s','now')*1000),
(4, '목적', 'purpose', strftime('%s','now')*1000),
(4, '못생기다', 'to be ugly', strftime('%s','now')*1000),
(4, '무01', 'no, not (version 1)', strftime('%s','now')*1000),
(4, '무게', 'weight', strftime('%s','now')*1000),
(4, '무궁화', 'rose of Sharon', strftime('%s','now')*1000),
(4, '무료01', 'free (of charge, version 1)', strftime('%s','now')*1000),
(4, '무릎', 'knee', strftime('%s','now')*1000),
(4, '무섭다', 'to be scary', strftime('%s','now')*1000),
(4, '무척', 'very', strftime('%s','now')*1000),
(4, '문제', 'problem', strftime('%s','now')*1000),
(4, '물고기', 'fish', strftime('%s','now')*1000),
(4, '물론02/물론01', 'of course (version 2/1)', strftime('%s','now')*1000),
(4, '물어보다', 'to ask', strftime('%s','now')*1000),
(4, '미끄러지다', 'to slip', strftime('%s','now')*1000),
(4, '미래', 'future', strftime('%s','now')*1000),
(4, '미리', 'in advance', strftime('%s','now')*1000),
(4, '미술관', 'art gallery', strftime('%s','now')*1000),
(4, '미역국', 'seaweed soup', strftime('%s','now')*1000),
(4, '미터', 'meter', strftime('%s','now')*1000),
(4, '믿다', 'to believe', strftime('%s','now')*1000),
(4, '밀가루', 'flour', strftime('%s','now')*1000),
(4, '밀다', 'to push', strftime('%s','now')*1000),
(4, '바깥', 'outside', strftime('%s','now')*1000),
(4, '바깥쪽', 'outer side', strftime('%s','now')*1000),
(4, '바뀌다', 'to be changed', strftime('%s','now')*1000),
(4, '바닥', 'floor', strftime('%s','now')*1000),
(4, '바닷가', 'beach', strftime('%s','now')*1000),
(4, '바라다', 'to wish, hope', strftime('%s','now')*1000),
(4, '바라보다', 'to look at, gaze at', strftime('%s','now')*1000),
(4, '바르다01', 'to apply, to be correct (version 1)', strftime('%s','now')*1000),
(4, '바이올린', 'violin', strftime('%s','now')*1000),
(4, '박수', 'applause', strftime('%s','now')*1000),
(4, '반대', 'opposite, opposition', strftime('%s','now')*1000),
(4, '반드시', 'certainly, surely', strftime('%s','now')*1000),
(4, '반바지', 'shorts', strftime('%s','now')*1000),
(4, '반지', 'ring', strftime('%s','now')*1000),
(4, '반찬', 'side dish', strftime('%s','now')*1000),
(4, '받아쓰다', 'to take dictation', strftime('%s','now')*1000),
(4, '발가락', 'toe', strftime('%s','now')*1000),
(4, '발바닥', 'sole of foot', strftime('%s','now')*1000),
(4, '밝다02/밝다01', 'to be bright (version 2/1)', strftime('%s','now')*1000),
(4, '방금02/방금01', 'just now (version 2/1)', strftime('%s','now')*1000),
(4, '방문02', 'visit (version 2)', strftime('%s','now')*1000),
(4, '방문03', 'door (version 3)', strftime('%s','now')*1000),
(4, '방법', 'method, way', strftime('%s','now')*1000),
(4, '방송01', 'broadcast (version 1)', strftime('%s','now')*1000),
(4, '방송국', 'broadcasting station', strftime('%s','now')*1000),
(4, '방향', 'direction', strftime('%s','now')*1000),
(4, '배05', 'back (of body, version 5)', strftime('%s','now')*1000),
(4, '배달02', 'delivery (version 2)', strftime('%s','now')*1000),
(4, '배드민턴', 'badminton', strftime('%s','now')*1000),
(4, '배추', 'Chinese cabbage', strftime('%s','now')*1000),
(4, '배탈', 'stomach trouble', strftime('%s','now')*1000),
(4, '뱀', 'snake', strftime('%s','now')*1000),
(4, '버릇', 'habit', strftime('%s','now')*1000),
(4, '버리다01', 'to throw away (version 1)', strftime('%s','now')*1000),
(4, '번째', 'th (ordinal number)', strftime('%s','now')*1000),
(4, '벌02', 'bee (version 2)', strftime('%s','now')*1000),
(4, '벌다02', 'to earn (version 2)', strftime('%s','now')*1000),
(4, '벌써', 'already', strftime('%s','now')*1000),
(4, '벗다', 'to take off (clothes)', strftime('%s','now')*1000),
(4, '벽', 'wall', strftime('%s','now')*1000),
(4, '변하다', 'to change', strftime('%s','now')*1000),
(4, '변호사', 'lawyer', strftime('%s','now')*1000),
(4, '별01', 'star (version 1)', strftime('%s','now')*1000),
(4, '병문안', 'hospital visit', strftime('%s','now')*1000),
(4, '보라색', 'purple', strftime('%s','now')*1000),
(4, '보이다01', 'to be seen (version 1)', strftime('%s','now')*1000),
(4, '보이다02', 'to be seen (version 2)', strftime('%s','now')*1000),
(4, '복습', 'review', strftime('%s','now')*1000),
(4, '복잡하다', 'to be complicated', strftime('%s','now')*1000),
(4, '볶다', 'to stir-fry', strftime('%s','now')*1000),
(4, '볶음밥', 'fried rice', strftime('%s','now')*1000),
(4, '봉투', 'envelope, bag', strftime('%s','now')*1000),
(4, '뵙다', 'to meet (humble)', strftime('%s','now')*1000),
(4, '부끄럽다', 'to be shy', strftime('%s','now')*1000),
(4, '부드럽다', 'to be soft', strftime('%s','now')*1000),
(4, '부럽다', 'to be jealous', strftime('%s','now')*1000),
(4, '부르다02', 'to call (version 2)', strftime('%s','now')*1000),
(4, '부부', 'couple', strftime('%s','now')*1000),
(4, '부분', 'part', strftime('%s','now')*1000),
(4, '부인01', 'wife (version 1)', strftime('%s','now')*1000),
(4, '부자02', 'rich person (version 2)', strftime('%s','now')*1000),
(4, '부장', 'department head', strftime('%s','now')*1000),
(4, '부족01', 'shortage (version 1)', strftime('%s','now')*1000),
(4, '부지런하다', 'to be diligent', strftime('%s','now')*1000),
(4, '부치다02', 'to mail (version 2)', strftime('%s','now')*1000),
(4, '북쪽', 'north', strftime('%s','now')*1000),
(4, '분명하다', 'to be clear', strftime('%s','now')*1000),
(4, '분식', 'snack food', strftime('%s','now')*1000),
(4, '분위기', 'atmosphere', strftime('%s','now')*1000),
(4, '분홍색', 'pink', strftime('%s','now')*1000),
(4, '불쌍하다', 'to be pitiful', strftime('%s','now')*1000),
(4, '불안', 'anxiety', strftime('%s','now')*1000),
(4, '불편', 'discomfort', strftime('%s','now')*1000),
(4, '붉다', 'to be red', strftime('%s','now')*1000),
(4, '붙다', 'to stick', strftime('%s','now')*1000),
(4, '붙이다', 'to attach', strftime('%s','now')*1000),
(4, '블라우스', 'blouse', strftime('%s','now')*1000),
(4, '비교', 'comparison', strftime('%s','now')*1000),
(4, '비누', 'soap', strftime('%s','now')*1000),
(4, '비다', 'to be empty', strftime('%s','now')*1000),
(4, '비디오', 'video', strftime('%s','now')*1000),
(4, '비밀', 'secret', strftime('%s','now')*1000),
(4, '비슷하다', 'to be similar', strftime('%s','now')*1000),
(4, '빌딩', 'building', strftime('%s','now')*1000),
(4, '빠지다02', 'to fall out (version 2)', strftime('%s','now')*1000),
(4, '빨간색', 'red', strftime('%s','now')*1000),
(4, '빨갛다', 'to be red', strftime('%s','now')*1000),
(4, '빨다02', 'to suck (version 2)', strftime('%s','now')*1000),
(4, '빨래', 'laundry', strftime('%s','now')*1000),
(4, '빵집', 'bakery', strftime('%s','now')*1000),
(4, '빼다01', 'to take out (version 1)', strftime('%s','now')*1000),
(4, '뽑다', 'to choose, to pick', strftime('%s','now')*1000),
(4, '사거리', 'intersection', strftime('%s','now')*1000),
(4, '사계절', 'four seasons', strftime('%s','now')*1000),
(4, '사고01', 'accident (version 1)', strftime('%s','now')*1000),
(4, '사실01/사실02', 'fact (version 1/2)', strftime('%s','now')*1000),
(4, '사업', 'business', strftime('%s','now')*1000),
(4, '사이즈', 'size', strftime('%s','now')*1000),
(4, '사장', 'boss, president', strftime('%s','now')*1000),
(4, '사탕', 'candy', strftime('%s','now')*1000),
(4, '사흘', 'three days', strftime('%s','now')*1000),
(4, '살01', 'to live, life (version 1)', strftime('%s','now')*1000),
(4, '삼거리', 'three-way intersection', strftime('%s','now')*1000),
(4, '삼겹살', 'pork belly', strftime('%s','now')*1000),
(4, '삼촌', 'uncle', strftime('%s','now')*1000),
(4, '상06', 'reward, prize (version 6)', strftime('%s','now')*1000),
(4, '상자', 'box', strftime('%s','now')*1000),
(4, '상처02', 'wound (version 2)', strftime('%s','now')*1000),
(4, '상추', 'lettuce', strftime('%s','now')*1000),
(4, '상품02', 'product (version 2)', strftime('%s','now')*1000),
(4, '새02', 'bird (version 2)', strftime('%s','now')*1000),
(4, '새03', 'new (version 3)', strftime('%s','now')*1000),
(4, '새로', 'newly', strftime('%s','now')*1000),
(4, '새롭다', 'to be new', strftime('%s','now')*1000),
(4, '새벽', 'dawn', strftime('%s','now')*1000),
(4, '새해', 'new year', strftime('%s','now')*1000),
(4, '색', 'color', strftime('%s','now')*1000),
(4, '색깔', 'color (with more emphasis)', strftime('%s','now')*1000),
(4, '샌드위치', 'sandwich', strftime('%s','now')*1000),
(4, '생각나다', 'to come to mind, to remember', strftime('%s','now')*1000),
(4, '생기다01', 'to appear, to come to life (version 1)', strftime('%s','now')*1000),
(4, '생선', 'fish (for eating)', strftime('%s','now')*1000),
(4, '서너', 'three or four', strftime('%s','now')*1000),
(4, '서다', 'to stand', strftime('%s','now')*1000),
(4, '서두르다', 'to hurry', strftime('%s','now')*1000),
(4, '서랍', 'drawer', strftime('%s','now')*1000),
(4, '서로02', 'each other (version 2)', strftime('%s','now')*1000),
(4, '서류', 'document', strftime('%s','now')*1000),
(4, '서비스', 'service', strftime('%s','now')*1000),
(4, '서양', 'the West', strftime('%s','now')*1000),
(4, '서쪽', 'west', strftime('%s','now')*1000),
(4, '섞다', 'to mix', strftime('%s','now')*1000),
(4, '선배', 'senior (in school or work)', strftime('%s','now')*1000),
(4, '선선하다', 'to be cool (weather)', strftime('%s','now')*1000),
(4, '선수02', 'player (version 2)', strftime('%s','now')*1000),
(4, '선택', 'choice, selection', strftime('%s','now')*1000),
(4, '선풍기', 'electric fan', strftime('%s','now')*1000),
(4, '설거지', 'washing dishes', strftime('%s','now')*1000),
(4, '설날', 'Lunar New Year', strftime('%s','now')*1000),
(4, '설렁탕', 'beef soup', strftime('%s','now')*1000),
(4, '설탕', 'sugar', strftime('%s','now')*1000),
(4, '섬03', 'island (version 3)', strftime('%s','now')*1000),
(4, '섭섭하다', 'to be sorry, disappointed', strftime('%s','now')*1000),
(4, '성02', 'success (version 2)', strftime('%s','now')*1000),
(4, '성격', 'personality', strftime('%s','now')*1000),
(4, '성공', 'success', strftime('%s','now')*1000),
(4, '성적03', 'grades, score (version 3)', strftime('%s','now')*1000),
(4, '성함', 'name (honorific)', strftime('%s','now')*1000),
(4, '세05', 'tax (version 5)', strftime('%s','now')*1000),
(4, '세계', 'world', strftime('%s','now')*1000),
(4, '세다03', 'to count, to be strong (version 3)', strftime('%s','now')*1000),
(4, '세배', 'New Year’s bow', strftime('%s','now')*1000),
(4, '세상', 'world, society', strftime('%s','now')*1000),
(4, '세우다', 'to set up', strftime('%s','now')*1000),
(4, '세탁', 'laundry', strftime('%s','now')*1000),
(4, '세탁기', 'washing machine', strftime('%s','now')*1000),
(4, '세탁소', 'laundry shop', strftime('%s','now')*1000),
(4, '센터', 'center', strftime('%s','now')*1000),
(4, '센티미터', 'centimeter', strftime('%s','now')*1000),
(4, '셋째02‧셋째01/셋째03', 'third (version 2)', strftime('%s','now')*1000),
(4, '소02', 'cow (version 2)', strftime('%s','now')*1000),
(4, '소고기', 'beef', strftime('%s','now')*1000),
(4, '소리', 'sound', strftime('%s','now')*1000),
(4, '소설02', 'novel (version 2)', strftime('%s','now')*1000),
(4, '소식02', 'news (version 2)', strftime('%s','now')*1000),
(4, '소주', 'soju', strftime('%s','now')*1000),
(4, '소중하다', 'to be precious', strftime('%s','now')*1000),
(4, '소파', 'sofa', strftime('%s','now')*1000),
(4, '소포', 'parcel', strftime('%s','now')*1000),
(4, '소풍', 'picnic', strftime('%s','now')*1000),
(4, '소화제', 'digestive medicine', strftime('%s','now')*1000),
(4, '속', 'inside', strftime('%s','now')*1000),
(4, '속도', 'speed', strftime('%s','now')*1000),
(4, '속옷', 'underwear', strftime('%s','now')*1000),
(4, '손가락', 'finger', strftime('%s','now')*1000),
(4, '손녀', 'granddaughter', strftime('%s','now')*1000),
(4, '손바닥', 'palm of hand', strftime('%s','now')*1000),
(4, '손수건', 'handkerchief', strftime('%s','now')*1000),
(4, '송편', 'songpyeon (rice cake)', strftime('%s','now')*1000),
(4, '수10', 'number 10', strftime('%s','now')*1000),
(4, '수건', 'towel', strftime('%s','now')*1000),
(4, '수고', 'effort', strftime('%s','now')*1000),
(4, '수술02', 'surgery (version 2)', strftime('%s','now')*1000),
(4, '수영복', 'swimsuit', strftime('%s','now')*1000),
(4, '수저', 'spoon and chopsticks', strftime('%s','now')*1000),
(4, '순두부찌개', 'soft tofu stew', strftime('%s','now')*1000),
(4, '순서', 'order', strftime('%s','now')*1000),
(4, '숟가락', 'spoon', strftime('%s','now')*1000),
(4, '술집', 'bar', strftime('%s','now')*1000),
(4, '숫자', 'number', strftime('%s','now')*1000),
(4, '쉬다04', 'to rest (version 4)', strftime('%s','now')*1000),
(4, '쉰02·쉰01', 'fifty (version 2)', strftime('%s','now')*1000),
(4, '스무', 'twenty', strftime('%s','now')*1000),
(4, '스스로02/스스로01', 'oneself, by oneself', strftime('%s','now')*1000),
(4, '스웨터', 'sweater', strftime('%s','now')*1000),
(4, '스카프', 'scarf', strftime('%s','now')*1000),
(4, '스케이트', 'skate', strftime('%s','now')*1000),
(4, '스키장', 'ski resort', strftime('%s','now')*1000),
(4, '스타', 'star', strftime('%s','now')*1000),
(4, '스트레스', 'stress', strftime('%s','now')*1000),
(4, '스파게티', 'spaghetti', strftime('%s','now')*1000),
(4, '스포츠', 'sports', strftime('%s','now')*1000),
(4, '슬퍼하다', 'to be sad', strftime('%s','now')*1000),
(4, '슬픔', 'sadness', strftime('%s','now')*1000),
(4, '습관', 'habit', strftime('%s','now')*1000),
(4, '시01', 'poem (version 1)', strftime('%s','now')*1000),
(4, '시간표', 'schedule', strftime('%s','now')*1000),
(4, '시계01', 'clock, watch (version 1)', strftime('%s','now')*1000),
(4, '시골', 'countryside', strftime('%s','now')*1000),
(4, '시끄럽다', 'to be noisy', strftime('%s','now')*1000),
(4, '시내02', 'downtown (version 2)', strftime('%s','now')*1000),
(4, '시민', 'citizen', strftime('%s','now')*1000),
(4, '시어머니', 'mother-in-law', strftime('%s','now')*1000),
(4, '식구', 'family member', strftime('%s','now')*1000),
(4, '식다', 'to become cold (food)', strftime('%s','now')*1000),
(4, '식빵', 'loaf of bread', strftime('%s','now')*1000),
(4, '식초', 'vinegar', strftime('%s','now')*1000),
(4, '식탁', 'dining table', strftime('%s','now')*1000),
(4, '식품', 'food products', strftime('%s','now')*1000),
(4, '신랑', 'bridegroom', strftime('%s','now')*1000),
(4, '신부02', 'bride (version 2)', strftime('%s','now')*1000),
(4, '신분증', 'ID card', strftime('%s','now')*1000),
(4, '신선하다', 'to be fresh', strftime('%s','now')*1000),
(4, '신청', 'application', strftime('%s','now')*1000),
(4, '신호', 'signal', strftime('%s','now')*1000),
(4, '신호등', 'traffic light', strftime('%s','now')*1000),
(4, '신혼여행', 'honeymoon', strftime('%s','now')*1000),
(4, '싣다', 'to load', strftime('%s','now')*1000),
(4, '실수', 'mistake', strftime('%s','now')*1000),
(4, '실패02', 'failure (version 2)', strftime('%s','now')*1000),
(4, '심다', 'to plant', strftime('%s','now')*1000),
(4, '심심하다01', 'to be bored (version 1)', strftime('%s','now')*1000),
(4, '심하다', 'to be severe, intense', strftime('%s','now')*1000),
(4, '싸다01', 'to be cheap (version 1)', strftime('%s','now')*1000),
(4, '싸우다', 'to fight', strftime('%s','now')*1000),
(4, '쌀', 'rice (uncooked)', strftime('%s','now')*1000),
(4, '쌀쌀하다', 'to be chilly', strftime('%s','now')*1000),
(4, '쌓다01', 'to pile up (version 1)', strftime('%s','now')*1000),
(4, '썰다', 'to slice', strftime('%s','now')*1000),
(4, '쓰다02', 'to use (version 2)', strftime('%s','now')*1000),
(4, '쓰레기', 'garbage', strftime('%s','now')*1000),
(4, '쓰레기통', 'garbage can', strftime('%s','now')*1000),
(4, '씹다', 'to chew', strftime('%s','now')*1000),
(4, '아가씨', 'young lady', strftime('%s','now')*1000),
(4, '아까02/아까01', 'earlier (version 2/1)', strftime('%s','now')*1000),
(4, '아나운서', 'announcer', strftime('%s','now')*1000),
(4, '아니02', 'no (version 2)', strftime('%s','now')*1000),
(4, '아들', 'son', strftime('%s','now')*1000),
(4, '아래쪽', 'below, underneath', strftime('%s','now')*1000),
(4, '아마', 'perhaps, maybe', strftime('%s','now')*1000),
(4, '아무02/아무01', 'any, anyone (version 2/1)', strftime('%s','now')*1000),
(4, '아무것', 'anything', strftime('%s','now')*1000),
(4, '아무리01', 'no matter how (version 1)', strftime('%s','now')*1000),
(4, '아버님', 'father (honorific)', strftime('%s','now')*1000),
(4, '아빠', 'dad', strftime('%s','now')*1000),
(4, '아줌마', 'woman (married woman)', strftime('%s','now')*1000),
(4, '악기', 'musical instrument', strftime('%s','now')*1000),
(4, '안개', 'fog', strftime('%s','now')*1000),
(4, '안내문', 'notice, guide', strftime('%s','now')*1000),
(4, '안다', 'to know', strftime('%s','now')*1000),
(4, '안되다01', 'to not work (version 1)', strftime('%s','now')*1000),
(4, '안전01', 'safety (version 1)', strftime('%s','now')*1000),
(4, '안쪽', 'inside', strftime('%s','now')*1000),
(4, '알맞다', 'to be proper, right', strftime('%s','now')*1000),
(4, '알아보다', 'to recognize, to check', strftime('%s','now')*1000),
(4, '앞쪽', 'front side', strftime('%s','now')*1000),
(4, '애02', 'child (version 2)', strftime('%s','now')*1000),
(4, '애인', 'lover', strftime('%s','now')*1000),
(4, '앨범', 'album', strftime('%s','now')*1000),
(4, '야02', 'wild, 야 (version 2)', strftime('%s','now')*1000),
(4, '야채', 'vegetables', strftime('%s','now')*1000),
(4, '약간02/약간01', 'slightly (version 2/1)', strftime('%s','now')*1000),
(4, '약사', 'pharmacist', strftime('%s','now')*1000),
(4, '어울리다', 'to suit to match', strftime('%s','now')*1000),
(4, '어젯밤', 'last night', strftime('%s','now')*1000),
(4, '언어', 'language (speech)', strftime('%s','now')*1000),
(4, '언제나', 'always', strftime('%s','now')*1000),
(4, '얻다', 'to get obtain', strftime('%s','now')*1000),
(4, '얼다', 'to freeze', strftime('%s','now')*1000),
(4, '얼음', 'ice', strftime('%s','now')*1000),
(4, '엄ма', 'mom, mother', strftime('%s','now')*1000),
(4, '엉덩이', 'buttocks', strftime('%s','now')*1000),
(4, '엘리베이터', 'elevator', strftime('%s','now')*1000),
(4, '여기저기', 'here and there, everywhere', strftime('%s','now')*1000),
(4, '여성', 'woman, female', strftime('%s','now')*1000),
(4, '여쭙다', 'to ask (hon.)', strftime('%s','now')*1000),
(4, '여학생', 'female student', strftime('%s','now')*1000),
(4, '여행지', 'travel destination', strftime('%s','now')*1000),
(4, '역사', 'history', strftime('%s','now')*1000),
(4, '역시', 'also, as expected', strftime('%s','now')*1000),
(4, '연결', 'connection, link', strftime('%s','now')*1000),
(4, '연락', 'contact, communication', strftime('%s','now')*1000),
(4, '연락처', 'contact information', strftime('%s','now')*1000),
(4, '연말', 'year-end', strftime('%s','now')*1000),
(4, '연세', 'age (honorific)', strftime('%s','now')*1000),
(4, '연예인', 'celebrity, entertainer', strftime('%s','now')*1000),
(4, '연휴', 'long holiday', strftime('%s','now')*1000),
(4, '열', 'fever, heat, row', strftime('%s','now')*1000),
(4, '열리다', 'to open (be opened)', strftime('%s','now')*1000),
(4, '열차', 'train', strftime('%s','now')*1000),
(4, '열흘', 'ten days', strftime('%s','now')*1000),
(4, '엽서', 'postcard', strftime('%s','now')*1000),
(4, '영수증', 'receipt', strftime('%s','now')*1000),
(4, '영하', 'below zero', strftime('%s','now')*1000),
(4, '옆집', 'next-door house', strftime('%s','now')*1000),
(4, '예매', 'advance purchase (ticket)', strftime('%s','now')*1000),
(4, '예순', 'sixty', strftime('%s','now')*1000),
(4, '예술', 'art', strftime('%s','now')*1000),
(4, '예습', 'pre-study, preparation', strftime('%s','now')*1000),
(4, '예약', 'reservation', strftime('%s','now')*1000),
(4, '옛', 'old, ancient', strftime('%s','now')*1000),
(4, '옛날', 'the old days, long ago', strftime('%s','now')*1000),
(4, '오래', 'for a long time', strftime('%s','now')*1000),
(4, '오래간만', 'after a long time', strftime('%s','now')*1000),
(4, '오래되다', 'old (thing/place)', strftime('%s','now')*1000),
(4, '오랜만', 'long time no see', strftime('%s','now')*1000),
(4, '오랫동안', 'for a long time', strftime('%s','now')*1000),
(4, '오르다', 'to rise, climb', strftime('%s','now')*1000),
(4, '오른손', 'right hand', strftime('%s','now')*1000),
(4, '오이', 'cucumber', strftime('%s','now')*1000),
(4, '온도', 'temperature', strftime('%s','now')*1000),
(4, '올라오다', 'to come up', strftime('%s','now')*1000),
(4, '올리다', 'to raise, upload', strftime('%s','now')*1000),
(4, '올림', 'from (in a letter)', strftime('%s','now')*1000);